### ISSUE TITLE
YouDrive

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9301]
**App Name:** YouDrive
**Bundle ID:** today.youdrive.rent
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=989836024">989836024</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/youdrive/id989836024?mt=8&uo=4">https://itunes.apple.com/us/app/youdrive/id989836024?mt=8&uo=4</a>
**App Version:** 2.3.1
**Seller:** NTS, OOO
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/youdrive/id1080473313?uo=4">© YouDrive</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/df/b1/4c/dfb14c42-7b6b-9da9-c667-bc7f3a63b831/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29395767-9c1bb9aa-8313-11e7-8993-d2d2c3f9c634.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29395767-9c1bb9aa-8313-11e7-8993-d2d2c3f9c634.png)
https://user-images.githubusercontent.com/2068130/29395767-9c1bb9aa-8313-11e7-8993-d2d2c3f9c634.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29395775-ab18dc8a-8313-11e7-8f37-2279a155c1b7.png
