### ISSUE TITLE
Яндекс.Район — не пропустите полезное рядом

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9304]
**App Name:** Яндекс.Район — не пропустите полезное рядом
**Bundle ID:** ru.yandex.khamovniki
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1108941291">1108941291</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/%D1%8F%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D1%80%D0%B0%D0%B9%D0%BE%D0%BD-%D0%BD%D0%B5-%D0%BF%D1%80%D0%BE%D0%BF%D1%83%D1%81%D1%82%D0%B8%D1%82%D0%B5-%D0%BF%D0%BE%D0%BB%D0%B5%D0%B7%D0%BD%D0%BE%D0%B5-%D1%80%D1%8F%D0%B4%D0%BE%D0%BC/id1108941291?mt=8&uo=4">https://itunes.apple.com/us/app/%D1%8F%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D1%80%D0%B0%D0%B9%D0%BE%D0%BD-%D0%BD%D0%B5-%D0%BF%D1%80%D0%BE%D0%BF%D1%83%D1%81%D1%82%D0%B8%D1%82%D0%B5-%D0%BF%D0%BE%D0%BB%D0%B5%D0%B7%D0%BD%D0%BE%D0%B5-%D1%80%D1%8F%D0%B4%D0%BE%D0%BC/id1108941291?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yandex-llc/id308094652?uo=4">© Yandex LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/c6/ac/d5/c6acd56f-d993-6d9f-be8b-c0e2813faf1d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29396177-900d8546-8316-11e7-9447-94d76ad60767.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29396177-900d8546-8316-11e7-9447-94d76ad60767.png)
https://user-images.githubusercontent.com/2068130/29396177-900d8546-8316-11e7-9447-94d76ad60767.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29396188-a1150a08-8316-11e7-9a4f-5999940771db.png
