### ISSUE TITLE
SnapBridge

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9305]
**App Name:** SnapBridge
**Bundle ID:** com.nikon-image.SnapBridge
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1121563450">1121563450</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/snapbridge/id1121563450?mt=8&uo=4">https://itunes.apple.com/us/app/snapbridge/id1121563450?mt=8&uo=4</a>
**App Version:** 1.3.0
**Seller:** NIKON CORPORATION
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nikon-corporation/id299293370?uo=4">© Nikon Corporation</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple117/v4/78/66/2e/78662e65-9dd0-d859-cc31-116ad54c6764/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29396419-2e1b6e64-8318-11e7-89d8-d026f7225ccb.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29396419-2e1b6e64-8318-11e7-89d8-d026f7225ccb.png)
https://user-images.githubusercontent.com/2068130/29396419-2e1b6e64-8318-11e7-89d8-d026f7225ccb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29396444-3e9a3d2e-8318-11e7-928c-5414347eb005.png
