### ISSUE TITLE
AmpliFi WiFi

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9306]
**App Name:** AmpliFi WiFi
**Bundle ID:** com.ubnt.amplifi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1115225220">1115225220</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amplifi-wifi/id1115225220?mt=8&uo=4">https://itunes.apple.com/us/app/amplifi-wifi/id1115225220?mt=8&uo=4</a>
**App Version:** 1.6.0
**Seller:** Ubiquiti Networks, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ubiquiti-networks/id683620863?uo=4">© Ubiquiti Networks</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple117/v4/3a/14/ee/3a14eec6-c9bb-ffc7-3f46-299dd967a1f4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29427406-fe8e63f0-8389-11e7-9d46-f8a5cb34f22c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29427406-fe8e63f0-8389-11e7-9d46-f8a5cb34f22c.png)
https://user-images.githubusercontent.com/2068130/29427406-fe8e63f0-8389-11e7-9d46-f8a5cb34f22c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29427429-0e52a38c-838a-11e7-97f5-90e059fffbaa.png
