### ISSUE TITLE
Unread: RSS Reader

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9307]
**App Name:** Unread: RSS Reader
**Bundle ID:** com.goldenhillsoftware.Unread
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1252376153">1252376153</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/unread-rss-reader/id1252376153?mt=8&uo=4">https://itunes.apple.com/us/app/unread-rss-reader/id1252376153?mt=8&uo=4</a>
**App Version:** 1.7.1
**Seller:** John Brayton
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/golden-hill-software/id404445480?uo=4">© Golden Hill Software</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/45/0d/0a/450d0a07-628e-b478-c191-d5bd98cf00a8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29427580-8f785dd0-838a-11e7-83d1-dda9ebe70f6c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/29427580-8f785dd0-838a-11e7-83d1-dda9ebe70f6c.png)
https://user-images.githubusercontent.com/2068130/29427580-8f785dd0-838a-11e7-83d1-dda9ebe70f6c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/29427600-9f74a324-838a-11e7-8330-738893524449.png
