### ISSUE TITLE
Zurich Seguros ES

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9312]
**App Name:** Zurich Seguros ES
**Bundle ID:** zurich.seguros
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=485033181">485033181</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zurich-seguros-es/id485033181?mt=8&uo=4">https://itunes.apple.com/us/app/zurich-seguros-es/id485033181?mt=8&uo=4</a>
**App Version:** 4.8.2
**Seller:** Zurich Insurance Company Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/zurich-insurance-company-ltd/id366671743?uo=4">© Zurich Insurance Company Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple117/v4/f6/c0/d4/f6c0d458-2b36-27d9-a9a0-ce932ad4a947/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29668467-4aa5cb88-88ae-11e7-9eac-849a85f37a2c.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/29668467-4aa5cb88-88ae-11e7-9eac-849a85f37a2c.png)
https://user-images.githubusercontent.com/3090247/29668467-4aa5cb88-88ae-11e7-9eac-849a85f37a2c.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/29668468-4ab73df0-88ae-11e7-9f6c-85015fe52181.png
