### ISSUE TITLE
PDF Pro 3 – The ultimate PDF app

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9316]
**App Name:** PDF Pro 3 – The ultimate PDF app
**Bundle ID:** net.domzilla.pdfpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=454936656">454936656</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pdf-pro-3-the-ultimate-pdf-app/id454936656?mt=8&uo=4">https://itunes.apple.com/us/app/pdf-pro-3-the-ultimate-pdf-app/id454936656?mt=8&uo=4</a>
**App Version:** 3.6.1
**Seller:** Dominic Rodemer
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dominic-rodemer/id309872333?uo=4">© Dominic Rodemer</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/1d/bc/b1/1dbcb147-f308-bfe7-434e-c1f4557a49ba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29773402-a4520d02-8bfd-11e7-8fe2-ba1efb9d63f1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29773171-7c9fe3ac-8bfc-11e7-86f9-1c7ab4c64089.png)
https://user-images.githubusercontent.com/20930745/29773171-7c9fe3ac-8bfc-11e7-86f9-1c7ab4c64089.png

Source:
https://user-images.githubusercontent.com/20930745/29773195-91a3816e-8bfc-11e7-8cdd-74b61d495966.png
