### ISSUE TITLE
PDF Markup Ultimate - Annotate PDFs and Web Pages

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9317]
**App Name:** PDF Markup Ultimate - Annotate PDFs and Web Pages
**Bundle ID:** com.kdanmobile.universal.pdfreader
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=909254807">909254807</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pdf-markup-ultimate-annotate-pdfs-and-web-pages/id909254807?mt=8&uo=4">https://itunes.apple.com/us/app/pdf-markup-ultimate-annotate-pdfs-and-web-pages/id909254807?mt=8&uo=4</a>
**App Version:** 7.0
**Seller:** Kdan Mobile Software LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kdan-mobile-software-ltd/id318936474?uo=4">© Kdan Mobile Software LTD</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple127/v4/fd/f8/7a/fdf87af7-41eb-338c-87af-3cf4bfe31701/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29772622-ec157b6e-8bf9-11e7-8b4f-7cdf7f0e0c70.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29772622-ec157b6e-8bf9-11e7-8b4f-7cdf7f0e0c70.png)
https://user-images.githubusercontent.com/20930745/29772622-ec157b6e-8bf9-11e7-8b4f-7cdf7f0e0c70.png

Source:
https://user-images.githubusercontent.com/20930745/29772643-fd4088de-8bf9-11e7-8daa-655a47f15c83.png
