### ISSUE TITLE
Pocket Scanner Ultimate – PDF Scanner

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9318]
**App Name:** Pocket Scanner Ultimate – PDF Scanner
**Bundle ID:** com.kdanmobile.PocketScanner
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=359793767">359793767</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pocket-scanner-ultimate-pdf-scanner/id359793767?mt=8&uo=4">https://itunes.apple.com/us/app/pocket-scanner-ultimate-pdf-scanner/id359793767?mt=8&uo=4</a>
**App Version:** 3.7
**Seller:** Kdan Mobile Software LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kdan-mobile-software-ltd/id318936474?uo=4">© Kdan Mobile Software LTD</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/6a/a7/53/6aa75328-77b3-9fed-f7b5-b2377905484f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29772125-8d1504b0-8bf7-11e7-9e8f-6ea875a6b47c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29772125-8d1504b0-8bf7-11e7-9e8f-6ea875a6b47c.png)
https://user-images.githubusercontent.com/20930745/29772125-8d1504b0-8bf7-11e7-9e8f-6ea875a6b47c.png

Source:
https://user-images.githubusercontent.com/20930745/29772144-a05baefc-8bf7-11e7-91c2-434505ad9818.png
