### ISSUE TITLE
Outline – one note app to write, organize & print

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9319]
**App Name:** Outline – one note app to write, organize & print
**Bundle ID:** com.gorillized.outline
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=538029496">538029496</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/outline-one-note-app-to-write-organize-print/id538029496?mt=8&uo=4">https://itunes.apple.com/us/app/outline-one-note-app-to-write-organize-print/id538029496?mt=8&uo=4</a>
**App Version:** 3.21.1
**Seller:** GORILLIZED CORPORATION
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gorillized/id538029499?uo=4">© Gorillized</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple127/v4/2a/1f/31/2a1f3170-981e-b9cf-a943-7d1097080715/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29684819-9fb37764-8913-11e7-8191-7a076fbd89c9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29684819-9fb37764-8913-11e7-8191-7a076fbd89c9.png)
https://user-images.githubusercontent.com/20930745/29684819-9fb37764-8913-11e7-8191-7a076fbd89c9.png

Source:
https://user-images.githubusercontent.com/20930745/29684838-b1cc581c-8913-11e7-9998-c97b3fcc8145.png
