### ISSUE TITLE
nanoloop

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#932]
**App Name:** nanoloop
**Bundle ID:** com.nanoloop.nanoloop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=322700286">322700286</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nanoloop/id322700286?mt=8&uo=4">https://itunes.apple.com/us/app/nanoloop/id322700286?mt=8&uo=4</a>
**App Version:** 3.26
**Seller:** ume software, SP
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/ume-software-sp/id322700289?uo=4>© ume software, SP</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple5/v4/c1/20/92/c12092d0-c29b-c72c-34c6-b250d65f38f1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410679/8bad2098-92f2-11e6-9738-199f8f26d35a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410679/8bad2098-92f2-11e6-9738-199f8f26d35a.png)
https://cloud.githubusercontent.com/assets/20930745/19410679/8bad2098-92f2-11e6-9738-199f8f26d35a.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19410681/9de26728-92f2-11e6-8e66-416ac1f68639.png
