### ISSUE TITLE
Scores ◦

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9320]
**App Name:** Scores ◦
**Bundle ID:** com.logcabinapps.scores
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=704136889">704136889</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scores/id704136889?mt=8&uo=4">https://itunes.apple.com/us/app/scores/id704136889?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Log Cabin Apps LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/log-cabin-apps-llc/id630731052?uo=4">© Log Cabin Apps LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/df/94/20/df9420fb-39d4-b61f-34b0-ed60b82863ae/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29684455-52abe128-8912-11e7-81a9-572bef8cd830.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29684455-52abe128-8912-11e7-81a9-572bef8cd830.png)
https://user-images.githubusercontent.com/20930745/29684455-52abe128-8912-11e7-81a9-572bef8cd830.png

Source:
https://user-images.githubusercontent.com/20930745/29684483-6d7b2932-8912-11e7-8511-508d8732ebf7.png
