### ISSUE TITLE
ReBoard Keyboard + GIF & Themes

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9321]
**App Name:** ReBoard Keyboard + GIF & Themes
**Bundle ID:** com.gursimranjeet.ReBoard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=984982881">984982881</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/reboard-keyboard-gif-themes/id984982881?mt=8&uo=4">https://itunes.apple.com/us/app/reboard-keyboard-gif-themes/id984982881?mt=8&uo=4</a>
**App Version:** 3.0.2
**Seller:** Gursimranjeet Singh
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gursimranjeet-singh/id849782477?uo=4">© Gursimranjeet Singh</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple117/v4/3e/7d/ee/3e7dee20-8593-0d5d-59cd-6613d4797a48/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29771913-64b8f284-8bf6-11e7-927e-da6b44091742.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29771913-64b8f284-8bf6-11e7-927e-da6b44091742.png)
https://user-images.githubusercontent.com/20930745/29771913-64b8f284-8bf6-11e7-927e-da6b44091742.png

Source:
https://user-images.githubusercontent.com/20930745/29771930-7bc06d68-8bf6-11e7-8364-056204c8fd13.png
