### ISSUE TITLE
YO TV Guide

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9322]
**App Name:** YO TV Guide
**Bundle ID:** tv.yo.Yo-TV
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=522539108">522539108</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yo-tv-guide/id522539108?mt=8&uo=4">https://itunes.apple.com/us/app/yo-tv-guide/id522539108?mt=8&uo=4</a>
**App Version:** 6.14
**Seller:** Yo.TV Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yo-tv/id522539111?uo=4">© YO.TV</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/43/11/ac/4311acd3-9f91-4000-ffbf-3fed2ce6b2ea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29684263-9d3a84ca-8911-11e7-824d-da5812775e68.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/29684263-9d3a84ca-8911-11e7-824d-da5812775e68.png)
https://user-images.githubusercontent.com/20930745/29684263-9d3a84ca-8911-11e7-824d-da5812775e68.png

Source:
https://user-images.githubusercontent.com/20930745/29684292-aeea5b0a-8911-11e7-990b-001cbea1e0f4.png
