### ISSUE TITLE
Annotate+

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9323]
**App Name:** Annotate+
**Bundle ID:** com.brohawn.Annotation
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1227197910">1227197910</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/annotate/id1227197910?mt=8&uo=4">https://itunes.apple.com/us/app/annotate/id1227197910?mt=8&uo=4</a>
**App Version:** 10.1.10
**Seller:** yicai yang
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yicai-yang/id1016315440?uo=4">© yicai yang</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/a1/54/8d/a1548da3-236e-33f3-ef2f-25210d2124fc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38265299-b6cbf3f2-3775-11e8-869e-f718922d192b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/30343957-98fa065e-97ff-11e7-9c47-138d404df0af.png)
https://user-images.githubusercontent.com/2068130/30343957-98fa065e-97ff-11e7-9c47-138d404df0af.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/30343970-a970ef7a-97ff-11e7-9d57-8e1ece971dff.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Annotate+
**Bundle ID:** com.brohawn.Annotation
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1227197910">1227197910</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/annotate/id1227197910?mt=8&uo=4">https://itunes.apple.com/us/app/annotate/id1227197910?mt=8&uo=4</a>
**App Version:** 10.1.10
**Seller:** yicai yang
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yicai-yang/id1016315440?uo=4">© yicai yang</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/a1/54/8d/a1548da3-236e-33f3-ef2f-25210d2124fc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38265299-b6cbf3f2-3775-11e8-869e-f718922d192b.png)
https://user-images.githubusercontent.com/2068130/38265299-b6cbf3f2-3775-11e8-869e-f718922d192b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38265314-c9eadcf0-3775-11e8-955a-0e1d1e4067d7.png
