### ISSUE TITLE
SquadQL - Fantasy Sports

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9324]
**App Name:** SquadQL - Fantasy Sports
**Bundle ID:** com.rotoql.squadql
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1254173762">1254173762</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/squadql-fantasy-sports/id1254173762?mt=8&uo=4">https://itunes.apple.com/us/app/squadql-fantasy-sports/id1254173762?mt=8&uo=4</a>
**App Version:** 3.0.6
**Seller:** RotoQL, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rotoql/id1245785380?uo=4">© RotoQL</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/b3/30/86/b3308677-bef4-1c5f-7fd0-15d1a3d272e2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45231811-acaf2780-b2cd-11e8-95f1-97af8a2a04e2.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/30180129-76ab3be2-93d4-11e7-9b1f-9392b0c2f5cf.png)
https://user-images.githubusercontent.com/3090247/30180129-76ab3be2-93d4-11e7-9b1f-9392b0c2f5cf.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/30180128-76ab44c0-93d4-11e7-9ca3-a661d23c531d.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** SquadQL - Fantasy Sports
**Bundle ID:** com.rotoql.squadql
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1254173762">1254173762</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/squadql-fantasy-sports/id1254173762?mt=8&uo=4">https://itunes.apple.com/us/app/squadql-fantasy-sports/id1254173762?mt=8&uo=4</a>
**App Version:** 3.0.6
**Seller:** RotoQL, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rotoql/id1245785380?uo=4">© RotoQL</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/b3/30/86/b3308677-bef4-1c5f-7fd0-15d1a3d272e2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45231811-acaf2780-b2cd-11e8-95f1-97af8a2a04e2.png)
https://user-images.githubusercontent.com/2068130/45231811-acaf2780-b2cd-11e8-95f1-97af8a2a04e2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45231827-bd5f9d80-b2cd-11e8-8f0f-3a9c34c78742.png
