### ISSUE TITLE
Google Earth

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9325]
**App Name:** Google Earth
**Bundle ID:** com.google.b612
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=293622097">293622097</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-earth/id293622097?mt=8&uo=4">https://itunes.apple.com/us/app/google-earth/id293622097?mt=8&uo=4</a>
**App Version:** 9.0.79
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/google-inc/id281956209?uo=4">© Google, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/46/a2/3a/46a23abe-8df4-bc14-6c2c-467450c45a10/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/30342787-5bf4b938-97fb-11e7-9c3c-f9a8e0f7b4f1.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/30038410-ce957ec8-9189-11e7-8dda-184db7698660.png)
https://user-images.githubusercontent.com/3090247/30038410-ce957ec8-9189-11e7-8dda-184db7698660.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/30038411-ce95e2fa-9189-11e7-8210-d0ce533ee117.png

**Comment by dreamnet** [comment]
...hmmm...
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/30342787-5bf4b938-97fb-11e7-9c3c-f9a8e0f7b4f1.png)
https://user-images.githubusercontent.com/2068130/30342787-5bf4b938-97fb-11e7-9c3c-f9a8e0f7b4f1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/30342811-6ba81f00-97fb-11e7-8e57-faa4b8685090.png
