### ISSUE TITLE
Edmodo for Parents

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9327]
**App Name:** Edmodo for Parents
**Bundle ID:** com.edmodo.Parents
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=944465276">944465276</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/edmodo-for-parents/id944465276?uo=4">https://apps.apple.com/us/app/edmodo-for-parents/id944465276?uo=4</a>
**App Version:** 1.9.8
**Seller:** Edmodo, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/edmodo-inc/id378352303?uo=4">© Edmodo, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/c2/78/ff/c278ffe4-ae18-42d6-8f15-501f0b00bcf4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60389176-90c77d00-9abd-11e9-89bd-84f9561c0800.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/30170747-95f635fc-93b5-11e7-816c-cb776d36e507.png)
https://user-images.githubusercontent.com/3090247/30170747-95f635fc-93b5-11e7-816c-cb776d36e507.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/30170750-96954322-93b5-11e7-9890-b1506e17441d.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388360-9d91a400-9ab0-11e9-90a0-f13e22ddda06.png)
https://user-images.githubusercontent.com/20930745/60388360-9d91a400-9ab0-11e9-90a0-f13e22ddda06.png

Source:
https://user-images.githubusercontent.com/20930745/60388362-a1bdc180-9ab0-11e9-8af3-e750b0bfdd37.png

**Comment by dreamnet** [comment]
Because of #1768:
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60389176-90c77d00-9abd-11e9-89bd-84f9561c0800.png)
https://user-images.githubusercontent.com/2068130/60389176-90c77d00-9abd-11e9-89bd-84f9561c0800.png
Source:
https://user-images.githubusercontent.com/2068130/60389181-a50b7a00-9abd-11e9-8cca-762c45c0ff14.png
