### ISSUE TITLE
Palaver - IRC Client

### ISSUE THREAD

**Issue by alldayremix** [glasklart/hd#933]
**App Name:** Palaver - IRC Client
**Bundle ID:** com.kylefuller.palaver
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=538073623">538073623</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/palaver-irc-client/id538073623?mt=8&uo=4">https://itunes.apple.com/us/app/palaver-irc-client/id538073623?mt=8&uo=4</a>
**App Version:** 2.4.1
**Seller:** COCODE LTD
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/cocode-ltd/id369711524?uo=4>© COCODE LTD</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple30/v4/63/bc/7f/63bc7f4a-2c82-8f83-0179-611581116011/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410724/6b056fa2-92f3-11e6-8236-1d654afd741c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410724/6b056fa2-92f3-11e6-8236-1d654afd741c.png)
https://cloud.githubusercontent.com/assets/20930745/19410724/6b056fa2-92f3-11e6-8236-1d654afd741c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19410725/7ec98ed8-92f3-11e6-827d-eb0eadba37f0.png
