### ISSUE TITLE
El Gaaas

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9330]
**App Name:** El Gaaas
**Bundle ID:** Cuantum.CuantoGas
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1004672363">1004672363</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/el-gaaas/id1004672363?uo=4">https://apps.apple.com/us/app/el-gaaas/id1004672363?uo=4</a>
**App Version:** 5.1.3
**Seller:** EDISON EFFECT SA DE CV
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/edison-effect-sa-de-cv/id1456797133?uo=4">© EDISON EFFECT SA DE CV</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/e6/3d/50/e63d5033-037a-8133-f38b-0d3781a142f9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388411-6d96d080-9ab1-11e9-8d50-e47bb8c697b7.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32037115-e8a5ff6e-ba23-11e7-9ca9-d67fbb719c55.png)
https://user-images.githubusercontent.com/2068130/32037115-e8a5ff6e-ba23-11e7-9ca9-d67fbb719c55.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32037125-f8954e48-ba23-11e7-9451-8bb683a14853.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388411-6d96d080-9ab1-11e9-8d50-e47bb8c697b7.png)
https://user-images.githubusercontent.com/20930745/60388411-6d96d080-9ab1-11e9-8d50-e47bb8c697b7.png

Source:
https://user-images.githubusercontent.com/20930745/60388412-7091c100-9ab1-11e9-9019-2eb78192ba4f.png
