### ISSUE TITLE
Joom

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9331]
**App Name:** Joom
**Bundle ID:** com.joom.joom
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1117424833">1117424833</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/joom/id1117424833?mt=8&uo=4">https://itunes.apple.com/us/app/joom/id1117424833?mt=8&uo=4</a>
**App Version:** 1.17.1
**Seller:** Joom
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/joom/id1127769311?uo=4">© Joom</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/f5/9a/b9/f59ab9e3-fe74-0e1e-7d68-881cdfe87d42/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/30746778-3c9d2130-9fab-11e7-892d-76f8e61ef640.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/30746778-3c9d2130-9fab-11e7-892d-76f8e61ef640.png)
https://user-images.githubusercontent.com/20930745/30746778-3c9d2130-9fab-11e7-892d-76f8e61ef640.png

Source:
https://user-images.githubusercontent.com/20930745/30746805-59a2f41c-9fab-11e7-9331-e563ced1b4e7.png
