### ISSUE TITLE
Sunsky

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9332]
**App Name:** Sunsky
**Bundle ID:** com.sunsky
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=629085425">629085425</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sunsky/id629085425?mt=8&uo=4">https://itunes.apple.com/us/app/sunsky/id629085425?mt=8&uo=4</a>
**App Version:** 4.2.2
**Seller:** Shenzhen eForChina Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/shenzhen-sunsky-technology-limited/id629085428?uo=4">© ShenZhen SUNSKY Technology Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/eb/40/38/eb40387f-d80b-bb45-cdeb-18b2cadb7593/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31034084-d4802256-a562-11e7-954a-f2fafb1943c0.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31034084-d4802256-a562-11e7-954a-f2fafb1943c0.png)
https://user-images.githubusercontent.com/2068130/31034084-d4802256-a562-11e7-954a-f2fafb1943c0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/31034099-e3c45e3a-a562-11e7-9a48-a2c3d56b7f6a.png
