### ISSUE TITLE
Mein Schiff 4 Bordfinder [Icon Request]

### ISSUE THREAD

**Issue by punuoffi** [glasklart/hd#9334]
Great work! Can someone make an icon for Mein Schiff 4 Bordfinder App? [https://itunes.apple.com/de/app/mein-schiff-4-bordfinder/id1175575949?mt=8](url)

**Comment by ivanov007** [comment]
please follow this guide to make your [request](https://github.com/glasklart/hd/wiki/How-to-Submit-an-Icon-Request)

**Comment by punuoffi** [comment]
@ivanov007 thanks for the tutorial link. But how can I submit apps from Cydia?

**Comment by punuoffi** [comment]
@ivanov007 oh, just see the tutorial. Its Done.
