### ISSUE TITLE
Mein Schiff 4 Bordfinder

### ISSUE THREAD

**Issue by punuoffi** [glasklart/hd#9335]
**App Name:** Mein Schiff 4 Bordfinder
**Bundle ID:** com.victorlobe.meinschiff4
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1175575949">1175575949</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mein-schiff-4-bordfinder/id1175575949?mt=8&uo=4">https://itunes.apple.com/us/app/mein-schiff-4-bordfinder/id1175575949?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Victor Lobe
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/victor-lobe/id1175461065?uo=4">© Victor Lobe</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/11/b3/43/11b343a5-9bca-0c7a-196a-3b09a257c61c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31245574-11f34cba-aa0b-11e7-8a2e-d5ea121e637c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31245574-11f34cba-aa0b-11e7-8a2e-d5ea121e637c.png)
https://user-images.githubusercontent.com/2068130/31245574-11f34cba-aa0b-11e7-8a2e-d5ea121e637c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/31245587-20710e12-aa0b-11e7-8af5-2cf459c73007.png

**Comment by punuoffi** [comment]
@dreamnet very nice
