### ISSUE TITLE
Loxone Smart Home

### ISSUE THREAD

**Issue by punuoffi** [glasklart/hd#9336]
**App Name:** Loxone Smart Home
**Bundle ID:** com.loxone.kerberos
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=924399400">924399400</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/loxone-smart-home/id924399400?mt=8&uo=4">https://itunes.apple.com/us/app/loxone-smart-home/id924399400?mt=8&uo=4</a>
**App Version:** 9.0
**Seller:** Loxone Electronics GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/loxone-electronics-gmbh/id377003828?uo=4">© Loxone Electronics GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/b5/38/be/b538bef1-d1b4-26c3-f150-8f3470324fe0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31241559-7c098d32-aa04-11e7-8e0f-f2da83ee5752.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31241559-7c098d32-aa04-11e7-8e0f-f2da83ee5752.png)
https://user-images.githubusercontent.com/2068130/31241559-7c098d32-aa04-11e7-8e0f-f2da83ee5752.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/31241570-8b83624c-aa04-11e7-8e46-e51e4bf75bdb.png

**Comment by punuoffi** [comment]
@dreamnet this looks great
