### ISSUE TITLE
Jelly Bear

### ISSUE THREAD

**Issue by allliee** [glasklart/hd#934]
**App Name:** Jelly Bear
**Bundle ID:** com.7thplayground.jellybear
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=438199408">438199408</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jelly-bear/id438199408?mt=8&uo=4">https://itunes.apple.com/us/app/jelly-bear/id438199408?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Glen Poon
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/7th-playground/id371860732?uo=4">© 7th Playground</a>
**Supported Devices:** iPod-touch-with-mic, iPhone-3G, iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple/v4/a5/d2/0a/a5d20a15-1047-90b6-6a21-c66168395810/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20219477/e91f1654-a829-11e6-94ec-0e308c04bb59.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20219477/e91f1654-a829-11e6-94ec-0e308c04bb59.png)
https://cloud.githubusercontent.com/assets/20930745/20219477/e91f1654-a829-11e6-94ec-0e308c04bb59.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20219500/01a37440-a82a-11e6-8034-d5c20deb0917.png
