### ISSUE TITLE
CalcBuddy Calculator

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#9344]
**App Name:** CalcBuddy Calculator
**Bundle ID:** com.applicvision.CalcBuddy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=528375634">528375634</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calcbuddy-calculator/id528375634?mt=8&uo=4">https://itunes.apple.com/us/app/calcbuddy-calculator/id528375634?mt=8&uo=4</a>
**App Version:** 5.0
**Seller:** ApplicVision AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/applicvision/id528375637?uo=4">© ApplicVision</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/55/23/4a/55234aac-7351-4685-fa9c-0c72fa4b1249/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31332235-d2508f36-ace5-11e7-8c3f-e99104f15ce9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31332235-d2508f36-ace5-11e7-8c3f-e99104f15ce9.png)
https://user-images.githubusercontent.com/20930745/31332235-d2508f36-ace5-11e7-8c3f-e99104f15ce9.png

Source:
https://user-images.githubusercontent.com/20930745/31332255-e7adc024-ace5-11e7-90cf-297dce9bd0e2.png
