### ISSUE TITLE
Nordnet

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#9345]
**App Name:** Nordnet
**Bundle ID:** com.nordnet.Nordnet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=345038631">345038631</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nordnet/id345038631?mt=8&uo=4">https://itunes.apple.com/us/app/nordnet/id345038631?mt=8&uo=4</a>
**App Version:** 4.2.3
**Seller:** Nordnet Bank AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nordnet/id335774758?uo=4">© Nordnet</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/ab/d3/03/abd303c3-bc96-8387-6b02-5dbb34dbc5ee/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31332351-5d52aa74-ace6-11e7-9d82-cc7d209f8779.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31332351-5d52aa74-ace6-11e7-9d82-cc7d209f8779.png)
https://user-images.githubusercontent.com/20930745/31332351-5d52aa74-ace6-11e7-9d82-cc7d209f8779.png

Source:
https://user-images.githubusercontent.com/20930745/31332364-6da2f1c2-ace6-11e7-9ad6-5a551adbf886.png
