### ISSUE TITLE
Shareville

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#9346]
**App Name:** Shareville
**Bundle ID:** com.shareville.shareville
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1059715112">1059715112</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shareville/id1059715112?mt=8&uo=4">https://itunes.apple.com/us/app/shareville/id1059715112?mt=8&uo=4</a>
**App Version:** 1.1.3
**Seller:** Shareville AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/shareville-ab/id1059715111?uo=4">© Shareville AB</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/71/ad/01/71ad0136-8b94-3344-386a-49a1ff2edca6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31340816-a95b391a-ad07-11e7-91da-b361c544434c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31340816-a95b391a-ad07-11e7-91da-b361c544434c.png)
https://user-images.githubusercontent.com/20930745/31340816-a95b391a-ad07-11e7-91da-b361c544434c.png

Source:
https://user-images.githubusercontent.com/20930745/31340890-f49b11de-ad07-11e7-9b5e-533d90a90a40.png
