### ISSUE TITLE
Västtrafik To Go

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#9349]
**App Name:** Västtrafik To Go
**Bundle ID:** com.vaesttrafik.vaesttrafik
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=424903083">424903083</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/v%C3%A4sttrafik-to-go/id424903083?mt=8&uo=4">https://itunes.apple.com/us/app/v%C3%A4sttrafik-to-go/id424903083?mt=8&uo=4</a>
**App Version:** 2.10.2
**Seller:** Vasttrafik AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/v%C3%A4sttrafik-ab/id424903086?uo=4">© Västtrafik AB</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/70/50/9e/70509eed-6680-79be-ffd8-9c7764fd87e2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31341299-67d6d51a-ad09-11e7-9780-140b392c3f33.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31341299-67d6d51a-ad09-11e7-9780-140b392c3f33.png)
https://user-images.githubusercontent.com/20930745/31341299-67d6d51a-ad09-11e7-9780-140b392c3f33.png

Source:
https://user-images.githubusercontent.com/20930745/31341325-7e31a81c-ad09-11e7-81d4-0236d82765ee.png
