### ISSUE TITLE
Timehop - Memories Then & Now

### ISSUE THREAD

**Issue by NuckChorris** [glasklart/hd#935]
**App Name:** Timehop - Memories Then & Now
**Bundle ID:** com.timehop.ios.Timehop
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=569077959">569077959</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/timehop-memories-then-now/id569077959?uo=4">https://apps.apple.com/us/app/timehop-memories-then-now/id569077959?uo=4</a>
**App Version:** 4.10.0
**Seller:** TIMEHOP INC.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/timehop-inc/id569077962?uo=4">© TIMEHOP INC.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/25/b7/e3/25b7e312-0f22-41df-6209-88f8969051d1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73138601-cab52d80-4064-11ea-9401-32a935f38e7c.png)

**Comment by Mitchdog27** [comment]
possibly needs an update? the icon is that dinosaur guy now

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/73138601-cab52d80-4064-11ea-9401-32a935f38e7c.png)
https://user-images.githubusercontent.com/2068130/73138601-cab52d80-4064-11ea-9401-32a935f38e7c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/73138602-da347680-4064-11ea-9919-b2e10bb5a77c.png
