### ISSUE TITLE
Amazing Slow Downer Lite

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#9350]
**App Name:** Amazing Slow Downer Lite
**Bundle ID:** com.ronimusic.asdlite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=310204778">310204778</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amazing-slow-downer-lite/id310204778?mt=8&uo=4">https://itunes.apple.com/us/app/amazing-slow-downer-lite/id310204778?mt=8&uo=4</a>
**App Version:** 5.9.7
**Seller:** Roni Music
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/roni-music/id308998721?uo=4">© Roni Music</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple127/v4/3a/af/65/3aaf6578-b4b9-8b19-a90b-1dab027dc33b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31332762-f3bc6558-ace7-11e7-987c-4681432799c6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31332762-f3bc6558-ace7-11e7-987c-4681432799c6.png)
https://user-images.githubusercontent.com/20930745/31332762-f3bc6558-ace7-11e7-987c-4681432799c6.png

Source:
https://user-images.githubusercontent.com/20930745/31332788-08bd1ea2-ace8-11e7-93b9-d0acb9a7b9d2.png
