### ISSUE TITLE
Storytel

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#9351]
**App Name:** Storytel
**Bundle ID:** com.storytel.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=348177651">348177651</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/storytel/id348177651?mt=8&uo=4">https://itunes.apple.com/us/app/storytel/id348177651?mt=8&uo=4</a>
**App Version:** 4.8.1
**Seller:** Storytel AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/storytel-ab/id348177654?uo=4">© Storytel AB</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/49/e2/6c/49e26cf5-674a-bd51-474a-29105c2183fe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31332927-7babb086-ace8-11e7-8516-60503a5751b2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31332927-7babb086-ace8-11e7-8516-60503a5751b2.png)
https://user-images.githubusercontent.com/20930745/31332927-7babb086-ace8-11e7-8516-60503a5751b2.png

Source:
https://user-images.githubusercontent.com/20930745/31332937-8e4b7974-ace8-11e7-8678-13289de79f26.png
