### ISSUE TITLE
Browser and File Manager for Documents

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#9352]
**App Name:** Browser and File Manager for Documents
**Bundle ID:** com.eilvera.idwl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=979401801">979401801</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/browser-and-file-manager-for-documents/id979401801?mt=8&uo=4">https://itunes.apple.com/us/app/browser-and-file-manager-for-documents/id979401801?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** Eilvera UAB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/download-apps/id979401800?uo=4">© Download Apps</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple69/v4/58/d0/d0/58d0d001-d277-aee8-af3d-0d946e2f7009/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31333096-193975ea-ace9-11e7-8af5-cb299ae9ff6e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31333096-193975ea-ace9-11e7-8af5-cb299ae9ff6e.png)
https://user-images.githubusercontent.com/20930745/31333096-193975ea-ace9-11e7-8af5-cb299ae9ff6e.png

Source:
https://user-images.githubusercontent.com/20930745/31333125-2dd51f18-ace9-11e7-8e81-509379418221.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/31333447-739527ae-acea-11e7-84c9-2451768320fe.png)
https://user-images.githubusercontent.com/20930745/31333447-739527ae-acea-11e7-84c9-2451768320fe.png

Source:
https://user-images.githubusercontent.com/20930745/31333477-85acc460-acea-11e7-9414-02da7820aa8a.png
