### ISSUE TITLE
Fruit Ninja®

### ISSUE THREAD

**Issue by OstGlass** [glasklart/hd#9353]
**App Name:** Fruit Ninja®
**Bundle ID:** com.halfbrick.FruitNinjaLite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=403858572">403858572</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fruit-ninja/id403858572?mt=8&uo=4">https://itunes.apple.com/us/app/fruit-ninja/id403858572?mt=8&uo=4</a>
**App Version:** 2.5.5
**Seller:** Halfbrick
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/halfbrick-studios/id356994313?uo=4">© Halfbrick Studios</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/bc/39/fa/bc39fa4a-3892-ed4e-315e-20ede15c6f67/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19012523/cbfea9fe-87b8-11e6-9657-a8170b2a95cb.png)

**Comment by dreamnet** [comment]
Refers to #7595 . Icon by @2Qt2beStr8 .
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19012523/cbfea9fe-87b8-11e6-9657-a8170b2a95cb.png)
https://cloud.githubusercontent.com/assets/20930745/19012523/cbfea9fe-87b8-11e6-9657-a8170b2a95cb.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/20930745/19012525/d795d5da-87b8-11e6-80c4-57af611316d4.png
