### ISSUE TITLE
Пятёрочка

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9355]
**App Name:** Пятёрочка
**Bundle ID:** ru.5ka.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1174271758">1174271758</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/%D0%BF%D1%8F%D1%82%D1%91%D1%80%D0%BE%D1%87%D0%BA%D0%B0/id1174271758?mt=8&uo=4">https://itunes.apple.com/us/app/%D0%BF%D1%8F%D1%82%D1%91%D1%80%D0%BE%D1%87%D0%BA%D0%B0/id1174271758?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** AGROTORG, OOO
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/%D0%BF%D1%8F%D1%82%D1%91%D1%80%D0%BE%D1%87%D0%BA%D0%B0/id1174271757?uo=4">© Пятёрочка</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/9f/13/2c/9f132c4b-a865-c5b6-9f8c-965aac3ef71f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31853840-0750af50-b690-11e7-8f29-19c2905b453b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/31853840-0750af50-b690-11e7-8f29-19c2905b453b.png)
https://user-images.githubusercontent.com/2068130/31853840-0750af50-b690-11e7-8f29-19c2905b453b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/31853845-1803c3d2-b690-11e7-89fa-95ac5943aeab.png
