### ISSUE TITLE
Netatmo Energy

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#9358]
**App Name:** Netatmo Energy
**Bundle ID:** com.netatmo.thermostat
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=730893725">730893725</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/netatmo-energy/id730893725?uo=4">https://apps.apple.com/us/app/netatmo-energy/id730893725?uo=4</a>
**App Version:** 3.1.12
**Seller:** Netatmo
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/netatmo/id532538502?uo=4">© Netatmo</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/2a/b7/dc/2ab7dc51-e708-7781-059d-e733453b5a31/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85229355-85b1df00-b3e9-11ea-8755-05b7cbf0b6d0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32006721-d1b53d46-b9a7-11e7-956b-40d713a1608e.png)
https://user-images.githubusercontent.com/20930745/32006721-d1b53d46-b9a7-11e7-956b-40d713a1608e.png

Source:
https://user-images.githubusercontent.com/20930745/32006763-e76cd6da-b9a7-11e7-81ac-f9365f2ba257.png

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85229355-85b1df00-b3e9-11ea-8755-05b7cbf0b6d0.png)
https://user-images.githubusercontent.com/2068130/85229355-85b1df00-b3e9-11ea-8755-05b7cbf0b6d0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85229362-95312800-b3e9-11ea-8384-1b285ffa783a.png
