### ISSUE TITLE
Google Opinion Rewards

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9363]
**App Name:** Google Opinion Rewards
**Bundle ID:** com.google.paidtasks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1227019728">1227019728</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-opinion-rewards/id1227019728?mt=8&uo=4">https://itunes.apple.com/us/app/google-opinion-rewards/id1227019728?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/google-inc/id281956209?uo=4">© Google, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/91/55/f4/9155f4b9-4dd8-3ff4-b4b2-8d279a3c4d5b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32132868-47a76ec2-bbcc-11e7-83b8-447f2196b3ec.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32132868-47a76ec2-bbcc-11e7-83b8-447f2196b3ec.png)
https://user-images.githubusercontent.com/2068130/32132868-47a76ec2-bbcc-11e7-83b8-447f2196b3ec.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32132874-57372814-bbcc-11e7-94e0-438d1ac6c809.png
