### ISSUE TITLE
Must for Movies & TV

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9364]
**App Name:** Must for Movies & TV
**Bundle ID:** ru.ayyo.must
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1071382493">1071382493</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/must-for-movies-tv/id1071382493?mt=8&uo=4">https://itunes.apple.com/us/app/must-for-movies-tv/id1071382493?mt=8&uo=4</a>
**App Version:** 2.2.2
**Seller:** Must App Corp.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/must-app-corp/id1192354883?uo=4">© Must App Corp.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/b5/f2/36/b5f236af-59c4-2340-1c15-d6b614073143/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/46257614-11206980-c4bd-11e8-8545-56c1b1c3bf6d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32076095-1767a656-ba9f-11e7-95c2-ed913d53ed01.png)
https://user-images.githubusercontent.com/20930745/32076095-1767a656-ba9f-11e7-95c2-ed913d53ed01.png

Source:
https://user-images.githubusercontent.com/20930745/32076133-2e8ef6d6-ba9f-11e7-8777-b2bebec1759b.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/46257614-11206980-c4bd-11e8-8545-56c1b1c3bf6d.png)
https://user-images.githubusercontent.com/20930745/46257614-11206980-c4bd-11e8-8545-56c1b1c3bf6d.png

Source:
https://user-images.githubusercontent.com/20930745/46257622-23020c80-c4bd-11e8-8c58-da2312aa39a2.png
