### ISSUE TITLE
Magic Dialer Pro

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9365]
**App Name:** Magic Dialer Pro
**Bundle ID:** com.roxwin.dialer.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1226278564">1226278564</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/magic-dialer-pro/id1226278564?mt=8&uo=4">https://itunes.apple.com/us/app/magic-dialer-pro/id1226278564?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Roxwin Vietnam Technologies Company Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/roxwin-vietnam-technologies-company-limited/id1077249023?uo=4">© Roxwin Vietnam Technologies Company Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/2d/9c/81/2d9c81e5-f608-ee2c-d7dc-7cdb37ede3cd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32076312-d2390fba-ba9f-11e7-8fa8-5a4c014925e8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32076312-d2390fba-ba9f-11e7-8fa8-5a4c014925e8.png)
https://user-images.githubusercontent.com/20930745/32076312-d2390fba-ba9f-11e7-8fa8-5a4c014925e8.png

Source:
https://user-images.githubusercontent.com/20930745/32076340-e6e3c22a-ba9f-11e7-886c-a2e926ee9dd7.png
