### ISSUE TITLE
iCaller - T9 set, fast, search for contacts,secret

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9366]
**App Name:** iCaller - T9 set, fast, search for contacts,secret
**Bundle ID:** com.Kiraline.iCaller
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=593003940">593003940</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/icaller-t9-set-fast-search-for-contacts-secret/id593003940?mt=8&uo=4">https://itunes.apple.com/us/app/icaller-t9-set-fast-search-for-contacts-secret/id593003940?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** Kiraline Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kiraline-inc/id593003943?uo=4">© Kiraline Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/c1/bc/7f/c1bc7f30-8ffa-dd6c-c4f8-eed80991bf6d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32076520-823b30a0-baa0-11e7-84c8-a8dad5e5ef61.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32076520-823b30a0-baa0-11e7-84c8-a8dad5e5ef61.png)
https://user-images.githubusercontent.com/20930745/32076520-823b30a0-baa0-11e7-84c8-a8dad5e5ef61.png

Source:
https://user-images.githubusercontent.com/20930745/32076537-944f1270-baa0-11e7-85e8-1ed2b2507e90.png)
