### ISSUE TITLE
Whay: Shopping List Assistant

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9367]
**App Name:** Whay: Shopping List Assistant
**Bundle ID:** com.synble.whay
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1239465762">1239465762</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/whay-shopping-list-assistant/id1239465762?mt=8&uo=4">https://itunes.apple.com/us/app/whay-shopping-list-assistant/id1239465762?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Synble Oy
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/synble/id649950564?uo=4">© Synble</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/47/51/fb/4751fb02-c0b1-c4de-67c3-46cfe24eabe9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32076879-c1aa7bfa-baa1-11e7-9242-35d9b6fed5a8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32076879-c1aa7bfa-baa1-11e7-9242-35d9b6fed5a8.png)
https://user-images.githubusercontent.com/20930745/32076879-c1aa7bfa-baa1-11e7-9242-35d9b6fed5a8.png

Source:
https://user-images.githubusercontent.com/20930745/32076899-d46e48a2-baa1-11e7-8bb2-58aaeaede565.png
