### ISSUE TITLE
MyGrocery Shopping List

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9368]
**App Name:** MyGrocery Shopping List
**Bundle ID:** com.macropinch.Jaeger
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=867500392">867500392</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mygrocery-shopping-list/id867500392?mt=8&uo=4">https://itunes.apple.com/us/app/mygrocery-shopping-list/id867500392?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** MacroPinch ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/macropinch-ltd/id441079432?uo=4">© MacroPinch Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/86/04/6b/86046bde-da44-9be4-4b11-ba85d6659539/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32123832-004caa44-bb66-11e7-8b1f-c6d6df808388.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32123832-004caa44-bb66-11e7-8b1f-c6d6df808388.png)
https://user-images.githubusercontent.com/20930745/32123832-004caa44-bb66-11e7-8b1f-c6d6df808388.png

Source:
https://user-images.githubusercontent.com/20930745/32123857-12c48c32-bb66-11e7-9336-73d1398232ba.png
