### ISSUE TITLE
Dribbble

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9370]
**App Name:** Dribbble
**Bundle ID:** com.dribbble.dribbble
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1228326440">1228326440</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dribbble/id1228326440?mt=8&uo=4">https://itunes.apple.com/us/app/dribbble/id1228326440?mt=8&uo=4</a>
**App Version:** 1.1.7
**Seller:** Dribbble Holdings Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dribbble-holdings-ltd/id1228326439?uo=4">© Dribbble Holdings Ltd.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/54/53/7a/54537a7c-6bfa-7f0a-b36f-c2ea0f9ca8f1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32121693-fbb82042-bb5d-11e7-9b3e-f9aa6670bd73.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32121693-fbb82042-bb5d-11e7-9b3e-f9aa6670bd73.png)
https://user-images.githubusercontent.com/20930745/32121693-fbb82042-bb5d-11e7-9b3e-f9aa6670bd73.png

Source:
https://user-images.githubusercontent.com/20930745/32121711-0dad6032-bb5e-11e7-9fba-a8bdecc97609.png
