### ISSUE TITLE
Better Notes + Lists and Todos

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9371]
**App Name:** Better Notes + Lists and Todos
**Bundle ID:** com.walksoft.SFN
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=980887055">980887055</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/better-notes-lists-and-todos/id980887055?mt=8&uo=4">https://itunes.apple.com/us/app/better-notes-lists-and-todos/id980887055?mt=8&uo=4</a>
**App Version:** 0.8.12
**Seller:** Better Notes, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/better-notes-llc/id360256774?uo=4">© Better Notes, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/96/15/5c/96155c5b-3d02-a3bf-5be8-b910905d6ce9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32121911-cec769e8-bb5e-11e7-83f9-604d0137ce44.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32121911-cec769e8-bb5e-11e7-83f9-604d0137ce44.png)
https://user-images.githubusercontent.com/20930745/32121911-cec769e8-bb5e-11e7-83f9-604d0137ce44.png

Source:
https://user-images.githubusercontent.com/20930745/32121921-e1afa548-bb5e-11e7-8f62-6a0bac02a26c.png
