### ISSUE TITLE
Cirkus: Task Management

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9372]
**App Name:** Cirkus: Task Management
**Bundle ID:** com.farmerswife.cirkus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1157319715">1157319715</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cirkus-task-management/id1157319715?mt=8&uo=4">https://itunes.apple.com/us/app/cirkus-task-management/id1157319715?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Farmers WIFE S.L.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/farmerswife/id571048737?uo=4">© farmerswife</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/67/57/5e/67575e6e-9e4f-c729-72b0-a87f9b8c3c45/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32125209-1b328734-bb6b-11e7-8027-ec6f4ed83ca0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32125209-1b328734-bb6b-11e7-8027-ec6f4ed83ca0.png)
https://user-images.githubusercontent.com/20930745/32125209-1b328734-bb6b-11e7-8027-ec6f4ed83ca0.png

Source:
https://user-images.githubusercontent.com/20930745/32125229-35e37430-bb6b-11e7-9938-6e384a47a43b.png
