### ISSUE TITLE
Sago Mini World

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9373]
**App Name:** Sago Mini World
**Bundle ID:** com.sagosago.Friends
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=874425722">874425722</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sago-mini-world/id874425722?mt=8&uo=4">https://itunes.apple.com/us/app/sago-mini-world/id874425722?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Sago Sago Toys Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sago-mini/id640702079?uo=4">© Sago Mini</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/7b/d1/45/7bd145a5-fd76-30f9-12cb-4e78353c39a1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32124897-ea323c84-bb69-11e7-8564-06cfd3ab1690.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32124897-ea323c84-bb69-11e7-8564-06cfd3ab1690.png)
https://user-images.githubusercontent.com/20930745/32124897-ea323c84-bb69-11e7-8564-06cfd3ab1690.png

Source:
https://user-images.githubusercontent.com/20930745/32124915-fedee466-bb69-11e7-994a-24ea53198eb5.png
