### ISSUE TITLE
Skullgirls

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9374]
**App Name:** Skullgirls
**Bundle ID:** com.linecorp.LGGIRLS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1098137253">1098137253</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skullgirls/id1098137253?mt=8&uo=4">https://itunes.apple.com/us/app/skullgirls/id1098137253?mt=8&uo=4</a>
**App Version:** 1.5.0
**Seller:** LINE Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/line-corporation/id359067226?uo=4">© LINE Corporation</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/24/21/bf/2421bf2e-c811-4412-8fd3-b721673363d7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32132360-c842772a-bbc2-11e7-9281-f2c7b19b13c2.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32132360-c842772a-bbc2-11e7-9281-f2c7b19b13c2.png)
https://user-images.githubusercontent.com/2068130/32132360-c842772a-bbc2-11e7-9281-f2c7b19b13c2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32132363-d6cdb0de-bbc2-11e7-8081-f326d8dcf1dd.png
