### ISSUE TITLE
FanDuel Scout

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9375]
**App Name:** FanDuel Scout
**Bundle ID:** com.fanduel.scout
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1275873422">1275873422</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fanduel-scout/id1275873422?mt=8&uo=4">https://itunes.apple.com/us/app/fanduel-scout/id1275873422?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** FanDuel Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fanduel-inc/id599664829?uo=4">© FanDuel, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/e6/df/03/e6df03ef-77f7-a64f-f63c-c2bc924676c3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32122425-901006a4-bb60-11e7-845f-a7f6b5740ee2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32122425-901006a4-bb60-11e7-845f-a7f6b5740ee2.png)
https://user-images.githubusercontent.com/20930745/32122425-901006a4-bb60-11e7-845f-a7f6b5740ee2.png

Source:
https://user-images.githubusercontent.com/20930745/32122460-a8ef80a0-bb60-11e7-89ca-94f180456d7c.png
