### ISSUE TITLE
Basic Calc Pro - Calculator faithful to the basics

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9376]
**App Name:** Basic Calc Pro - Calculator faithful to the basics
**Bundle ID:** com.superdg.basiccalcpro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=821421514">821421514</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/basic-calc-pro-calculator-faithful-to-the-basics/id821421514?mt=8&uo=4">https://itunes.apple.com/us/app/basic-calc-pro-calculator-faithful-to-the-basics/id821421514?mt=8&uo=4</a>
**App Version:** 3.0.2
**Seller:** SuperDG Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/superdg-inc/id635709768?uo=4">© SuperDG Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple117/v4/de/fa/4b/defa4b6e-5152-c28e-20ae-386ee5deb9e7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32124037-b85c84b0-bb66-11e7-9e4b-36eb8a18ad8f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32124037-b85c84b0-bb66-11e7-9e4b-36eb8a18ad8f.png)
https://user-images.githubusercontent.com/20930745/32124037-b85c84b0-bb66-11e7-9e4b-36eb8a18ad8f.png

Source:
https://user-images.githubusercontent.com/20930745/32124075-d369fe18-bb66-11e7-829f-09190775e2c9.png
