### ISSUE TITLE
Tasty

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9377]
**App Name:** Tasty
**Bundle ID:** com.buzzfeed.tasty
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1217456898">1217456898</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tasty/id1217456898?mt=8&uo=4">https://itunes.apple.com/us/app/tasty/id1217456898?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** BuzzFeed
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/buzzfeed/id352970000?uo=4">© BuzzFeed</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/23/d0/06/23d006dd-ed11-4e32-52a2-8af58735d6f4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32132431-ba1769b6-bbc3-11e7-804d-42e1e2fef8e6.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32132431-ba1769b6-bbc3-11e7-804d-42e1e2fef8e6.png)
https://user-images.githubusercontent.com/2068130/32132431-ba1769b6-bbc3-11e7-804d-42e1e2fef8e6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32132442-c9065298-bbc3-11e7-885d-8fcb1a21544c.png
