### ISSUE TITLE
Enero - Review and rating tracking for apps

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9379]
**App Name:** Enero - Review and rating tracking for apps
**Bundle ID:** com.robmaceachern.enero
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=963559212">963559212</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/enero-review-and-rating-tracking-for-apps/id963559212?mt=8&uo=4">https://itunes.apple.com/us/app/enero-review-and-rating-tracking-for-apps/id963559212?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Black Tusk Software Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/black-tusk-software-inc/id645771982?uo=4">© Black Tusk Software Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple117/v4/14/03/41/14034114-25ce-b7c6-39dd-bac7b1c87a57/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32134979-9eb42e8c-bbf7-11e7-8146-21e0b4f5c5a2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32134979-9eb42e8c-bbf7-11e7-8146-21e0b4f5c5a2.png)
https://user-images.githubusercontent.com/20930745/32134979-9eb42e8c-bbf7-11e7-8146-21e0b4f5c5a2.png

Source:
https://user-images.githubusercontent.com/20930745/32134982-b0519652-bbf7-11e7-92f0-2f2f3e874fb4.png
