### ISSUE TITLE
Weather Crave

### ISSUE THREAD

**Issue by gaetan-petit** [glasklart/hd#938]
**App Name:** Weather Crave
**Bundle ID:** com.lachainemeteo.appli
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=324565014">324565014</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-crave/id324565014?mt=8&uo=4">https://itunes.apple.com/us/app/weather-crave/id324565014?mt=8&uo=4</a>
**App Version:** 6.0.1
**Seller:** METEO CONSULT
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/meteo-consult/id324565017?uo=4">© METEO CONSULT</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/55/6c/bb/556cbb49-e685-49d8-9990-08d7136a0334/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38535041-f86facca-3c81-11e8-84f3-f4f189b8a683.png)

**Comment by 2Qt2beStr8** [comment]
no idea for this Icon :-(

![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38517425-450a970e-3c3a-11e8-92cb-1cb886a1e0e0.png)
https://user-images.githubusercontent.com/20930745/38517425-450a970e-3c3a-11e8-92cb-1cb886a1e0e0.png

Source
https://user-images.githubusercontent.com/20930745/38517440-5134fd62-3c3a-11e8-8db2-cc68cd2ccdcf.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38517649-ecf3ddcc-3c3a-11e8-9923-417b7aeb31b3.png)
https://user-images.githubusercontent.com/20930745/38517649-ecf3ddcc-3c3a-11e8-9923-417b7aeb31b3.png

Source:
https://user-images.githubusercontent.com/20930745/38517680-fdecf6b8-3c3a-11e8-9f6d-e95ebb171fc8.png

**Comment by dreamnet** [comment]
Another idea:
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38535041-f86facca-3c81-11e8-84f3-f4f189b8a683.png)
https://user-images.githubusercontent.com/2068130/38535041-f86facca-3c81-11e8-84f3-f4f189b8a683.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38535059-08a7f6e2-3c82-11e8-9a7d-56a8ab502be5.png
