### ISSUE TITLE
Streaks

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9380]
**App Name:** Streaks
**Bundle ID:** com.streaksapp.streak
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=963034692">963034692</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/streaks/id963034692?mt=8&uo=4">https://itunes.apple.com/us/app/streaks/id963034692?mt=8&uo=4</a>
**App Version:** 3.1.4
**Seller:** Crunchy Bagel Pty Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/crunchy-bagel/id1084571682?uo=4">© Crunchy Bagel</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple122/v4/6c/cb/5b/6ccb5bfa-eb2c-0b17-0a2b-b3fa6968e00b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32135031-7aeadc70-bbf8-11e7-97bc-9eae997e4dd7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32135031-7aeadc70-bbf8-11e7-97bc-9eae997e4dd7.png)
https://user-images.githubusercontent.com/20930745/32135031-7aeadc70-bbf8-11e7-97bc-9eae997e4dd7.png

Source:
https://user-images.githubusercontent.com/20930745/32135037-8f466ef0-bbf8-11e7-8680-f11930a5b14a.png
