### ISSUE TITLE
Bowflex® Max Trainer® 2

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9381]
**App Name:** Bowflex® Max Trainer® 2
**Bundle ID:** com.nautilus.maxtrainer2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1066433013">1066433013</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bowflex-max-trainer-2/id1066433013?mt=8&uo=4">https://itunes.apple.com/us/app/bowflex-max-trainer-2/id1066433013?mt=8&uo=4</a>
**App Version:** 1.5.0
**Seller:** Nautilus, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bowflex/id598794983?uo=4">© Bowflex</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/b6/35/46/b6354664-0677-1656-e462-2dd99c9730ae/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32135655-ebc34978-bc02-11e7-9b88-46d9d1cad543.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32135655-ebc34978-bc02-11e7-9b88-46d9d1cad543.png)
https://user-images.githubusercontent.com/20930745/32135655-ebc34978-bc02-11e7-9b88-46d9d1cad543.png

Source:
https://user-images.githubusercontent.com/20930745/32135662-fc893718-bc02-11e7-8ad2-c5fcbadb3bf2.png
