### ISSUE TITLE
HomeDash

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9382]
**App Name:** HomeDash
**Bundle ID:** com.marcusreul.lumify
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1003033186">1003033186</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/homedash/id1003033186?mt=8&uo=4">https://itunes.apple.com/us/app/homedash/id1003033186?mt=8&uo=4</a>
**App Version:** 2.2.0
**Seller:** Marcus Reul
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/marcus-reul/id1003033185?uo=4">© Marcus Reul</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/15/46/84/15468455-3cc0-e283-644a-ea0e8f26ec10/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32135287-b17b177e-bbfc-11e7-923a-9b851ee48eba.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32135287-b17b177e-bbfc-11e7-923a-9b851ee48eba.png)
https://user-images.githubusercontent.com/20930745/32135287-b17b177e-bbfc-11e7-923a-9b851ee48eba.png

Sourc:e:
https://user-images.githubusercontent.com/20930745/32135294-c538d2a6-bbfc-11e7-8b60-8e0857249f1e.png
