### ISSUE TITLE
The Home Remote

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9383]
**App Name:** The Home Remote
**Bundle ID:** com.thehomeremote.homeremote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1015015446">1015015446</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/the-home-remote/id1015015446?uo=4">https://apps.apple.com/us/app/the-home-remote/id1015015446?uo=4</a>
**App Version:** 3.0.18
**Seller:** The Home Remote LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/the-home-remote-llc/id1015015445?uo=4">© The Home Remote LLC</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/38/6f/bf/386fbf08-e3a6-ae90-f23f-d50954d36120/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/80416923-319ce980-88d5-11ea-9e65-658d171a8021.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32135073-2bf87f90-bbf9-11e7-97b1-626f6fce8a4f.png)
https://user-images.githubusercontent.com/20930745/32135073-2bf87f90-bbf9-11e7-97b1-626f6fce8a4f.png

Source:
https://user-images.githubusercontent.com/20930745/32135078-3e96fa0a-bbf9-11e7-8359-aadf83c40bb2.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** The Home Remote
**Bundle ID:** com.thehomeremote.homeremote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1015015446">1015015446</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/the-home-remote/id1015015446?uo=4">https://apps.apple.com/us/app/the-home-remote/id1015015446?uo=4</a>
**App Version:** 3.0.18
**Seller:** The Home Remote LLC
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/the-home-remote-llc/id1015015445?uo=4">© The Home Remote LLC</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/38/6f/bf/386fbf08-e3a6-ae90-f23f-d50954d36120/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/80416923-319ce980-88d5-11ea-9e65-658d171a8021.png)
https://user-images.githubusercontent.com/2068130/80416923-319ce980-88d5-11ea-9e65-658d171a8021.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/80416964-424d5f80-88d5-11ea-8c16-ebfc5824bcd1.png
