### ISSUE TITLE
Haystack TV News – Watch Live, Local & World News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9384]
**App Name:** Haystack TV News – Watch Live, Local & World News
**Bundle ID:** com.haystack.HaystackApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=829825445">829825445</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/haystack-tv-news-watch-live-local-world-news/id829825445?mt=8&uo=4">https://itunes.apple.com/us/app/haystack-tv-news-watch-live-local-world-news/id829825445?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Haystack TV, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/haystack-tv/id829825448?uo=4">© Haystack TV</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple127/v4/bb/af/fe/bbaffefc-4653-bc0d-fa8b-a4b368d6dfc2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32135107-c9d275b8-bbf9-11e7-8b0e-bc3d6e20bb2b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32135107-c9d275b8-bbf9-11e7-8b0e-bc3d6e20bb2b.png)
https://user-images.githubusercontent.com/20930745/32135107-c9d275b8-bbf9-11e7-8b0e-bc3d6e20bb2b.png

Source:
https://user-images.githubusercontent.com/20930745/32135122-dd58fbac-bbf9-11e7-94dc-d6d2112bae40.png
