### ISSUE TITLE
Apollo for Reddit

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9385]
**App Name:** Apollo for Reddit
**Bundle ID:** com.christianselig.Apollo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=979274575">979274575</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/apollo-for-reddit/id979274575?mt=8&uo=4">https://itunes.apple.com/us/app/apollo-for-reddit/id979274575?mt=8&uo=4</a>
**App Version:** 1.1.9
**Seller:** Christian Selig
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/christian-selig/id687795558?uo=4">© Christian Selig</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/c2/4a/ff/c24aff5e-8383-fdbf-96c0-4ee5482d077d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38458670-05571f8c-3aa1-11e8-9515-8899c522a309.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32135402-fcfa0636-bbfe-11e7-8d02-794b60515ea6.png)
https://user-images.githubusercontent.com/20930745/32135402-fcfa0636-bbfe-11e7-8d02-794b60515ea6.png

Source:
https://user-images.githubusercontent.com/20930745/32135406-109b21b6-bbff-11e7-9d15-5fdcbf07b85e.png

**Comment by dreamnet** [comment]
Icon needs an update.
