### ISSUE TITLE
Bible

### ISSUE THREAD

**Issue by TheEpicPie3** [glasklart/hd#9386]
**App Name:** Bible
**Bundle ID:** tv.lifechurch.bible
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=282935706">282935706</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bible/id282935706?mt=8&uo=4">https://itunes.apple.com/us/app/bible/id282935706?mt=8&uo=4</a>
**App Version:** 7.7 
**Seller:** Life.Church
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/life-church/id282935709?uo=4">© Life.Church</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/89/d3/5b/89d35b80-f525-1e0f-a474-d1ee85ff9c97/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32142224-b94f8ec6-bc92-11e7-9bb6-238ef651bb6b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32142224-b94f8ec6-bc92-11e7-9bb6-238ef651bb6b.png)
https://user-images.githubusercontent.com/20930745/32142224-b94f8ec6-bc92-11e7-9bb6-238ef651bb6b.png

Source:
https://user-images.githubusercontent.com/20930745/32142227-d01c175a-bc92-11e7-82ec-bd8fb80f09fd.png
