### ISSUE TITLE
Birthday Sweet - Birthday calendar & reminder for Facebook

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#9387]
**App Name:** Birthday Sweet - Birthday calendar & reminder for Facebook
**Bundle ID:** com.bestsparks.birthdaycalendar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=367346406">367346406</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/birthday-sweet-birthday-calendar-reminder-for-facebook/id367346406?mt=8&uo=4">https://itunes.apple.com/us/app/birthday-sweet-birthday-calendar-reminder-for-facebook/id367346406?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Express Network Solutions Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/express-network-solutions-limited/id367346409?uo=4">© Express Network Solutions Limited</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/96/f4/25/96f4250a-3e21-fb17-6c65-a213e13d4aa6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32141995-7b370276-bc8e-11e7-9c04-2e60b7cd7a98.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32141995-7b370276-bc8e-11e7-9c04-2e60b7cd7a98.png)
https://user-images.githubusercontent.com/20930745/32141995-7b370276-bc8e-11e7-9c04-2e60b7cd7a98.png

Source:
https://user-images.githubusercontent.com/20930745/32141999-8dab8f26-bc8e-11e7-99d0-0a89406c7172.png
