### ISSUE TITLE
Public : news, actus, buzz et infos people

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#94]
**App Name:** Public : news, actus, buzz et infos people
**Bundle ID:** com.lagardere.public
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=308310131">308310131</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/public-news-actus-buzz-et-infos-people/id308310131?mt=8&uo=4">https://itunes.apple.com/us/app/public-news-actus-buzz-et-infos-people/id308310131?mt=8&uo=4</a>
**App Version:** 3.1.4
**Seller:** LAGARDERE ACTIVE DIGITAL
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lagard%C3%A8re-active-digital/id308310134?uo=4">© Lagardère Active Digital</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/24/fd/ed/24fdeddb-ee0a-1250-827c-b84058c1f4d4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692587-065e5700-c71b-11e7-8f1c-ac17ec4e4643.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692587-065e5700-c71b-11e7-8f1c-ac17ec4e4643.png)
https://user-images.githubusercontent.com/2068130/32692587-065e5700-c71b-11e7-8f1c-ac17ec4e4643.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32692593-15568bec-c71b-11e7-8da6-2817fdd8b114.png
