### ISSUE TITLE
Kickstarter

### ISSUE THREAD

**Issue by rentiak** [glasklart/hd#940]
**App Name:** Kickstarter
**Bundle ID:** com.kickstarter.kickstarter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=596961532">596961532</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kickstarter/id596961532?mt=8&uo=4">https://itunes.apple.com/us/app/kickstarter/id596961532?mt=8&uo=4</a>
**App Version:** 3.8
**Seller:** Kickstarter, PBC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kickstarter-pbc/id596961535?uo=4">© Kickstarter, PBC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/93/c4/e9/93c4e99c-6b63-f093-d20c-2448507211e0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/3090247/32849970-5fad8f32-c9f6-11e7-8fe8-950f68374c59.png)

**Comment by Trubbel** [comment]
Updating the icon,

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/11450458/9156f85c-95a0-11e5-8e9b-c36560301c20.png)
https://cloud.githubusercontent.com/assets/10730122/11450458/9156f85c-95a0-11e5-8e9b-c36560301c20.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/11450457/8de78272-95a0-11e5-9028-d117df1bbff9.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Kickstarter
**Bundle ID:** com.kickstarter.kickstarter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=596961532">596961532</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kickstarter/id596961532?mt=8&uo=4">https://itunes.apple.com/us/app/kickstarter/id596961532?mt=8&uo=4</a>
**App Version:** 3.8
**Seller:** Kickstarter, PBC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kickstarter-pbc/id596961535?uo=4">© Kickstarter, PBC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/93/c4/e9/93c4e99c-6b63-f093-d20c-2448507211e0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by ivanov007** [comment]
wow seems new icon has being eating too much 🤣

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/3090247/32849970-5fad8f32-c9f6-11e7-8fe8-950f68374c59.png)
https://user-images.githubusercontent.com/3090247/32849970-5fad8f32-c9f6-11e7-8fe8-950f68374c59.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/32849971-5fd80de8-c9f6-11e7-8e64-0f17bde3ffe4.png

**Comment by l8er4now** [comment]
Looks horrible but blame it kickstarter.
