### ISSUE TITLE
Cubles: colorful puzzle action!

### ISSUE THREAD

**Issue by alderz** [glasklart/hd#941]
**App Name:** Cubles: colorful puzzle action!
**Bundle ID:** com.jollyjellyfish.games.cubles
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=583918921">583918921</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cubles-colorful-puzzle-action!/id583918921?mt=8&uo=4">https://itunes.apple.com/us/app/cubles-colorful-puzzle-action!/id583918921?mt=8&uo=4</a>
**App Version:** 1.0.15
**Seller:** Yuntao Zhou
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yuntao-zhou/id672991993?uo=4">© Yuntao Zhou</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple4/v4/c8/a0/9c/c8a09cce-0fed-91cf-eac9-1d8a2be0fb2f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20219814/563fa3b0-a82b-11e6-9b3d-de1668e5b6c0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20219814/563fa3b0-a82b-11e6-9b3d-de1668e5b6c0.png)
https://cloud.githubusercontent.com/assets/20930745/20219814/563fa3b0-a82b-11e6-9b3d-de1668e5b6c0.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20219840/72d61c2a-a82b-11e6-9967-c5ba39f89d0f.png
