### ISSUE TITLE
Sidekix: Urban Navigation

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9419]
**App Name:** Sidekix: Urban Navigation
**Bundle ID:** com.sidekix.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1060013635">1060013635</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sidekix-urban-navigation/id1060013635?mt=8&uo=4">https://itunes.apple.com/us/app/sidekix-urban-navigation/id1060013635?mt=8&uo=4</a>
**App Version:** 3.93
**Seller:** Wego As one Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wego-as-one-ltd/id991761226?uo=4">© WEGO as one Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/ea/9e/50/ea9e5081-bb8b-b574-de39-8a346ec2442d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32145456-3e3db1e0-bcc9-11e7-9e5e-5c1af85b9f24.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32145456-3e3db1e0-bcc9-11e7-9e5e-5c1af85b9f24.png)
https://user-images.githubusercontent.com/20930745/32145456-3e3db1e0-bcc9-11e7-9e5e-5c1af85b9f24.png

Source:
https://user-images.githubusercontent.com/20930745/32145458-5032e92e-bcc9-11e7-8f2c-a9781c109815.png
