### ISSUE TITLE
Magic Earth Navigation & Maps

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9420]
**App Name:** Magic Earth Navigation & Maps
**Bundle ID:** com.generalmagic.magicearth
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1007331679">1007331679</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/magic-earth-navigation-maps/id1007331679?mt=8&uo=4">https://itunes.apple.com/us/app/magic-earth-navigation-maps/id1007331679?mt=8&uo=4</a>
**App Version:** 4.0.0
**Seller:** General Magic GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/general-magic-gmbh/id342995675?uo=4">© General Magic GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/2b/fd/ae/2bfdaec8-1334-579a-626a-228affec4a02/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32145389-f86c146e-bcc7-11e7-8203-95fe4eda1375.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32145389-f86c146e-bcc7-11e7-8203-95fe4eda1375.png)
https://user-images.githubusercontent.com/20930745/32145389-f86c146e-bcc7-11e7-8203-95fe4eda1375.png

Source:
https://user-images.githubusercontent.com/20930745/32145397-0c096a80-bcc8-11e7-95c0-7bf2df731f55.png
