### ISSUE TITLE
TASKING - The Final Boss of Task Management

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9421]
**App Name:** TASKING - The Final Boss of Task Management
**Bundle ID:** com.favorie.task.TASK
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1089440544">1089440544</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tasking-the-final-boss-of-task-management/id1089440544?mt=8&uo=4">https://itunes.apple.com/us/app/tasking-the-final-boss-of-task-management/id1089440544?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Favorie, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/favorie-inc/id842529489?uo=4">© Favorie, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/56/44/70/564470e3-c25a-7206-7d3a-8601f76ec768/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32145363-69ab5c58-bcc7-11e7-92ef-0ef7bd06f629.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32145363-69ab5c58-bcc7-11e7-92ef-0ef7bd06f629.png)
https://user-images.githubusercontent.com/20930745/32145363-69ab5c58-bcc7-11e7-92ef-0ef7bd06f629.png

Source:
https://user-images.githubusercontent.com/20930745/32145367-79fd285c-bcc7-11e7-8834-62ae2f0d4661.png
