### ISSUE TITLE
Todayday

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9422]
**App Name:** Todayday
**Bundle ID:** app.dp.todayday
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1263495434">1263495434</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/todayday/id1263495434?mt=8&uo=4">https://itunes.apple.com/us/app/todayday/id1263495434?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Damian Plak
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/damian-plak/id1188445389?uo=4">© Damian Plak</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/21/f5/7c/21f57c75-8673-323b-57f7-0b6289afcad2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32145320-c82e4ab6-bcc6-11e7-89a5-111d050a7df6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32145320-c82e4ab6-bcc6-11e7-89a5-111d050a7df6.png)
https://user-images.githubusercontent.com/20930745/32145320-c82e4ab6-bcc6-11e7-89a5-111d050a7df6.png

Source:
https://user-images.githubusercontent.com/20930745/32145325-da4dc21c-bcc6-11e7-97d4-d5a55bbd5665.png
