### ISSUE TITLE
Note-Ify Notes

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9423]
**App Name:** Note-Ify Notes
**Bundle ID:** com.sergey-gerasimenko.FNotes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=675708914">675708914</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/note-ify-notes/id675708914?mt=8&uo=4">https://itunes.apple.com/us/app/note-ify-notes/id675708914?mt=8&uo=4</a>
**App Version:** 1.8.12
**Seller:** Sergii Gerasimenko
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sergii-gerasimenko/id642586860?uo=4">© Sergii Gerasimenko</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/35/a7/b1/35a7b145-bdda-db3e-2e92-ca05a0eaa135/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32145288-1c025976-bcc6-11e7-842b-cdb4011880fc.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32145288-1c025976-bcc6-11e7-842b-cdb4011880fc.png)
https://user-images.githubusercontent.com/20930745/32145288-1c025976-bcc6-11e7-842b-cdb4011880fc.png

Source:
https://user-images.githubusercontent.com/20930745/32145292-2dfedbf4-bcc6-11e7-8edc-aa40da14c10d.png
