### ISSUE TITLE
Teeevo

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9424]
**App Name:** Teeevo
**Bundle ID:** com.tgbtt.teeevoapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1050550155">1050550155</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/teeevo/id1050550155?mt=8&uo=4">https://itunes.apple.com/us/app/teeevo/id1050550155?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** GBTT Online Services Private Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-great-brown-think-tank/id1050550154?uo=4">© The Great Brown Think Tank</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/5e/a8/d8/5ea8d8f8-e9ec-a26d-0a6d-0119e9fd979f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32157809-23adee26-bd46-11e7-8d93-ca7e9a925a76.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32157809-23adee26-bd46-11e7-8d93-ca7e9a925a76.png)
https://user-images.githubusercontent.com/2068130/32157809-23adee26-bd46-11e7-8d93-ca7e9a925a76.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32157824-32915d38-bd46-11e7-8f73-b48486450ace.png
