### ISSUE TITLE
Tubi TV - Movies & TV Shows

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9425]
**App Name:** Tubi TV - Movies & TV Shows
**Bundle ID:** com.adrise.tubitv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=886445756">886445756</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tubi-tv-movies-tv-shows/id886445756?mt=8&uo=4">https://itunes.apple.com/us/app/tubi-tv-movies-tv-shows/id886445756?mt=8&uo=4</a>
**App Version:** 4.1.2
**Seller:** adRise, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/adrise-inc/id492046858?uo=4">© adRise, Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/11/8c/5b/118c5b9c-db0e-3983-e5c1-0aa377fcc407/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32148158-eee5a74a-bcf2-11e7-8017-eba71e4358a0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32148158-eee5a74a-bcf2-11e7-8017-eba71e4358a0.png)
https://user-images.githubusercontent.com/20930745/32148158-eee5a74a-bcf2-11e7-8017-eba71e4358a0.png

Source:
https://user-images.githubusercontent.com/20930745/32148164-016f6694-bcf3-11e7-9935-54050fb79f04.png
