### ISSUE TITLE
Movies Anywhere

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9426]
**App Name:** Movies Anywhere
**Bundle ID:** com.moviesanywhere.ma
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1245330908">1245330908</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/movies-anywhere/id1245330908?mt=8&uo=4">https://itunes.apple.com/us/app/movies-anywhere/id1245330908?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Movies Anywhere, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/movies-anywhere/id1245330907?uo=4">© Movies Anywhere</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/0e/ae/d8/0eaed8b6-c574-b790-cfd0-c90913b87457/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32148225-e5fbdcfc-bcf3-11e7-818f-3afeef4f1e5c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32148225-e5fbdcfc-bcf3-11e7-818f-3afeef4f1e5c.png)
https://user-images.githubusercontent.com/20930745/32148225-e5fbdcfc-bcf3-11e7-818f-3afeef4f1e5c.png

Source:
https://user-images.githubusercontent.com/20930745/32148229-f9121216-bcf3-11e7-9502-0f8936fc0d1f.png
