### ISSUE TITLE
Dribeee

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9427]
**App Name:** Dribeee
**Bundle ID:** jp.shimaApps.DribbbleClient
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1168906090">1168906090</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dribeee/id1168906090?mt=8&uo=4">https://itunes.apple.com/us/app/dribeee/id1168906090?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** jinsei shima
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jinsei-shima/id1168906089?uo=4">© jinsei shima</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/7d/1a/e4/7d1ae472-7a3e-e935-7407-8853f71d3be8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32148284-bff728f8-bcf4-11e7-9f4a-a71135b4a868.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32148284-bff728f8-bcf4-11e7-9f4a-a71135b4a868.png)
https://user-images.githubusercontent.com/2068130/32148284-bff728f8-bcf4-11e7-9f4a-a71135b4a868.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32148286-cfa033bc-bcf4-11e7-96fe-46a5f38c18cf.png
