### ISSUE TITLE
Design Hunt

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9428]
**App Name:** Design Hunt
**Bundle ID:** com.talkaboutdesign.tdnewsapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=968588816">968588816</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/design-hunt/id968588816?mt=8&uo=4">https://itunes.apple.com/us/app/design-hunt/id968588816?mt=8&uo=4</a>
**App Version:** 2.9
**Seller:** Talkabout Design LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/talkabout-design-llc/id913695621?uo=4">© Talkabout Design LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/e0/a5/3d/e0a53dfc-2d25-45cf-02b7-8d0dd5b15d07/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32148199-884dd0a6-bcf3-11e7-802c-952cba767321.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnert.at?image=https://user-images.githubusercontent.com/2068130/32148199-884dd0a6-bcf3-11e7-802c-952cba767321.png)
https://user-images.githubusercontent.com/2068130/32148199-884dd0a6-bcf3-11e7-802c-952cba767321.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32148202-9a8889be-bcf3-11e7-81ef-26b994f72e33.png
