### ISSUE TITLE
DunkShot for Dribbble

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9429]
**App Name:** DunkShot for Dribbble
**Bundle ID:** com.garylaw.dunkshot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=588157789">588157789</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dunkshot-for-dribbble/id588157789?mt=8&uo=4">https://itunes.apple.com/us/app/dunkshot-for-dribbble/id588157789?mt=8&uo=4</a>
**App Version:** 1.9.1
**Seller:** Gary Law
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gary-law/id315428734?uo=4">© Gary Law</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/e8/70/d9/e870d99c-2808-6b07-497f-b756e7ee5af2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32148262-7e81ac04-bcf4-11e7-81ba-f2ffd47d8f71.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32148262-7e81ac04-bcf4-11e7-81ba-f2ffd47d8f71.png)
https://user-images.githubusercontent.com/20930745/32148262-7e81ac04-bcf4-11e7-81ba-f2ffd47d8f71.png

Source:
https://user-images.githubusercontent.com/20930745/32148272-9350afea-bcf4-11e7-8d49-923396354424.png
