### ISSUE TITLE
Diptic

### ISSUE THREAD

**Issue by thatsoaustin** [glasklart/hd#943]
**App Name:** Diptic
**Bundle ID:** com.peaksystems.Diptic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=377989827">377989827</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/diptic/id377989827?mt=8&uo=4">https://itunes.apple.com/us/app/diptic/id377989827?mt=8&uo=4</a>
**App Version:** 9.2.1
**Seller:** Peak Systems
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/peak-systems/id377989830?uo=4>© Peak Systems</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/82/5b/59/825b5954-584b-a3a1-23db-cbb8be88ee50/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19850456/e0ad5c4e-9f58-11e6-82c2-0122a677673e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19850456/e0ad5c4e-9f58-11e6-82c2-0122a677673e.png)
https://cloud.githubusercontent.com/assets/20930745/19850456/e0ad5c4e-9f58-11e6-82c2-0122a677673e.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19850479/fbe7fa32-9f58-11e6-85a3-973fc7ec12dd.png
