### ISSUE TITLE
Drive Ahead!

### ISSUE THREAD

**Issue by TheEpicPie3** [glasklart/hd#9430]
**App Name:** Drive Ahead!
**Bundle ID:** com.dodreams.crashonwheels
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=964436963">964436963</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/drive-ahead/id964436963?mt=8&uo=4">https://itunes.apple.com/us/app/drive-ahead/id964436963?mt=8&uo=4</a>
**App Version:** 1.58.1
**Seller:** Dodreams Fairytale Company Oy
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dodreams-fairytale-company-oy/id553181157?uo=4">© Dodreams Fairytale Company Oy</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/00/9d/09/009d0985-52ad-3b9f-1c4f-644c5f846949/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32157132-e21910fc-bd41-11e7-820a-31c144793213.png)

**Comment by dreamnet** [comment]
Can't do the original...
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32157132-e21910fc-bd41-11e7-820a-31c144793213.png)
https://user-images.githubusercontent.com/2068130/32157132-e21910fc-bd41-11e7-820a-31c144793213.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32157139-f1da5a1e-bd41-11e7-8b02-e2d81955ba08.png
