### ISSUE TITLE
Bullet Force

### ISSUE THREAD

**Issue by TheEpicPie3** [glasklart/hd#9431]
**App Name:** Bullet Force
**Bundle ID:** com.blayzegames.iosfps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1009134067">1009134067</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bullet-force/id1009134067?mt=8&uo=4">https://itunes.apple.com/us/app/bullet-force/id1009134067?mt=8&uo=4</a>
**App Version:** 1.11
**Seller:** Clint Wilde
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/clint-wilde/id705432216?uo=4">© Clint Wilde</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/d8/ff/bd/d8ffbdd8-4bf3-2d96-b918-3f472d993e0e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32184904-093d650a-bd9e-11e7-97b1-00c4e99db458.png)

**Comment by dreamnet** [comment]
Hmmm...
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32184904-093d650a-bd9e-11e7-97b1-00c4e99db458.png)
https://user-images.githubusercontent.com/2068130/32184904-093d650a-bd9e-11e7-97b1-00c4e99db458.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32184915-1a767564-bd9e-11e7-8816-148842065bff.png

**Comment by dreamnet** [comment]
@TheEpicPie3 Please dont close issues - I will do that when I add the icon to the master.
