### ISSUE TITLE
1Touch Widgets - Speed Up Your Life

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9432]
**App Name:** 1Touch Widgets - Speed Up Your Life
**Bundle ID:** com.xapps.widgets
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1272549890">1272549890</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/1touch-widgets-speed-up-your-life/id1272549890?mt=8&uo=4">https://itunes.apple.com/us/app/1touch-widgets-speed-up-your-life/id1272549890?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Dat Nguyen
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dat-nguyen/id1255795544?uo=4">© Dat Nguyen</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/28/02/58/28025845-86ea-e8bf-f4ef-f3a82e997c64/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32175228-9b0b0182-bd84-11e7-95bd-21ef507363d4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32175228-9b0b0182-bd84-11e7-95bd-21ef507363d4.png)
https://user-images.githubusercontent.com/20930745/32175228-9b0b0182-bd84-11e7-95bd-21ef507363d4.png

Source:
https://user-images.githubusercontent.com/20930745/32175250-ac98e928-bd84-11e7-8f20-e5ecd13228f0.png
