### ISSUE TITLE
Textify - Don't listen.. Read!

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9434]
**App Name:** Textify - Don't listen.. Read!
**Bundle ID:** com.christinenixon.textify
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1207383840">1207383840</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/textify-dont-listen-read/id1207383840?mt=8&uo=4">https://itunes.apple.com/us/app/textify-dont-listen-read/id1207383840?mt=8&uo=4</a>
**App Version:** 1.2.2
**Seller:** Christine Nixon
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/christine-nixon/id1207383839?uo=4">© Christine Nixon</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/d7/8e/49/d78e4951-b257-6a33-6e21-55038ef1aa00/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32175871-74484fb2-bd86-11e7-909d-ffc0ac451279.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32175871-74484fb2-bd86-11e7-909d-ffc0ac451279.png)
https://user-images.githubusercontent.com/20930745/32175871-74484fb2-bd86-11e7-909d-ffc0ac451279.png

Source:
https://user-images.githubusercontent.com/20930745/32175891-85463784-bd86-11e7-8458-5283b236cfc6.png
