### ISSUE TITLE
Battery Graph Widget

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9435]
**App Name:** Battery Graph Widget
**Bundle ID:** com.lubosmikusiak.batterygraphwidget
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=921354569">921354569</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/battery-graph-widget/id921354569?mt=8&uo=4">https://itunes.apple.com/us/app/battery-graph-widget/id921354569?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** L Mikusiak
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lubos-mikusiak/id466504885?uo=4">© Lubos Mikusiak</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/1c/5a/8b/1c5a8b54-a7c3-2ed0-fbd6-33f5a9d7ab67/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32176132-19df09a2-bd87-11e7-8a31-f0622c65b4f8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32176132-19df09a2-bd87-11e7-8a31-f0622c65b4f8.png)
https://user-images.githubusercontent.com/20930745/32176132-19df09a2-bd87-11e7-8a31-f0622c65b4f8.png

Source:
https://user-images.githubusercontent.com/20930745/32176158-2da9f9a6-bd87-11e7-9635-75aaab307cc0.png
