### ISSUE TITLE
Yandex

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9437]
**App Name:** Yandex
**Bundle ID:** ru.yandex.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1050704155">1050704155</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yandex/id1050704155?mt=8&uo=4">https://itunes.apple.com/us/app/yandex/id1050704155?mt=8&uo=4</a>
**App Version:** 3.51
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yandex-llc/id308094652?uo=4">© Yandex LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/df/e4/8e/dfe48e0a-1af6-69e8-d8ef-0d1e1f250cfe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32252947-8a49b8ce-be98-11e7-893f-4f6c1c65f33b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32252947-8a49b8ce-be98-11e7-893f-4f6c1c65f33b.png)
https://user-images.githubusercontent.com/20930745/32252947-8a49b8ce-be98-11e7-893f-4f6c1c65f33b.png

Source:
https://user-images.githubusercontent.com/20930745/32252964-a5f7bdfa-be98-11e7-9c03-a3f1f6a8bde8.png
