### ISSUE TITLE
myShopi – promos, coupons, loyalty & shopping list

### ISSUE THREAD

**Issue by thatsoaustin** [glasklart/hd#944]
**App Name:** myShopi – promos, coupons, loyalty & shopping list
**Bundle ID:** com.agilys.shopi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=406663341">406663341</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/myshopi-promos-coupons-loyalty/id406663341?mt=8&uo=4">https://itunes.apple.com/us/app/myshopi-promos-coupons-loyalty/id406663341?mt=8&uo=4</a>
**App Version:** 5.6.1
**Seller:** Agilys
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/agilys/id398472193?uo=4>© Agilys</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/8a/06/57/8a06575d-8b42-75d5-9af6-65f769342560/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19735800/50f296e0-9bad-11e6-8ccf-b103fce950b9.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19735800/50f296e0-9bad-11e6-8ccf-b103fce950b9.png)
https://cloud.githubusercontent.com/assets/2068130/19735800/50f296e0-9bad-11e6-8ccf-b103fce950b9.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19735815/5fd1b312-9bad-11e6-9f7c-75a8fb759b1f.png
