### ISSUE TITLE
Lost Souls: Enchanted Paintings

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9447]
**App Name:** Lost Souls: Enchanted Paintings
**Bundle ID:** com.g5e.lsoul.freemium
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520132784">520132784</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lost-souls-enchanted-paintings/id520132784?mt=8&uo=4">https://itunes.apple.com/us/app/lost-souls-enchanted-paintings/id520132784?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** G5 Entertainment AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/g5-entertainment/id305426797?uo=4">© G5 Entertainment</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/d4/d6/28/d4d628c5-cb33-ad89-c07c-422be3fc29a8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563303/406c0480-ce81-11e6-8730-7d7cd67ec45f.png)

**Comment by dreamnet** [comment]
@ivanov007 Should we use the one from #8721 ?

**Comment by ivanov007** [comment]
@dreamnet yeah, that one will do

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563303/406c0480-ce81-11e6-8730-7d7cd67ec45f.png)
https://cloud.githubusercontent.com/assets/2068130/21563303/406c0480-ce81-11e6-8730-7d7cd67ec45f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21563308/504d1a2e-ce81-11e6-869e-6130fa54e38a.png
