### ISSUE TITLE
アイドリッシュセブン

### ISSUE THREAD

**Issue by jmaeshawn** [glasklart/hd#9455]
**App Name:** アイドリッシュセブン
**Bundle ID:** jp.co.bandainamcoonline.idolish7
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1019437222">1019437222</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/jp/app/%E3%82%A2%E3%82%A4%E3%83%89%E3%83%AA%E3%83%83%E3%82%B7%E3%83%A5%E3%82%BB%E3%83%96%E3%83%B3/id1019437222?mt=8&uo=4">https://itunes.apple.com/jp/app/%E3%82%A2%E3%82%A4%E3%83%89%E3%83%AA%E3%83%83%E3%82%B7%E3%83%A5%E3%82%BB%E3%83%96%E3%83%B3/id1019437222?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** BANDAI NAMCO Online Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/jp/developer/bandai-namco-online-inc/id648288742?uo=4">© BANDAI NAMCO Online Inc.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/3f/70/3e/3f703e55-35d8-4332-76f7-2fbf9b24744a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32412946-43a0ac18-c206-11e7-8c82-740aa17fcd5c.png)

**Comment by dreamnet** [comment]
@jmaeshawn Uuh, than's hard... I only can do something like this:
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32412946-43a0ac18-c206-11e7-8c82-740aa17fcd5c.png)
https://user-images.githubusercontent.com/2068130/32412946-43a0ac18-c206-11e7-8c82-740aa17fcd5c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32412951-585b85c4-c206-11e7-8653-1828d6ccc2b5.png

**Comment by dreamnet** [comment]
Well, I think it's fine...
