### ISSUE TITLE
Whoscall - Caller ID & Block

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9458]
**App Name:** Whoscall - Caller ID & Block
**Bundle ID:** gogolook.whoscall
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=929968679">929968679</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/whoscall-caller-id-block/id929968679?mt=8&uo=4">https://itunes.apple.com/us/app/whoscall-caller-id-block/id929968679?mt=8&uo=4</a>
**App Version:** 2.2.10
**Seller:** GOGOLOOK CO., LTD.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gogolook/id922417541?uo=4">© Gogolook</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/62/a0/b4/62a0b412-c038-3299-96d3-50c18ff3737e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32455711-55c971d6-c323-11e7-889f-75e2d3a5aa58.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32455711-55c971d6-c323-11e7-889f-75e2d3a5aa58.png)
https://user-images.githubusercontent.com/20930745/32455711-55c971d6-c323-11e7-889f-75e2d3a5aa58.png

Source:
https://user-images.githubusercontent.com/20930745/32455732-67e91164-c323-11e7-933a-d1175e522b47.png
