### ISSUE TITLE
TapMeasure – AR utility

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9459]
**App Name:** TapMeasure – AR utility
**Bundle ID:** com.occipital.TapMeasure
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1281766938">1281766938</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tapmeasure-ar-utility/id1281766938?mt=8&uo=4">https://itunes.apple.com/us/app/tapmeasure-ar-utility/id1281766938?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Occipital, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/occipital-inc/id304567629?uo=4">© Occipital, Inc.</a>
**Supported Devices:** iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/5f/8b/ac/5f8bac67-b474-c6dd-16c9-7927ab6ab9c6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32455508-cb145b82-c322-11e7-9a4c-5dea62c0bebf.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32455508-cb145b82-c322-11e7-9a4c-5dea62c0bebf.png)
https://user-images.githubusercontent.com/20930745/32455508-cb145b82-c322-11e7-9a4c-5dea62c0bebf.png

Source:
https://user-images.githubusercontent.com/20930745/32455553-e36668d8-c322-11e7-9b63-c8c3e6e48e8d.png
