### ISSUE TITLE
SpeakEasy French ~ Offline Phrasebook and Flashcards with Native Speaker Voice and Phonetics

### ISSUE THREAD

**Issue by thatsoaustin** [glasklart/hd#946]
**App Name:** SpeakEasy French ~ Offline Phrasebook and Flashcards with Native Speaker Voice and Phonetics
**Bundle ID:** com.pocketglow.ios.speakeasyfrench
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=412991664">412991664</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/speakeasy-french-offline-phrasebook/id412991664?mt=8&uo=4">https://itunes.apple.com/us/app/speakeasy-french-offline-phrasebook/id412991664?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** Pocketglow Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pocketglow-inc./id405254720?uo=4>© Pocketglow Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple3/v4/50/13/33/50133341-325c-c773-017a-1c7f00eed486/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410779/9dba1834-92f4-11e6-854d-ef62dcd3a4f1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19410779/9dba1834-92f4-11e6-854d-ef62dcd3a4f1.png)
https://cloud.githubusercontent.com/assets/20930745/19410779/9dba1834-92f4-11e6-854d-ef62dcd3a4f1.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19410785/af1609b2-92f4-11e6-9f32-a29621a43d12.png
