### ISSUE TITLE
AirMeasure - AR Tape & Ruler

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9460]
**App Name:** AirMeasure - AR Tape & Ruler
**Bundle ID:** com.laan.labs.ARMeasure
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1251282152">1251282152</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/airmeasure-ar-tape-ruler/id1251282152?mt=8&uo=4">https://itunes.apple.com/us/app/airmeasure-ar-tape-ruler/id1251282152?mt=8&uo=4</a>
**App Version:** 1.1.3
**Seller:** Laan Consulting Corp
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/laan-labs/id310916919?uo=4">© Laan Labs</a>
**Supported Devices:** iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/4d/99/ea/4d99eacf-0a8a-5b63-d7db-4adf25a0e267/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32455863-e27bbecc-c323-11e7-87e5-0df2b022d27a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32455863-e27bbecc-c323-11e7-87e5-0df2b022d27a.png)
https://user-images.githubusercontent.com/20930745/32455863-e27bbecc-c323-11e7-87e5-0df2b022d27a.png

Source:
https://user-images.githubusercontent.com/20930745/32455879-f55e85e2-c323-11e7-8e6a-d976b2bfffd6.png
