### ISSUE TITLE
Stitch It! - Edit & share screenshots! - Combining screengrabs as a seamless vertical collage!

### ISSUE THREAD

**Issue by thatsoaustin** [glasklart/hd#947]
**App Name:** Stitch It! - Edit & share screenshots! - Combining screengrabs as a seamless vertical collage!
**Bundle ID:** com.stitchitapp.Stitch-It
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=554594252">554594252</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stitch-it!-edit-share-screenshots!/id554594252?mt=8&uo=4">https://itunes.apple.com/us/app/stitch-it!-edit-share-screenshots!/id554594252?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** Lucky Bunny LLC
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/lucky-bunny-llc/id554594255?uo=4>© Lucky Bunny LLC</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple49/v4/08/02/61/08026169-d411-c0c0-becd-dca320a6e860/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18794157/7c1321f4-81be-11e6-9c6b-d3d2e3c7d43d.png)

**Comment by nekholm** [comment]
Icon missing in 5.0

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18794157/7c1321f4-81be-11e6-9c6b-d3d2e3c7d43d.png)
https://cloud.githubusercontent.com/assets/20930745/18794157/7c1321f4-81be-11e6-9c6b-d3d2e3c7d43d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18794177/8c87e95c-81be-11e6-8d85-05f970f56512.png
