### ISSUE TITLE
Shopular: Black Friday Coupons

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9479]
**App Name:** Shopular: Black Friday Coupons
**Bundle ID:** com.aircrunch.shopalerts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=544118997">544118997</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shopular-black-friday-coupons/id544118997?mt=8&uo=4">https://itunes.apple.com/us/app/shopular-black-friday-coupons/id544118997?mt=8&uo=4</a>
**App Version:** 7.02
**Seller:** AirCrunch Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/aircrunch-inc/id504536408?uo=4">© AirCrunch Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/e3/eb/67/e3eb67e1-7f5d-2ed9-2909-7b7881ac08a8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/3090247/32850711-884bfa58-c9f8-11e7-88c9-ee0e0c597eca.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/3090247/32850711-884bfa58-c9f8-11e7-88c9-ee0e0c597eca.png)
https://user-images.githubusercontent.com/3090247/32850711-884bfa58-c9f8-11e7-88c9-ee0e0c597eca.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/32850715-8877ae64-c9f8-11e7-9d15-088b7b3693dc.png
