### ISSUE TITLE
Glasklart Settings.theme With No Underlay

### ISSUE THREAD

**Issue by throughtheiris25** [glasklart/hd#9480]
I wonder if its possible to get an optional "Glasklart Settings.theme" without the background AnemoneEffect for those who use a dark settings tweak. It looks way better having no underlay with nothing but the icon.

**Comment by 2Qt2beStr8** [comment]
hi,
it is possible to hide the baseplate with the "Glasklart Hide Baseplate.theme"

**Comment by throughtheiris25** [comment]
The 'Settings' icons have the baseplate (underlay) in the image files (png), so no Anemone tweak is going to get rid of a part of the defining icon images. Those tweaks can only get rid of Anemone effects such as using an AnemoneEffect on the home screen. You need all the barebone icon images without any underlay to show only the icon in Settings, as they do on the home screen if no AnemoneEffects are applied.

**Comment by throughtheiris25** [comment]
I think I haven't explained my situation properly, and I apologize for that.

I use the icons flat, with AnemoneIconEffects.dylib disabled, so the baseplate or underlying square background is disabled behind the icons on the home screen. (Icons like in IconBundles)

Now, what I am hoping is to match the Settings icons with these icons, so no baseplate or underlay is not showing on those icons and the theme is consistent for me.

I know this isn't the intended way for this theme to be used, but trust me, the glyph effect is nice. Hoping someone has the original set of associated pngs for all the settings theme lying around somwhere without the underlay.

**Comment by 2Qt2beStr8** [comment]
ah, sorry … i was wrong :–(  you mean the settings icons

**Comment by dreamnet** [comment]
@throughtheiris25 I don't have the png's without the underlay, but I have the glyphs as svg and the Photoshop files. In the Photoshop files (one for 2x and one for 3x), you just have to hide the background and the baseplate, then you can save icon by icon als glyph. But that's a lot of work - hundrets of files to save.
Here you go: [Settings Icons.zip](https://github.com/glasklart/hd/files/1485040/Settings.Icons.zip)
I hope, you use a dark background in the settings... 😁

**Comment by throughtheiris25** [comment]
@dreamnet. Thanks, that is great. It will take some work, but it's better than nothing. Which I could batch it, lol. Anyhow, thanks again.

**Comment by dreamnet** [comment]
@throughtheiris25 You are welcome! - and it would be nice, if you can post some screenshots here. 👍

**Comment by throughtheiris25** [comment]
@dreamnet. Will drop some when I get through these icons.

**Comment by throughtheiris25** [comment]
@dreamnet Check it out, looks pretty nice. Only done the necessary icons for now though.

[http://i89.photobucket.com/albums/k227/xb2iris/2017_11_19_IMG_0256_zps8r4ebwyy.png](url)

**Comment by throughtheiris25** [comment]
@dreamnet Hey, you don't have family@2x/family@3x icon from com.apple.castlesettings without a underlay or baseplate lying around, do you. It's not in the PSD you sent me. It's the only icon, the rest of the wholes I managed to plug with the other icons, so thanks again for that.

**Comment by dreamnet** [comment]
@throughtheiris25 It's not in the psd, because these icons have an other format (80x80px and 120x120px) - here you go: [family.zip](https://github.com/glasklart/hd/files/1500960/family.zip)

**Comment by throughtheiris25** [comment]
@dreamnet Thanks man. Much appreciate it. As usual, perfect stuff. Keep this amazing theme up. One day, they'll replace the official Appstore repository with these icons, lol!
