### ISSUE TITLE
Unlimited Music Player VIBBIDI

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9481]
**App Name:** Unlimited Music Player VIBBIDI
**Bundle ID:** com.glue-th.VIBBIDIAPP
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=993532230">993532230</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/unlimited-music-player-vibbidi/id993532230?mt=8&uo=4">https://itunes.apple.com/us/app/unlimited-music-player-vibbidi/id993532230?mt=8&uo=4</a>
**App Version:** 4.2.6
**Seller:** Glue-th, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/glue-th-inc/id676109346?uo=4">© Glue-th, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/f6/49/99/f64999f9-c32e-ca49-c1f2-adca97816694/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32911878-c4178a14-cb0d-11e7-8617-b667172c4e16.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/3090247/32852012-4f2fa810-c9fc-11e7-9d6e-a87131880b7b.png)
https://user-images.githubusercontent.com/3090247/32852012-4f2fa810-c9fc-11e7-9d6e-a87131880b7b.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/32852013-4f6359da-c9fc-11e7-9441-0dfeff702d0b.png

**Comment by 2Qt2beStr8** [comment]
@ivanov007 it‘s to big :-)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/32911878-c4178a14-cb0d-11e7-8617-b667172c4e16.png)
https://user-images.githubusercontent.com/20930745/32911878-c4178a14-cb0d-11e7-8617-b667172c4e16.png

Source:
https://user-images.githubusercontent.com/20930745/32911903-dda055a6-cb0d-11e7-8439-91fe5695f6f5.png
