### ISSUE TITLE
Dark Arcana: The Carnival (Full)

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9482]
**App Name:** Dark Arcana: The Carnival (Full)
**Bundle ID:** com.g5e.carnival
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=561405549">561405549</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dark-arcana-the-carnival-full/id561405549?mt=8&uo=4">https://itunes.apple.com/us/app/dark-arcana-the-carnival-full/id561405549?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** G5 Entertainment AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/g5-entertainment/id305426797?uo=4">© G5 Entertainment</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple4/v4/0f/c6/25/0fc625ff-6554-80a1-3204-6cf6b4199ec4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563461/ff670d02-ce82-11e6-88e7-3a8a95b7e669.png)

**Comment by dreamnet** [comment]
Same as #8723.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563461/ff670d02-ce82-11e6-88e7-3a8a95b7e669.png)
https://cloud.githubusercontent.com/assets/2068130/21563461/ff670d02-ce82-11e6-88e7-3a8a95b7e669.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21563467/0ed8b8e4-ce83-11e6-9835-d46996650d1b.png
