### ISSUE TITLE
Lost Souls: Timeless Fables (Full)

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9483]
**App Name:** Lost Souls: Timeless Fables (Full)
**Bundle ID:** com.g5e.lostsouls2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1021995617">1021995617</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lost-souls-timeless-fables-full/id1021995617?mt=8&uo=4">https://itunes.apple.com/us/app/lost-souls-timeless-fables-full/id1021995617?mt=8&uo=4</a>
**App Version:** 1.0.8
**Seller:** G5 Entertainment AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/g5-entertainment/id305426797?uo=4">© G5 Entertainment</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/e4/5f/74/e45f74f2-1799-4d18-1ec7-932f81927af5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563303/406c0480-ce81-11e6-8730-7d7cd67ec45f.png)

**Comment by dreamnet** [comment]
Same as #8721.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/21563303/406c0480-ce81-11e6-8730-7d7cd67ec45f.png)
https://cloud.githubusercontent.com/assets/2068130/21563303/406c0480-ce81-11e6-8730-7d7cd67ec45f.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/21563308/504d1a2e-ce81-11e6-869e-6130fa54e38a.png
