### ISSUE TITLE
Jaybird MySound

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9498]
**App Name:** Jaybird MySound
**Bundle ID:** com.jaybirdsport.audio
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1055470300">1055470300</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jaybird-mysound/id1055470300?mt=8&uo=4">https://itunes.apple.com/us/app/jaybird-mysound/id1055470300?mt=8&uo=4</a>
**App Version:** 1.9.1
**Seller:** Jaybird LLC.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jaybird-llc/id369634058?uo=4">© Jaybird LLC.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/23/6d/78/236d7848-6022-126c-03d6-ea1a329861bd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/33500968-1c369cd4-d6db-11e7-9882-d926d3165186.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/33500968-1c369cd4-d6db-11e7-9882-d926d3165186.png)
https://user-images.githubusercontent.com/20930745/33500968-1c369cd4-d6db-11e7-9882-d926d3165186.png

Source:
https://user-images.githubusercontent.com/20930745/33500996-33bc750e-d6db-11e7-81b8-6d8d3eb23126.png
