### ISSUE TITLE
20 Minutes.fr - l'actualité en continu

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#95]
**App Name:** 20 Minutes.fr - l'actualité en continu
**Bundle ID:** fr.20minutes.20minutes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=308834491">308834491</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/20-minutes.fr-lactualite-en/id308834491?mt=8&uo=4">https://itunes.apple.com/us/app/20-minutes.fr-lactualite-en/id308834491?mt=8&uo=4</a>
**App Version:** 4.2.8
**Seller:** 20 Minutes France
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/20minutes.fr/id308834494?uo=4">© 20minutes.fr</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/f5/d7/e5/f5d7e59c-ec14-64ba-5a14-a6de57bfb41f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20132565/d96073d8-a663-11e6-99d8-2879c6a7a638.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20132565/d96073d8-a663-11e6-99d8-2879c6a7a638.png)
https://cloud.githubusercontent.com/assets/20930745/20132565/d96073d8-a663-11e6-99d8-2879c6a7a638.png

Source:
(https://cloud.githubusercontent.com/assets/20930745/20132584/f14ba634-a663-11e6-89d3-95ec805eee13.png
