### ISSUE TITLE
Scotiabank Chile  - Banca Móvil

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9500]
**App Name:** Scotiabank Chile  - Banca Móvil
**Bundle ID:** com.scotiabank.Marimba.Chili
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=766608164">766608164</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scotiabank-chile-banca-m%C3%B3vil/id766608164?mt=8&uo=4">https://itunes.apple.com/us/app/scotiabank-chile-banca-m%C3%B3vil/id766608164?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** The Bank of Nova Scotia
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/scotiabank/id341151577?uo=4">© Scotiabank</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/09/88/5e/09885ee4-e59a-f26f-0934-993deeceff3e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19736350/2dff8006-9baf-11e6-972b-9f2b9875e240.png)

**Comment by dreamnet** [comment]
Same as #2446.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19736350/2dff8006-9baf-11e6-972b-9f2b9875e240.png)
https://cloud.githubusercontent.com/assets/2068130/19736350/2dff8006-9baf-11e6-972b-9f2b9875e240.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19736366/3c761d98-9baf-11e6-9ede-abdabaf2826d.png
