### ISSUE TITLE
Scotiabank Caribbean  - Mobile Banking

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9501]
**App Name:** Scotiabank Caribbean  - Mobile Banking
**Bundle ID:** com.scotiabank.Marimba
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=466029399">466029399</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scotiabank-caribbean-mobile-banking/id466029399?mt=8&uo=4">https://itunes.apple.com/us/app/scotiabank-caribbean-mobile-banking/id466029399?mt=8&uo=4</a>
**App Version:** 3.0.2
**Seller:** The Bank of Nova Scotia
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/scotiabank/id341151577?uo=4">© Scotiabank</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/6c/9c/0f/6c9c0f1a-8475-59d5-8d9e-aba90dfc71bc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19736350/2dff8006-9baf-11e6-972b-9f2b9875e240.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/33835288-97576f20-de4b-11e7-974d-64630c93b906.png)
https://user-images.githubusercontent.com/3090247/33835288-97576f20-de4b-11e7-974d-64630c93b906.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/33835289-976fd6d2-de4b-11e7-90d6-fc4144549c9c.png

**Comment by dreamnet** [comment]
Same as #2446.
