### ISSUE TITLE
ScotiaMóvil 4.0

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9502]
**App Name:** ScotiaMóvil 4.0
**Bundle ID:** com.sbi.ellavevirtual
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=720812080">720812080</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scotiam%C3%B3vil-4-0/id720812080?mt=8&uo=4">https://itunes.apple.com/us/app/scotiam%C3%B3vil-4-0/id720812080?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** Grupo Financiero Scotiabank Inverlat, S.A. de C.V.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/scotiabank-m%C3%A9xico/id620146442?uo=4">© Scotiabank México</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/11/b6/e5/11b6e5c7-5ac0-8c3f-43e4-f8cea6aca23f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19736350/2dff8006-9baf-11e6-972b-9f2b9875e240.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/33835288-97576f20-de4b-11e7-974d-64630c93b906.png)
https://user-images.githubusercontent.com/3090247/33835288-97576f20-de4b-11e7-974d-64630c93b906.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/33835289-976fd6d2-de4b-11e7-90d6-fc4144549c9c.png

**Comment by dreamnet** [comment]
Same as #2446.
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19736350/2dff8006-9baf-11e6-972b-9f2b9875e240.png)
https://cloud.githubusercontent.com/assets/2068130/19736350/2dff8006-9baf-11e6-972b-9f2b9875e240.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19736366/3c761d98-9baf-11e6-9ede-abdabaf2826d.png
