### ISSUE TITLE
Relive Running & Cycling

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9503]
**App Name:** Relive Running & Cycling
**Bundle ID:** cc.relive.reliveapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1201703657">1201703657</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/relive-running-cycling/id1201703657?mt=8&uo=4">https://itunes.apple.com/us/app/relive-running-cycling/id1201703657?mt=8&uo=4</a>
**App Version:** 1.9.6
**Seller:** Relive B.V.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/relive-b-v/id1201703656?uo=4">© Relive B.V.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/78/48/20/784820a1-3f9d-1716-34fa-95536878b00c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34129216-9e5ec1e4-e443-11e7-897e-b560857dc309.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34129140-5139b748-e443-11e7-920d-1d6)
https://user-images.githubusercontent.com/20930745/34129140-5139b748-e443-11e7-920d-1d6f30b44b87.pngf30b44b87.png

Source:
https://user-images.githubusercontent.com/20930745/34129187-7fa2773c-e443-11e7-8256-77fc87f29f99.png
