### ISSUE TITLE
MoviePass

### ISSUE THREAD

**Issue by ChaudhryAtif** [glasklart/hd#9504]
**App Name:** MoviePass
**Bundle ID:** com.moviepass.MoviePass
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=556183291">556183291</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moviepass/id556183291?mt=8&uo=4">https://itunes.apple.com/us/app/moviepass/id556183291?mt=8&uo=4</a>
**App Version:** 2.31
**Seller:** Moviepass Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/moviepass-inc/id556183294?uo=4">© MoviePass, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/c6/55/06/c655064e-b729-4db2-d0e7-d470df2f05d2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/34213098-ee0a890a-e563-11e7-90c9-8f57e5070ef3.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/34213098-ee0a890a-e563-11e7-90c9-8f57e5070ef3.png)
https://user-images.githubusercontent.com/3090247/34213098-ee0a890a-e563-11e7-90c9-8f57e5070ef3.png
--- ---
Source:
https://user-images.githubusercontent.com/3090247/34213099-ee2e7112-e563-11e7-8d90-4f06bd614f35.png
