### ISSUE TITLE
eWeLink - Smart Home Control

### ISSUE THREAD

**Issue by ChaudhryAtif** [glasklart/hd#9505]
**App Name:** eWeLink - Smart Home Control
**Bundle ID:** cc.coolkit.ios.cn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035163158">1035163158</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ewelink-smart-home-control/id1035163158?mt=8&uo=4">https://itunes.apple.com/us/app/ewelink-smart-home-control/id1035163158?mt=8&uo=4</a>
**App Version:** 3.1.5
**Seller:** Shenzhen CoolKit Technologies Co. Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/%E6%B7%B1%E5%9C%B3%E9%85%B7%E5%AE%85%E7%A7%91%E6%8A%80%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/id1035163157?uo=4">© 深圳酷宅科技有限公司</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/99/c6/b8/99c6b88c-8d35-f0c5-d678-ce262460981c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34268231-3cab4d34-e680-11e7-8b28-6572d64c5855.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34268231-3cab4d34-e680-11e7-8b28-6572d64c5855.png)
https://user-images.githubusercontent.com/20930745/34268231-3cab4d34-e680-11e7-8b28-6572d64c5855.png

Source:
https://user-images.githubusercontent.com/20930745/34268254-549bb5c8-e680-11e7-96b6-ff6b414a00c3.png
