### ISSUE TITLE
Scan Halal - World's Largest Halal Products Guide

### ISSUE THREAD

**Issue by ChaudhryAtif** [glasklart/hd#9506]
**App Name:** Scan Halal - World's Largest Halal Products Guide
**Bundle ID:** com.scanhalal.scanhalal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=589534185">589534185</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scan-halal-worlds-largest-halal-products-guide/id589534185?mt=8&uo=4">https://itunes.apple.com/us/app/scan-halal-worlds-largest-halal-products-guide/id589534185?mt=8&uo=4</a>
**App Version:** 3.8
**Seller:** Ummah Labs & Co.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ummah-labs-co/id589534188?uo=4">© Ummah Labs & Co.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple127/v4/4f/74/42/4f744232-d9c3-7a60-90fb-92bcdbbefb23/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34268512-440904b2-e681-11e7-9e37-1b22d4ab3a5c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34268512-440904b2-e681-11e7-9e37-1b22d4ab3a5c.png)
https://user-images.githubusercontent.com/20930745/34268512-440904b2-e681-11e7-9e37-1b22d4ab3a5c.png

Source:
https://user-images.githubusercontent.com/20930745/34268524-5564cb74-e681-11e7-98f6-aa96d81235d5.png
