### ISSUE TITLE
ETimes

### ISSUE THREAD

**Issue by ChaudhryAtif** [glasklart/hd#9507]
**App Name:** ETimes
**Bundle ID:** in.til.popkorn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=987892101">987892101</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/etimes/id987892101?uo=4">https://apps.apple.com/us/app/etimes/id987892101?uo=4</a>
**App Version:** 3.4.7
**Seller:** Times Internet Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/times-internet-limited/id427164656?uo=4">© Times Internet Limited</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/6e/3b/2f/6e3b2f19-d583-51d3-dc69-a7d5af6e06ba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388461-3ecd2a00-9ab2-11e9-8291-b35c5a3b31f8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34268724-19198352-e682-11e7-860c-4f18e535db54.png)
https://user-images.githubusercontent.com/20930745/34268724-19198352-e682-11e7-860c-4f18e535db54.png

Source:
https://user-images.githubusercontent.com/20930745/34268747-2ca5ffa4-e682-11e7-885e-630003ffa860.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388461-3ecd2a00-9ab2-11e9-8291-b35c5a3b31f8.png)
https://user-images.githubusercontent.com/20930745/60388461-3ecd2a00-9ab2-11e9-8291-b35c5a3b31f8.png

Source:
https://user-images.githubusercontent.com/20930745/60388462-412f8400-9ab2-11e9-8c1a-f41132665443.png
