### ISSUE TITLE
Patch: Smart Portrait Editor

### ISSUE THREAD

**Issue by ChaudhryAtif** [glasklart/hd#9508]
**App Name:** Patch: Smart Portrait Editor
**Bundle ID:** com.hal.CaffeApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1143698388">1143698388</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/patch-smart-portrait-editor/id1143698388?mt=8&uo=4">https://itunes.apple.com/us/app/patch-smart-portrait-editor/id1143698388?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Henry Lee
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/henry-lee/id1019294106?uo=4">© Henry Lee</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple71/v4/39/c2/33/39c233fe-5d6f-759e-d918-56194abc9336/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34318983-5644b702-e7d5-11e7-81b4-f2be348c68d5.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34318983-5644b702-e7d5-11e7-81b4-f2be348c68d5.png)
https://user-images.githubusercontent.com/2068130/34318983-5644b702-e7d5-11e7-81b4-f2be348c68d5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34318984-64f6452c-e7d5-11e7-8b4d-e67978448c83.png
