### ISSUE TITLE
Private Internet Access VPN

### ISSUE THREAD

**Issue by ChaudhryAtif** [glasklart/hd#9509]
**App Name:** Private Internet Access VPN
**Bundle ID:** com.privateinternetaccess.ios.PIA-VPN
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=955626407">955626407</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/private-internet-access-vpn/id955626407?mt=8&uo=4">https://itunes.apple.com/us/app/private-internet-access-vpn/id955626407?mt=8&uo=4</a>
**App Version:** 2.2.2
**Seller:** London Trust Media Incorporated
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/london-trust-media-inc/id445501786?uo=4">© London Trust Media, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/14/b3/89/14b389b0-7982-79dc-84d2-52e4e803823c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34357927-84634f5e-ea4b-11e7-81ec-566014a4f516.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34357927-84634f5e-ea4b-11e7-81ec-566014a4f516.png)
https://user-images.githubusercontent.com/20930745/34357927-84634f5e-ea4b-11e7-81ec-566014a4f516.png

Source:
https://user-images.githubusercontent.com/20930745/34357935-99f3b642-ea4b-11e7-9a00-64c101577ef0.png
