### ISSUE TITLE
Rotimatic Mobile

### ISSUE THREAD

**Issue by ChaudhryAtif** [glasklart/hd#9510]
**App Name:** Rotimatic Mobile
**Bundle ID:** com.zimplistic.rotimaticmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1055598959">1055598959</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rotimatic-mobile/id1055598959?mt=8&uo=4">https://itunes.apple.com/us/app/rotimatic-mobile/id1055598959?mt=8&uo=4</a>
**App Version:** 1.1.92
**Seller:** Rishi Israni
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rishi-israni/id1055598958?uo=4">© Rishi Israni</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/1d/24/26/1d2426e4-c0a8-b726-d7f7-a0eb4a51db91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34269339-2e1e772e-e684-11e7-82da-9197d0729833.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34269339-2e1e772e-e684-11e7-82da-9197d0729833.png)
https://user-images.githubusercontent.com/20930745/34269339-2e1e772e-e684-11e7-82da-9197d0729833.png

Source:
https://user-images.githubusercontent.com/20930745/34269359-42e4990e-e684-11e7-90b5-a10f8c927c78.png
