### ISSUE TITLE
Ionic View

### ISSUE THREAD

**Issue by ChaudhryAtif** [glasklart/hd#9511]
**App Name:** Ionic View
**Bundle ID:** com.ionic.viewapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=849930087">849930087</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ionic-view/id849930087?mt=8&uo=4">https://itunes.apple.com/us/app/ionic-view/id849930087?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Drifty Co.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/drifty/id849930090?uo=4">© Drifty</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/79/51/a7/7951a73b-7d0b-d174-67f1-c878ff13d87b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34269648-85531436-e685-11e7-8bbb-bc869f5c8a36.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34269648-85531436-e685-11e7-8bbb-bc869f5c8a36.png)
https://user-images.githubusercontent.com/20930745/34269648-85531436-e685-11e7-8bbb-bc869f5c8a36.png

Source:
https://user-images.githubusercontent.com/20930745/34269673-9801fa84-e685-11e7-9cec-5b58eac2d8a6.png
