### ISSUE TITLE
LocationHandle

### ISSUE THREAD

**Issue by ChaudhryAtif** [glasklart/hd#9512]
**App Name:** LocationHandle
**Bundle ID:** com.cunstuck.locationhandle
**iTunes ID:** N/A (Cydia app)
**App Version:** 2.0
**Developer:** Constuck
**Cydia Link:** <a target="_blank" href="http://cydia.saurik.com/package/org.thebigboss.locationhandle/">LocationHandle</a>
**Original Artwork:** 
<img src="https://user-images.githubusercontent.com/7082580/34186765-54b075d2-e4f3-11e7-8031-eb6085ca6143.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34311131-000b929e-e75c-11e7-9d92-be62dc3c5c03.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34269849-44eed366-e686-11e7-89f3-603665ca4bf8.png)
https://user-images.githubusercontent.com/20930745/34269849-44eed366-e686-11e7-89f3-603665ca4bf8.png

Source:
https://user-images.githubusercontent.com/20930745/34269878-59356b3c-e686-11e7-95c6-82c573b03f80.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34311131-000b929e-e75c-11e7-9d92-be62dc3c5c03.png)
https://user-images.githubusercontent.com/2068130/34311131-000b929e-e75c-11e7-9d92-be62dc3c5c03.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34311138-0e6fa596-e75c-11e7-897b-3dbaeb2ef3d1.png
