### ISSUE TITLE
NGXPlay

### ISSUE THREAD

**Issue by ChaudhryAtif** [glasklart/hd#9513]
**App Name:** NGXPlay
**Bundle ID:** com.eason.NGXPlay
**iTunes ID:** N/A (Cydia app)
**App Version:** 1.0-29
**Developer:** Eas0n
**Cydia Link:** <a target="_blank" href="http://apt.thebigboss.org/onepackage.php?bundleid=com.eason.carplay">NGXPlay</a>
**Original Artwork:** 
<img src="https://user-images.githubusercontent.com/7082580/34186867-dc3049a6-e4f3-11e7-94c5-80095b128f36.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34310907-59686a26-e75a-11e7-98f3-197db65586ec.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34310907-59686a26-e75a-11e7-98f3-197db65586ec.png)
https://user-images.githubusercontent.com/2068130/34310907-59686a26-e75a-11e7-98f3-197db65586ec.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34310915-6884a510-e75a-11e7-8a0b-fc8e6fafa065.png
