### ISSUE TITLE
SYSMonitor - System Status Wgt

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9514]
**App Name:** SYSMonitor - System Status Wgt
**Bundle ID:** com.wzh.mingzi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=937687645">937687645</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sysmonitor-system-status-wgt/id937687645?mt=8&uo=4">https://itunes.apple.com/us/app/sysmonitor-system-status-wgt/id937687645?mt=8&uo=4</a>
**App Version:** 3.31
**Seller:** Zehui Wang
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/zehui-wang/id892030257?uo=4">© Zehui Wang</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/39/b9/45/39b94563-87a6-46a0-2d99-1c14e76d56be/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34308339-45012df0-e74d-11e7-998f-c58e6d1fa07a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34308339-45012df0-e74d-11e7-998f-c58e6d1fa07a.png)
https://user-images.githubusercontent.com/2068130/34308339-45012df0-e74d-11e7-998f-c58e6d1fa07a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34308378-54142a72-e74d-11e7-92c8-a5af572f8398.png
