### ISSUE TITLE
SysMonitor -System Monitor

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9515]
**App Name:** SysMonitor -System Monitor
**Bundle ID:** cn.likejin.www.getSystems.getSystems
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1249798778">1249798778</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sysmonitor-system-monitor/id1249798778?mt=8&uo=4">https://itunes.apple.com/us/app/sysmonitor-system-monitor/id1249798778?mt=8&uo=4</a>
**App Version:** 1.0.6
**Seller:** wang jinwei
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wang-jinwei/id1013405164?uo=4">© wang jinwei</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/ca/84/65/ca8465fe-7312-8d4f-01c7-13edf1c19bd2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34308149-1b2337ea-e74c-11e7-9603-b5813cc68eaf.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34308149-1b2337ea-e74c-11e7-9603-b5813cc68eaf.png)
https://user-images.githubusercontent.com/2068130/34308149-1b2337ea-e74c-11e7-9603-b5813cc68eaf.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34308157-29ca36e0-e74c-11e7-960a-492e0164de7c.png
