### ISSUE TITLE
AGU Events

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9516]
**App Name:** AGU Events
**Bundle ID:** com.agu.AGUEnt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1303525553">1303525553</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/agu-events/id1303525553?uo=4">https://apps.apple.com/us/app/agu-events/id1303525553?uo=4</a>
**App Version:** 2.4
**Seller:** American Geophysical Union (AGU)
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/american-geophysical-union-agu/id476096201?uo=4">© American Geophysical Union (AGU)</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/2f/6f/76/2f6f762d-7a62-a4bc-5f30-840cba475cff/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979432-3f644d00-95e8-11e9-8883-3939d1dfec2f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34308042-7b05af7c-e74b-11e7-819d-5593bb1013b3.png)
https://user-images.githubusercontent.com/2068130/34308042-7b05af7c-e74b-11e7-819d-5593bb1013b3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34308050-89e8dc8a-e74b-11e7-9b9d-5b378f583515.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979432-3f644d00-95e8-11e9-8883-3939d1dfec2f.png)
https://user-images.githubusercontent.com/2068130/59979432-3f644d00-95e8-11e9-8883-3939d1dfec2f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59979437-4f7c2c80-95e8-11e9-957f-916a59eb19ec.png
