### ISSUE TITLE
MySolarCity

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9517]
**App Name:** MySolarCity
**Bundle ID:** com.solarcity.mysolarcity
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=620496798">620496798</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mysolarcity/id620496798?mt=8&uo=4">https://itunes.apple.com/us/app/mysolarcity/id620496798?mt=8&uo=4</a>
**App Version:** 2.8.5
**Seller:** SolarCity Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/solarcity-corporation/id620496801?uo=4">© SolarCity Corporation</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/7d/b5/d7/7db5d756-24ae-68a0-8402-a4716d60d5d4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com solarcity mysolarcity-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34307758-0f23805a-e74a-11e7-9a43-c4aa66ac4308.png)

**Comment by dreamnet** [comment]
![com solarcity mysolarcity-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34307758-0f23805a-e74a-11e7-9a43-c4aa66ac4308.png)
https://user-images.githubusercontent.com/2068130/34307758-0f23805a-e74a-11e7-9a43-c4aa66ac4308.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34307773-203cff38-e74a-11e7-8672-229b54c86d82.png
