### ISSUE TITLE
Vert S

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9518]
**App Name:** Vert S
**Bundle ID:** com.calumaa.vert3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1006372607">1006372607</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vert-s/id1006372607?mt=8&uo=4">https://itunes.apple.com/us/app/vert-s/id1006372607?mt=8&uo=4</a>
**App Version:** 1.1.3
**Seller:** Andrej Mihelic
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/andrej-mihelic/id691346633?uo=4">© Andrej Mihelic</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/c7/3c/27/c73c27fa-de17-f2d7-aa43-7ebf185d00b6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34329042-0229ad26-e8f2-11e7-9d75-7dd5a6ef7156.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34329042-0229ad26-e8f2-11e7-9d75-7dd5a6ef7156.png)
https://user-images.githubusercontent.com/20930745/34329042-0229ad26-e8f2-11e7-9d75-7dd5a6ef7156.png

Source:
https://user-images.githubusercontent.com/20930745/34329046-1c6285be-e8f2-11e7-8ee5-fd67e54518ef.png
