### ISSUE TITLE
Ember - A few degrees better

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9519]
**App Name:** Ember - A few degrees better
**Bundle ID:** com.embertech.ios.Ember
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1147470931">1147470931</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ember-a-few-degrees-better/id1147470931?mt=8&uo=4">https://itunes.apple.com/us/app/ember-a-few-degrees-better/id1147470931?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** Ember Technologies Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ember-technologies-inc/id1063861447?uo=4">© Ember Technologies, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/ee/de/51/eede5142-57e1-c4a5-4677-9b28b4069b6b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34329069-af028c52-e8f2-11e7-9a25-fa992ed6d01a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34329069-af028c52-e8f2-11e7-9a25-fa992ed6d01a.png)
https://user-images.githubusercontent.com/20930745/34329069-af028c52-e8f2-11e7-9a25-fa992ed6d01a.png

Source:
https://user-images.githubusercontent.com/20930745/34329075-ca5a67ea-e8f2-11e7-8360-59dc46a84f02.png
