### ISSUE TITLE
Empower Retirement

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9520]
**App Name:** Empower Retirement
**Bundle ID:** com.empower-retirement.ios.Participant-Mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1001257338">1001257338</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/empower-retirement/id1001257338?mt=8&uo=4">https://itunes.apple.com/us/app/empower-retirement/id1001257338?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** GREAT-WEST LIFE & ANNUITY INSURANCE COMPANY
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/empower-retirement/id1001257337?uo=4">© Empower Retirement</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/2e/5a/79/2e5a793f-5875-e9e2-5a1a-a6825fb25399/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34329119-83f1367a-e8f3-11e7-8b9b-8979ecefb989.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34329119-83f1367a-e8f3-11e7-8b9b-8979ecefb989.png)
https://user-images.githubusercontent.com/20930745/34329119-83f1367a-e8f3-11e7-8b9b-8979ecefb989.png

Source:
https://user-images.githubusercontent.com/20930745/34329122-972044fc-e8f3-11e7-90fa-ea4f9a8cc426.png
