### ISSUE TITLE
iRobot HOME

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9521]
**App Name:** iRobot HOME
**Bundle ID:** com.irobot.home
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1012014442">1012014442</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/irobot-home/id1012014442?mt=8&uo=4">https://itunes.apple.com/us/app/irobot-home/id1012014442?mt=8&uo=4</a>
**App Version:** 2.5.0
**Seller:** iRobot Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/irobot-corporation/id479370968?uo=4">© iRobot Corporation</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/92/0c/06/920c062d-8c0d-57a9-ab97-83c16f425df2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34329135-250fdf34-e8f4-11e7-8fa6-51885454d51e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34329135-250fdf34-e8f4-11e7-8fa6-51885454d51e.png)
https://user-images.githubusercontent.com/20930745/34329135-250fdf34-e8f4-11e7-8fa6-51885454d51e.png

Source:
https://user-images.githubusercontent.com/20930745/34329138-38964eb2-e8f4-11e7-9a22-e7a12ca98a13.png
