### ISSUE TITLE
Club Penguin Island

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9522]
**App Name:** Club Penguin Island
**Bundle ID:** com.disney.clubpenguinremix
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=991869606">991869606</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/club-penguin-island/id991869606?mt=8&uo=4">https://itunes.apple.com/us/app/club-penguin-island/id991869606?mt=8&uo=4</a>
**App Version:** 1.8.1
**Seller:** Disney Electronic Content, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/disney/id284888248?mt=8&uo=4">© Disney</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/51/3a/1d/513a1dc8-a4a7-a490-f6b2-135cd2bca5b1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34403004-b97d1e08-eba5-11e7-9bce-6eb76ae927c7.png)

**Comment by Christian9901** [comment]
![club_penguin_island_logo](https://user-images.githubusercontent.com/34829888/34371098-0e0b23ac-ea7f-11e7-8f1f-a222ed72384d.png)

Use this is the penguins are too hard ;)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34403004-b97d1e08-eba5-11e7-9bce-6eb76ae927c7.png)
https://user-images.githubusercontent.com/2068130/34403004-b97d1e08-eba5-11e7-9bce-6eb76ae927c7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34403017-cd974d96-eba5-11e7-8d41-47e04c5b89ce.png
