### ISSUE TITLE
PowerSchool Mobile

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9523]
**App Name:** PowerSchool Mobile
**Bundle ID:** com.powerschool.portal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=973741088">973741088</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/powerschool-mobile/id973741088?mt=8&uo=4">https://itunes.apple.com/us/app/powerschool-mobile/id973741088?mt=8&uo=4</a>
**App Version:** 2.1.2
**Seller:** PowerSchool Group LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/powerschool-group-llc/id1057394489?uo=4">© PowerSchool Group LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/2b/ca/30/2bca30e5-09d5-86f1-6d87-6378ea8af942/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34357411-29ba872e-ea47-11e7-8026-90d46d4e1c78.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34357411-29ba872e-ea47-11e7-8026-90d46d4e1c78.png)
https://user-images.githubusercontent.com/20930745/34357411-29ba872e-ea47-11e7-8026-90d46d4e1c78.png

Source:
https://user-images.githubusercontent.com/20930745/34357425-417f2d38-ea47-11e7-97e2-84ab23c47b5b.png
