### ISSUE TITLE
Sandbox Coloring

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9524]
**App Name:** Sandbox Coloring
**Bundle ID:** art.sandbox.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1237405816">1237405816</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sandbox-coloring/id1237405816?mt=8&uo=4">https://itunes.apple.com/us/app/sandbox-coloring/id1237405816?mt=8&uo=4</a>
**App Version:** 1.1.4
**Seller:** Alexey Grigorkin
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/alexey-grigorkin/id1023358977?uo=4">© Alexey Grigorkin</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/27/14/eb/2714eb5d-af93-bb63-976d-c1c14b963935/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34357495-fbc3b254-ea47-11e7-90a5-c26cb47fb0c3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34357495-fbc3b254-ea47-11e7-90a5-c26cb47fb0c3.png)
https://user-images.githubusercontent.com/20930745/34357495-fbc3b254-ea47-11e7-90a5-c26cb47fb0c3.png

Source:
https://user-images.githubusercontent.com/20930745/34357513-120a269c-ea48-11e7-82bf-995597d625b2.png
