### ISSUE TITLE
Drimsim — go roaming free

### ISSUE THREAD

**Issue by vpww** [glasklart/hd#9525]
**App Name:** Drimsim — go roaming free
**Bundle ID:** com.drimsim
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1075908840">1075908840</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/drimsim-go-roaming-free/id1075908840?mt=8&uo=4">https://itunes.apple.com/us/app/drimsim-go-roaming-free/id1075908840?mt=8&uo=4</a>
**App Version:** 1.6.0
**Seller:** Sergey Redkov
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sergey-redkov/id1075908839?uo=4">© Sergey Redkov</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/dc/b3/6f/dcb36fef-e8b3-eca6-d11d-b376cd16ed5d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34357766-1a3b2062-ea4a-11e7-87a3-012e4c31ea59.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34357766-1a3b2062-ea4a-11e7-87a3-012e4c31ea59.png)
https://user-images.githubusercontent.com/20930745/34357766-1a3b2062-ea4a-11e7-87a3-012e4c31ea59.png

Source:
https://user-images.githubusercontent.com/20930745/34357777-2c77a6a6-ea4a-11e7-9b87-c6b2fab6ad0d.png
