### ISSUE TITLE
Yandex.Weather for iPhone

### ISSUE THREAD

**Issue by vpww** [glasklart/hd#9526]
**App Name:** Yandex.Weather for iPhone
**Bundle ID:** ru.yandex.mobile.weather-v2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1041008044">1041008044</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yandex-weather-for-iphone/id1041008044?mt=8&uo=4">https://itunes.apple.com/us/app/yandex-weather-for-iphone/id1041008044?mt=8&uo=4</a>
**App Version:** 4.1.4
**Seller:** Yandex, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yandex-llc/id308094652?uo=4">© Yandex LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/3e/19/f2/3e19f2ca-6cc1-1a36-f350-b58c77ac4dcf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34359633-e248516a-ea59-11e7-8980-4013ab6bece2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34359633-e248516a-ea59-11e7-8980-4013ab6bece2.png)
https://user-images.githubusercontent.com/20930745/34359633-e248516a-ea59-11e7-8980-4013ab6bece2.png

Source:
https://user-images.githubusercontent.com/20930745/34359637-f36edfcc-ea59-11e7-8473-7067c9aabfec.png
