### ISSUE TITLE
Мой МТС

### ISSUE THREAD

**Issue by vpww** [glasklart/hd#9527]
**App Name:** Мой МТС
**Bundle ID:** ru.mts.mymts
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1069871095">1069871095</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/%D0%BC%D0%BE%D0%B9-%D0%BC%D1%82%D1%81/id1069871095?mt=8&uo=4">https://itunes.apple.com/us/app/%D0%BC%D0%BE%D0%B9-%D0%BC%D1%82%D1%81/id1069871095?mt=8&uo=4</a>
**App Version:** 4.8.3
**Seller:** Mobile TeleSystems Public Joint Stock Company
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mobile-telesystems-public-joint-stock-company/id406999351?uo=4">© Mobile TeleSystems Public Joint Stock Company</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/c6/93/0f/c6930f5f-6533-abe3-85f1-b7fe5045e95b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34359701-74b9003a-ea5a-11e7-9054-7e7407cdb076.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34359701-74b9003a-ea5a-11e7-9054-7e7407cdb076.png)
https://user-images.githubusercontent.com/20930745/34359701-74b9003a-ea5a-11e7-9054-7e7407cdb076.png

Source:
https://user-images.githubusercontent.com/20930745/34359706-864a80bc-ea5a-11e7-812e-68505a3c9acd.png
