### ISSUE TITLE
Aeroexpress

### ISSUE THREAD

**Issue by vpww** [glasklart/hd#9528]
**App Name:** Aeroexpress
**Bundle ID:** ru.aeroexpress.mobileapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=587379898">587379898</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aeroexpress/id587379898?mt=8&uo=4">https://itunes.apple.com/us/app/aeroexpress/id587379898?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** AEROEKSPRESS OOO
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/aeroexpress-llc/id587379901?uo=4">© Aeroexpress LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple111/v4/10/74/ee/1074ee46-25be-7dc9-d8c1-e8e481d310eb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34359752-0de12c60-ea5b-11e7-84db-88fb31154d2d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34359752-0de12c60-ea5b-11e7-84db-88fb31154d2d.png)
https://user-images.githubusercontent.com/20930745/34359752-0de12c60-ea5b-11e7-84db-88fb31154d2d.png

Source:
https://user-images.githubusercontent.com/20930745/34359759-2430a6e4-ea5b-11e7-8aa7-f20ae1ebef45.png
