### ISSUE TITLE
Альфа-Банк

### ISSUE THREAD

**Issue by vpww** [glasklart/hd#9529]
**App Name:** Альфа-Банк
**Bundle ID:** com.alfabank.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=353127685">353127685</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/%D0%B0%D0%BB%D1%8C%D1%84%D0%B0-%D0%B1%D0%B0%D0%BD%D0%BA/id353127685?mt=8&uo=4">https://itunes.apple.com/us/app/%D0%B0%D0%BB%D1%8C%D1%84%D0%B0-%D0%B1%D0%B0%D0%BD%D0%BA/id353127685?mt=8&uo=4</a>
**App Version:** 10.0.1
**Seller:** AO ALFA-BANK
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ao-alfa-bank/id353127688?uo=4">© AO ALFA-BANK</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/c1/5f/c9/c15fc953-0453-b9c2-5ed0-3a0ccb904df1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34359844-afede660-ea5b-11e7-8096-062f6cb0f74e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34359844-afede660-ea5b-11e7-8096-062f6cb0f74e.png)
https://user-images.githubusercontent.com/20930745/34359844-afede660-ea5b-11e7-8096-062f6cb0f74e.png

Source:
https://user-images.githubusercontent.com/20930745/34359860-c385d598-ea5b-11e7-98c8-8d66397e8863.png
