### ISSUE TITLE
Поиск вакансий на HeadHunter

### ISSUE THREAD

**Issue by vpww** [glasklart/hd#9530]
**App Name:** Поиск вакансий на HeadHunter
**Bundle ID:** ru.hh.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=502838820">502838820</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/%D0%BF%D0%BE%D0%B8%D1%81%D0%BA-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D0%B9-%D0%BD%D0%B0-headhunter/id502838820?mt=8&uo=4">https://itunes.apple.com/us/app/%D0%BF%D0%BE%D0%B8%D1%81%D0%BA-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D0%B9-%D0%BD%D0%B0-headhunter/id502838820?mt=8&uo=4</a>
**App Version:** 4.5.1712
**Seller:** HeadHunter LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/headhunter/id502838823?uo=4">© HeadHunter</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/f3/cb/ae/f3cbaee1-061c-6b4a-96a7-1129e26f4e9b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34359924-3e4ea926-ea5c-11e7-8258-49866229220f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34359924-3e4ea926-ea5c-11e7-8258-49866229220f.png)
https://user-images.githubusercontent.com/20930745/34359924-3e4ea926-ea5c-11e7-8258-49866229220f.png

Source:
https://user-images.githubusercontent.com/20930745/34359928-5152cade-ea5c-11e7-8d9c-0a97ee142d4e.png
