### ISSUE TITLE
Buy Me a Pie! Classic - Grocery Shopping List

### ISSUE THREAD

**Issue by vpww** [glasklart/hd#9531]
**App Name:** Buy Me a Pie! Classic - Grocery Shopping List
**Bundle ID:** com.newskript.piefull
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=491322606">491322606</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/buy-me-a-pie-classic-grocery-shopping-list/id491322606?mt=8&uo=4">https://itunes.apple.com/us/app/buy-me-a-pie-classic-grocery-shopping-list/id491322606?mt=8&uo=4</a>
**App Version:** 3.5.7
**Seller:** National Business Group Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/skript-llc/id484021784?uo=4">© Skript, LLC</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple3/v4/80/70/73/8070733c-b5fc-8a21-5131-eeb8803d7e96/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34466604-d48187d4-eed9-11e7-92bf-9bb445b9d085.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34466604-d48187d4-eed9-11e7-92bf-9bb445b9d085.png)
https://user-images.githubusercontent.com/20930745/34466604-d48187d4-eed9-11e7-92bf-9bb445b9d085.png

Source:
https://user-images.githubusercontent.com/20930745/34466606-ecd814e2-eed9-11e7-98c7-c0510e8bf2d9.png
