### ISSUE TITLE
Meduza

### ISSUE THREAD

**Issue by vpww** [glasklart/hd#9532]
**App Name:** Meduza
**Bundle ID:** io.meduza.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=921508170">921508170</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/meduza/id921508170?mt=8&uo=4">https://itunes.apple.com/us/app/meduza/id921508170?mt=8&uo=4</a>
**App Version:** 3.16.1
**Seller:** Medusa Project SIA
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/meduza-project/id921508169?uo=4">© Meduza Project</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/61/6f/51/616f511a-0f9e-196e-1380-b621e3d4d411/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34360019-3e75ba24-ea5d-11e7-9a2b-b44cfab130fe.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34360019-3e75ba24-ea5d-11e7-9a2b-b44cfab130fe.png)
https://user-images.githubusercontent.com/20930745/34360019-3e75ba24-ea5d-11e7-9a2b-b44cfab130fe.png

Source:
https://user-images.githubusercontent.com/20930745/34360029-50b161b6-ea5d-11e7-82b0-cef649c81c47.png
