### ISSUE TITLE
Aeroflot — Online Tickets

### ISSUE THREAD

**Issue by vpww** [glasklart/hd#9533]
**App Name:** Aeroflot — Online Tickets
**Bundle ID:** ru.aeroflot.afl
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=580243869">580243869</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aeroflot-online-tickets/id580243869?mt=8&uo=4">https://itunes.apple.com/us/app/aeroflot-online-tickets/id580243869?mt=8&uo=4</a>
**App Version:** 3.11.1
**Seller:** Aeroflot - Russian airlines
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/%D0%BE%D0%B0%D0%BE-%D0%B0%D1%8D%D1%80%D0%BE%D1%84%D0%BB%D0%BE%D1%82/id580243872?uo=4">© ОАО "Аэрофлот"</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/65/d6/04/65d6043a-348d-271b-b3d3-c1345b63f17c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34360092-c767d45c-ea5d-11e7-8a09-113c208cfc19.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34360092-c767d45c-ea5d-11e7-8a09-113c208cfc19.png)
https://user-images.githubusercontent.com/20930745/34360092-c767d45c-ea5d-11e7-8a09-113c208cfc19.png

Source:
https://user-images.githubusercontent.com/20930745/34360106-d8017d9a-ea5d-11e7-8387-0e873ac26fcc.png
