### ISSUE TITLE
SmartDriver: Radar Detector

### ISSUE THREAD

**Issue by vpww** [glasklart/hd#9534]
**App Name:** SmartDriver: Radar Detector
**Bundle ID:** ru.reactivephone.AntiRadar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=866980876">866980876</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smartdriver-radar-detector/id866980876?mt=8&uo=4">https://itunes.apple.com/us/app/smartdriver-radar-detector/id866980876?mt=8&uo=4</a>
**App Version:** 1.6.13
**Seller:** Reactive Phone Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/reactive-phone-ltd/id407204784?uo=4">© Reactive Phone Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/97/72/65/977265c0-7ff8-e9f0-c7ca-b9025ddf930f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34390872-d00ad59c-eb42-11e7-9777-6e0bd22cdc14.png)

**Comment by vpww** [comment]
https://user-images.githubusercontent.com/34859751/34379688-83d67080-eb0d-11e7-95d5-05f6ba92c6e5.png
![ru reactivephone antiradar 3x](https://user-images.githubusercontent.com/34859751/34379688-83d67080-eb0d-11e7-95d5-05f6ba92c6e5.png)

![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/34859751/34379688-83d67080-eb0d-11e7-95d5-05f6ba92c6e5.png)

**Comment by dreamnet** [comment]
@vpww Very nice, but Your icon is a bit too big and I think the line in the middle is needed:
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34390872-d00ad59c-eb42-11e7-9777-6e0bd22cdc14.png)
https://user-images.githubusercontent.com/2068130/34390872-d00ad59c-eb42-11e7-9777-6e0bd22cdc14.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34390886-df2681de-eb42-11e7-995e-a616ef2b517c.png
