### ISSUE TITLE
i-Ready for Students

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9535]
**App Name:** i-Ready for Students
**Bundle ID:** com.i-ready.ireadyapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1155613065">1155613065</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/i-ready-for-students/id1155613065?mt=8&uo=4">https://itunes.apple.com/us/app/i-ready-for-students/id1155613065?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Curriculum Associates, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/curriculum-associates-llc/id454523409?uo=4">© Curriculum Associates, LLC</a>
**Supported Devices:** iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple127/v4/ce/29/d1/ce29d11c-7e4d-15b2-9d8b-42f896bc3014/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34394124-837cc84c-eb57-11e7-8fcc-58b1e9238dc7.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34394124-837cc84c-eb57-11e7-8fcc-58b1e9238dc7.png)
https://user-images.githubusercontent.com/2068130/34394124-837cc84c-eb57-11e7-8fcc-58b1e9238dc7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34394137-9452420a-eb57-11e7-88de-2d2111cbd861.png
