### ISSUE TITLE
Trampoline Park Stars

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9536]
**App Name:** Trampoline Park Stars
**Bundle ID:** com.jandogames.skyzonegame
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=996850274">996850274</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trampoline-park-stars/id996850274?mt=8&uo=4">https://itunes.apple.com/us/app/trampoline-park-stars/id996850274?mt=8&uo=4</a>
**App Version:** 1.4.7
**Seller:** JanDo Games, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jando-games/id996850273?uo=4">© Jando Games</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple117/v4/b6/fb/66/b6fb6653-da0e-26a0-4e1a-bfb081f2cb78/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34393917-5471aa00-eb56-11e7-9c60-ab55cb2afcdc.png)

**Comment by vpww** [comment]
![trampoline](https://user-images.githubusercontent.com/34859751/34382071-82853300-eb1d-11e7-8d26-3f4a7ccc2d75.png)

![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/34859751/34382071-82853300-eb1d-11e7-8d26-3f4a7ccc2d75.png)

**Comment by dreamnet** [comment]
@vpww WOW! Great work - but we need the [source file](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#icon-sources).

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34393917-5471aa00-eb56-11e7-9c60-ab55cb2afcdc.png)
https://user-images.githubusercontent.com/2068130/34393917-5471aa00-eb56-11e7-9c60-ab55cb2afcdc.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34393930-62e1ea00-eb56-11e7-9773-918a76959dc3.png
