### ISSUE TITLE
99 Arrows

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9538]
**App Name:** 99 Arrows
**Bundle ID:** com.tastypill.99arrows
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1257214099">1257214099</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/99-arrows/id1257214099?mt=8&uo=4">https://itunes.apple.com/us/app/99-arrows/id1257214099?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Tastypill LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tastypill/id1022434729?uo=4">© tastypill</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/87/a1/a1/87a1a1fa-ed69-abc4-0292-a89a75eb5b0f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34402041-84641d58-eb9f-11e7-9949-c4f12e6a536e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34402041-84641d58-eb9f-11e7-9949-c4f12e6a536e.png)
https://user-images.githubusercontent.com/2068130/34402041-84641d58-eb9f-11e7-9949-c4f12e6a536e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34402048-93dfd31c-eb9f-11e7-8457-30a2bea073ea.png
