### ISSUE TITLE
DICK’S Sporting Goods, Fitness

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9539]
**App Name:** DICK’S Sporting Goods, Fitness
**Bundle ID:** com.dsg.mobile.consumer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=556653197">556653197</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dicks-sporting-goods-fitness/id556653197?mt=8&uo=4">https://itunes.apple.com/us/app/dicks-sporting-goods-fitness/id556653197?mt=8&uo=4</a>
**App Version:** 4.1.2
**Seller:** Dick's Sporting Goods, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dicks-sporting-goods/id533803663?uo=4">© Dick's Sporting Goods</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/a1/b5/dc/a1b5dcdc-6d38-7ca2-283c-1abb9886d48b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34403480-bdc98570-eba8-11e7-9e97-542dc213816e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34403480-bdc98570-eba8-11e7-9e97-542dc213816e.png)
https://user-images.githubusercontent.com/2068130/34403480-bdc98570-eba8-11e7-9e97-542dc213816e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34403490-cd226f00-eba8-11e7-8c01-a766c400a10f.png
