### ISSUE TITLE
Transit • Real-Time App for Bus, Subway & Metro

### ISSUE THREAD

**Issue by richarddwalsh** [glasklart/hd#954]
**App Name:** Transit • Real-Time App for Bus, Subway & Metro
**Bundle ID:** com.samvermette.Transit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=498151501">498151501</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/transit-real-time-app-for/id498151501?mt=8&uo=4">https://itunes.apple.com/us/app/transit-real-time-app-for/id498151501?mt=8&uo=4</a>
**App Version:** 4.0.1
**Seller:** 9280-0366 Quebec inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/transit-app-inc./id889728710?uo=4>© Transit App, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/20/a9/3c/20a93c79-5339-ee23-415a-53dac79d73bc/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18794906/2281f1b6-81c2-11e6-918b-bcedc372fd77.png)

**Comment by ivanov007** [comment]
need update

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18794906/2281f1b6-81c2-11e6-918b-bcedc372fd77.png)
https://cloud.githubusercontent.com/assets/20930745/18794906/2281f1b6-81c2-11e6-918b-bcedc372fd77.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18794916/31a9eefa-81c2-11e6-9e93-5e79f8bd6714.png
