### ISSUE TITLE
Kum & Go &Rewards

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9540]
**App Name:** Kum & Go &Rewards
**Bundle ID:** com.kumandgo.rewards
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1065661067">1065661067</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/kum-go-rewards/id1065661067?mt=8&uo=4">https://itunes.apple.com/us/app/kum-go-rewards/id1065661067?mt=8&uo=4</a>
**App Version:** 1.2.2
**Seller:** Kum & Go, L.C.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kum-go/id467745341?uo=4">© Kum & Go</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/51/8c/71/518c7120-92c6-1bbe-ae46-c73f1d521ab4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34391170-73df5e80-eb44-11e7-8dbc-2096aef80f73.png)

**Comment by vpww** [comment]
![kum](https://user-images.githubusercontent.com/34859751/34381131-a3f4fda0-eb17-11e7-8ab9-b6ccc360ae4f.png)

![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/34859751/34381131-a3f4fda0-eb17-11e7-8ab9-b6ccc360ae4f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34391170-73df5e80-eb44-11e7-8dbc-2096aef80f73.png)
https://user-images.githubusercontent.com/2068130/34391170-73df5e80-eb44-11e7-8dbc-2096aef80f73.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34391187-84ba77b2-eb44-11e7-8b81-ad97e5c4f916.png
