### ISSUE TITLE
Trump Story - Make Money

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9541]
**App Name:** Trump Story - Make Money
**Bundle ID:** com.trumpcoin.58al4h
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1312293249">1312293249</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trump-story-make-money/id1312293249?mt=8&uo=4">https://itunes.apple.com/us/app/trump-story-make-money/id1312293249?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** wenjun Xiong
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wenjun-xiong/id1310518812?uo=4">© wenjun Xiong</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/4a/da/b2/4adab20f-2630-21d7-44a5-a4dbf75532f2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34636946-1dc3a474-f2ac-11e7-8d64-83b07141617f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34636946-1dc3a474-f2ac-11e7-8d64-83b07141617f.png)
https://user-images.githubusercontent.com/2068130/34636946-1dc3a474-f2ac-11e7-8d64-83b07141617f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34636952-2def3f5c-f2ac-11e7-89f0-fefefe4d2a39.png
