### ISSUE TITLE
Штрафы ПДД – ГИБДД, ГАИ онлайн

### ISSUE THREAD

**Issue by vpww** [glasklart/hd#9542]
**App Name:** Штрафы ПДД – ГИБДД, ГАИ онлайн
**Bundle ID:** ru.reactivephone.shtrafy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=407732503">407732503</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/%D1%88%D1%82%D1%80%D0%B0%D1%84%D1%8B-%D0%BF%D0%B4%D0%B4-%D0%B3%D0%B8%D0%B1%D0%B4%D0%B4-%D0%B3%D0%B0%D0%B8-%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD/id407732503?mt=8&uo=4">https://itunes.apple.com/us/app/%D1%88%D1%82%D1%80%D0%B0%D1%84%D1%8B-%D0%BF%D0%B4%D0%B4-%D0%B3%D0%B8%D0%B1%D0%B4%D0%B4-%D0%B3%D0%B0%D0%B8-%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD/id407732503?mt=8&uo=4</a>
**App Version:** 3.24
**Seller:** Reactive Phone Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/reactive-phone-ltd/id407204784?uo=4">© Reactive Phone Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/37/26/42/372642cc-e90a-5174-a8da-9c81b9736301/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34393696-9f9267e2-eb54-11e7-9243-547e1fcad115.png)

**Comment by vpww** [comment]
https://user-images.githubusercontent.com/34859751/34380578-986d7632-eb13-11e7-9a43-fafe4560817b.png

![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/34859751/34380578-986d7632-eb13-11e7-9a43-fafe4560817b.png)

**Comment by dreamnet** [comment]
@vpww Jup, great work - but please include the [source file](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#icon-sources) in your contribution.

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34393696-9f9267e2-eb54-11e7-9243-547e1fcad115.png)
https://user-images.githubusercontent.com/2068130/34393696-9f9267e2-eb54-11e7-9243-547e1fcad115.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34393703-add6467a-eb54-11e7-8854-7c4066eeebed.png
