### ISSUE TITLE
Jerrycan

### ISSUE THREAD

**Issue by vpww** [glasklart/hd#9543]
**App Name:** Jerrycan
**Bundle ID:** com.Jerrycan.Jerrycan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=707458900">707458900</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jerrycan/id707458900?mt=8&uo=4">https://itunes.apple.com/us/app/jerrycan/id707458900?mt=8&uo=4</a>
**App Version:** 1.3.2
**Seller:** Pavlo Grozian
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pavlo-grozian/id707458903?uo=4">© Pavlo Grozian</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/62/18/2e/62182e75-9e43-71ea-9c67-4f2a4ecfcbe3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34393476-07ed511e-eb53-11e7-9c94-4e8df9904036.png)

**Comment by vpww** [comment]
https://user-images.githubusercontent.com/34859751/34380688-7b6c42a6-eb14-11e7-9e5a-c5b5d95ae4cd.png

![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/34859751/34380688-7b6c42a6-eb14-11e7-9e5a-c5b5d95ae4cd.png)

**Comment by dreamnet** [comment]
@vpww Great work - but please include the [source file](https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon#icon-sources) in your contribution.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34393476-07ed511e-eb53-11e7-9c94-4e8df9904036.png)
https://user-images.githubusercontent.com/20930745/34393476-07ed511e-eb53-11e7-9c94-4e8df9904036.png

Source:
https://user-images.githubusercontent.com/20930745/34393485-19a2a79c-eb53-11e7-95cb-432bfc0d75bb.png
