### ISSUE TITLE
Round Icons

### ISSUE THREAD

**Issue by vpww** [glasklart/hd#9545]
Hello guys!
Which files should i edit to make round shape of icons?

**Comment by dreamnet** [comment]
@vpww Check [this](https://github.com/AnemoneTeam/Anemone/wiki/Icon-Effects).

**Comment by dreamnet** [comment]
@vpww Question answered?

**Comment by vpww** [comment]
@dreamnet yes!
made round icons. here is the result for homescreen and carplay
![2017-12-29 11 15 52](https://user-images.githubusercontent.com/34859751/34454248-5e93fd2a-ed78-11e7-8a5c-42860ab2358d.png)
![2017-12-29 11 15 53](https://user-images.githubusercontent.com/34859751/34454249-5eb15f14-ed78-11e7-8c59-6c334fc8c36a.png)

**Comment by dreamnet** [comment]
@vpww Yeah, some icons are too big, but generally it looks very nice. Congrats! 👍
