### ISSUE TITLE
The Sandbox Evolution

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9546]
**App Name:** The Sandbox Evolution
**Bundle ID:** com.pixowl.tsb2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=944393180">944393180</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-sandbox-evolution/id944393180?mt=8&uo=4">https://itunes.apple.com/us/app/the-sandbox-evolution/id944393180?mt=8&uo=4</a>
**App Version:** 1.4.8
**Seller:** PIXOWL INC.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pixowl-inc/id436959453?uo=4">© PIXOWL INC.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/18/65/d9/1865d9cd-be82-c7ae-09cf-646393f51298/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34636446-f97eba04-f2a1-11e7-8c12-4d3123ad666e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34636446-f97eba04-f2a1-11e7-8c12-4d3123ad666e.png)
https://user-images.githubusercontent.com/2068130/34636446-f97eba04-f2a1-11e7-8c12-4d3123ad666e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34636458-09828778-f2a2-11e7-9579-f2fada39e425.png
