### ISSUE TITLE
World's Worst Pet - Vocabulary

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9548]
**App Name:** World's Worst Pet - Vocabulary
**Bundle ID:** com.i-ready.wwp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=730540095">730540095</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/worlds-worst-pet-vocabulary/id730540095?mt=8&uo=4">https://itunes.apple.com/us/app/worlds-worst-pet-vocabulary/id730540095?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Curriculum Associates, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/curriculum-associates-llc/id454523409?uo=4">© Curriculum Associates, LLC</a>
**Supported Devices:** iPadWifi-iPadWifi, iPad3G-iPad3G, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/eb/7f/ec/eb7fec6f-eaef-1c5f-8f87-e3d087c6ced6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34467385-1410ccbe-eef0-11e7-83c1-840ac6189785.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34467385-1410ccbe-eef0-11e7-83c1-840ac6189785.png)
https://user-images.githubusercontent.com/20930745/34467385-1410ccbe-eef0-11e7-83c1-840ac6189785.png

Source:
https://user-images.githubusercontent.com/20930745/34467387-238cd976-eef0-11e7-86f7-0c1e4398f8ec.png
