### ISSUE TITLE
Animal Crossing: Pocket Camp

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9549]
**App Name:** Animal Crossing: Pocket Camp
**Bundle ID:** com.nintendo.zaca
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1179915619">1179915619</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/animal-crossing-pocket-camp/id1179915619?mt=8&uo=4">https://itunes.apple.com/us/app/animal-crossing-pocket-camp/id1179915619?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Nintendo Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nintendo-co-ltd/id1062496488?uo=4">© Nintendo Co., Ltd.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/ed/c2/96/edc296d1-6402-e62b-c049-f58823e57c9c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36916268-bcb923e2-1e53-11e8-94d6-c20d374d7b2e.png)

**Comment by 2Qt2beStr8** [comment]
only a try, i don't like it. game app Icons are not my passion

![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36665214-455c6a30-1ae7-11e8-8b0f-7843e7cff714.png)
https://user-images.githubusercontent.com/20930745/36665214-455c6a30-1ae7-11e8-8b0f-7843e7cff714.png

Source:
https://user-images.githubusercontent.com/20930745/36665282-6362e676-1ae7-11e8-80cc-93a5a6afc3d5.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 There are some missing details, but I think ist's not bad for a try! 👍

**Comment by 2Qt2beStr8** [comment]
so, i am out now - i can't do this - have no nerv for the little details
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36778157-3e058eac-1c6c-11e8-8a6b-998938aa8f13.png)
https://user-images.githubusercontent.com/20930745/36778157-3e058eac-1c6c-11e8-8a6b-998938aa8f13.png

Source:
https://user-images.githubusercontent.com/20930745/36778198-55d8f91a-1c6c-11e8-8e68-3df49574f09a.png

**Comment by ivanov007** [comment]
@2Qt2beStr8 I guess @dreamnet means that the two characters look like they are sticked together

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36913384-126e8016-1e4a-11e8-9d51-97fc0cf65f27.png)
https://user-images.githubusercontent.com/2068130/36913384-126e8016-1e4a-11e8-9d51-97fc0cf65f27.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/36913414-25c93e58-1e4a-11e8-906d-0fca07aa77b0.png
