### ISSUE TITLE
Pokémon: Magikarp Jump

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9550]
**App Name:** Pokémon: Magikarp Jump
**Bundle ID:** jp.pokemon.koiking
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1162679453">1162679453</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pok%C3%A9mon-magikarp-jump/id1162679453?mt=8&uo=4">https://itunes.apple.com/us/app/pok%C3%A9mon-magikarp-jump/id1162679453?mt=8&uo=4</a>
**App Version:** 1.3.4
**Seller:** The Pokemon Company
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-pokemon-company/id446737235?uo=4">© The Pokemon Company</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/6e/b1/e8/6eb1e899-e0bc-f095-dbaa-432c3f4ff5c1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/34464773-f56c9dba-ee54-11e7-8eab-df84df1e3958.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/34464773-f56c9dba-ee54-11e7-8eab-df84df1e3958.png)
https://user-images.githubusercontent.com/3090247/34464773-f56c9dba-ee54-11e7-8eab-df84df1e3958.png
Source:
https://user-images.githubusercontent.com/3090247/34464774-f586c29e-ee54-11e7-9182-c9680e7b7f02.png
