### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9551]
**App Name:** Microsoft Edge
**Bundle ID:** com.microsoft.msedge
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1288723196">1288723196</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/microsoft-edge/id1288723196?uo=4">https://apps.apple.com/us/app/microsoft-edge/id1288723196?uo=4</a>
**App Version:** 44.11.15
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/microsoft-corporation/id298856275?uo=4">© Microsoft Corporation</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/7e/11/30/7e1130bd-8770-aad9-3d0c-f54fd442c223/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/74263903-00624380-4d00-11ea-8d08-7df182a6fd39.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34393233-5dc3793a-eb51-11e7-95f3-7eb543771374.png)
https://user-images.githubusercontent.com/2068130/34393233-5dc3793a-eb51-11e7-95f3-7eb543771374.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34393238-6b9b484e-eb51-11e7-9759-c6c87bc1eff0.png

**Comment by Christian9901** [comment]
@dreamnet 

Dang, you're quick!

**Comment by dreamnet** [comment]
@Christian9901 Sometimes.... 😆

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/74263903-00624380-4d00-11ea-8d08-7df182a6fd39.png)
https://user-images.githubusercontent.com/2068130/74263903-00624380-4d00-11ea-8d08-7df182a6fd39.png
--- --- 
Source:
https://user-images.githubusercontent.com/2068130/74263927-0fe18c80-4d00-11ea-9b1c-2c7d22bbbbb3.png
