### ISSUE TITLE
Colorfy: Coloring Book

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9552]
**App Name:** Colorfy: Coloring Book
**Bundle ID:** com.fungames.colorfy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1009442510">1009442510</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/colorfy-coloring-book/id1009442510?mt=8&uo=4">https://itunes.apple.com/us/app/colorfy-coloring-book/id1009442510?mt=8&uo=4</a>
**App Version:** 4.8
**Seller:** Fun Games For Free
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/fun-games-for-free/id618574061?uo=4">© Fun Games For Free</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/af/b5/54/afb554ad-ff52-5f77-89d8-4c506d85041f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34396161-bd93345c-eb67-11e7-859e-b538d80fb66e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34396161-bd93345c-eb67-11e7-859e-b538d80fb66e.png)
https://user-images.githubusercontent.com/2068130/34396161-bd93345c-eb67-11e7-859e-b538d80fb66e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34396167-cc7adbb4-eb67-11e7-95e0-18d83e77cc1d.png
