### ISSUE TITLE
Windows Soundbar

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9553]
**App Name:** Windows Soundbar
**Bundle ID:** eu.akstudio.soundbar.windows
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=963132352">963132352</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/windows-soundbar/id963132352?mt=8&uo=4">https://itunes.apple.com/us/app/windows-soundbar/id963132352?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Appkaren s.r.o.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/appkaren-s-r-o/id914363112?uo=4">© Appkaren s.r.o.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple1/v4/1b/86/e3/1b86e31e-7a58-9edb-1a6a-af1f4affa5f5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34393759-21169be4-eb55-11e7-87ed-4a91e93f2b4e.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34393759-21169be4-eb55-11e7-87ed-4a91e93f2b4e.png)
https://user-images.githubusercontent.com/20930745/34393759-21169be4-eb55-11e7-87ed-4a91e93f2b4e.png

Source:
https://user-images.githubusercontent.com/20930745/34393770-369f2a26-eb55-11e7-82e9-de15503a7a47.png

**Comment by Christian9901** [comment]
insert windows xp startup sound here
