### ISSUE TITLE
Pineapple Pen

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9554]
**App Name:** Pineapple Pen
**Bundle ID:** com.ketchapp.pineapplepen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1159035153">1159035153</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pineapple-pen/id1159035153?mt=8&uo=4">https://itunes.apple.com/us/app/pineapple-pen/id1159035153?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Ketchapp
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ketchapp/id528065807?uo=4">© Ketchapp</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple111/v4/25/6f/2c/256f2c4f-06e0-bcfb-1a4e-8b236bf462f9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/34464607-25f7df70-ee4c-11e7-966c-206f83dc95af.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/34464607-25f7df70-ee4c-11e7-966c-206f83dc95af.png)
https://user-images.githubusercontent.com/3090247/34464607-25f7df70-ee4c-11e7-966c-206f83dc95af.png
Source:
https://user-images.githubusercontent.com/3090247/34464608-260daa58-ee4c-11e7-9843-56a5dc0b2485.png
