### ISSUE TITLE
GoNoodle Kids

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9556]
**App Name:** GoNoodle Kids
**Bundle ID:** com.gonoodle.GoNoodle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1050712293">1050712293</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gonoodle-kids/id1050712293?mt=8&uo=4">https://itunes.apple.com/us/app/gonoodle-kids/id1050712293?mt=8&uo=4</a>
**App Version:** 1.0.10
**Seller:** GoNoodle, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gonoodle-inc/id548928982?uo=4">© GoNoodle, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/bf/ea/0b/bfea0bb3-6434-7c20-a2e7-385535daa1c3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34396419-fb6ba6b2-eb6a-11e7-892b-29fd13537bc1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34396419-fb6ba6b2-eb6a-11e7-892b-29fd13537bc1.png)
https://user-images.githubusercontent.com/2068130/34396419-fb6ba6b2-eb6a-11e7-892b-29fd13537bc1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34396426-0a3c4700-eb6b-11e7-9cea-2a5438cb1fc0.png
