### ISSUE TITLE
Nick

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9557]
**App Name:** Nick
**Bundle ID:** com.mtvn.Nickelodeon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=596133590">596133590</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nick/id596133590?mt=8&uo=4">https://itunes.apple.com/us/app/nick/id596133590?mt=8&uo=4</a>
**App Version:** 3.5
**Seller:** Viacom International Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nickelodeon/id304682075?mt=8&uo=4">© Nickelodeon</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/ab/65/a6/ab65a692-78b8-6e7f-7959-af86eb7b5fe5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34396279-f4918700-eb68-11e7-9f9a-78b6b1192385.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34396279-f4918700-eb68-11e7-9f9a-78b6b1192385.png)
https://user-images.githubusercontent.com/2068130/34396279-f4918700-eb68-11e7-9f9a-78b6b1192385.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34396286-047dd1c8-eb69-11e7-8306-a4dc0becbfae.png
