### ISSUE TITLE
Chuck E. Cheese's Party Galaxy

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9558]
**App Name:** Chuck E. Cheese's Party Galaxy
**Bundle ID:** com.cec.partygalaxy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1035688651">1035688651</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chuck-e-cheeses-party-galaxy/id1035688651?mt=8&uo=4">https://itunes.apple.com/us/app/chuck-e-cheeses-party-galaxy/id1035688651?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** CEC Entertainment, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/chuck-e-cheeses/id615095509?uo=4">© Chuck E. Cheese’s</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/71/5c/42/715c42c5-90a0-7c0d-a394-1e9622bae5e7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36355170-e45d4478-14df-11e8-80ef-6a5e5a43a145.png)

**Comment by dreamnet** [comment]
Here is a sharper original artwork image:
<img src="http://is2.mzstatic.com/image/thumb/Purple111/v4/b7/b7/7e/b7b77e8f-2086-16ca-f72b-a626bf5d49b3/source/1024x1024bb.png" width="180" height="180">

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36355170-e45d4478-14df-11e8-80ef-6a5e5a43a145.png)
https://user-images.githubusercontent.com/2068130/36355170-e45d4478-14df-11e8-80ef-6a5e5a43a145.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/36355180-f1e8d08a-14df-11e8-9fdf-892a31419795.png
