### ISSUE TITLE
McPlay™

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9559]
**App Name:** McPlay™
**Bundle ID:** com.happymeal.mcplay
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=634672279">634672279</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mcplay/id634672279?mt=8&uo=4">https://itunes.apple.com/us/app/mcplay/id634672279?mt=8&uo=4</a>
**App Version:** 5.0.0
**Seller:** McDonald's Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mcdonalds-corporation/id425684917?uo=4">© McDonald's Corporation</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/ba/d8/d7/bad8d70c-931f-43c4-a27d-2c97f1f0a4c2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34411148-2b57bbe4-ebd5-11e7-87cb-dddfcffd5f89.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34411148-2b57bbe4-ebd5-11e7-87cb-dddfcffd5f89.png)
https://user-images.githubusercontent.com/2068130/34411148-2b57bbe4-ebd5-11e7-87cb-dddfcffd5f89.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34411160-3f334692-ebd5-11e7-8e17-9681aefa2162.png
