### ISSUE TITLE
GM Coach’s Playbook

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9560]
**App Name:** GM Coach’s Playbook
**Bundle ID:** com.mcdonalds.gmplaybook
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=624765131">624765131</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gm-coachs-playbook/id624765131?mt=8&uo=4">https://itunes.apple.com/us/app/gm-coachs-playbook/id624765131?mt=8&uo=4</a>
**App Version:** 1.5.3
**Seller:** McDonald's Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mcdonalds-corporation/id425684917?uo=4">© McDonald's Corporation</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPadWifi-iPadWifi, iPad3G-iPad3G, iPodTouchThirdGen-iPodTouchThirdGen, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple2/v4/41/91/94/419194f6-c296-d124-2558-b4904171fb68/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34432535-7204e3a2-ec78-11e7-9514-7e2a0998e03f.png)

**Comment by dreamnet** [comment]
Going the simple way:
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34432535-7204e3a2-ec78-11e7-9514-7e2a0998e03f.png)
https://user-images.githubusercontent.com/2068130/34432535-7204e3a2-ec78-11e7-9514-7e2a0998e03f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34432542-81975052-ec78-11e7-9cc1-9feac245423d.png
