### ISSUE TITLE
Grammarly Keyboard

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9561]
**App Name:** Grammarly Keyboard
**Bundle ID:** com.grammarly.keyboard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1158877342">1158877342</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/grammarly-keyboard/id1158877342?mt=8&uo=4">https://itunes.apple.com/us/app/grammarly-keyboard/id1158877342?mt=8&uo=4</a>
**App Version:** 1.0.17
**Seller:** Grammarly, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/grammarly-inc/id1134927945?uo=4">© Grammarly, Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/e2/ad/83/e2ad8336-2957-8ccf-4e28-6de14fe17af4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34396214-3cd07d74-eb68-11e7-9a25-c6d828ec29b4.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34396214-3cd07d74-eb68-11e7-9a25-c6d828ec29b4.png)
https://user-images.githubusercontent.com/2068130/34396214-3cd07d74-eb68-11e7-9a25-c6d828ec29b4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34396221-4b0a9d66-eb68-11e7-86bc-4a162dccc05f.png
