### ISSUE TITLE
BabyTV Mobile

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9562]
**App Name:** BabyTV Mobile
**Bundle ID:** com.applicaster.babytv.vod
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=418900349">418900349</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/babytv-mobile/id418900349?mt=8&uo=4">https://itunes.apple.com/us/app/babytv-mobile/id418900349?mt=8&uo=4</a>
**App Version:** 4.2.2
**Seller:** Baby Network Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/babytv-fox-networks-group/id418900352?uo=4">© BabyTV, Fox Networks Group</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/a9/91/f0/a991f036-a8e0-466d-ad64-32b0b6b49fd3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/34464706-1b3457b6-ee52-11e7-9749-e43839cc49a5.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/34464706-1b3457b6-ee52-11e7-9749-e43839cc49a5.png)
https://user-images.githubusercontent.com/3090247/34464706-1b3457b6-ee52-11e7-9749-e43839cc49a5.png
Source:
https://user-images.githubusercontent.com/3090247/34464707-1b5859b8-ee52-11e7-8b5a-09a44413c525.png
