### ISSUE TITLE
Amino: Communities and Groups

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9563]
**App Name:** Amino: Communities and Groups
**Bundle ID:** com.narvii.master
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1115565187">1115565187</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/amino-communities-and-groups/id1115565187?mt=8&uo=4">https://itunes.apple.com/us/app/amino-communities-and-groups/id1115565187?mt=8&uo=4</a>
**App Version:** 1.8.28
**Seller:** Narvii Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/narvii-inc/id490555895?uo=4">© Narvii Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/71/66/18/716618a5-5a83-aa2e-017b-ae721036daf1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34402546-8d66ef04-eba2-11e7-86f9-f8148d94234a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34402546-8d66ef04-eba2-11e7-86f9-f8148d94234a.png)
https://user-images.githubusercontent.com/2068130/34402546-8d66ef04-eba2-11e7-86f9-f8148d94234a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34402557-9f9b0638-eba2-11e7-969d-9ab9d2543a68.png
