### ISSUE TITLE
Rudolph Red-Nosed Reindeer

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9564]
**App Name:** Rudolph Red-Nosed Reindeer
**Bundle ID:** com.oceanhousemedia.BookRudolphDeluxe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1055204150">1055204150</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rudolph-red-nosed-reindeer/id1055204150?mt=8&uo=4">https://itunes.apple.com/us/app/rudolph-red-nosed-reindeer/id1055204150?mt=8&uo=4</a>
**App Version:** 4.0.10
**Seller:** Oceanhouse Media, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/oceanhouse-media/id309501176?uo=4">© Oceanhouse Media</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/99/8c/5c/998c5ca7-c4f5-c109-c4e2-b00f82d943af/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34467674-952e0b6a-eef8-11e7-99bf-e100045a366e.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34467479-a0eed164-eef3-11e7-9ae1-b129c842e2c2.png)
https://user-images.githubusercontent.com/20930745/34467479-a0eed164-eef3-11e7-9ae1-b129c842e2c2.png

Source:
https://user-images.githubusercontent.com/20930745/34467482-b38addd6-eef3-11e7-951b-41146df579ae.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 I think it's fine to include the the "OM" amd the line at the bottom.
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34467674-952e0b6a-eef8-11e7-99bf-e100045a366e.png)
https://user-images.githubusercontent.com/2068130/34467674-952e0b6a-eef8-11e7-99bf-e100045a366e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34467678-a564e170-eef8-11e7-9cc8-d95e48b6387d.png
Credits are going to you anyway. 😄
