### ISSUE TITLE
Quidd: Stickers, GIFs & More!

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9565]
**App Name:** Quidd: Stickers, GIFs & More!
**Bundle ID:** com.quidd.quidd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1063166978">1063166978</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quidd-stickers-gifs-more/id1063166978?mt=8&uo=4">https://itunes.apple.com/us/app/quidd-stickers-gifs-more/id1063166978?mt=8&uo=4</a>
**App Version:** 3.2.0
**Seller:** Quidd Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/quidd-inc/id1063166977?mt=8&uo=4">© Quidd Inc</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/95/8d/4b/958d4b86-1f2b-313f-0fd0-ee2a55047ef8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54256147-4eece800-455b-11e9-8828-0b09008fe223.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34456722-449d2e0c-ed9e-11e7-8854-eec1e5317384.png)
https://user-images.githubusercontent.com/2068130/34456722-449d2e0c-ed9e-11e7-8854-eec1e5317384.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34456723-555894f2-ed9e-11e7-8981-86c2af953c04.png
❓ ❓ ❓

**Comment by Christian9901** [comment]
needs new icon

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54256147-4eece800-455b-11e9-8828-0b09008fe223.png)
https://user-images.githubusercontent.com/20930745/54256147-4eece800-455b-11e9-8828-0b09008fe223.png

Source:
https://user-images.githubusercontent.com/20930745/54256148-50b6ab80-455b-11e9-8936-6f4a15b748af.png
