### ISSUE TITLE
LookUp: An elegant dictionary

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9566]
**App Name:** LookUp: An elegant dictionary
**Bundle ID:** in.muditbhargava.LookUp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=872564448">872564448</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lookup-an-elegant-dictionary/id872564448?mt=8&uo=4">https://itunes.apple.com/us/app/lookup-an-elegant-dictionary/id872564448?mt=8&uo=4</a>
**App Version:** 4.0.2
**Seller:** Rajesh Bhargava
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rajesh-bhargava/id458980813?uo=4">© Rajesh Bhargava</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/3c/78/e2/3c78e260-080a-c3c1-1bbc-c5fdfd65170c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34466472-a937cc96-eed4-11e7-8b38-49eb7f3b74e1.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34466472-a937cc96-eed4-11e7-8b38-49eb7f3b74e1.png)
https://user-images.githubusercontent.com/20930745/34466472-a937cc96-eed4-11e7-8b38-49eb7f3b74e1.png

Source:
https://user-images.githubusercontent.com/20930745/34466473-bb5fc964-eed4-11e7-8ba7-dc10e4addf06.png
