### ISSUE TITLE
Laserlike

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9567]
**App Name:** Laserlike
**Bundle ID:** com.laserlike.searchlike
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1246441938">1246441938</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/laserlike/id1246441938?mt=8&uo=4">https://itunes.apple.com/us/app/laserlike/id1246441938?mt=8&uo=4</a>
**App Version:** 5.16.120
**Seller:** Laserlike Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/laserlike-inc/id1097783264?uo=4">© Laserlike Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/5d/2e/fe/5d2efe28-2b05-1fcf-173a-6b8615f9343e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com laserlike laserlike-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37559434-5f335d62-2a26-11e8-9b33-aa3c3eeaa98a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34455673-5cd86c58-ed84-11e7-99dc-f346f2dfa054.png)
https://user-images.githubusercontent.com/2068130/34455673-5cd86c58-ed84-11e7-99dc-f346f2dfa054.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34455678-6dbe03a2-ed84-11e7-804a-30032883bc8a.png

**Comment by l8er4now** [comment]
Needs an update. Can use icon from old version [here](https://github.com/glasklart/hd/issues/9235)

**App Name:** Laserlike
**Bundle ID:** com.laserlike.searchlike
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1246441938">1246441938</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/laserlike/id1246441938?mt=8&uo=4">https://itunes.apple.com/us/app/laserlike/id1246441938?mt=8&uo=4</a>
**App Version:** 5.16.120
**Seller:** Laserlike Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/laserlike-inc/id1097783264?uo=4">© Laserlike Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/5d/2e/fe/5d2efe28-2b05-1fcf-173a-6b8615f9343e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
Icon from @2Qt2beStr8 .
![com laserlike laserlike-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37559434-5f335d62-2a26-11e8-9b33-aa3c3eeaa98a.png)
https://user-images.githubusercontent.com/2068130/37559434-5f335d62-2a26-11e8-9b33-aa3c3eeaa98a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37559436-6ea7eb28-2a26-11e8-8952-6035c57b04a0.png
