### ISSUE TITLE
Linnk - Powerful Bookmarking

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9568]
**App Name:** Linnk - Powerful Bookmarking
**Bundle ID:** com.linnk.Linnk
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1113361350">1113361350</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/linnk-powerful-bookmarking/id1113361350?mt=8&uo=4">https://itunes.apple.com/us/app/linnk-powerful-bookmarking/id1113361350?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Suzhou YuanJing Information Technology Co.,LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yuanjing-co-ltd/id1113361349?uo=4">© YuanJing Co.,Ltd.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/f2/c6/3e/f2c63ef7-0ecf-3315-bfbd-11c586e78ed8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34455626-7f5481aa-ed83-11e7-915f-5b92f81de023.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34455626-7f5481aa-ed83-11e7-915f-5b92f81de023.png)
https://user-images.githubusercontent.com/2068130/34455626-7f5481aa-ed83-11e7-915f-5b92f81de023.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34455632-8eed4df4-ed83-11e7-932a-c97a9ad861e8.png
