### ISSUE TITLE
IKEA Home smart (TRÅDFRI)

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9569]
**App Name:** IKEA Home smart (TRÅDFRI)
**Bundle ID:** com.ikea.tradfri.lighting
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1195836071">1195836071</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ikea-home-smart-tr%C3%A5dfri/id1195836071?uo=4">https://apps.apple.com/us/app/ikea-home-smart-tr%C3%A5dfri/id1195836071?uo=4</a>
**App Version:** 1.10.1
**Seller:** Inter IKEA Systems B.V.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/inter-ikea-systems-b-v/id339722471?uo=4">© Inter IKEA Systems B.V.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/fe/e7/4e/fee74ed6-06e6-a9d3-2a76-d33cbf245ac6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63653637-c4e2b580-c76f-11e9-81a9-ac9049f26d9b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34456526-05639e06-ed99-11e7-85a7-f9704fcfaa7c.png)
https://user-images.githubusercontent.com/2068130/34456526-05639e06-ed99-11e7-85a7-f9704fcfaa7c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34456530-14f44a6e-ed99-11e7-876e-ad33c2e963fc.png

**Comment by l8er4now** [comment]
Needs an update

**App Name:** IKEA Home smart (TRÅDFRI)
**Bundle ID:** com.ikea.tradfri.lighting
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1195836071">1195836071</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/ikea-home-smart-tr%C3%A5dfri/id1195836071?uo=4">https://apps.apple.com/us/app/ikea-home-smart-tr%C3%A5dfri/id1195836071?uo=4</a>
**App Version:** 1.10.1
**Seller:** Inter IKEA Systems B.V.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/inter-ikea-systems-b-v/id339722471?uo=4">© Inter IKEA Systems B.V.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/fe/e7/4e/fee74ed6-06e6-a9d3-2a76-d33cbf245ac6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/63653637-c4e2b580-c76f-11e9-81a9-ac9049f26d9b.png)
https://user-images.githubusercontent.com/20930745/63653637-c4e2b580-c76f-11e9-81a9-ac9049f26d9b.png

Source:
https://user-images.githubusercontent.com/20930745/63653639-c613e280-c76f-11e9-8ccf-cbe3a6bda25a.png
