### ISSUE TITLE
Plume Air Report — Pollution

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9570]
**App Name:** Plume Air Report — Pollution
**Bundle ID:** com.plumehq.Jungle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=950289243">950289243</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/plume-air-report-pollution/id950289243?mt=8&uo=4">https://itunes.apple.com/us/app/plume-air-report-pollution/id950289243?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Plume Labs SAS
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/plume-labs/id950289242?uo=4">© Plume Labs</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/19/42/b6/1942b69f-d163-1ed9-6874-2b6c694f3c0d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34455603-92960a3c-ed82-11e7-8267-684bf614c1c1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34455603-92960a3c-ed82-11e7-8267-684bf614c1c1.png)
https://user-images.githubusercontent.com/2068130/34455603-92960a3c-ed82-11e7-8267-684bf614c1c1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34455607-a288c1c8-ed82-11e7-9541-23e5c907cb39.png
