### ISSUE TITLE
AP News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9571]
**App Name:** AP News
**Bundle ID:** com.apnews.ipad.mobilenewsdevel
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364677107">364677107</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ap-news/id364677107?mt=8&uo=4">https://itunes.apple.com/us/app/ap-news/id364677107?mt=8&uo=4</a>
**App Version:** 1.9.9
**Seller:** The Associated Press
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-associated-press/id284901419?uo=4">© The Associated Press</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/30/62/43/3062430b-a9f5-c5a3-560a-f0b069713a1f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34460151-42470e70-ee07-11e7-93b9-8a8751f8820b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34460151-42470e70-ee07-11e7-93b9-8a8751f8820b.png)
https://user-images.githubusercontent.com/2068130/34460151-42470e70-ee07-11e7-93b9-8a8751f8820b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34460153-5436ebe6-ee07-11e7-9782-a358b892addd.png
