### ISSUE TITLE
Calendar 366: Events & Tasks

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9572]
**App Name:** Calendar 366: Events & Tasks
**Bundle ID:** com.nspektor.ios.Calendar-366
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1265892516">1265892516</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/calendar-366-events-tasks/id1265892516?uo=4">https://apps.apple.com/us/app/calendar-366-events-tasks/id1265892516?uo=4</a>
**App Version:** 1.10.8
**Seller:** Vincent Miethe
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/vincent-miethe/id928053823?uo=4">© Vincent Miethe</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/7e/98/ec/7e98ec3c-4b09-dc13-0b99-4541e75bb56a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83298141-31ee1480-a1f4-11ea-82d7-04d0a32bdf09.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34460329-52612e90-ee0b-11e7-9751-a60a7b0b21b4.png)
https://user-images.githubusercontent.com/2068130/34460329-52612e90-ee0b-11e7-9751-a60a7b0b21b4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34460333-61da2a34-ee0b-11e7-88dd-2270f8e587c7.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Calendar 366
**Bundle ID:** com.nspektor.ios.Calendar-366
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1265892516">1265892516</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calendar-366/id1265892516?mt=8&uo=4">https://itunes.apple.com/us/app/calendar-366/id1265892516?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** Vincent Miethe
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vincent-miethe/id928053823?uo=4">© Vincent Miethe</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/e4/5d/e4/e45de4e5-d7d2-506d-9752-df567c918b3e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37878649-9b4f0e8a-306c-11e8-8127-f3141240bde7.png)
https://user-images.githubusercontent.com/2068130/37878649-9b4f0e8a-306c-11e8-8127-f3141240bde7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37878651-aafdfc60-306c-11e8-94c5-58a20f847002.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Calendar 366: Events & Tasks
**Bundle ID:** com.nspektor.ios.Calendar-366
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1265892516">1265892516</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/calendar-366-events-tasks/id1265892516?uo=4">https://apps.apple.com/us/app/calendar-366-events-tasks/id1265892516?uo=4</a>
**App Version:** 1.10.8
**Seller:** Vincent Miethe
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/vincent-miethe/id928053823?uo=4">© Vincent Miethe</a>
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/7e/98/ec/7e98ec3c-4b09-dc13-0b99-4541e75bb56a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/83298141-31ee1480-a1f4-11ea-82d7-04d0a32bdf09.png)
https://user-images.githubusercontent.com/2068130/83298141-31ee1480-a1f4-11ea-82d7-04d0a32bdf09.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/83298190-4205f400-a1f4-11ea-8f26-31fd52be85d3.png
