### ISSUE TITLE
ShopSavvy Barcode Scanner

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9573]
**App Name:** ShopSavvy Barcode Scanner
**Bundle ID:** com.biggu.shopsavvyapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=338828953">338828953</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/shopsavvy-barcode-scanner/id338828953?uo=4">https://apps.apple.com/us/app/shopsavvy-barcode-scanner/id338828953?uo=4</a>
**App Version:** 14.5.6
**Seller:** ShopSavvy, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/shopsavvy-inc/id327762559?uo=4">© ShopSavvy, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/df/04/e4/df04e409-b161-d40e-c1ee-3dc5f6023f7a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65357950-abab1880-dbf8-11e9-8878-c12fface2e0e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34460270-e0e12b9a-ee09-11e7-8df6-08579c4cfbf2.png)
https://user-images.githubusercontent.com/2068130/34460270-e0e12b9a-ee09-11e7-8df6-08579c4cfbf2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34460274-f09a02be-ee09-11e7-9def-5520262638c9.png

**Comment by l8er4now** [comment]
Needs an update

**App Name:** ShopSavvy Barcode Scanner
**Bundle ID:** com.biggu.shopsavvyapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=338828953">338828953</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/shopsavvy-barcode-scanner/id338828953?uo=4">https://apps.apple.com/us/app/shopsavvy-barcode-scanner/id338828953?uo=4</a>
**App Version:** 14.5.6
**Seller:** ShopSavvy, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/shopsavvy-inc/id327762559?uo=4">© ShopSavvy, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/df/04/e4/df04e409-b161-d40e-c1ee-3dc5f6023f7a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/65357950-abab1880-dbf8-11e9-8878-c12fface2e0e.png)
https://user-images.githubusercontent.com/2068130/65357950-abab1880-dbf8-11e9-8878-c12fface2e0e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/65357971-bb2a6180-dbf8-11e9-92e7-4bc6b262f454.png
