### ISSUE TITLE
Savelist

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9574]
**App Name:** Savelist
**Bundle ID:** co.savelist.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=989575671">989575671</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/savelist/id989575671?mt=8&uo=4">https://itunes.apple.com/us/app/savelist/id989575671?mt=8&uo=4</a>
**App Version:** 2.4.0
**Seller:** Savelist SL
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/savelist-sl/id1105000971?uo=4">© Savelist SL</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/fb/e3/69/fbe369a7-fde4-71b9-1d17-200689cb3e35/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large_2](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34456591-6e4948c0-ed9a-11e7-8a98-6f34a9ab8f26.png)

**Comment by dreamnet** [comment]
This:
![-large_1](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34456585-4f143e92-ed9a-11e7-8cc8-c0a11c24bf8b.png)
https://user-images.githubusercontent.com/2068130/34456585-4f143e92-ed9a-11e7-8cc8-c0a11c24bf8b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34456588-60e7e376-ed9a-11e7-8839-34b01a92f4bf.png)
or this:
![-large_2](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34456591-6e4948c0-ed9a-11e7-8a98-6f34a9ab8f26.png)
https://user-images.githubusercontent.com/2068130/34456591-6e4948c0-ed9a-11e7-8a98-6f34a9ab8f26.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34456594-80a8d562-ed9a-11e7-9b6c-2c6c9e8a7cf3.png
@l8er4now ?

**Comment by dreamnet** [comment]
Taking the second one.
