### ISSUE TITLE
Anews.com

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9575]
**App Name:** Anews.com
**Bundle ID:** com.onlinepp.anews
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=711455211">711455211</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/anews-com/id711455211?mt=8&uo=4">https://itunes.apple.com/us/app/anews-com/id711455211?mt=8&uo=4</a>
**App Version:** 2.48
**Seller:** Anews Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/anews-inc/id863952770?uo=4">© Anews Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/55/b8/24/55b824e4-196e-e591-2369-0d2be1ca16e8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34456445-aefb7d74-ed96-11e7-8bce-1b035c9f3ffd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34456445-aefb7d74-ed96-11e7-8bce-1b035c9f3ffd.png)
https://user-images.githubusercontent.com/2068130/34456445-aefb7d74-ed96-11e7-8bce-1b035c9f3ffd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34456448-c1f764b0-ed96-11e7-8740-1506c3c451c7.png
