### ISSUE TITLE
Crunchbase

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9576]
**App Name:** Crunchbase
**Bundle ID:** com.crunchbase
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1134089028">1134089028</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/crunchbase/id1134089028?mt=8&uo=4">https://itunes.apple.com/us/app/crunchbase/id1134089028?mt=8&uo=4</a>
**App Version:** 1.4.3
**Seller:** CrunchBase, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/crunchbase/id1134089027?uo=4">© Crunchbase</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/6d/53/05/6d530523-8269-e562-6dec-f12d212860e0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34456472-4aea159c-ed97-11e7-8eca-74559d2ff8e1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34456472-4aea159c-ed97-11e7-8eca-74559d2ff8e1.png)
https://user-images.githubusercontent.com/2068130/34456472-4aea159c-ed97-11e7-8eca-74559d2ff8e1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34456474-594c4222-ed97-11e7-9a86-584be02e9449.png
