### ISSUE TITLE
Dashboard for Apple Health App

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9577]
**App Name:** Dashboard for Apple Health App
**Bundle ID:** com.sunnystudio.fitcoach
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=963634595">963634595</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dashboard-for-apple-health-app/id963634595?mt=8&uo=4">https://itunes.apple.com/us/app/dashboard-for-apple-health-app/id963634595?mt=8&uo=4</a>
**App Version:** 1.5
**Seller:** Rong Liu
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sunny-studio/id430274590?uo=4">© Sunny Studio</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/d6/85/b5/d685b5ce-02e1-1beb-03a2-30b3361d2778/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34462523-114a1c6a-ee46-11e7-8892-c54274e5fd2a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34462523-114a1c6a-ee46-11e7-8892-c54274e5fd2a.png)
https://user-images.githubusercontent.com/20930745/34462523-114a1c6a-ee46-11e7-8892-c54274e5fd2a.png

Source:
https://user-images.githubusercontent.com/20930745/34462531-28a301c4-ee46-11e7-8be5-9f2362bacfd9.png
