### ISSUE TITLE
Stepwise Pedometer

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9578]
**App Name:** Stepwise Pedometer
**Bundle ID:** com.progressconcepts.stepwise
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=788761724">788761724</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stepwise-pedometer/id788761724?mt=8&uo=4">https://itunes.apple.com/us/app/stepwise-pedometer/id788761724?mt=8&uo=4</a>
**App Version:** 3.1.16
**Seller:** Progress Concepts Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/progress-concepts-limited/id788761727?uo=4">© Progress Concepts Limited</a>
**Supported Devices:** iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/27/0c/1f/270c1ff0-55a6-aaaf-2471-007ea4afc141/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34462562-d389cfa0-ee46-11e7-8e30-eccb3926546a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34462562-d389cfa0-ee46-11e7-8e30-eccb3926546a.png)
https://user-images.githubusercontent.com/20930745/34462562-d389cfa0-ee46-11e7-8e30-eccb3926546a.png

Source:
https://user-images.githubusercontent.com/20930745/34462564-ed3cb908-ee46-11e7-86dc-c5ccf1c7c2bd.png
