### ISSUE TITLE
Quora

### ISSUE THREAD

**Issue by NuckChorris** [glasklart/hd#958]
**App Name:** Quora
**Bundle ID:** com.quora.app.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=456034437">456034437</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quora/id456034437?mt=8&uo=4">https://itunes.apple.com/us/app/quora/id456034437?mt=8&uo=4</a>
**App Version:** 5.0.7
**Seller:** Quora, Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/quora-inc./id456034440?uo=4>© Quora, Inc.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/20/b6/4e/20b64e53-adf2-2eb9-a329-dc0ff0c6ecdd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222590/676183cc-8e5c-11e6-8327-4ee2ac07ae1c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/19222590/676183cc-8e5c-11e6-8327-4ee2ac07ae1c.png)
https://cloud.githubusercontent.com/assets/2068130/19222590/676183cc-8e5c-11e6-8327-4ee2ac07ae1c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/19222594/759b8848-8e5c-11e6-819d-340940de7356.png
