### ISSUE TITLE
Tuber: Watch videos natively

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9580]
**App Name:** Tuber: Watch videos natively
**Bundle ID:** com.muhammadbassio.Tuber
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=555919650">555919650</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tuber-watch-videos-natively/id555919650?mt=8&uo=4">https://itunes.apple.com/us/app/tuber-watch-videos-natively/id555919650?mt=8&uo=4</a>
**App Version:** 8.0
**Seller:** Muhammad Al Bassiouny
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/muhammad-al-bassiouny/id477536169?uo=4">© Muhammad Al Bassiouny</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/ed/05/30/ed053059-9fe7-7352-35cc-56e33a23f987/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34462634-7f1873b6-ee48-11e7-808b-0267cbfad334.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34462634-7f1873b6-ee48-11e7-808b-0267cbfad334.png)
https://user-images.githubusercontent.com/20930745/34462634-7f1873b6-ee48-11e7-808b-0267cbfad334.png

Source:
https://user-images.githubusercontent.com/20930745/34462638-9138dba8-ee48-11e7-888d-fe1d7e81fc2c.png
