### ISSUE TITLE
ZoneTime

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9581]
**App Name:** ZoneTime
**Bundle ID:** info.gtbox.ZoneTime
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=852849552">852849552</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zonetime/id852849552?mt=8&uo=4">https://itunes.apple.com/us/app/zonetime/id852849552?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Glen Tregoning
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/glen-tregoning/id852849555?uo=4">© Glen Tregoning</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/4b/ab/17/4bab1777-56e3-f0bd-472f-0f15542ce211/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34462855-10b0004c-ee4d-11e7-900b-d160a49b5654.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34462855-10b0004c-ee4d-11e7-900b-d160a49b5654.png)
https://user-images.githubusercontent.com/20930745/34462855-10b0004c-ee4d-11e7-900b-d160a49b5654.png

Soure:
https://user-images.githubusercontent.com/20930745/34462857-224c06d4-ee4d-11e7-9147-e99c899b7102.png
