### ISSUE TITLE
Time Intersect - World Time

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9582]
**App Name:** Time Intersect - World Time
**Bundle ID:** com.josesantos.TimeIntersect
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=998121750">998121750</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/time-intersect-world-time/id998121750?mt=8&uo=4">https://itunes.apple.com/us/app/time-intersect-world-time/id998121750?mt=8&uo=4</a>
**App Version:** 1.3.4
**Seller:** Jose Santos
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jose-santos/id998121749?uo=4">© Jose Santos</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/e2/97/21/e29721fa-191b-52f5-c4ec-7fb36640d647/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34462742-d5283d84-ee4a-11e7-9a51-e5acb0777bff.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34462742-d5283d84-ee4a-11e7-9a51-e5acb0777bff.png)
https://user-images.githubusercontent.com/20930745/34462742-d5283d84-ee4a-11e7-9a51-e5acb0777bff.png

Source:
https://user-images.githubusercontent.com/20930745/34462746-e502e542-ee4a-11e7-8cf7-aa5d8cb38d50.png
