### ISSUE TITLE
CARROT Weather

### ISSUE THREAD

**Issue by SparksCatcher** [glasklart/hd#9585]
**App Name:** CARROT Weather
**Bundle ID:** com.grailr.CARROTweather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=961390574">961390574</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/carrot-weather/id961390574?mt=8&uo=4">https://itunes.apple.com/us/app/carrot-weather/id961390574?mt=8&uo=4</a>
**App Version:** 4.4
**Seller:** Grailr LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/grailr-llc/id556706923?uo=4">© Grailr LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/00/c6/26/00c62681-9969-c8a0-49d2-9579dc7eedcf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34915800-63e45f58-f92c-11e7-9c41-c5232511d1bd.png)

**Comment by dreamnet** [comment]
@SparksCatcher Please read our WIKI - [How to Submit an Icon Request](https://github.com/glasklart/hd/wiki/How-to-Submit-an-Icon-Request)
We need the iTunes ID for the apps your requested.

**Comment by Christian9901** [comment]
**App Name:** CARROT Weather
**Bundle ID:** com.grailr.CARROTweather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=961390574">961390574</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/carrot-weather/id961390574?mt=8&uo=4">https://itunes.apple.com/us/app/carrot-weather/id961390574?mt=8&uo=4</a>
**App Version:** 4.4
**Seller:** Grailr LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/grailr-llc/id556706923?uo=4">© Grailr LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/00/c6/26/00c62681-9969-c8a0-49d2-9579dc7eedcf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34915800-63e45f58-f92c-11e7-9c41-c5232511d1bd.png)
https://user-images.githubusercontent.com/20930745/34915800-63e45f58-f92c-11e7-9c41-c5232511d1bd.png

Source:
https://user-images.githubusercontent.com/20930745/34915807-74fc2a32-f92c-11e7-869a-ebe9517cb882.png
