### ISSUE TITLE
VeganXpress - Menu & Shopping Assistance

### ISSUE THREAD

**Issue by SparksCatcher** [glasklart/hd#9586]
**App Name:** VeganXpress - Menu & Shopping Assistance
**Bundle ID:** com.tofupunk.VeganXpress
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=307591991">307591991</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/veganxpress-menu-shopping-assistance/id307591991?mt=8&uo=4">https://itunes.apple.com/us/app/veganxpress-menu-shopping-assistance/id307591991?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** Brandon Berger
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/brandon-berger/id307591994?uo=4">© Brandon Berger</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/90/fe/01/90fe0197-9b0e-cc00-d2ce-2811981e8856/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36349340-646d2e14-1484-11e8-8621-be4db26e554d.png)

**Comment by Christian9901** [comment]
**App Name:** VeganXpress - Menu & Shopping Assistance
**Bundle ID:** com.tofupunk.VeganXpress
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=307591991">307591991</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/veganxpress-menu-shopping-assistance/id307591991?mt=8&uo=4">https://itunes.apple.com/us/app/veganxpress-menu-shopping-assistance/id307591991?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** Brandon Berger
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/brandon-berger/id307591994?uo=4">© Brandon Berger</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple69/v4/90/fe/01/90fe0197-9b0e-cc00-d2ce-2811981e8856/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36349340-646d2e14-1484-11e8-8621-be4db26e554d.png)
https://user-images.githubusercontent.com/20930745/36349340-646d2e14-1484-11e8-8621-be4db26e554d.png

Source:
![veganxpress](https://user-images.githubusercontent.com/20930745/36349343-79e711b0-1484-11e8-8d17-8bb43316d8b6.png)
