### ISSUE TITLE
LIFX

### ISSUE THREAD

**Issue by SparksCatcher** [glasklart/hd#9587]
**App Name:** LIFX
**Bundle ID:** com.lifx.lifx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=657758311">657758311</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lifx/id657758311?mt=8&uo=4">https://itunes.apple.com/us/app/lifx/id657758311?mt=8&uo=4</a>
**App Version:** 3.8.6
**Seller:** LIFI LABS MANAGEMENT PTY LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lifx/id657758314?uo=4">© LIFX</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/65/4c/c2/654cc2eb-1101-299b-3774-6f5a31cead36/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34913656-7750fbc4-f903-11e7-8867-325732fb4c99.png)

**Comment by Christian9901** [comment]
**App Name:** LIFX
**Bundle ID:** com.lifx.lifx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=657758311">657758311</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lifx/id657758311?mt=8&uo=4">https://itunes.apple.com/us/app/lifx/id657758311?mt=8&uo=4</a>
**App Version:** 3.8.6
**Seller:** LIFI LABS MANAGEMENT PTY LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lifx/id657758314?uo=4">© LIFX</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/65/4c/c2/654cc2eb-1101-299b-3774-6f5a31cead36/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34913656-7750fbc4-f903-11e7-8867-325732fb4c99.png)
https://user-images.githubusercontent.com/2068130/34913656-7750fbc4-f903-11e7-8867-325732fb4c99.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34913659-8698a352-f903-11e7-8833-3d5086a2451c.png
