### ISSUE TITLE
Astro Mail - Email Meets AI

### ISSUE THREAD

**Issue by SparksCatcher** [glasklart/hd#9588]
**App Name:** Astro Mail - Email Meets AI
**Bundle ID:** com.pexlabs.Huskymail.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1076356487">1076356487</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/astro-mail-email-meets-ai/id1076356487?mt=8&uo=4">https://itunes.apple.com/us/app/astro-mail-email-meets-ai/id1076356487?mt=8&uo=4</a>
**App Version:** 2.6.6
**Seller:** Astro Technology, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/astro-technology-inc/id1076356486?uo=4">© Astro Technology, Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/27/df/11/27df11f6-737a-a298-5a05-6b76af94c290/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34918570-b953a048-f954-11e7-9e47-39afa72176c7.png)

**Comment by Christian9901** [comment]
**App Name:** Astro Mail - Email Meets AI
**Bundle ID:** com.pexlabs.Huskymail.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1076356487">1076356487</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/astro-mail-email-meets-ai/id1076356487?mt=8&uo=4">https://itunes.apple.com/us/app/astro-mail-email-meets-ai/id1076356487?mt=8&uo=4</a>
**App Version:** 2.6.6
**Seller:** Astro Technology, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/astro-technology-inc/id1076356486?uo=4">© Astro Technology, Inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/27/df/11/27df11f6-737a-a298-5a05-6b76af94c290/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34918570-b953a048-f954-11e7-9e47-39afa72176c7.png)
https://user-images.githubusercontent.com/2068130/34918570-b953a048-f954-11e7-9e47-39afa72176c7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34918571-cc56a8a2-f954-11e7-9ea9-e418eef39d35.png
