### ISSUE TITLE
Focus-before inspiration fades

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9589]
**App Name:** Focus-before inspiration fades
**Bundle ID:** com.Space-Inc.Focus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1296583540">1296583540</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/focus-before-inspiration-fades/id1296583540?mt=8&uo=4">https://itunes.apple.com/us/app/focus-before-inspiration-fades/id1296583540?mt=8&uo=4</a>
**App Version:** 1.0.7
**Seller:** Hamad Fouad
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/hamad-fouad/id1296583539?uo=4">© Hamad Fouad</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/1c/2f/67/1c2f67c2-0ea1-bd30-7b66-80ad1eb768c4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34909243-b17e3f48-f89d-11e7-8190-ca576f96f831.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34909243-b17e3f48-f89d-11e7-8190-ca576f96f831.png)
https://user-images.githubusercontent.com/2068130/34909243-b17e3f48-f89d-11e7-8190-ca576f96f831.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34909248-c1145dfc-f89d-11e7-8da9-c7baaef6ec18.png
