### ISSUE TITLE
Taskful: The Smart To-Do List

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9590]
**App Name:** Taskful: The Smart To-Do List
**Bundle ID:** com.radstag.taskful
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1195370211">1195370211</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/taskful-the-smart-to-do-list/id1195370211?mt=8&uo=4">https://itunes.apple.com/us/app/taskful-the-smart-to-do-list/id1195370211?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** Big Bold Company, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/big-bold-company-llc/id1170236101?uo=4">© Big Bold Company, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/be/94/1d/be941d7b-24da-ec25-7d46-a83abda75f34/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34909276-45791e5c-f89e-11e7-9783-3f6141dcd243.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34909276-45791e5c-f89e-11e7-9783-3f6141dcd243.png)
https://user-images.githubusercontent.com/2068130/34909276-45791e5c-f89e-11e7-9783-3f6141dcd243.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34909280-59126fe0-f89e-11e7-8433-3fbe0fa691c4.png
