### ISSUE TITLE
Widget Reminders

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9591]
**App Name:** Widget Reminders
**Bundle ID:** kr.co.ll2016.WidgetReminders
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1209759007">1209759007</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/widget-reminders/id1209759007?mt=8&uo=4">https://itunes.apple.com/us/app/widget-reminders/id1209759007?mt=8&uo=4</a>
**App Version:** 1.0.5
**Seller:** TaeSu Lee
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/taesu-lee/id545155271?uo=4">© TaeSu Lee</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/b8/7e/9d/b87e9d4a-a9dd-2aa2-84a2-a5b9d54a4425/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34909302-e321dcc0-f89e-11e7-90e7-e5e5398273c2.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34909302-e321dcc0-f89e-11e7-90e7-e5e5398273c2.png)
https://user-images.githubusercontent.com/2068130/34909302-e321dcc0-f89e-11e7-90e7-e5e5398273c2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34909304-f281020e-f89e-11e7-9bb0-3e3efff132f2.png
