### ISSUE TITLE
Sleek Calendar

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9592]
**App Name:** Sleek Calendar
**Bundle ID:** com.enseeyab.sleek
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1139617717">1139617717</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sleek-calendar/id1139617717?mt=8&uo=4">https://itunes.apple.com/us/app/sleek-calendar/id1139617717?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Saqib Halwani
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/saqib-halwani/id1315781977?uo=4">© Saqib Halwani</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/f9/f4/a6/f9f4a63c-f2d1-96ae-8340-9462477d93c3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34909220-1a373004-f89d-11e7-8de1-335ff0414267.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34909220-1a373004-f89d-11e7-8de1-335ff0414267.png)
https://user-images.githubusercontent.com/2068130/34909220-1a373004-f89d-11e7-8de1-335ff0414267.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34909222-2aafac68-f89d-11e7-8c13-81693d234df1.png
