### ISSUE TITLE
Tiny Month - Easy Calendar

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9593]
**App Name:** Tiny Month - Easy Calendar
**Bundle ID:** com.limepresso.pocketmonth
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=763303815">763303815</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tiny-month-easy-calendar/id763303815?mt=8&uo=4">https://itunes.apple.com/us/app/tiny-month-easy-calendar/id763303815?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Sangwon Kim
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/limepresso/id541568418?uo=4">© Limepresso</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/e7/4e/7b/e74e7b9e-7128-9746-5e46-5bb72fd0ecb4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34909457-a1a99596-f8a1-11e7-84b1-aac65ac10b9a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34909457-a1a99596-f8a1-11e7-84b1-aac65ac10b9a.png)
https://user-images.githubusercontent.com/2068130/34909457-a1a99596-f8a1-11e7-84b1-aac65ac10b9a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34909458-b10996f8-f8a1-11e7-9cbf-0515e46618e6.png
