### ISSUE TITLE
Widget Calendar : Easy&Simple

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9594]
**App Name:** Widget Calendar : Easy&Simple
**Bundle ID:** kr.co.ll2016.WidgetCalendar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1078875308">1078875308</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/widget-calendar-easy-simple/id1078875308?mt=8&uo=4">https://itunes.apple.com/us/app/widget-calendar-easy-simple/id1078875308?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** TaeSu Lee
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/taesu-lee/id545155271?uo=4">© TaeSu Lee</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/8a/a5/70/8aa57056-3a0e-ba85-59a2-a290f22c0aaa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34909520-07372cd8-f8a3-11e7-91e8-84d5afa0d861.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34909520-07372cd8-f8a3-11e7-91e8-84d5afa0d861.png)
https://user-images.githubusercontent.com/2068130/34909520-07372cd8-f8a3-11e7-91e8-84d5afa0d861.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34909525-183042f4-f8a3-11e7-9c41-8cb3d1e0a8a7.png
