### ISSUE TITLE
Deemo

### ISSUE THREAD

**Issue by Dengekiko** [glasklart/hd#9596]
**App Name:** Deemo
**Bundle ID:** com.rayark.pluto
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=700637744">700637744</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/deemo/id700637744?mt=8&uo=4">https://itunes.apple.com/us/app/deemo/id700637744?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** Rayark International Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rayark-international-limited/id483529071?uo=4">© Rayark International Limited</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/f3/b9/0c/f3b90cce-46de-09e0-3b7e-2b6f25153157/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34908981-a24d5bc0-f899-11e7-8044-1ebc6d67be53.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34908981-a24d5bc0-f899-11e7-8044-1ebc6d67be53.png)
https://user-images.githubusercontent.com/2068130/34908981-a24d5bc0-f899-11e7-8044-1ebc6d67be53.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34908993-b5039b44-f899-11e7-9542-6b265b33f69a.png
