### ISSUE TITLE
VOEZ

### ISSUE THREAD

**Issue by Dengekiko** [glasklart/hd#9597]
**App Name:** VOEZ
**Bundle ID:** com.rayark.valkyrie
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1007929736">1007929736</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/voez/id1007929736?mt=8&uo=4">https://itunes.apple.com/us/app/voez/id1007929736?mt=8&uo=4</a>
**App Version:** 1.1.3
**Seller:** Rayark International Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rayark-international-limited/id483529071?uo=4">© Rayark International Limited</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/71/18/77/71187709-1101-ae38-4257-788f1e7df271/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36366374-229cdb04-154e-11e8-8ed6-6c4e1992bb71.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36366374-229cdb04-154e-11e8-8ed6-6c4e1992bb71.png)
https://user-images.githubusercontent.com/20930745/36366374-229cdb04-154e-11e8-8ed6-6c4e1992bb71.png

Source:
https://user-images.githubusercontent.com/20930745/36366395-3a6f2f5c-154e-11e8-830a-78dfee3ff4cf.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Yup 👍Maybe there is no other way...
