### ISSUE TITLE
Cytus

### ISSUE THREAD

**Issue by Dengekiko** [glasklart/hd#9598]
**App Name:** Cytus
**Bundle ID:** com.rayark.Cytus.full
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=485246824">485246824</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cytus/id485246824?mt=8&uo=4">https://itunes.apple.com/us/app/cytus/id485246824?mt=8&uo=4</a>
**App Version:** 10.0.0
**Seller:** Rayark International Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rayark-international-limited/id483529071?uo=4">© Rayark International Limited</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple71/v4/1f/1c/82/1f1c82e8-5bcb-0121-4c65-e9709568a4c4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36366635-46fe2c86-154f-11e8-92a5-b96d64b451d0.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36366635-46fe2c86-154f-11e8-92a5-b96d64b451d0.png)
https://user-images.githubusercontent.com/20930745/36366635-46fe2c86-154f-11e8-92a5-b96d64b451d0.png

Source:
https://user-images.githubusercontent.com/20930745/36366653-5daee786-154f-11e8-8308-c6ae03aef3aa.png

**Comment by Neoflare** [comment]
Can you try cropping out the background and just leaving the head?

**Comment by 2Qt2beStr8** [comment]
@Neoflare it's not so easy and Looks not perfect

![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36412687-8c608e78-161b-11e8-8326-4f9cf18ed553.png)
https://user-images.githubusercontent.com/20930745/36412687-8c608e78-161b-11e8-8326-4f9cf18ed553.png

Source:
https://user-images.githubusercontent.com/20930745/36412692-97615096-161b-11e8-876f-73bd965c747f.png

**Comment by dreamnet** [comment]
I think the first one is better...
