### ISSUE TITLE
The Manga.

### ISSUE THREAD

**Issue by Dengekiko** [glasklart/hd#9599]
**App Name:** The Manga.
**Bundle ID:** com.acghhh.comich
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1089887918">1089887918</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-manga/id1089887918?mt=8&uo=4">https://itunes.apple.com/us/app/the-manga/id1089887918?mt=8&uo=4</a>
**App Version:** 3.7
**Seller:** Cao Ye
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/cao-ye/id1089887917?uo=4">© Cao Ye</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/c7/61/0d/c7610df0-8f73-0fda-cb46-6a26c651ac97/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34909041-b5a42892-f89a-11e7-9b1b-0404aacab04f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34909041-b5a42892-f89a-11e7-9b1b-0404aacab04f.png)
https://user-images.githubusercontent.com/2068130/34909041-b5a42892-f89a-11e7-9b1b-0404aacab04f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34909044-c43fef80-f89a-11e7-8384-da3e1f3cccb4.png
