### ISSUE TITLE
Expo Client

### ISSUE THREAD

**Issue by tmillerklugman** [glasklart/hd#9600]
**App Name:** Expo Client
**Bundle ID:** host.exp.Exponent
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=982107779">982107779</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/expo-client/id982107779?uo=4">https://apps.apple.com/us/app/expo-client/id982107779?uo=4</a>
**App Version:** 2.11.1
**Seller:** 650 Industries, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/nametag/id905743090?uo=4">© Nametag</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/53/b4/96/53b4969f-ae00-d9cc-305e-67b7afdab04a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388511-fd894a00-9ab2-11e9-9960-cd8d9be4f4b3.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34909014-391954fa-f89a-11e7-887c-89d3b1124d44.png)
https://user-images.githubusercontent.com/2068130/34909014-391954fa-f89a-11e7-887c-89d3b1124d44.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34909019-4bd9a0ea-f89a-11e7-9d65-4c4b77f5eadf.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60388511-fd894a00-9ab2-11e9-9960-cd8d9be4f4b3.png)
https://user-images.githubusercontent.com/20930745/60388511-fd894a00-9ab2-11e9-9960-cd8d9be4f4b3.png

Source:
https://user-images.githubusercontent.com/20930745/60388517-10038380-9ab3-11e9-88e0-b9541a6a9457.png
