### ISSUE TITLE
Sankaku

### ISSUE THREAD

**Issue by SparksCatcher** [glasklart/hd#9601]
**App Name:** Sankaku
**Bundle ID:** com.complex.ichan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1139689972">1139689972</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sankaku/id1139689972?mt=8&uo=4">https://itunes.apple.com/us/app/sankaku/id1139689972?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Complex Developments LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/complex-developments/id1139689971?uo=4">© Complex Developments</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/a3/b4/33/a3b433a3-24da-3afa-433a-38e18f81d983/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34915714-35725e1e-f92b-11e7-8b03-2a2d6bb36b33.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34915714-35725e1e-f92b-11e7-8b03-2a2d6bb36b33.png)
https://user-images.githubusercontent.com/20930745/34915714-35725e1e-f92b-11e7-8b03-2a2d6bb36b33.png

Source:
https://user-images.githubusercontent.com/20930745/34915729-73af4142-f92b-11e7-914c-4194cebf4ac1.png
