### ISSUE TITLE
djay 2

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9602]
**App Name:** djay 2
**Bundle ID:** com.algoriddim.djay2-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=669196929">669196929</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/djay-2/id669196929?mt=8&uo=4">https://itunes.apple.com/us/app/djay-2/id669196929?mt=8&uo=4</a>
**App Version:** 2.8.8
**Seller:** algoriddim GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/algoriddim-gmbh/id355721993?uo=4">© algoriddim GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/f1/de/41/f1de4115-37a3-4e20-e4cd-4dbd105f20a4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34915601-a78e6030-f929-11e7-8643-051f3c00be6e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/34915601-a78e6030-f929-11e7-8643-051f3c00be6e.png)
https://user-images.githubusercontent.com/2068130/34915601-a78e6030-f929-11e7-8643-051f3c00be6e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/34915605-b64ee5c2-f929-11e7-8022-2001dacab110.png
