### ISSUE TITLE
Mi Amena

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9605]
**App Name:** Mi Amena
**Bundle ID:** com.orange.sp.miamena
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=848377755">848377755</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/es/app/mi-amena/id848377755?mt=8&uo=4">https://itunes.apple.com/es/app/mi-amena/id848377755?mt=8&uo=4</a>
**App Version:** 4.1.0
**Seller:** France Telecom Espana S.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/es/developer/orange-spain/id370553435?uo=4">© Orange Spain</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/3a/be/6a/3abe6ac5-6102-d4a9-7414-29d1044fbd7d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34954708-c5495a14-fa21-11e7-9cb2-0123bc07cc22.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34954708-c5495a14-fa21-11e7-9cb2-0123bc07cc22.png)
https://user-images.githubusercontent.com/20930745/34954708-c5495a14-fa21-11e7-9cb2-0123bc07cc22.png

Source:
https://user-images.githubusercontent.com/20930745/34954732-d8e7c13c-fa21-11e7-952d-b9b5f9d1d631.png
