### ISSUE TITLE
RenfeTicket

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9606]
**App Name:** RenfeTicket
**Bundle ID:** com.renfe.RenfeTicket
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=727555862">727555862</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/renfeticket/id727555862?mt=8&uo=4">https://itunes.apple.com/us/app/renfeticket/id727555862?mt=8&uo=4</a>
**App Version:** 1.6.18
**Seller:** RENFE OPERADORA
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/renfe-operadora/id547564349?uo=4">© Renfe Operadora</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/bc/a7/73/bca77390-a44e-c2cf-0bac-93adefab19dd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34954931-9c6d8d6c-fa22-11e7-8f62-ea19c759e939.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34954931-9c6d8d6c-fa22-11e7-8f62-ea19c759e939.png)
https://user-images.githubusercontent.com/20930745/34954931-9c6d8d6c-fa22-11e7-8f62-ea19c759e939.png

Source:
https://user-images.githubusercontent.com/20930745/34954947-b0833cd4-fa22-11e7-8633-cb3e49387129.png
