### ISSUE TITLE
ALSA: buy bus tickets

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9607]
**App Name:** ALSA: buy bus tickets
**Bundle ID:** es.alsa.Alsa
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=444511709">444511709</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/alsa-buy-bus-tickets/id444511709?mt=8&uo=4">https://itunes.apple.com/us/app/alsa-buy-bus-tickets/id444511709?mt=8&uo=4</a>
**App Version:** 5.11.1
**Seller:** ALSA GRUPO SL
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/alsa-grupo-s-l-u/id444511712?uo=4">© Alsa Grupo S.L.U</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/66/53/c0/6653c082-02ed-85c5-8a30-0f962c35e5ba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34955094-40e8599e-fa23-11e7-9e19-290e0148a8db.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34955094-40e8599e-fa23-11e7-9e19-290e0148a8db.png)
https://user-images.githubusercontent.com/20930745/34955094-40e8599e-fa23-11e7-9e19-290e0148a8db.png

Source:
https://user-images.githubusercontent.com/20930745/34955119-52c126a0-fa23-11e7-9a7e-228319e797ff.png
