### ISSUE TITLE
¡HOLA! ESPAÑA Sitio web

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9608]
**App Name:** ¡HOLA! ESPAÑA Sitio web
**Bundle ID:** com.hola.holamagazine
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=598586345">598586345</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hola-espa%C3%B1a-sitio-web/id598586345?mt=8&uo=4">https://itunes.apple.com/us/app/hola-espa%C3%B1a-sitio-web/id598586345?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** HOLA S.L.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/hola-s-l/id487150718?uo=4">© HOLA S.L.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/ba/c6/8a/bac68afc-1adf-b8c1-f9ac-45849ea399d7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34955239-cf92e434-fa23-11e7-841c-7a51f7951c29.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34955239-cf92e434-fa23-11e7-841c-7a51f7951c29.png)
https://user-images.githubusercontent.com/20930745/34955239-cf92e434-fa23-11e7-841c-7a51f7951c29.png

Source:
https://user-images.githubusercontent.com/20930745/34955255-e1708d1e-fa23-11e7-8b83-c2d621cfd15e.png
