### ISSUE TITLE
HubSpot

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9609]
**App Name:** HubSpot
**Bundle ID:** com.hubspot.CRMAppRelease
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1107711722">1107711722</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hubspot/id1107711722?mt=8&uo=4">https://itunes.apple.com/us/app/hubspot/id1107711722?mt=8&uo=4</a>
**App Version:** 2.28.2
**Seller:** HubSpot
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/hubspot-inc/id380033836?uo=4">© HubSpot, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/f2/04/96/f2049627-f645-5d9d-fc1d-cff9dc164906/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34955364-5820507a-fa24-11e7-972d-9876b88311a0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34955364-5820507a-fa24-11e7-972d-9876b88311a0.png)
https://user-images.githubusercontent.com/20930745/34955364-5820507a-fa24-11e7-972d-9876b88311a0.png

Source:
https://user-images.githubusercontent.com/20930745/34955383-6ad0c1b4-fa24-11e7-81b1-fbc10de311fe.png
