### ISSUE TITLE
Dolphin Web Browser for iPad

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9610]
**App Name:** Dolphin Web Browser for iPad
**Bundle ID:** com.dolphin.browser.pad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=460812023">460812023</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dolphin-web-browser-for-ipad/id460812023?mt=8&uo=4">https://itunes.apple.com/us/app/dolphin-web-browser-for-ipad/id460812023?mt=8&uo=4</a>
**App Version:** 9.24.4
**Seller:** MOBOTAP INC.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mobotap-inc/id433626481?uo=4">© MoboTap Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/74/0b/29/740b2959-e30b-5c29-8d9b-a96a3d61dd52/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34955955-22853b80-fa27-11e7-88f8-d7033c1467f7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34955955-22853b80-fa27-11e7-88f8-d7033c1467f7.png)
https://user-images.githubusercontent.com/20930745/34955955-22853b80-fa27-11e7-88f8-d7033c1467f7.png

Source:
https://user-images.githubusercontent.com/20930745/34955966-35cd67bc-fa27-11e7-88c8-320de57b6c07.png
