### ISSUE TITLE
boon.

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9611]
**App Name:** boon.
**Bundle ID:** de.wirecard.boon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1042647367">1042647367</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/boon/id1042647367?mt=8&uo=4">https://itunes.apple.com/gb/app/boon/id1042647367?mt=8&uo=4</a>
**App Version:** 1.14
**Seller:** Wirecard Technologies GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/wirecard-technologies-gmbh/id560550245?uo=4">© Wirecard Technologies GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/92/c2/9e/92c29e50-0f09-a1df-6d9b-7296dd77a5f8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34956087-d159c428-fa27-11e7-9ef7-03bc16950c50.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34956087-d159c428-fa27-11e7-9ef7-03bc16950c50.png)
https://user-images.githubusercontent.com/20930745/34956087-d159c428-fa27-11e7-9ef7-03bc16950c50.png

Source:
https://user-images.githubusercontent.com/20930745/34956099-e64752d8-fa27-11e7-89c8-9968eeb3a49d.png
