### ISSUE TITLE
MASmusculo

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9612]
**App Name:** MASmusculo
**Bundle ID:** com.paldeveloppers.masmusculo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=642606259">642606259</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/masmusculo/id642606259?mt=8&uo=4">https://itunes.apple.com/us/app/masmusculo/id642606259?mt=8&uo=4</a>
**App Version:** 4.0.3
**Seller:** Osunasport Desarollo
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/osunasport-desarollo/id983649149?uo=4">© Osunasport Desarollo</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/7d/aa/45/7daa45a8-926e-bcca-ac58-74431e4f3ee1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34956182-5a691e4e-fa28-11e7-9b4d-dfae682067c3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34956182-5a691e4e-fa28-11e7-9b4d-dfae682067c3.png)
https://user-images.githubusercontent.com/20930745/34956182-5a691e4e-fa28-11e7-9b4d-dfae682067c3.png

Source:
https://user-images.githubusercontent.com/20930745/34956208-705949b8-fa28-11e7-9448-eed8d7282a78.png
