### ISSUE TITLE
Telegram X

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9613]
**App Name:** Telegram X
**Bundle ID:** org.telegram.TelegramHD
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=898228810">898228810</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/telegram-x/id898228810?mt=8&uo=4">https://itunes.apple.com/us/app/telegram-x/id898228810?mt=8&uo=4</a>
**App Version:** 5.0.1
**Seller:** TELEGRAM MESSENGER LLP
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/telegram-messenger-llp/id898228813?uo=4">© Telegram Messenger LLP</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/45/7c/6f/457c6f60-d7e1-8955-06bb-f910ce8ba56c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34956392-1bea4cd2-fa29-11e7-9468-ed3795176cd7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34956392-1bea4cd2-fa29-11e7-9468-ed3795176cd7.png)
https://user-images.githubusercontent.com/20930745/34956392-1bea4cd2-fa29-11e7-9468-ed3795176cd7.png

Source:
https://user-images.githubusercontent.com/20930745/34956412-2fb4cc4c-fa29-11e7-8e4c-a1ee5d7efe87.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/34956542-dd650bea-fa29-11e7-8ec6-886d6edc45c3.png)
https://user-images.githubusercontent.com/20930745/34956542-dd650bea-fa29-11e7-8ec6-886d6edc45c3.png

Source:
https://user-images.githubusercontent.com/20930745/34956559-f2373692-fa29-11e7-81c1-90af23f0ea13.png
