### ISSUE TITLE
Carrefour PASS Móvil

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9614]
**App Name:** Carrefour PASS Móvil
**Bundle ID:** com.carrefour.carrefourPass
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1016811445">1016811445</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/carrefour-pass-m%C3%B3vil/id1016811445?mt=8&uo=4">https://itunes.apple.com/us/app/carrefour-pass-m%C3%B3vil/id1016811445?mt=8&uo=4</a>
**App Version:** 2.0.14
**Seller:** CENTROS COMERCIALES CARREFOUR SA
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/centros-comerciales-carrefour-sa/id602547112?uo=4">© CENTROS COMERCIALES CARREFOUR SA</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/8c/b3/95/8cb39538-5152-5b4a-0bfc-d3378792776d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35056552-77553f2a-fbb2-11e7-98ba-438ce761679b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35056491-49adb638-fbb2-11e7-8352-bdad54ac0413.png)
https://user-images.githubusercontent.com/20930745/35056491-49adb638-fbb2-11e7-8352-bdad54ac0413.png

Source:
https://user-images.githubusercontent.com/20930745/35056520-5c9150ca-fbb2-11e7-8e1c-395dabc8a0e6.png
