### ISSUE TITLE
Dashlane Password Manager

### ISSUE THREAD

**Issue by mryli** [glasklart/hd#9616]
**App Name:** Dashlane Password Manager
**Bundle ID:** com.dashlane.dashlanephonefinal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=517914548">517914548</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dashlane-password-manager/id517914548?mt=8&uo=4">https://itunes.apple.com/us/app/dashlane-password-manager/id517914548?mt=8&uo=4</a>
**App Version:** 5.4.2
**Seller:** Dashlane
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dashlane/id507134346?uo=4">© Dashlane</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/0e/58/78/0e587831-ef04-1495-9ed2-f2d44251611a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35467916-325d5b54-0315-11e8-8b01-1d50f13f2775.png)

**Comment by mryli** [comment]
![com dashlane dashlanephonefinal-large](https://user-images.githubusercontent.com/35707855/35245604-c6d0a1ea-ffbb-11e7-8fa8-0c265c42deaf.png)
![](http://preview.dreamnet.at/?image=(https://user-images.githubusercontent.com/35707855/35245604-c6d0a1ea-ffbb-11e7-8fa8-0c265c42deaf.png)

**Comment by mryli** [comment]
![com dashlane dashlanephonefinal-large](https://user-images.githubusercontent.com/35707855/35248694-fdfe701a-ffc6-11e7-9a70-7b9df2454b6e.png)
![](http://preview.dreamnet.at/?image=(https://user-images.githubusercontent.com/35707855/35248694-fdfe701a-ffc6-11e7-9a70-7b9df2454b6e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35467916-325d5b54-0315-11e8-8b01-1d50f13f2775.png)
https://user-images.githubusercontent.com/2068130/35467916-325d5b54-0315-11e8-8b01-1d50f13f2775.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/35467924-4680b202-0315-11e8-9751-8967d1dd041d.png
