### ISSUE TITLE
first direct

### ISSUE THREAD

**Issue by mryli** [glasklart/hd#9617]
**App Name:** first direct
**Bundle ID:** com.firstdirect.bankingonthego
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405905004">405905004</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/first-direct/id405905004?mt=8&uo=4">https://itunes.apple.com/us/app/first-direct/id405905004?mt=8&uo=4</a>
**App Version:** 2.5.2
**Seller:** first direct
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/first-direct/id405905007?uo=4">© first direct</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/a5/43/b5/a543b5fc-b2ae-1cc5-50f8-83b417833e49/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35467991-9955000e-0316-11e8-9e6e-5dfe8b8b65e2.png)

**Comment by mryli** [comment]
![com firstdirect bankingonthego-large](https://user-images.githubusercontent.com/35707855/35247334-eacaa4d2-ffc1-11e7-8376-c5f7fbc94e21.png)
![](http://preview.dreamnet.at/?image=(https://user-images.githubusercontent.com/35707855/35247334-eacaa4d2-ffc1-11e7-8376-c5f7fbc94e21.png)

**Comment by mryli** [comment]
![com firstdirect bankingonthego-large](https://user-images.githubusercontent.com/35707855/35248733-2a5ba286-ffc7-11e7-920c-ec9ed408b864.png)
![](http://preview.dreamnet.at/?image=(https://user-images.githubusercontent.com/35707855/35248733-2a5ba286-ffc7-11e7-920c-ec9ed408b864.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35467991-9955000e-0316-11e8-9e6e-5dfe8b8b65e2.png)
https://user-images.githubusercontent.com/2068130/35467991-9955000e-0316-11e8-9e6e-5dfe8b8b65e2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/35467996-a9696a8e-0316-11e8-9212-a3252a75d671.png
