### ISSUE TITLE
ClearScore - report tracker

### ISSUE THREAD

**Issue by mryli** [glasklart/hd#9618]
**App Name:** ClearScore - report tracker
**Bundle ID:** com.clearscore.wrapper
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1056640628">1056640628</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/clearscore-report-tracker/id1056640628?mt=8&uo=4">https://itunes.apple.com/gb/app/clearscore-report-tracker/id1056640628?mt=8&uo=4</a>
**App Version:** 2.6.0
**Seller:** Clear Score Technology Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/clear-score-technology-ltd/id1056640627?uo=4">© Clear Score Technology Ltd.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/08/bf/bf/08bfbfd1-9abf-20a4-98f9-cb4d41bb28b9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35468049-aeab3c42-0317-11e8-83ba-0d53368a01d2.png)

**Comment by mryli** [comment]
![com clearscore wrapper-large](https://user-images.githubusercontent.com/35707855/35247641-09587a90-ffc3-11e7-8f93-eec77f640dfd.png)
![](http://preview.dreamnet.at/?image=(https://user-images.githubusercontent.com/35707855/35247641-09587a90-ffc3-11e7-8f93-eec77f640dfd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35468049-aeab3c42-0317-11e8-83ba-0d53368a01d2.png)
https://user-images.githubusercontent.com/2068130/35468049-aeab3c42-0317-11e8-83ba-0d53368a01d2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/35468054-bf4ff11e-0317-11e8-9559-c217f31c09d5.png
