### ISSUE TITLE
Experian - Credit Score

### ISSUE THREAD

**Issue by mryli** [glasklart/hd#9619]
**App Name:** Experian - Credit Score
**Bundle ID:** uk.co.creditexpert.companion
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1114748256">1114748256</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/experian-credit-score/id1114748256?mt=8&uo=4">https://itunes.apple.com/gb/app/experian-credit-score/id1114748256?mt=8&uo=4</a>
**App Version:** 4.0.2
**Seller:** Experian Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/gb/developer/experian-ltd/id410298819?uo=4">© Experian Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/0b/c4/1b/0bc41bbe-d5ec-d24c-8ad1-a22c6349d5e9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35468120-269b7de8-0318-11e8-8dc8-1c139d575a8e.png)

**Comment by mryli** [comment]
![uk co creditexpert companion-large](https://user-images.githubusercontent.com/35707855/35249414-cecfc228-ffc9-11e7-930f-0c9ed90631ad.png)
![](http://preview.dreamnet.at/?image=(https://user-images.githubusercontent.com/35707855/35249414-cecfc228-ffc9-11e7-930f-0c9ed90631ad.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35468120-269b7de8-0318-11e8-8dc8-1c139d575a8e.png)
https://user-images.githubusercontent.com/2068130/35468120-269b7de8-0318-11e8-8dc8-1c139d575a8e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/35468126-367c9116-0318-11e8-81f7-198fa63d507f.png
