### ISSUE TITLE
GoToMeeting

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9620]
**App Name:** GoToMeeting
**Bundle ID:** com.logmein.gotomeeting
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1239774423">1239774423</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gotomeeting/id1239774423?mt=8&uo=4">https://itunes.apple.com/us/app/gotomeeting/id1239774423?mt=8&uo=4</a>
**App Version:** 6.7.2
**Seller:** LogMeIn, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/logmein-inc/id299616804?uo=4">© LogMeIn, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/e6/06/3d/e6063d3a-8e90-1e9b-6091-00e2c90af24b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420556/2204e8ea-93ee-11e6-867f-5a0f9f11d291.png)

**Comment by Sly-Fi** [comment]
This is a new version of a previous app with the same name that already has a Glasklart icon, and uses the same icon labeled "com.citrixonline.iOS.GoToMeeting-large.png" from Issue #1789
![com citrixonline ios gotomeeting-large](https://user-images.githubusercontent.com/11544849/35484753-a5db8252-0411-11e8-9eb7-4aae6e18cbcb.png)

**Comment by dreamnet** [comment]
Icon by @2Qt2beStr8.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19420556/2204e8ea-93ee-11e6-867f-5a0f9f11d291.png)
https://cloud.githubusercontent.com/assets/20930745/19420556/2204e8ea-93ee-11e6-867f-5a0f9f11d291.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/20930745/19420565/478e4688-93ee-11e6-9242-537f8f47857a.png
