### ISSUE TITLE
MedBridge GO for Patients

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9621]
**App Name:** MedBridge GO for Patients
**Bundle ID:** com.medbridgeeducation.HEP
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1089747982">1089747982</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/medbridge-go-for-patients/id1089747982?mt=8&uo=4">https://itunes.apple.com/us/app/medbridge-go-for-patients/id1089747982?mt=8&uo=4</a>
**App Version:** 1.4.0
**Seller:** MedBridge Education LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/medbridge-education-llc/id1003848914?uo=4">© MedBridge Education LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/d6/a4/46/d6a44653-23e3-2e10-974b-ef8f68cbe0bb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35523502-4c7f21be-051f-11e8-9b3f-f4b7d10e790c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35523502-4c7f21be-051f-11e8-9b3f-f4b7d10e790c.png)
https://user-images.githubusercontent.com/20930745/35523502-4c7f21be-051f-11e8-9b3f-f4b7d10e790c.png

Source::
https://user-images.githubusercontent.com/20930745/35523540-619e4480-051f-11e8-93b4-137896fdc2bb.png
