### ISSUE TITLE
myETraining

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9622]
**App Name:** myETraining
**Bundle ID:** com.elite-it.myetraining
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=672249377">672249377</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/myetraining/id672249377?mt=8&uo=4">https://itunes.apple.com/us/app/myetraining/id672249377?mt=8&uo=4</a>
**App Version:** 3.6.2
**Seller:** Elite srl
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/elite-srl/id546000017?uo=4">© Elite srl</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/bc/70/47/bc704784-8d11-b627-33df-83b607770080/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35523836-1000e3de-0520-11e8-9a72-a3e7585a9016.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35523836-1000e3de-0520-11e8-9a72-a3e7585a9016.png)
https://user-images.githubusercontent.com/20930745/35523836-1000e3de-0520-11e8-9a72-a3e7585a9016.png

Source:
https://user-images.githubusercontent.com/20930745/35523871-25cd63b8-0520-11e8-9e37-7f61cab94da4.png
