### ISSUE TITLE
Optimum for iPad

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9623]
**App Name:** Optimum for iPad
**Bundle ID:** com.cablevision.iOTV
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=424612367">424612367</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/optimum-for-ipad/id424612367?mt=8&uo=4">https://itunes.apple.com/us/app/optimum-for-ipad/id424612367?mt=8&uo=4</a>
**App Version:** 4.5.3
**Seller:** CSC Holdings, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/csc-holdings-llc/id387231043?uo=4">© CSC Holdings, LLC.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/ef/9c/e9/ef9ce9ae-e6c9-c941-c1d4-7849d8c25242/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35524108-cc30da3c-0520-11e8-8317-5a12e9acd740.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35524108-cc30da3c-0520-11e8-8317-5a12e9acd740.png)
https://user-images.githubusercontent.com/20930745/35524108-cc30da3c-0520-11e8-8317-5a12e9acd740.png

Source:
https://user-images.githubusercontent.com/20930745/35524125-dd523478-0520-11e8-97ca-21f9e118e33f.png
