### ISSUE TITLE
Optimum

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9624]
**App Name:** Optimum
**Bundle ID:** com.cablevision.rDVR
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=387231038">387231038</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/optimum/id387231038?mt=8&uo=4">https://itunes.apple.com/us/app/optimum/id387231038?mt=8&uo=4</a>
**App Version:** 4.5.3
**Seller:** CSC Holdings, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/csc-holdings-llc/id387231043?uo=4">© CSC Holdings, LLC.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/5c/39/a4/5c39a417-e50c-9693-4ef2-8a683b39ddb1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35524108-cc30da3c-0520-11e8-8317-5a12e9acd740.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35524108-cc30da3c-0520-11e8-8317-5a12e9acd740.png)
https://user-images.githubusercontent.com/20930745/35524108-cc30da3c-0520-11e8-8317-5a12e9acd740.png

Source:
https://user-images.githubusercontent.com/20930745/35524125-dd523478-0520-11e8-97ca-21f9e118e33f.png

**Comment by dreamnet** [comment]
Same as #9623.
