### ISSUE TITLE
Tabs & Chords HD

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9625]
**App Name:** Tabs & Chords HD
**Bundle ID:** com.ultimateguitar.tabsipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=404167616">404167616</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tabs-chords-hd/id404167616?mt=8&uo=4">https://itunes.apple.com/us/app/tabs-chords-hd/id404167616?mt=8&uo=4</a>
**App Version:** 3.7.5
**Seller:** Ultimate Guitar
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ultimate-guitar/id337516725?uo=4">© Ultimate Guitar</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/3a/80/fa/3a80fad8-ab4d-cc0f-11a2-bfb50c310780/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35524493-0a6e46bc-0522-11e8-9983-719687ccc94a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35524493-0a6e46bc-0522-11e8-9983-719687ccc94a.png)
https://user-images.githubusercontent.com/20930745/35524493-0a6e46bc-0522-11e8-9983-719687ccc94a.png

Source:
https://user-images.githubusercontent.com/20930745/35524521-1f937eae-0522-11e8-974f-ae4cff274ed6.png

**Comment by dreamnet** [comment]
Same as #8321.
