### ISSUE TITLE
Guitar! by Smule

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9626]
**App Name:** Guitar! by Smule
**Bundle ID:** com.smule.guitar2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=632353530">632353530</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/guitar-by-smule/id632353530?mt=8&uo=4">https://itunes.apple.com/us/app/guitar-by-smule/id632353530?mt=8&uo=4</a>
**App Version:** 1.6.3
**Seller:** Smule
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/smule/id290596339?mt=8&uo=4">© Smule</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/d7/57/e3/d757e3c2-6744-9956-f509-17185929bf98/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36356200-a08bf564-14ee-11e8-90f5-0bc40a42b1d5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36356200-a08bf564-14ee-11e8-90f5-0bc40a42b1d5.png)
https://user-images.githubusercontent.com/20930745/36356200-a08bf564-14ee-11e8-90f5-0bc40a42b1d5.png

Source:
https://user-images.githubusercontent.com/20930745/36356208-b4248906-14ee-11e8-95e5-462ae524497e.png
