### ISSUE TITLE
Gyro Compass

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9627]
**App Name:** Gyro Compass
**Bundle ID:** com.yasinturkoglu.GyroCompass
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=515899618">515899618</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gyro-compass/id515899618?mt=8&uo=4">https://itunes.apple.com/us/app/gyro-compass/id515899618?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** yasin turkoglu
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yasin-turkoglu/id493011949?uo=4">© Yasin TURKOGLU</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/85/e7/3e/85e73e02-b1bb-c301-ff5d-2d9619dd37ca/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36354504-da73f268-14d5-11e8-8013-f37d82c91b9a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36354504-da73f268-14d5-11e8-8013-f37d82c91b9a.png)
https://user-images.githubusercontent.com/2068130/36354504-da73f268-14d5-11e8-8013-f37d82c91b9a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/36354509-ea1fa73e-14d5-11e8-9984-cd61db8a6112.png
