### ISSUE TITLE
Colorado Roads

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9628]
**App Name:** Colorado Roads
**Bundle ID:** com.urhub.cdot
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=542826138">542826138</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/colorado-roads/id542826138?mt=8&uo=4">https://itunes.apple.com/us/app/colorado-roads/id542826138?mt=8&uo=4</a>
**App Version:** 2.0.0
**Seller:** The Hub Companies, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/urhub/id472716293?uo=4">© urHub</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/0e/43/dd/0e43dd6f-c992-4709-8260-78ded9cf7198/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35765376-c9e5b2b6-08c2-11e8-8b9d-c50c7063d86f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35765376-c9e5b2b6-08c2-11e8-8b9d-c50c7063d86f.png)
https://user-images.githubusercontent.com/20930745/35765376-c9e5b2b6-08c2-11e8-8b9d-c50c7063d86f.png

Source:
https://user-images.githubusercontent.com/20930745/35765385-da97f376-08c2-11e8-9a59-6d66fc33b4eb.png
