### ISSUE TITLE
Hearts Tournament

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9629]
**App Name:** Hearts Tournament
**Bundle ID:** com.trivialtechnology.HeartsOnline
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=486434354">486434354</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hearts-tournament/id486434354?mt=8&uo=4">https://itunes.apple.com/us/app/hearts-tournament/id486434354?mt=8&uo=4</a>
**App Version:** 1.3.0
**Seller:** WildCard Games Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wildcard-games/id1116791610?uo=4">© WildCard Games</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple20/v4/ba/3c/89/ba3c896e-2d57-1686-1616-62b16d134139/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35771218-30b53370-0929-11e8-85de-bafc67febafb.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35765661-f8db30cc-08c8-11e8-98d8-00516f05c726.png)
https://user-images.githubusercontent.com/20930745/35765661-f8db30cc-08c8-11e8-98d8-00516f05c726.png

Source:
https://user-images.githubusercontent.com/20930745/35765664-0c6b4c44-08c9-11e8-8d10-dab19ae745a9.png

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35765746-a5f8d1f0-08ca-11e8-80a5-6b87344edfc8.png)
https://user-images.githubusercontent.com/20930745/35765746-a5f8d1f0-08ca-11e8-80a5-6b87344edfc8.png

Source:
https://user-images.githubusercontent.com/20930745/35765750-b88cfe36-08ca-11e8-92ec-e54b32c9d62b.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Did just some small corrections - credits are going to you!
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35771218-30b53370-0929-11e8-85de-bafc67febafb.png)
https://user-images.githubusercontent.com/2068130/35771218-30b53370-0929-11e8-85de-bafc67febafb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/35771225-4cb419f6-0929-11e8-8b00-1bdb3adc11ac.png
