### ISSUE TITLE
Sleep Talk Recorder

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#963]
**App Name:** Sleep Talk Recorder
**Bundle ID:** com.madinsweden.sleeptalkrecorder
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=391767653">391767653</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sleep-talk-recorder/id391767653?mt=8&uo=4">https://itunes.apple.com/us/app/sleep-talk-recorder/id391767653?mt=8&uo=4</a>
**App Version:** 5.4.3
**Seller:** Mad in Sweden AB (aktiebolaget grundstenen 122927)
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/madinsweden/id297744759?uo=4>© MadInSweden</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/e2/40/af/e240af3a-8ff5-6963-a3d3-c4122608841d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19412183/7216373c-9310-11e6-8002-793411ee4e30.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19402741/09d2eca4-9263-11e6-9ff7-324bcb33b03b.png)
https://cloud.githubusercontent.com/assets/20930745/19402741/09d2eca4-9263-11e6-9ff7-324bcb33b03b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19402747/176e5060-9263-11e6-8307-af43eb298091.png

**Comment by 2Qt2beStr8** [comment]
sorry @dreamnet  .. i forgot to round the corner 

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19412183/7216373c-9310-11e6-8002-793411ee4e30.png)
https://cloud.githubusercontent.com/assets/20930745/19412183/7216373c-9310-11e6-8002-793411ee4e30.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19412189/86a4c420-9310-11e6-85d3-7f8d518d38ad.png
