### ISSUE TITLE
RemoteMaster

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9630]
**App Name:** RemoteMaster
**Bundle ID:** com.yaokantv.remotemaster
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=947775284">947775284</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/remotemaster/id947775284?mt=8&uo=4">https://itunes.apple.com/us/app/remotemaster/id947775284?mt=8&uo=4</a>
**App Version:** 7.3
**Seller:** Shenzhen Yaokan Technology Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/shenzhen-yaokan-technology-co-ltd/id473623233?uo=4">© Shenzhen Yaokan Technology Co., Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/16/4c/4e/164c4e7a-6aa6-607a-f35b-c8eee0d1896f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35524909-4e1e9820-0523-11e8-9b0d-362d890a817a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35524909-4e1e9820-0523-11e8-9b0d-362d890a817a.png)
https://user-images.githubusercontent.com/20930745/35524909-4e1e9820-0523-11e8-9b0d-362d890a817a.png

Source:
https://user-images.githubusercontent.com/20930745/35524963-6be446f2-0523-11e8-91d8-3a38def1d7e2.png

**Comment by Grafovich** [comment]
👍
