### ISSUE TITLE
Fingertip Remote International

### ISSUE THREAD

**Issue by Grafovich** [glasklart/hd#9631]
**App Name:** Fingertip Remote International
**Bundle ID:** com.skyworth.fingertipInternational
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1091982627">1091982627</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fingertip-remote-international/id1091982627?mt=8&uo=4">https://itunes.apple.com/us/app/fingertip-remote-international/id1091982627?mt=8&uo=4</a>
**App Version:** 1.0.0
**Seller:** Skyworth group co., LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/skyworth-group-co-ltd/id1106812422?uo=4">© Skyworth group co., LTD</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple49/v4/12/08/ef/1208efab-bee2-d033-5955-d2870252ba34/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35525573-300fc51e-0525-11e8-9a2c-4826bd2188d0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35525573-300fc51e-0525-11e8-9a2c-4826bd2188d0.png)
https://user-images.githubusercontent.com/20930745/35525573-300fc51e-0525-11e8-9a2c-4826bd2188d0.png

Source:
https://user-images.githubusercontent.com/20930745/35525598-44dbc33a-0525-11e8-877e-355574ff1be7.png

**Comment by Grafovich** [comment]
👍
