### ISSUE TITLE
Cribbage Premium

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9632]
**App Name:** Cribbage Premium
**Bundle ID:** com.trivialtechnology.Cribbage
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=301154120">301154120</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cribbage-premium/id301154120?mt=8&uo=4">https://itunes.apple.com/us/app/cribbage-premium/id301154120?mt=8&uo=4</a>
**App Version:** 3.6.3
**Seller:** Trivial Technology
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/trivial-technology/id284954485?uo=4">© Trivial Technology</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/24/2e/c7/242ec71b-342e-8012-b582-1ac90712bbc1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36713872-ebb41c54-1b8f-11e8-9e5c-e43260a53135.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36713872-ebb41c54-1b8f-11e8-9e5c-e43260a53135.png)
https://user-images.githubusercontent.com/20930745/36713872-ebb41c54-1b8f-11e8-9e5c-e43260a53135.png

Source:
https://user-images.githubusercontent.com/20930745/36713903-0caa3948-1b90-11e8-8bdf-3f1a39a3ae3d.png

**Comment by ivanov007** [comment]
@2Qt2beStr8 way better than the original
