### ISSUE TITLE
mandiri online

### ISSUE THREAD

**Issue by rbych18** [glasklart/hd#9633]
**App Name:** mandiri online
**Bundle ID:** com.bankmandiri.mandirionline
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1117312908">1117312908</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mandiri-online/id1117312908?mt=8&uo=4">https://itunes.apple.com/us/app/mandiri-online/id1117312908?mt=8&uo=4</a>
**App Version:** 1.0.18
**Seller:** PT Bank Mandiri (Persero) Tbk.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pt-bank-mandiri-persero-tbk/id516447725?uo=4">© PT. Bank Mandiri (Persero) Tbk.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/48/d3/12/48d312ee-854e-90c9-2d10-5e2596aed7ee/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35763762-6d4c7526-08b3-11e8-852d-886b48ec832d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35763762-6d4c7526-08b3-11e8-852d-886b48ec832d.png)
https://user-images.githubusercontent.com/20930745/35763762-6d4c7526-08b3-11e8-852d-886b48ec832d.png

Source:
https://user-images.githubusercontent.com/20930745/35763766-832a72a8-08b3-11e8-87c2-92cc7be6990a.png
