### ISSUE TITLE
myXL–Cek Kuota & Beli Paket XL

### ISSUE THREAD

**Issue by rbych18** [glasklart/hd#9634]
**App Name:** myXL–Cek Kuota & Beli Paket XL
**Bundle ID:** com.xl.MyXL.Giant
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=683141076">683141076</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/myxl-cek-kuota-beli-paket-xl/id683141076?mt=8&uo=4">https://itunes.apple.com/us/app/myxl-cek-kuota-beli-paket-xl/id683141076?mt=8&uo=4</a>
**App Version:** 3.6.0
**Seller:** PT XL Axiata Tbk
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pt-xl-axiata-tbk/id549471399?uo=4">© PT XL Axiata Tbk</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/63/4c/f6/634cf694-fb18-b98b-4e14-2b3466e5ed25/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35763814-cc58f354-08b4-11e8-8cfb-f14165b72285.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35763814-cc58f354-08b4-11e8-8cfb-f14165b72285.png)
https://user-images.githubusercontent.com/20930745/35763814-cc58f354-08b4-11e8-8cfb-f14165b72285.png

Source:
https://user-images.githubusercontent.com/20930745/35763816-e0564f00-08b4-11e8-8074-98dd6d6b121d.png
