### ISSUE TITLE
JOOX Music - Live and Karaoke

### ISSUE THREAD

**Issue by rbych18** [glasklart/hd#9635]
**App Name:** JOOX Music - Live and Karaoke
**Bundle ID:** com.tencent.joox
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=914406371">914406371</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/hk/app/joox-music-live-and-karaoke/id914406371?mt=8&uo=4">https://itunes.apple.com/hk/app/joox-music-live-and-karaoke/id914406371?mt=8&uo=4</a>
**App Version:** 4.2.0
**Seller:** Tencent Mobility Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/hk/developer/tencent-mobility-limited/id912765941?uo=4">© Tencent Mobility Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/08/4d/26/084d26c4-73aa-7a7c-1c14-a7911d53f8f3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35764004-55bb6520-08b8-11e8-88e1-5e3c83de7981.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35764004-55bb6520-08b8-11e8-88e1-5e3c83de7981.png)
https://user-images.githubusercontent.com/20930745/35764004-55bb6520-08b8-11e8-88e1-5e3c83de7981.png

Source:
https://user-images.githubusercontent.com/20930745/35764008-689ee234-08b8-11e8-86a7-d8a3c6a94b12.png
