### ISSUE TITLE
JakOne Mobile - Bank DKI

### ISSUE THREAD

**Issue by rbych18** [glasklart/hd#9636]
**App Name:** JakOne Mobile - Bank DKI
**Bundle ID:** com.bankdki.jakone.customer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1198129179">1198129179</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/jakone-mobile-bank-dki/id1198129179?mt=8&uo=4">https://itunes.apple.com/us/app/jakone-mobile-bank-dki/id1198129179?mt=8&uo=4</a>
**App Version:** 3.1
**Seller:** BANK DKI, PT
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pt-bank-dki/id1104270366?uo=4">© PT. Bank DKI</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/45/86/0c/45860c9d-7f3c-4bea-694e-1646d7781291/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35764055-4f57b17e-08b9-11e8-8d91-fed7e4ab57e5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35764055-4f57b17e-08b9-11e8-8d91-fed7e4ab57e5.png)
https://user-images.githubusercontent.com/20930745/35764055-4f57b17e-08b9-11e8-8d91-fed7e4ab57e5.png

Source:
https://user-images.githubusercontent.com/20930745/35764059-60d4a88a-08b9-11e8-9575-77dd1cc6bfbe.png
