### ISSUE TITLE
Traveloka Book Flight & Hotel

### ISSUE THREAD

**Issue by rbych18** [glasklart/hd#9637]
**App Name:** Traveloka Book Flight & Hotel
**Bundle ID:** com.traveloka.traveloka
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=898244857">898244857</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/traveloka-book-flight-hotel/id898244857?mt=8&uo=4">https://itunes.apple.com/us/app/traveloka-book-flight-hotel/id898244857?mt=8&uo=4</a>
**App Version:** 2.20.0
**Seller:** Trinusa Travelindo, PT
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pt-traveloka-indonesia/id898244860?uo=4">© PT Traveloka Indonesia</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/e0/74/c9/e074c967-b8b9-1eef-52db-3e816dc2c62e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35764647-60cff162-08bb-11e8-8032-06c975f33d08.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35764647-60cff162-08bb-11e8-8032-06c975f33d08.png)
https://user-images.githubusercontent.com/20930745/35764647-60cff162-08bb-11e8-8032-06c975f33d08.png

Source:
https://user-images.githubusercontent.com/20930745/35764849-7f793c40-08bb-11e8-94f8-b46318962d86.png
