### ISSUE TITLE
GOJEK

### ISSUE THREAD

**Issue by imrobbyrc** [glasklart/hd#9638]
**App Name:** GOJEK
**Bundle ID:** com.go-jek.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=944875099">944875099</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/gojek/id944875099?uo=4">https://apps.apple.com/us/app/gojek/id944875099?uo=4</a>
**App Version:** 3.31
**Seller:** PT GO-JEK INDONESIA
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/pt-go-jek-indonesia/id944875098?uo=4">© PT GO-JEK INDONESIA</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/f3/85/15/f3851594-7caa-eb1f-5e62-b2222bab36d3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60539626-71bf2a00-9d0d-11e9-8226-007795fa03e0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35765017-4520424a-08bc-11e8-8073-1b8176b2fac2.png)
https://user-images.githubusercontent.com/20930745/35765017-4520424a-08bc-11e8-8073-1b8176b2fac2.png

Source:
https://user-images.githubusercontent.com/20930745/35765019-5a5ced20-08bc-11e8-9f1c-c8a7b558d7d5.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60539626-71bf2a00-9d0d-11e9-8226-007795fa03e0.png)
https://user-images.githubusercontent.com/20930745/60539626-71bf2a00-9d0d-11e9-8226-007795fa03e0.png

Source:
https://user-images.githubusercontent.com/20930745/60539630-72f05700-9d0d-11e9-938f-56a7bc46c878.png
