### ISSUE TITLE
Puzzledom

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#9639]
**App Name:** Puzzledom
**Bundle ID:** com.puzzlegame.puzzledom
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1261300725">1261300725</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/puzzledom/id1261300725?mt=8&uo=4">https://itunes.apple.com/us/app/puzzledom/id1261300725?mt=8&uo=4</a>
**App Version:** 6.2
**Seller:** chengwei wu
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/chengwei-wu/id885758269?uo=4">© chengwei wu</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/83/f5/40/83f540e2-cf03-525c-8fd5-391efbcaa735/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36071118-a28bbc72-0f09-11e8-9a83-9f1caa6bf1b2.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36071118-a28bbc72-0f09-11e8-9a83-9f1caa6bf1b2.png)
https://user-images.githubusercontent.com/20930745/36071118-a28bbc72-0f09-11e8-9a83-9f1caa6bf1b2.png

https://user-images.githubusercontent.com/20930745/36071124-b584b9f0-0f09-11e8-8f72-31e860f2c527.png
