### ISSUE TITLE
FEZ Pocket Edition

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#9640]
**App Name:** FEZ Pocket Edition
**Bundle ID:** com.polytron.fez
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1209489068">1209489068</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fez-pocket-edition/id1209489068?mt=8&uo=4">https://itunes.apple.com/us/app/fez-pocket-edition/id1209489068?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Corporation Polytron Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/polytron-inc/id1209489067?uo=4">© Polytron Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/a6/a0/b9/a6a0b9e0-91d1-3f3c-56af-42cdd0f6fca7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35768290-b3d29e08-08f9-11e8-9b32-e9ce4378500e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35768290-b3d29e08-08f9-11e8-9b32-e9ce4378500e.png)
https://user-images.githubusercontent.com/20930745/35768290-b3d29e08-08f9-11e8-9b32-e9ce4378500e.png

Source:
https://user-images.githubusercontent.com/20930745/35768294-c1d08cb8-08f9-11e8-9827-639ea9a3e999.png
