### ISSUE TITLE
LG TV Plus

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#9641]
**App Name:** LG TV Plus
**Bundle ID:** com.lge.remoteapp.webos14
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=838611484">838611484</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lg-tv-plus/id838611484?mt=8&uo=4">https://itunes.apple.com/us/app/lg-tv-plus/id838611484?mt=8&uo=4</a>
**App Version:** 4.0.0
**Seller:** LG Electronics
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lg-electronics-inc/id382800716?uo=4">© LG Electronics, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/8a/09/e4/8a09e4e6-baec-b5a6-9fdb-b41871cfa7de/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36063994-b203f848-0e84-11e8-8c33-8a94f93b6e8e.png)

**Comment by Mitchdog27** [comment]
Recently updated icon
![lg_tv](https://user-images.githubusercontent.com/31022613/35767542-f91ec1ec-0941-11e8-924e-2f2538566869.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36063994-b203f848-0e84-11e8-8c33-8a94f93b6e8e.png)
https://user-images.githubusercontent.com/20930745/36063994-b203f848-0e84-11e8-8c33-8a94f93b6e8e.png

Source:
https://user-images.githubusercontent.com/20930745/36063999-c2eab6c4-0e84-11e8-8141-cfae5a6345ea.png
