### ISSUE TITLE
Telstra Air

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#9642]
**App Name:** Telstra Air
**Bundle ID:** com.telstra.telstraair
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=997598303">997598303</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/telstra-air/id997598303?mt=8&uo=4">https://itunes.apple.com/us/app/telstra-air/id997598303?mt=8&uo=4</a>
**App Version:** 9.0.0.487
**Seller:** Telstra Corporation Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/telstra-corporation-ltd/id315429741?uo=4">© Telstra Corporation Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/fc/89/1f/fc891fec-a3f3-f9b3-e971-e3e1c71b0cc7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35768052-8a1c2938-08f6-11e8-83ce-fd534fd794c1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/35768052-8a1c2938-08f6-11e8-83ce-fd534fd794c1.png)
https://user-images.githubusercontent.com/20930745/35768052-8a1c2938-08f6-11e8-83ce-fd534fd794c1.png

Source:
https://user-images.githubusercontent.com/20930745/35768058-9be605bc-08f6-11e8-9ff3-d5f92e623ca9.png
