### ISSUE TITLE
GamePigeon

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#9643]
**App Name:** GamePigeon
**Bundle ID:** com.gamerdelights.gamepigeon
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1124197642">1124197642</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gamepigeon/id1124197642?mt=8&uo=4">https://itunes.apple.com/us/app/gamepigeon/id1124197642?mt=8&uo=4</a>
**App Version:** 1.0.22.2
**Seller:** Vitalii Zlotskii
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vitalii-zlotskii/id519501340?uo=4">© Vitalii Zlotskii</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/86/d6/ac/86d6ac31-c396-1059-954a-e361581344d3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36349112-e5f8970c-147f-11e8-9044-cb28ca0e2488.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36349112-e5f8970c-147f-11e8-9044-cb28ca0e2488.png)
https://user-images.githubusercontent.com/20930745/36349112-e5f8970c-147f-11e8-9044-cb28ca0e2488.png

Source:
https://user-images.githubusercontent.com/20930745/36349114-ff2372ba-147f-11e8-83e4-0694d29fc294.png
