### ISSUE TITLE
Popspedia - Pop! Vinyl Tracker

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#9645]
**App Name:** Popspedia - Pop! Vinyl Tracker
**Bundle ID:** org.reactjs.native.Popspedia
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1286964746">1286964746</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/popspedia-pop-vinyl-tracker/id1286964746?mt=8&uo=4">https://itunes.apple.com/us/app/popspedia-pop-vinyl-tracker/id1286964746?mt=8&uo=4</a>
**App Version:** 2.1.4
**Seller:** Justin Lok
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/justin-lok/id1286964745?uo=4">© Justin Lok</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/a3/a8/a9/a3a8a90d-f2e8-8a87-0980-2374a2449869/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35774878-da043ebe-097c-11e8-8182-8a9a81cecf12.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/35774878-da043ebe-097c-11e8-8182-8a9a81cecf12.png)
https://user-images.githubusercontent.com/2068130/35774878-da043ebe-097c-11e8-8182-8a9a81cecf12.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/35774881-ecf4ea82-097c-11e8-9dc5-8154750b697d.png
