### ISSUE TITLE
Gardenscapes

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#9646]
**App Name:** Gardenscapes
**Bundle ID:** com.playrix.gardenscapes-m3-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1105855019">1105855019</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gardenscapes/id1105855019?mt=8&uo=4">https://itunes.apple.com/us/app/gardenscapes/id1105855019?mt=8&uo=4</a>
**App Version:** 2.2.0
**Seller:** PLR Worldwide Sales Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/playrix-games/id1162116447?uo=4">© Playrix Games</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/ae/69/33/ae6933fd-cfa0-4baa-79da-895da46684cd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37878763-337c469a-306e-11e8-84da-b7c95b6f4e35.png)

**Comment by dreamnet** [comment]
???
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37878763-337c469a-306e-11e8-84da-b7c95b6f4e35.png)
https://user-images.githubusercontent.com/2068130/37878763-337c469a-306e-11e8-84da-b7c95b6f4e35.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37878768-4464d1ca-306e-11e8-8a4e-4f2ba045c978.png
