### ISSUE TITLE
Seabeard

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9650]
**App Name:** Seabeard
**Bundle ID:** com.backflipstudios.seabeard
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=913754563">913754563</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/seabeard/id913754563?mt=8&uo=4">https://itunes.apple.com/us/app/seabeard/id913754563?mt=8&uo=4</a>
**App Version:** 1.5.5
**Seller:** Backflip Studios
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/backflip-studios/id315282170?uo=4">© Backflip Studios</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple117/v4/82/9f/7f/829f7f08-8611-0a50-518a-de9b49b59728/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36351050-c74796b8-14a3-11e8-98b0-e017e46ba879.png)

**Comment by 2Qt2beStr8** [comment]
??? maybe someone can make a better one - i don't like game app Icons :-(
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36351050-c74796b8-14a3-11e8-98b0-e017e46ba879.png)
https://user-images.githubusercontent.com/20930745/36351050-c74796b8-14a3-11e8-98b0-e017e46ba879.png

Source:
https://user-images.githubusercontent.com/20930745/36351041-a524f7f6-14a3-11e8-8e85-b870b940305a.png
