### ISSUE TITLE
King of Opera

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#9651]
**App Name:** King of Opera
**Bundle ID:** com.tuokio.kingofopera
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=408697793">408697793</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/king-of-opera/id408697793?mt=8&uo=4">https://itunes.apple.com/us/app/king-of-opera/id408697793?mt=8&uo=4</a>
**App Version:** 1.16.38
**Seller:** Tuotantoyhtio Tuokio Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tuokio-inc/id408697797?uo=4">© Tuokio Inc.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/b9/ec/13/b9ec13fd-2ce0-7954-26be-fd792fa8be0a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36060373-95bb95a6-0e48-11e8-8b22-48ec8a0192b6.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36060373-95bb95a6-0e48-11e8-8b22-48ec8a0192b6.png)
https://user-images.githubusercontent.com/2068130/36060373-95bb95a6-0e48-11e8-8b22-48ec8a0192b6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/36060376-a5893970-0e48-11e8-887e-139ff0303976.png
