### ISSUE TITLE
Mathspace

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#9653]
**App Name:** Mathspace
**Bundle ID:** au.com.mathspace.MathSpace
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=586612052">586612052</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mathspace/id586612052?mt=8&uo=4">https://itunes.apple.com/us/app/mathspace/id586612052?mt=8&uo=4</a>
**App Version:** 2.6.5
**Seller:** Mathspace PTY LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mathspace-pty-ltd/id586612058?uo=4">© Mathspace Pty Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/07/d8/a2/07d8a264-ab59-11cf-3493-e253a9e2027c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36053043-63ee7122-0df0-11e8-933f-e1d8f4c14e47.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36053043-63ee7122-0df0-11e8-933f-e1d8f4c14e47.png)
https://user-images.githubusercontent.com/20930745/36053043-63ee7122-0df0-11e8-933f-e1d8f4c14e47.png

Source:
https://user-images.githubusercontent.com/20930745/36053072-7aab6b54-0df0-11e8-9b71-02ff76646295.png
