### ISSUE TITLE
HQ - Trivia & Words

### ISSUE THREAD

**Issue by Neoflare** [glasklart/hd#9654]
**App Name:** HQ - Trivia & Words
**Bundle ID:** co.intermedialabs.hq
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1232278996">1232278996</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/hq-trivia-words/id1232278996?uo=4">https://apps.apple.com/us/app/hq-trivia-words/id1232278996?uo=4</a>
**App Version:** 1.5.1
**Seller:** Intermedia Labs Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/intermedia-labs/id1095766942?uo=4">© Intermedia Labs</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/a8/44/9c/a8449c26-6ea8-0fe4-80cc-c7b139264b84/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63886094-fe1e5e00-c9d9-11e9-8316-e6a65146dfa2.png)

**Comment by Neoflare** [comment]
![co intermedialabs hq](https://user-images.githubusercontent.com/36319424/36058174-f97e9e14-0de7-11e8-90f1-d187d4b115b3.png)

**Comment by Neoflare** [comment]
![co intermedialabs hq](https://user-images.githubusercontent.com/36319424/36058179-1fa539e0-0de8-11e8-858a-0087b851f5c4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36059481-f829c8fc-0e39-11e8-95eb-90de43097e46.png)
https://user-images.githubusercontent.com/20930745/36059481-f829c8fc-0e39-11e8-95eb-90de43097e46.png

Source:
https://user-images.githubusercontent.com/20930745/36059504-08d993ee-0e3a-11e8-91c6-ece96d6a824a.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/62392910-02856180-b569-11e9-9db3-58cea675c9d9.png)
=https://user-images.githubusercontent.com/20930745/62392910-02856180-b569-11e9-9db3-58cea675c9d9.png

Source:
https://user-images.githubusercontent.com/20930745/62392911-044f2500-b569-11e9-92ac-ce0e4cf1fa65.png

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/63886094-fe1e5e00-c9d9-11e9-8316-e6a65146dfa2.png)
https://user-images.githubusercontent.com/2068130/63886094-fe1e5e00-c9d9-11e9-8316-e6a65146dfa2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/63886124-0f676a80-c9da-11e9-8369-350bda4a429c.png
