### ISSUE TITLE
StudentVUE

### ISSUE THREAD

**Issue by Neoflare** [glasklart/hd#9655]
**App Name:** StudentVUE
**Bundle ID:** com.edupoint.StudentVUE
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=412050327">412050327</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/studentvue/id412050327?mt=8&uo=4">https://itunes.apple.com/us/app/studentvue/id412050327?mt=8&uo=4</a>
**App Version:** 5.1
**Seller:** Edupoint
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/edupoint-educational-systems/id412050330?uo=4">© Edupoint Educational Systems</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/5b/d0/96/5bd0960c-182b-db8c-a359-7082c0d11b88/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36059543-79683be2-0e3a-11e8-8100-9055502ea575.png)

**Comment by Neoflare** [comment]
![com edupoint studentvue-large](https://user-images.githubusercontent.com/36319424/36058368-19690e72-0dec-11e8-946a-95d0f46d1154.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36059543-79683be2-0e3a-11e8-8100-9055502ea575.png)
https://user-images.githubusercontent.com/20930745/36059543-79683be2-0e3a-11e8-8100-9055502ea575.png

Source:
https://user-images.githubusercontent.com/20930745/36059548-8bf6df20-0e3a-11e8-96bc-751ded020fff.png
