### ISSUE TITLE
Brawl Stars

### ISSUE THREAD

**Issue by Neoflare** [glasklart/hd#9656]
**App Name:** Brawl Stars
**Bundle ID:** com.supercell.laser
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1229016807">1229016807</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/ca/app/brawl-stars/id1229016807?mt=8&uo=4">https://itunes.apple.com/ca/app/brawl-stars/id1229016807?mt=8&uo=4</a>
**App Version:** 6.52
**Seller:** Supercell Oy
**Developer:** <a target="_blank" href="https://itunes.apple.com/ca/developer/supercell/id488106216?uo=4">© Supercell</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/b3/09/6d/b3096d55-f15d-f572-8b85-7954d3114bdb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36059501-fdb7c8e6-0e39-11e8-9e91-38dd85d30b7f.png)

**Comment by Neoflare** [comment]
![com supercell laser-large](https://user-images.githubusercontent.com/36319424/36058457-4dd993aa-0dee-11e8-9001-a4d641235b75.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36059501-fdb7c8e6-0e39-11e8-9e91-38dd85d30b7f.png)
https://user-images.githubusercontent.com/2068130/36059501-fdb7c8e6-0e39-11e8-9e91-38dd85d30b7f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/36059505-0d15df9e-0e3a-11e8-9cc5-c6ea5c5dd2b4.png
