### ISSUE TITLE
Cash Show - Win Real Cash!

### ISSUE THREAD

**Issue by Neoflare** [glasklart/hd#9657]
**App Name:** Cash Show - Win Real Cash!
**Bundle ID:** com.triviagames.cashshow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1335097700">1335097700</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cash-show-win-real-cash/id1335097700?mt=8&uo=4">https://itunes.apple.com/us/app/cash-show-win-real-cash/id1335097700?mt=8&uo=4</a>
**App Version:** 1.5.1
**Seller:** Zentertain Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/zentertain-ltd/id371114041?uo=4">© Zentertain Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/b1/bb/2f/b1bb2fed-9c15-3d96-ba41-11925e677ec8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36059449-75be8164-0e39-11e8-848a-752a89e3d9df.png)

**Comment by Neoflare** [comment]
![com triviagames cashshow-large](https://user-images.githubusercontent.com/36319424/36058527-ecdf3d54-0df0-11e8-92d9-41ac5acc3452.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36059449-75be8164-0e39-11e8-848a-752a89e3d9df.png)
https://user-images.githubusercontent.com/2068130/36059449-75be8164-0e39-11e8-848a-752a89e3d9df.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/36059454-83e8b020-0e39-11e8-9e19-d10b458a81d8.png
