### ISSUE TITLE
Parental Control & Screen Time

### ISSUE THREAD

**Issue by Neoflare** [glasklart/hd#9658]
**App Name:** Parental Control & Screen Time
**Bundle ID:** com.parentsware.ourpact
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=954029412">954029412</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/parental-control-screen-time/id954029412?mt=8&uo=4">https://itunes.apple.com/us/app/parental-control-screen-time/id954029412?mt=8&uo=4</a>
**App Version:** 4.9
**Seller:** Eturi Corp.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/eturi-corp/id661488682?uo=4">© Eturi Corp.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/87/f1/c3/87f1c3b0-fe8a-581e-29b2-901745cf0f49/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36059402-d01d4c2c-0e38-11e8-9be9-e0878d2a7999.png)

**Comment by Neoflare** [comment]
![com parentsware ourpact-large](https://user-images.githubusercontent.com/36319424/36058606-d8d8f5fa-0df2-11e8-9e0b-9b2924644144.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/36059402-d01d4c2c-0e38-11e8-9be9-e0878d2a7999.png)
https://user-images.githubusercontent.com/2068130/36059402-d01d4c2c-0e38-11e8-9be9-e0878d2a7999.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/36059404-e0a755e2-0e38-11e8-8366-b8f60c86f29c.png
