### ISSUE TITLE
Knife Hit

### ISSUE THREAD

**Issue by Neoflare** [glasklart/hd#9659]
**App Name:** Knife Hit
**Bundle ID:** com.ketchapp.knifehit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1336527043">1336527043</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/knife-hit/id1336527043?mt=8&uo=4">https://itunes.apple.com/us/app/knife-hit/id1336527043?mt=8&uo=4</a>
**App Version:** 1.2.1
**Seller:** Ketchapp
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ketchapp/id528065807?uo=4">© Ketchapp</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/dd/83/9c/dd839c26-e590-156f-aa19-b4c6c2185bc6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36341415-379823d0-13ee-11e8-8c6e-0607a187cfad.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36341415-379823d0-13ee-11e8-8c6e-0607a187cfad.png)
https://user-images.githubusercontent.com/20930745/36341415-379823d0-13ee-11e8-8c6e-0607a187cfad.png

Source:
https://user-images.githubusercontent.com/20930745/36341420-488fee66-13ee-11e8-985e-706bdf6f5e3c.png
