### ISSUE TITLE
Yahoo Video Guide

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9661]
**App Name:** Yahoo Video Guide
**Bundle ID:** com.yahoo.guidefall
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1062329611">1062329611</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yahoo-video-guide/id1062329611?mt=8&uo=4">https://itunes.apple.com/us/app/yahoo-video-guide/id1062329611?mt=8&uo=4</a>
**App Version:** 1.0.7
**Seller:** Yahoo! Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yahoo/id281970157?mt=8&uo=4">© Yahoo</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/40/f6/3a/40f63ae3-934f-d3b0-a704-9414f362dd72/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36165413-ca241814-10ef-11e8-97e8-10d254fbfd0a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36165413-ca241814-10ef-11e8-97e8-10d254fbfd0a.png)
https://user-images.githubusercontent.com/20930745/36165413-ca241814-10ef-11e8-97e8-10d254fbfd0a.png

Source:
https://user-images.githubusercontent.com/20930745/36165434-d9edd0b4-10ef-11e8-8f74-1e7f4e444894.png
