### ISSUE TITLE
Atom - Movie Tickets & Times

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9662]
**App Name:** Atom - Movie Tickets & Times
**Bundle ID:** org.gamatech.Movie-Friends
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=926058555">926058555</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/atom-movie-tickets-times/id926058555?mt=8&uo=4">https://itunes.apple.com/us/app/atom-movie-tickets-times/id926058555?mt=8&uo=4</a>
**App Version:** 2.9.6
**Seller:** Atom Tickets, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/atom-tickets-llc/id923631407?uo=4">© Atom Tickets, LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/b0/04/52/b0045275-e238-c934-3863-6b75681b8b88/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36165663-9db13d74-10f0-11e8-955b-9c69b5ea2e7d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36165663-9db13d74-10f0-11e8-955b-9c69b5ea2e7d.png)
https://user-images.githubusercontent.com/20930745/36165663-9db13d74-10f0-11e8-955b-9c69b5ea2e7d.png

Source:
https://user-images.githubusercontent.com/20930745/36165688-ae2b9bae-10f0-11e8-99dd-16f70ffea989.png
