### ISSUE TITLE
Storm Shield

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9663]
**App Name:** Storm Shield
**Bundle ID:** com.wdtinc.stormshield
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=526831380">526831380</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/storm-shield/id526831380?mt=8&uo=4">https://itunes.apple.com/us/app/storm-shield/id526831380?mt=8&uo=4</a>
**App Version:** 4.2.3
**Seller:** E.W. Scripps Company
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/e-w-scripps-company/id405974803?uo=4">© E.W. Scripps Company</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/4b/73/fb/4b73fb3f-3930-c2c5-43a5-1b562829b58f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36167260-817c7434-10f5-11e8-975c-2767c68f704b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36167260-817c7434-10f5-11e8-975c-2767c68f704b.png)
https://user-images.githubusercontent.com/20930745/36167260-817c7434-10f5-11e8-975c-2767c68f704b.png

Source:
https://user-images.githubusercontent.com/20930745/36167272-8f22cd90-10f5-11e8-87e4-32ecfce4819e.png
