### ISSUE TITLE
PDFelement - PDF Solutions

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9664]
**App Name:** PDFelement - PDF Solutions
**Bundle ID:** com.wondershare.PDFelement.Lite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1150215996">1150215996</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pdfelement-pdf-solutions/id1150215996?mt=8&uo=4">https://itunes.apple.com/us/app/pdfelement-pdf-solutions/id1150215996?mt=8&uo=4</a>
**App Version:** 5.0.6
**Seller:** Wondershare Software Co., Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wondershare-software-co-ltd/id298647757?uo=4">© Wondershare Software Co., Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/e2/f0/37/e2f0372f-ee3b-4445-8eec-d2dca12a691b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36165878-396768ec-10f1-11e8-9e4a-ab5db9869ed6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36165878-396768ec-10f1-11e8-9e4a-ab5db9869ed6.png)
https://user-images.githubusercontent.com/20930745/36165878-396768ec-10f1-11e8-9e4a-ab5db9869ed6.png

Source:
https://user-images.githubusercontent.com/20930745/36165900-4b4fcefa-10f1-11e8-88d9-f7a3d51c7502.png
