### ISSUE TITLE
Diigo-Your Learning,Simplified

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9665]
**App Name:** Diigo-Your Learning,Simplified
**Bundle ID:** com.diigo.WebAnnotator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=933773981">933773981</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/diigo-your-learning-simplified/id933773981?mt=8&uo=4">https://itunes.apple.com/us/app/diigo-your-learning-simplified/id933773981?mt=8&uo=4</a>
**App Version:** 2.7
**Seller:** Diigo
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/diigo-inc/id335006603?uo=4">© Diigo Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/ae/5b/6a/ae5b6a45-a489-7d5a-775e-5b02387ec112/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36166108-dc662074-10f1-11e8-964a-bccea136fba9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36166108-dc662074-10f1-11e8-964a-bccea136fba9.png)
https://user-images.githubusercontent.com/20930745/36166108-dc662074-10f1-11e8-964a-bccea136fba9.png

Source:
https://user-images.githubusercontent.com/20930745/36166140-f1a3dc7e-10f1-11e8-80d0-cec727a7ca79.png
