### ISSUE TITLE
PaperSpan: Save Web for Later

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9666]
**App Name:** PaperSpan: Save Web for Later
**Bundle ID:** com.paperspan.PaperSpan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1167530069">1167530069</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paperspan-save-web-for-later/id1167530069?mt=8&uo=4">https://itunes.apple.com/us/app/paperspan-save-web-for-later/id1167530069?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Sravan Kumar
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sravan-kumar/id1167530068?uo=4">© Sravan Kumar</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/7b/d8/3f/7bd83ffb-801a-efbe-b850-c72838cd3c54/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36166922-626ec886-10f4-11e8-80b8-4c783b7acaa9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36166922-626ec886-10f4-11e8-80b8-4c783b7acaa9.png)
https://user-images.githubusercontent.com/20930745/36166922-626ec886-10f4-11e8-80b8-4c783b7acaa9.png

Source:
https://user-images.githubusercontent.com/20930745/36166946-73a02668-10f4-11e8-988d-b1a15822577a.png
