### ISSUE TITLE
Renfe Ticket

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9667]
**App Name:** Renfe Ticket
**Bundle ID:** com.renfeviajeros.RenfeTicket
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1238211547">1238211547</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/renfe-ticket/id1238211547?mt=8&uo=4">https://itunes.apple.com/us/app/renfe-ticket/id1238211547?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Renfe Viajeros SA
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/renfe-viajeros/id859158040?uo=4">© Renfe Viajeros</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/24/a2/40/24a240de-050b-f28e-a5e9-853a72bd1244/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36341179-82ec319a-13ea-11e8-8905-ea779d427769.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36341179-82ec319a-13ea-11e8-8905-ea779d427769.png)
https://user-images.githubusercontent.com/20930745/36341179-82ec319a-13ea-11e8-8905-ea779d427769.png

Source:
https://user-images.githubusercontent.com/20930745/36341181-90dad66c-13ea-11e8-9bfe-6358a378769a.png
