### ISSUE TITLE
FANDOM Videos, News & Reviews

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9668]
**App Name:** FANDOM Videos, News & Reviews
**Bundle ID:** com.fandom.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1230063803">1230063803</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fandom-videos-news-reviews/id1230063803?mt=8&uo=4">https://itunes.apple.com/us/app/fandom-videos-news-reviews/id1230063803?mt=8&uo=4</a>
**App Version:** 1.5.0
**Seller:** Wikia Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wikia-inc/id422467077?uo=4">© Wikia, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/74/98/1b/74981b99-8925-799b-cad5-a6fbcaba2c0b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36364977-9982d75c-1547-11e8-9359-9f7addb0db51.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36364977-9982d75c-1547-11e8-9359-9f7addb0db51.png)
https://user-images.githubusercontent.com/20930745/36364977-9982d75c-1547-11e8-9359-9f7addb0db51.png

Source:
https://user-images.githubusercontent.com/20930745/36364996-b11cb310-1547-11e8-9155-70b9198d449e.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36365468-fad080ca-1549-11e8-84c4-9e8e9e7b2396.png)
https://user-images.githubusercontent.com/20930745/36365468-fad080ca-1549-11e8-84c4-9e8e9e7b2396.png

Source:
https://user-images.githubusercontent.com/20930745/36365483-0cae5588-154a-11e8-9eab-7033ab2720d9.png
