### ISSUE TITLE
Lyrically - Music Lyrics for Fans, By Fans - Powered by Lyric Wikia

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9669]
**App Name:** Lyrically - Music Lyrics for Fans, By Fans - Powered by Lyric Wikia
**Bundle ID:** com.wikia.LyricWiki
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=447519370">447519370</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lyrically-music-lyrics-for-fans-by-fans-powered-by/id447519370?mt=8&uo=4">https://itunes.apple.com/us/app/lyrically-music-lyrics-for-fans-by-fans-powered-by/id447519370?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Wikia Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wikia-inc/id422467077?uo=4">© Wikia, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple69/v4/f7/60/fe/f760fe47-f48d-887b-8437-4c73df71284d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36365240-ec2eed28-1548-11e8-959c-14231b4992a5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36365240-ec2eed28-1548-11e8-959c-14231b4992a5.png)
https://user-images.githubusercontent.com/20930745/36365240-ec2eed28-1548-11e8-959c-14231b4992a5.png

Source:
https://user-images.githubusercontent.com/20930745/36365254-fc01ef0c-1548-11e8-84b4-079eb2c892e1.png
