### ISSUE TITLE
Rules of Survival

### ISSUE THREAD

**Issue by Neoflare** [glasklart/hd#9670]
**App Name:** Rules of Survival
**Bundle ID:** com.netease.chiji
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1307961750">1307961750</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rules-of-survival/id1307961750?mt=8&uo=4">https://itunes.apple.com/us/app/rules-of-survival/id1307961750?mt=8&uo=4</a>
**App Version:** 1.0.14
**Seller:** Hong Kong Netease Interactive Entertainment Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/netease-games/id874255382?uo=4">© NetEase Games</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/9a/bf/71/9abf71e2-4ca6-3e83-56e5-a5e9126eaae5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36421612-707737de-1639-11e8-829e-bcd45aa99f88.png)

**Comment by ivanov007** [comment]
@Neoflare do not edit the text when submitting new issues

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36421612-707737de-1639-11e8-829e-bcd45aa99f88.png)
https://user-images.githubusercontent.com/20930745/36421612-707737de-1639-11e8-829e-bcd45aa99f88.png

Source:
https://user-images.githubusercontent.com/20930745/36421629-80fade76-1639-11e8-9551-7563e957290b.png
