### ISSUE TITLE
HP Orbit

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#9671]
**App Name:** HP Orbit
**Bundle ID:** com.hp.orbit
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1140275542">1140275542</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hp-orbit/id1140275542?mt=8&uo=4">https://itunes.apple.com/us/app/hp-orbit/id1140275542?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** HP Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/hp-inc/id299531650?uo=4">© HP Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple82/v4/2c/3c/50/2c3c50c7-c1cd-9c69-f72e-96cd05d98a7d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36420974-0adeb250-1637-11e8-90f0-1c9ef027ab22.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36420974-0adeb250-1637-11e8-90f0-1c9ef027ab22.png)
https://user-images.githubusercontent.com/20930745/36420974-0adeb250-1637-11e8-90f0-1c9ef027ab22.png

Source:
https://user-images.githubusercontent.com/20930745/36420992-1e0ccce0-1637-11e8-89e3-82728cff1e27.png
