### ISSUE TITLE
Cooking Fever

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#9673]
**App Name:** Cooking Fever
**Bundle ID:** com.nordcurrent.canteenhd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=714796093">714796093</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cooking-fever/id714796093?mt=8&uo=4">https://itunes.apple.com/us/app/cooking-fever/id714796093?mt=8&uo=4</a>
**App Version:** 2.6.2
**Seller:** Nordcurrent Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nordcurrent/id348389028?uo=4">© Nordcurrent</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/08/8f/63/088f63ff-ba0b-e95b-94e9-a79344185291/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36644969-302b960c-1a62-11e8-9795-652cfdf46209.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36644969-302b960c-1a62-11e8-9795-652cfdf46209.png)
https://user-images.githubusercontent.com/20930745/36644969-302b960c-1a62-11e8-9795-652cfdf46209.png

Source:
https://user-images.githubusercontent.com/20930745/36644975-48883836-1a62-11e8-97ba-f0922e6db963.png
