### ISSUE TITLE
Darts of Fury

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9679]
**App Name:** Darts of Fury
**Bundle ID:** uk.co.yakuto.DartsOfFury
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1098189391">1098189391</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/darts-of-fury/id1098189391?mt=8&uo=4">https://itunes.apple.com/us/app/darts-of-fury/id1098189391?mt=8&uo=4</a>
**App Version:** 1.1.0220
**Seller:** Yakuto Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yakuto/id860620716?uo=4">© Yakuto</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/6b/86/26/6b8626c7-21af-db5c-4656-5aa1169f148e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36668050-4eed1d70-1af0-11e8-99ae-ca4e53597634.png)

**Comment by 2Qt2beStr8** [comment]
maybe i try the original Icon tomorrow

![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36644655-c3c8fa26-1a5d-11e8-85f4-be5915eae3c1.png)
https://user-images.githubusercontent.com/20930745/36644655-c3c8fa26-1a5d-11e8-85f4-be5915eae3c1.png

Source:
https://user-images.githubusercontent.com/20930745/36644670-0c923b96-1a5e-11e8-9264-d039093e656f.png

**Comment by 2Qt2beStr8** [comment]
not the original Icon, but i can do this
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36668050-4eed1d70-1af0-11e8-99ae-ca4e53597634.png)
https://user-images.githubusercontent.com/20930745/36668050-4eed1d70-1af0-11e8-99ae-ca4e53597634.png

Source:
https://user-images.githubusercontent.com/20930745/36668071-60701bf6-1af0-11e8-9ea6-7e858501da6f.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Second one ist great! 👍
