### ISSUE TITLE
Calculator +

### ISSUE THREAD

**Issue by Gtech202** [glasklart/hd#968]
**App Name:** Calculator +
**Bundle ID:** com.yourcompany.Solve
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=351815470">351815470</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calculator-+/id351815470?mt=8&uo=4">https://itunes.apple.com/us/app/calculator-+/id351815470?mt=8&uo=4</a>
**App Version:** 2.2.3
**Seller:** Sarah Ragab
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/xneat.com/id327498295?uo=4>© xNeat.com</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/b9/2f/70/b92f70ef-411a-038b-64db-6010aca0f2ea/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18748046/d6e0dcd2-80d0-11e6-9db3-1afc63fa156d.png)

**Comment by quantum8** [comment]
Icon needs update please.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18748046/d6e0dcd2-80d0-11e6-9db3-1afc63fa156d.png)
https://cloud.githubusercontent.com/assets/20930745/18748046/d6e0dcd2-80d0-11e6-9db3-1afc63fa156d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18748068/e87fef82-80d0-11e6-9f53-451a3a842c17.png
