### ISSUE TITLE
Gentle Reader

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9680]
**App Name:** Gentle Reader
**Bundle ID:** com.gentlereader.gentle-reader-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1240825904">1240825904</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gentle-reader/id1240825904?mt=8&uo=4">https://itunes.apple.com/us/app/gentle-reader/id1240825904?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Cronycle Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/cronycle/id763527853?uo=4">© Cronycle</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/e9/d6/f5/e9d6f59f-8f25-58d1-5c06-975a90175d3e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36634810-d5b32666-19aa-11e8-98af-964a4a09c1f3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36634810-d5b32666-19aa-11e8-98af-964a4a09c1f3.png)
https://user-images.githubusercontent.com/20930745/36634810-d5b32666-19aa-11e8-98af-964a4a09c1f3.png

Source:
![gentlereader](https://user-images.githubusercontent.com/20930745/36634814-e88a106a-19aa-11e8-8ce4-6e32d58017c1.png)
