### ISSUE TITLE
Cronycle - News & RSS Reader

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9681]
**App Name:** Cronycle - News & RSS Reader
**Bundle ID:** com.cronycle.cronycle-ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1037299761">1037299761</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cronycle-news-rss-reader/id1037299761?mt=8&uo=4">https://itunes.apple.com/us/app/cronycle-news-rss-reader/id1037299761?mt=8&uo=4</a>
**App Version:** 3.8
**Seller:** Cronycle Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/cronycle/id763527853?uo=4">© Cronycle</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/8d/11/dc/8d11dc3a-971d-5a88-d50d-fc7aaad4541d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36634980-8865e788-19ad-11e8-8ec8-6b57d83e9ad0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36634980-8865e788-19ad-11e8-8ec8-6b57d83e9ad0.png)
https://user-images.githubusercontent.com/20930745/36634980-8865e788-19ad-11e8-8ec8-6b57d83e9ad0.png

Source:
https://user-images.githubusercontent.com/20930745/36634984-9a167916-19ad-11e8-8db1-51fde915222b.png
