### ISSUE TITLE
Microsoft Teams

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#9685]
**App Name:** Microsoft Teams
**Bundle ID:** com.microsoft.skype.teams
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1113153706">1113153706</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/microsoft-teams/id1113153706?mt=8&uo=4">https://itunes.apple.com/us/app/microsoft-teams/id1113153706?mt=8&uo=4</a>
**App Version:** 1.0.74
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?mt=8&uo=4">© Microsoft Corporation</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/79/a0/8e/79a08e8d-862a-6c11-a5dc-7ac845202146/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com microsoft skype teams-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58777210-8e145d80-85cd-11e9-8680-6feb3521f197.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36668411-872246ec-1af1-11e8-99da-f1196b12d7fb.png)
https://user-images.githubusercontent.com/20930745/36668411-872246ec-1af1-11e8-99da-f1196b12d7fb.png

Source:
https://user-images.githubusercontent.com/20930745/36668432-9886ab94-1af1-11e8-8393-3b4415c6ed3c.png

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
![com microsoft skype teams-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58777210-8e145d80-85cd-11e9-8680-6feb3521f197.png)
https://user-images.githubusercontent.com/2068130/58777210-8e145d80-85cd-11e9-8680-6feb3521f197.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58777224-9f5d6a00-85cd-11e9-886f-277b017e6275.png
