### ISSUE TITLE
ReformX

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9686]
**App Name:** ReformX
 **Bundle ID:** com.zestlabs.reformx
 **Version:** b5
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 
![icon 2x](https://user-images.githubusercontent.com/14794477/36699687-b0fa0098-1b4d-11e8-9341-e78ab2c6d387.png)

 **Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36712894-4a4283d2-1b8b-11e8-8d68-d071971e0971.png)

**Comment by grkka** [comment]
My first request for a Cydia app. I hope I have done well.

**Comment by ivanov007** [comment]
@grkka yup, looks good

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36712355-b1104584-1b88-11e8-8c59-ab94cd91036a.png)
https://user-images.githubusercontent.com/20930745/36712355-b1104584-1b88-11e8-8c59-ab94cd91036a.png

Source:
https://user-images.githubusercontent.com/20930745/36712387-d2a92288-1b88-11e8-8501-84a3e342f95f.png
