### ISSUE TITLE
Focos

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9687]
**App Name:** Focos
**Bundle ID:** com.focos
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1274938524">1274938524</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/focos/id1274938524?uo=4">https://apps.apple.com/us/app/focos/id1274938524?uo=4</a>
**App Version:** 1.7.2
**Seller:** Xiaodong Wang
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/xiaodong-wang/id1083287354?uo=4">© Xiaodong Wang</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/9c/66/d6/9c66d6d1-a382-ea52-107b-1f306e639265/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400350-ef9afe00-9b72-11e9-84bd-b83e5d0e4ff3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/36803739-c3f58890-1cb8-11e8-9a26-d28d0f74433e.png)
https://user-images.githubusercontent.com/20930745/36803739-c3f58890-1cb8-11e8-9a26-d28d0f74433e.png

Source:
https://user-images.githubusercontent.com/20930745/36803770-da4569b2-1cb8-11e8-9dc4-43c21312f9fd.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/60400350-ef9afe00-9b72-11e9-84bd-b83e5d0e4ff3.png)
https://user-images.githubusercontent.com/20930745/60400350-ef9afe00-9b72-11e9-84bd-b83e5d0e4ff3.png

Source:
https://user-images.githubusercontent.com/20930745/60400351-f164c180-9b72-11e9-8ada-4371d7595428.png
