### ISSUE TITLE
Filzaelectrocuted

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9688]
App Name: Filzaelectrocuted 
Bundle ID: com.scroublepokemon.filzaelectrocuted
Version: 1.0.3
iTunes ID: none (Cydia app)
Original Artwork:

![appicon60x60 3x](https://user-images.githubusercontent.com/14794477/37029501-f4402a7c-2137-11e8-9599-584d96475f18.png)
 
Accepted Artwork:
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37052399-7a7b7c5e-2179-11e8-835f-97c29c373391.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37052399-7a7b7c5e-2179-11e8-835f-97c29c373391.png)
https://user-images.githubusercontent.com/20930745/37052399-7a7b7c5e-2179-11e8-835f-97c29c373391.png

Source:
https://user-images.githubusercontent.com/20930745/37052426-8e6ba2ac-2179-11e8-814a-cdde187a79bc.png
