### ISSUE TITLE
White Night

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#9689]
**App Name:** White Night
**Bundle ID:** com.playdigious.whitenight
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1243555377">1243555377</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/white-night/id1243555377?mt=8&uo=4">https://itunes.apple.com/us/app/white-night/id1243555377?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Playdigious
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/playdigious/id1041387229?uo=4">© Playdigious</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/d9/82/f6/d982f660-c043-573f-d7e6-9e87d399e192/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37552165-c7d9c6ac-29af-11e8-8b57-1056a3bdd099.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37301655-7fee085a-2629-11e8-97cd-7b99d0ec40dd.png)
https://user-images.githubusercontent.com/20930745/37301655-7fee085a-2629-11e8-97cd-7b99d0ec40dd.png

Source:
https://user-images.githubusercontent.com/20930745/37301682-9b60f2dc-2629-11e8-8beb-3258c4a4e2ec.png

**Comment by dreamnet** [comment]
Hmmmm... I think ist better to invert this...
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37552165-c7d9c6ac-29af-11e8-8b57-1056a3bdd099.png)
https://user-images.githubusercontent.com/2068130/37552165-c7d9c6ac-29af-11e8-8b57-1056a3bdd099.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37552168-d8f04182-29af-11e8-8ee3-09f550478810.png

**Comment by 2Qt2beStr8** [comment]
@dreamnet … but the accepted artwork is not inverted 🤔

**Comment by dreamnet** [comment]
@2Qt2beStr8 ?? Try to hit refresh in your browser....

**Comment by 2Qt2beStr8** [comment]
![c9de100e-a940-4d4d-a66e-fa8db8d1aaf7](https://user-images.githubusercontent.com/20930745/37552775-bdc6dde2-29bb-11e8-9c63-d3f1afe5434c.jpeg)

Something is wrong — Look to your E-Mail

**Comment by dreamnet** [comment]
@2Qt2beStr8 Hm, strange. What happens if you open this page in your browser?

**Comment by 2Qt2beStr8** [comment]
really strange 😱

github
![d5414924-cce9-4406-95ef-ed789783857a](https://user-images.githubusercontent.com/20930745/37552860-32505f16-29bd-11e8-838d-1511e14188f3.png)

your page 
![1e1983dc-9e3c-4e60-b2f9-c6190d0293dc](https://user-images.githubusercontent.com/20930745/37552871-54570362-29bd-11e8-90a5-0085568e1070.png)

**Comment by dreamnet** [comment]
@2Qt2beStr8 Yes, strange... all fine for me,
--- ---
Safari on iPad:
![img_0341](https://user-images.githubusercontent.com/2068130/37552970-1f940c4a-29bf-11e8-86a4-1e3322eb8118.PNG)
--- ---
Chrome on iPad:
![img_0342](https://user-images.githubusercontent.com/2068130/37552975-31f8d456-29bf-11e8-846a-64141db761b9.PNG)
--- ---
I really think you need to clear the caches on your devices (use iCleaner).
