### ISSUE TITLE
American Airlines

### ISSUE THREAD

**Issue by odysseydla** [glasklart/hd#969]
**App Name:** American Airlines
**Bundle ID:** com.aa.AmericanAirlines
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=382698565">382698565</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/american-airlines/id382698565?mt=8&uo=4">https://itunes.apple.com/us/app/american-airlines/id382698565?mt=8&uo=4</a>
**App Version:** 4.8.0
**Seller:** American Airlines, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/american-airlines/id382698568?uo=4>© American Airlines</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple62/v4/48/67/c7/4867c7a5-b840-e343-0625-4900c2632ec9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19076115/d2c6cd20-8a47-11e6-99a8-211335af2167.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19075607/f9abf2d2-8a45-11e6-979c-262a8d8c42cd.png)
https://cloud.githubusercontent.com/assets/20930745/19075607/f9abf2d2-8a45-11e6-979c-262a8d8c42cd.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19075638/14c39e9e-8a46-11e6-8728-0e3930839288.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19076115/d2c6cd20-8a47-11e6-99a8-211335af2167.png)
https://cloud.githubusercontent.com/assets/20930745/19076115/d2c6cd20-8a47-11e6-99a8-211335af2167.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19076135/e61b8c6c-8a47-11e6-9b74-ef96c5cbe766.png
