### ISSUE TITLE
Starman

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#9690]
**App Name:** Starman
**Bundle ID:** games.nadastudio.starman
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1157484554">1157484554</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/starman/id1157484554?mt=8&uo=4">https://itunes.apple.com/us/app/starman/id1157484554?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** nada studio, sl
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nada-studio-sl/id1157484553?uo=4">© nada studio, sl</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/44/31/90/443190cf-c516-6aea-a7c7-96c9d70be06a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37303225-1fcaeb96-262e-11e8-8f08-971ec42baa71.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37303225-1fcaeb96-262e-11e8-8f08-971ec42baa71.png)
https://user-images.githubusercontent.com/20930745/37303225-1fcaeb96-262e-11e8-8f08-971ec42baa71.png

Source:
https://user-images.githubusercontent.com/20930745/37303257-30ee7faa-262e-11e8-94cb-eba53455e9a3.png
