### ISSUE TITLE
Now Playing (CarPlay)

### ISSUE THREAD

**Issue by s0cr4t1c** [glasklart/hd#9691]
Please add an icon for ‘Now Playing’ that shows on CarPlay connected devices.

**Comment by dreamnet** [comment]
@s0cr4t1c Can you please explain what exactly you mean and how to do this?

**Comment by s0cr4t1c** [comment]
When you connect an iPhone to a CarPlay compatible car infotainment system, your CarPlay compatible app icons are displayed on the screen along with one additional ‘Now Playing’ icon which loads whichever app is currently playing when pressed. This is a system icon located somewhere in iOS. Where exactly, I couldn’t tell you. The icon in question is in the lower left of this pic: http://cdn.osxdaily.com/wp-content/uploads/2016/07/carplay-dash-2-900x441.jpg

**Comment by s0cr4t1c** [comment]
I’ve searched through my file system but can’t seem to find the icon, but the bundle ID is com.apple.cardisplay.nowplaying

I suspect the icon is a cpbitmap rather than the standard png. I’ve found such a file in /var/mobile/Library/Caches/MappedImageCache/CarPlayIconCache

**Comment by dreamnet** [comment]
OK, maybe I've fond something (but can't try it out):
--- ---
Bundles Method:
`Bundles/com.apple.cardisplay.nowplaying/CarDisplayCanvasIcon.png`,
`Bundles/com.apple.cardisplay.nowplaying/CarDisplayCanvasIcon@2x.png`,
`Bundles/com.apple.cardisplay.nowplaying/CarDisplayCanvasIcon@3x.png` or
`Bundles/com.apple.cardisplay.nowplaying/CarDisplayCanvasIcon-com.apple.cardisplay.nowplaying.png`.
--- ---
IconBundles Method (**prefered**):
`IconBundles/com.apple.cardisplay.nowplaying-large.png` (180x180px)
--- ---
Here is the icon:
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37559365-d6577fa6-2a24-11e8-8a0f-15e8161f214e.png)
https://user-images.githubusercontent.com/2068130/37559365-d6577fa6-2a24-11e8-8a0f-15e8161f214e.png
Source:
https://user-images.githubusercontent.com/2068130/37559368-e68ea7dc-2a24-11e8-8a42-c80b956ffad1.png
--- ---
@s0cr4t1c Can you try it out and give us some feedback (IconBundles method prefered).

**Comment by s0cr4t1c** [comment]
Tried both Bundles and IconBundles methods. No luck. :(

**Comment by s0cr4t1c** [comment]
Yes, CarPlay respects many tweaks including Anemone themes. My car display shows Glaklart icons for Phone, Maps, Messages, Music, Pandora, NPR One, Podcasts, and Spotify. Cylinder also works on my car’s display. It’s pretty neat!

**Comment by dreamnet** [comment]
@s0cr4t1c Hmmm... as fas as I know it should work. Can you please ssh your device and post the content of the file `/System/Library/CoreServices/SpringBoard.app/DefaultIconState_CarDisplay.plist` ?

I've made a zip.
[Glasklart_CarPlay.theme.zip](https://github.com/glasklart/hd/files/1822497/Glasklart_CarPlay.theme.zip)
Please extract the content of the zip to `/Library/Themes`, activate it in Anemone, respring, try it again in your car and give me some feedback?

**Comment by 2Qt2beStr8** [comment]
@dreamnet .... here you are

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>iconLists</key>
	<array>
		<array>
			<string>com.apple.mobilephone</string>
			<string>com.apple.Music</string>
			<string>com.apple.Maps</string>
			<string>com.apple.MobileSMS</string>
			<string>com.apple.cardisplay.nowplaying</string>
			<string>com.apple.cardisplay.OEM</string>
			<string>com.apple.podcasts</string>
			<string>com.apple.iBooks</string>
		</array>
	</array>
</dict>
</plist>

**Comment by 2Qt2beStr8** [comment]
![a7b757a0-6cd8-4747-8c5d-7ab7a1db8ab9](https://user-images.githubusercontent.com/20930745/37565317-7afe5a8e-2aa7-11e8-903a-95c02779f7fc.jpeg)

I have tryed it in my car an it does not work :-(

**Comment by dreamnet** [comment]
`Aktueller Titel` should be `com.apple.cardisplay.nowplaying` and
`SKODA` should be `com.apple.cardisplay.OEM`
I don't know why this is not working. 🤔

**Comment by 2Qt2beStr8** [comment]
i have tryed the skoda Icon too - and it did not work also

if someone need the icon:
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37566512-7fdd9eb2-2aba-11e8-9c17-4063fa721e97.png)
https://user-images.githubusercontent.com/20930745/37566512-7fdd9eb2-2aba-11e8-9c17-4063fa721e97.png

Source:
https://user-images.githubusercontent.com/20930745/37566517-9566bde0-2aba-11e8-8b44-00aee850fafb.png

**Comment by dreamnet** [comment]
...stuck on this... 😢

**Comment by s0cr4t1c** [comment]
Thanks for trying. :)
