### ISSUE TITLE
Test & Check for iPhone

### ISSUE THREAD

**Issue by Wanny** [glasklart/hd#9692]
**App Name:** Test & Check for iPhone
**Bundle ID:** appkonthai.check
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1022281157">1022281157</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/test-check-for-iphone/id1022281157?mt=8&uo=4">https://itunes.apple.com/us/app/test-check-for-iphone/id1022281157?mt=8&uo=4</a>
**App Version:** 1.1.9
**Seller:** Prasomsak Khunmuen
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/prasomsak-khunmuen/id636412127?uo=4">© Prasomsak Khunmuen</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/c4/0d/48/c40d4805-f377-004b-5513-b475166aff7f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37417449-a37046fc-27b0-11e8-9e0d-1b1b21df74bb.png)

**Comment by Wanny** [comment]
![com appkonthai check-large-preview](https://user-images.githubusercontent.com/569307/37384889-1d03dd84-2730-11e8-862a-33d6d0dfb463.png)

I'm new to this. I wanted to test the new icon and I don't know how to name it. I tried naming it com.appkonthai.check-large.png and when applying the theme it isn't changed.

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37417449-a37046fc-27b0-11e8-9e0d-1b1b21df74bb.png)
https://user-images.githubusercontent.com/20930745/37417449-a37046fc-27b0-11e8-9e0d-1b1b21df74bb.png

Source:
https://user-images.githubusercontent.com/20930745/37417483-b4e079e8-27b0-11e8-82b0-dec2aee0da3b.png

**Comment by Wanny** [comment]
Where's the layer with the lines? it isn't in the templace v5.02..

**Comment by 2Qt2beStr8** [comment]
https://github.com/glasklart/hd/wiki/How-to-Contribute-an-Icon

**Comment by Wanny** [comment]
Oh Duh, I completely misread that section. I fixed the contribution post, thanks.

**Comment by 2Qt2beStr8** [comment]
You are welcome :-)

**Comment by Wanny** [comment]
Source:
https://user-images.githubusercontent.com/569307/37431895-48dec6b4-27b5-11e8-8dfd-383d31dda8d0.png

**Comment by dreamnet** [comment]
@Wanny Nice work! 👍
