### ISSUE TITLE
MuseCam

### ISSUE THREAD

**Issue by Wanny** [glasklart/hd#9693]
**App Name:** MuseCam
**Bundle ID:** com.museworks.musecam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1047340501">1047340501</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/musecam/id1047340501?mt=8&uo=4">https://itunes.apple.com/us/app/musecam/id1047340501?mt=8&uo=4</a>
**App Version:** 1.3.2
**Seller:** MuseWorks, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/museworks-inc/id991357924?uo=4">© MuseWorks, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/c1/d9/12/c1d91275-3676-3c8e-5dad-a7b2a1fb53ec/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37552631-8ab2c1d4-29b9-11e8-9dfd-fe55e29d3ef3.png)

**Comment by Wanny** [comment]
![com museworks musecam-large](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/569307/37424709-f1c69a88-279f-11e8-9489-d8485935f4df.png)

**Comment by 2Qt2beStr8** [comment]
We also need the source file 
Pls read the wiki again :-)
Because we want to make Glasklart available for future iOS releases and we don't know what Apple changes next, we need you to attach the 1024x1024px source file of the icon you made. The source file should be in png or svg format and it should only contain two colors - solid, opaque black and transparent (the black part will be white in the finished Glasklart icon). Here are some examples:
Example 1
Example 2
Example 3
The source file represents the 118x118px area between the guidelines in the center of the Glasklart .psd file. Having the source file, allow us to downsize it without quality loss, we also can use them for other iOS devices. So when you post your icon contribution, please drag and drop the source in the issue, remove the ![......]( and the ) and you are done - and we are happy.

**Comment by Wanny** [comment]
Oh no, I kept deleting them. Time to redo it... and the wiki says that it only has to be with only 2 colors, that means that this will be tough to remake since it looks odd with only one color D;

**Comment by 2Qt2beStr8** [comment]
not 2 colors — only black!

**Comment by Wanny** [comment]
"The source file should be in png or svg format and it should only contain **two colors**" (black and... well, nothing)

My point still stands. This icon looks strange only in black (and with the Glasklart layers added). I'll comply with it anyways. I uploaded an updated icon with greyscale colors removed, and the source is:

https://user-images.githubusercontent.com/569307/37426438-31a529ee-27a5-11e8-8a4f-9699872b3561.png

**Comment by 2Qt2beStr8** [comment]
maybe something like this?
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37427911-fbe6e6e6-27ca-11e8-9e97-2e9418e891d4.png)
https://user-images.githubusercontent.com/20930745/37427911-fbe6e6e6-27ca-11e8-9e97-2e9418e891d4.png

Source:
https://user-images.githubusercontent.com/20930745/37427932-0b710178-27cb-11e8-8235-d39b60c082f3.png

**Comment by Wanny** [comment]
mmm yeah, that's something I was doing now... blessed magic wand

**Comment by Wanny** [comment]
Another try:

![com museworks musecam-large](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/569307/37429748-03d9fa94-27af-11e8-9530-0d89eb54959a.png)

Source:
https://user-images.githubusercontent.com/569307/37429786-20412414-27af-11e8-92be-8aec38da7963.png

**Comment by dreamnet** [comment]
@Wanny Great! I'm just cleaning it up a bit and making bigger spaces between objects (~ 10px).
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37552631-8ab2c1d4-29b9-11e8-9dfd-fe55e29d3ef3.png)
https://user-images.githubusercontent.com/2068130/37552631-8ab2c1d4-29b9-11e8-9dfd-fe55e29d3ef3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37552637-9a16483a-29b9-11e8-9e31-00ddf21cc97d.png
