### ISSUE TITLE
Crash to Safemode Electra iOS 11

### ISSUE THREAD

**Issue by psychic2ombie** [glasklart/hd#9694]
When trying to use this theme on iOS 11, it will work for a little bit, but then crash to Safemode with Electra. I am aware this theme isn't officially supported for iOS 11, but I saw on reddit that some people had it working.

**Comment by psychic2ombie** [comment]
So it turns out that it only goes to safemode when trying to load Glasklart after disabling another theme. If you disable all themes, respring, and then enable Glasklart it works just fine

**Comment by grkka** [comment]
Glasklart it works for me since the first Electra beta. It must be another tweak or configuration that makes you enter SafeMode. @psychic2ombie

**Comment by psychic2ombie** [comment]
Yeah it's something on my side that I've fixed, so I'm closing this.
