### ISSUE TITLE
Fortnite

### ISSUE THREAD

**Issue by Neoflare** [glasklart/hd#9695]
**App Name:** Fortnite
**Bundle ID:** com.chairentertainment.Fortnite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1261357853">1261357853</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fortnite/id1261357853?mt=8&uo=4">https://itunes.apple.com/us/app/fortnite/id1261357853?mt=8&uo=4</a>
**App Version:** 3.3.0
**Seller:** Chair Entertainment Group
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/epic-games/id387428403?uo=4">© Epic Games</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/29/f7/3f/29f73ff2-4b4b-486a-5685-02121404568d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37553814-3cc9fb52-29cf-11e8-9f3f-298166f30d08.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37553814-3cc9fb52-29cf-11e8-9f3f-298166f30d08.png)
https://user-images.githubusercontent.com/2068130/37553814-3cc9fb52-29cf-11e8-9f3f-298166f30d08.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37553817-4aee8ef0-29cf-11e8-930d-9962449faf19.png
