### ISSUE TITLE
Airtable

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9696]
**App Name:** Airtable
**Bundle ID:** com.FormaGrid.Hyperbase
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=914172636">914172636</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/airtable/id914172636?mt=8&uo=4">https://itunes.apple.com/us/app/airtable/id914172636?mt=8&uo=4</a>
**App Version:** 3.6.7
**Seller:** Formagrid Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/formagrid/id914172639?uo=4">© Formagrid</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/37/dd/f4/37ddf492-9d01-1e75-085c-a3b090f5ff91/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37559783-1247495e-2a2c-11e8-9f61-7e59729ba0d6.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37559783-1247495e-2a2c-11e8-9f61-7e59729ba0d6.png)
https://user-images.githubusercontent.com/2068130/37559783-1247495e-2a2c-11e8-9f61-7e59729ba0d6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37559784-21f6a264-2a2c-11e8-8594-ace0f0ade431.png
