### ISSUE TITLE
GIVEMESPORT

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9697]
**App Name:** GIVEMESPORT
**Bundle ID:** com.sportsnewmedia.GiveMeSport
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1271388300">1271388300</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/givemesport/id1271388300?mt=8&uo=4">https://itunes.apple.com/us/app/givemesport/id1271388300?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Sports New Media Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sports-new-media-limited/id416104461?uo=4">© Sports New Media Limited</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/f3/cd/b2/f3cdb2e7-9cd0-f531-472a-3a5d4f2f47a6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37559742-564b9ee4-2a2b-11e8-8ba4-419b7691caf6.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37559742-564b9ee4-2a2b-11e8-8ba4-419b7691caf6.png)
https://user-images.githubusercontent.com/2068130/37559742-564b9ee4-2a2b-11e8-8ba4-419b7691caf6.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37559743-659378f4-2a2b-11e8-8884-327367b7f81e.png
