### ISSUE TITLE
Otter Voice Meeting Notes

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9698]
**App Name:** Otter Voice Meeting Notes
**Bundle ID:** com.aisense.otter
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1276437113">1276437113</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/otter-voice-meeting-notes/id1276437113?mt=8&uo=4">https://itunes.apple.com/us/app/otter-voice-meeting-notes/id1276437113?mt=8&uo=4</a>
**App Version:** 1.3.3
**Seller:** AISense Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/aisense-inc/id1276437112?uo=4">© AISense Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/e3/48/30/e3483074-b045-4fcd-25b9-a19ffc5b06aa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37559710-dfeaa902-2a2a-11e8-8f43-f2796836883f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37559710-dfeaa902-2a2a-11e8-8f43-f2796836883f.png)
https://user-images.githubusercontent.com/2068130/37559710-dfeaa902-2a2a-11e8-8f43-f2796836883f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37559714-f03acdd2-2a2a-11e8-93c9-bab509900cd8.png
