### ISSUE TITLE
Dictionary & Translator Pro

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9699]
**App Name:** Dictionary & Translator Pro
**Bundle ID:** com.erudite.ecdict
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=927791564">927791564</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dictionary-translator-pro/id927791564?mt=8&uo=4">https://itunes.apple.com/us/app/dictionary-translator-pro/id927791564?mt=8&uo=4</a>
**App Version:** 8.4
**Seller:** Erudite Education Group Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/erudite/id927791563?uo=4">© Erudite</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/cb/1e/ea/cb1eea8a-0f59-e093-3360-7e91d680c065/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37559676-7539c55c-2a2a-11e8-9b98-2e0373cf0005.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37559676-7539c55c-2a2a-11e8-9b98-2e0373cf0005.png)
https://user-images.githubusercontent.com/2068130/37559676-7539c55c-2a2a-11e8-9b98-2e0373cf0005.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37559678-8588ced0-2a2a-11e8-9660-d91a98f1c744.png
