### ISSUE TITLE
Le Monde, l'info en continu

### ISSUE THREAD

**Issue by iPhoneAddict** [glasklart/hd#97]
**App Name:** Le Monde, l'info en continu
**Bundle ID:** fr.lemonde.LeMonde
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=294047850">294047850</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/le-monde-linfo-en-continu/id294047850?mt=8&uo=4">https://itunes.apple.com/us/app/le-monde-linfo-en-continu/id294047850?mt=8&uo=4</a>
**App Version:** 8.5
**Seller:** Le Monde Interactif
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/le-monde-fr/id294047853?mt=8&uo=4">© Le Monde.fr</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/bd/3d/ae/bd3dae88-db68-aa24-1fe8-49deb24f9353/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692565-7d08134c-c71a-11e7-985f-bf372eaeaf2b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32692565-7d08134c-c71a-11e7-985f-bf372eaeaf2b.png)
https://user-images.githubusercontent.com/2068130/32692565-7d08134c-c71a-11e7-985f-bf372eaeaf2b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32692569-8b9b9e24-c71a-11e7-8d9c-b851727ffaf8.png
