### ISSUE TITLE
Cake Browser

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9700]
**App Name:** Cake Browser
**Bundle ID:** com.lipslabs.cake
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1163553130">1163553130</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cake-browser/id1163553130?mt=8&uo=4">https://itunes.apple.com/us/app/cake-browser/id1163553130?mt=8&uo=4</a>
**App Version:** 1.0.14
**Seller:** Cake Technologies, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/cake-technologies-inc/id1163553129?uo=4">© Cake Technologies, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/d5/a5/48/d5a548ad-b2b3-98eb-9c7a-2b1be95fc125/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37559654-e9d50882-2a29-11e8-80f3-a476f86723ce.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37559654-e9d50882-2a29-11e8-80f3-a476f86723ce.png)
https://user-images.githubusercontent.com/2068130/37559654-e9d50882-2a29-11e8-80f3-a476f86723ce.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37559657-f8b8b9e8-2a29-11e8-8bab-9f086102253b.png
