### ISSUE TITLE
SmartGym: Manage Your Workout

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9701]
**App Name:** SmartGym: Manage Your Workout
**Bundle ID:** com.smartgymapp.smartgym
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=922744883">922744883</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smartgym-manage-your-workout/id922744883?mt=8&uo=4">https://itunes.apple.com/us/app/smartgym-manage-your-workout/id922744883?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** Mateus Abras
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mateus-abras/id348784074?uo=4">© Mateus Abras</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/fa/d6/41/fad64122-2216-04d9-103f-5189c0ec8890/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37667198-b79fa126-2c61-11e8-95d7-20d4b0171981.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37667198-b79fa126-2c61-11e8-95d7-20d4b0171981.png)
https://user-images.githubusercontent.com/20930745/37667198-b79fa126-2c61-11e8-95d7-20d4b0171981.png

Source:
https://user-images.githubusercontent.com/20930745/37667233-ca239190-2c61-11e8-8bf6-2cfa5bdabf37.png

**Comment by grkka** [comment]
👌🏻
