### ISSUE TITLE
Canary Mail - Secure Email App

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9702]
**App Name:** Canary Mail - Secure Email App
**Bundle ID:** Mailroom.Canary-iOS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1155470386">1155470386</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/canary-mail-secure-email-app/id1155470386?mt=8&uo=4">https://itunes.apple.com/us/app/canary-mail-secure-email-app/id1155470386?mt=8&uo=4</a>
**App Version:** 2.01
**Seller:** Mailr Tech LLP
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mailr-tech-llp/id1137358501?uo=4">© Mailr Tech LLP</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/ef/39/5c/ef395c3e-f77a-a913-08dc-c4086b7d1a28/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37667860-544212f6-2c63-11e8-88ea-8f3908581f62.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37667828-3a04e47c-2c63-11e8-9249-3ac14163eaf0.png)
https://user-images.githubusercontent.com/20930745/37667828-3a04e47c-2c63-11e8-9249-3ac14163eaf0.png

Source:
https://user-images.githubusercontent.com/20930745/37667847-4ac82ab2-2c63-11e8-9016-5c9aba137953.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37667860-544212f6-2c63-11e8-88ea-8f3908581f62.png)
https://user-images.githubusercontent.com/20930745/37667860-544212f6-2c63-11e8-88ea-8f3908581f62.png

Source:
https://user-images.githubusercontent.com/20930745/37667883-675f38fa-2c63-11e8-96a4-8d98169e9247.png
