### ISSUE TITLE
ShopFully

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9703]
**App Name:** ShopFully
**Bundle ID:** it.doveconviene.DoveConviene
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=446366839">446366839</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shopfully/id446366839?mt=8&uo=4">https://itunes.apple.com/us/app/shopfully/id446366839?mt=8&uo=4</a>
**App Version:** 7.3.1
**Seller:** DoveConviene S.r.l.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/doveconviene-s-r-l/id446366842?uo=4">© DoveConviene S.r.l.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/e3/c9/c1/e3c9c189-f793-4dc9-97e2-41bb1dafdae7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37878583-91f1b1b8-306b-11e8-82e3-1d967933cec3.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37878583-91f1b1b8-306b-11e8-82e3-1d967933cec3.png)
https://user-images.githubusercontent.com/2068130/37878583-91f1b1b8-306b-11e8-82e3-1d967933cec3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37878593-aa843c28-306b-11e8-9ed6-13d9ba85d428.png
