### ISSUE TITLE
Paste 2

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9704]
**App Name:** Paste 2
**Bundle ID:** com.wiheads.paste.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1020667032">1020667032</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paste-2/id1020667032?mt=8&uo=4">https://itunes.apple.com/us/app/paste-2/id1020667032?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Dmitry Obukhov
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dmitry-obukhov/id967805234?uo=4">© Dmitry Obukhov</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/b4/72/c7/b472c721-e6bc-63b5-8c4f-3c2fbe7f7aad/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37872248-cd6429b4-3003-11e8-82af-701c32a8226d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37872248-cd6429b4-3003-11e8-82af-701c32a8226d.png)
https://user-images.githubusercontent.com/2068130/37872248-cd6429b4-3003-11e8-82af-701c32a8226d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37872255-dc721eb6-3003-11e8-8873-aeb3fc8d6b56.png
