### ISSUE TITLE
Pocket Lists 2

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9705]
**App Name:** Pocket Lists 2
**Bundle ID:** com.pocketlists
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1272049520">1272049520</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pocket-lists-2/id1272049520?mt=8&uo=4">https://itunes.apple.com/us/app/pocket-lists-2/id1272049520?mt=8&uo=4</a>
**App Version:** 2.1.0
**Seller:** Vladimir Tuporshin
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/1312/id482537119?uo=4">© 1312</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/b7/f5/12/b7f51294-c7c9-c003-abc2-c4574950d8de/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37872345-e81b9e2a-3005-11e8-910f-2b478defe035.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37872345-e81b9e2a-3005-11e8-910f-2b478defe035.png)
https://user-images.githubusercontent.com/2068130/37872345-e81b9e2a-3005-11e8-910f-2b478defe035.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37872347-f6fa84a6-3005-11e8-8ca1-5f688c71a9c0.png
