### ISSUE TITLE
ZEEEN - Dribbble client -

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9706]
**App Name:** ZEEEN - Dribbble client -
**Bundle ID:** jp.sparklerapps.arch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=923813895">923813895</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zeeen-dribbble-client/id923813895?mt=8&uo=4">https://itunes.apple.com/us/app/zeeen-dribbble-client/id923813895?mt=8&uo=4</a>
**App Version:** 1.3.5
**Seller:** Katsuhisa Ishii
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/katsuhisa-ishii/id619683571?uo=4">© Katsuhisa Ishii</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/ae/8b/f2/ae8bf2d0-f044-f8a4-1a73-3ecba0db9611/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37868683-dd5ba940-2faa-11e8-87e1-9f0064222048.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37868683-dd5ba940-2faa-11e8-87e1-9f0064222048.png)
https://user-images.githubusercontent.com/2068130/37868683-dd5ba940-2faa-11e8-87e1-9f0064222048.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37868687-ed98e93a-2faa-11e8-8b3f-929bb85383ec.png
