### ISSUE TITLE
Snappy - Snapshots, the smart way.

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9707]
**App Name:** Snappy - Snapshots, the smart way.
**Bundle ID:** ro.nextwave.SnappyiOS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=927687689">927687689</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/snappy-snapshots-the-smart-way/id927687689?mt=8&uo=4">https://itunes.apple.com/us/app/snappy-snapshots-the-smart-way/id927687689?mt=8&uo=4</a>
**App Version:** 2.0.1
**Seller:** NEXTWAVE SOFTWARE SOLUTIONS SRL
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nextwave-digital/id512617041?uo=4">© Nextwave Digital</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/4b/b5/20/4bb5203c-287c-d44e-976d-4efddd8f8a30/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37868519-facb6108-2fa7-11e8-8f11-1e294a8949ce.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37868519-facb6108-2fa7-11e8-8f11-1e294a8949ce.png)
https://user-images.githubusercontent.com/2068130/37868519-facb6108-2fa7-11e8-8f11-1e294a8949ce.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37868523-09ea38bc-2fa8-11e8-94ae-4f1c111ee7b3.png
