### ISSUE TITLE
Bookmark Thumbnails & Folders

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9708]
**App Name:** Bookmark Thumbnails & Folders
**Bundle ID:** com.fookiemonsters.Bookmark
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1249222100">1249222100</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bookmark-thumbnails-folders/id1249222100?mt=8&uo=4">https://itunes.apple.com/us/app/bookmark-thumbnails-folders/id1249222100?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Ryoichi Fukugawa
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ryoichi-fukugawa/id1249222099?uo=4">© Ryoichi Fukugawa</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/ef/51/04/ef51043e-b913-f27a-6668-342fd3a09e70/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37868470-26377a58-2fa7-11e8-87e3-17a767df721a.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37868470-26377a58-2fa7-11e8-87e3-17a767df721a.png)
https://user-images.githubusercontent.com/2068130/37868470-26377a58-2fa7-11e8-87e3-17a767df721a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37868475-357ac182-2fa7-11e8-9a35-a0cdb4c3645c.png
