### ISSUE TITLE
Mixface: Widgets on Watch Face

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9709]
**App Name:** Mixface: Widgets on Watch Face
**Bundle ID:** com.dclabs.Mixface
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1257564075">1257564075</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mixface-widgets-on-watch-face/id1257564075?mt=8&uo=4">https://itunes.apple.com/us/app/mixface-widgets-on-watch-face/id1257564075?mt=8&uo=4</a>
**App Version:** 5.4
**Seller:** Yingchi Wang
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yingchi-wang/id1114289020?uo=4">© Yingchi Wang</a>
**Supported Devices:** iPhone5-iPhone5, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple118/v4/1b/e8/09/1be80972-1ab9-721a-3123-82bc1f65d81c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37878980-1ae35170-3071-11e8-9b1b-d06852560dd9.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37878980-1ae35170-3071-11e8-9b1b-d06852560dd9.png)
https://user-images.githubusercontent.com/2068130/37878980-1ae35170-3071-11e8-9b1b-d06852560dd9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37878986-2afb3b22-3071-11e8-9891-de049a66371c.png
