### ISSUE TITLE
Age Of Zombies: Anniversary Edition

### ISSUE THREAD

**Issue by cr0w-69** [glasklart/hd#971]
Name: AoZ Anniv.
Bundle ID: com.halfbrick.AoZHD
iTunes ID: 451365136
PNG Icon Names: Icon.png | Icon@2x.png | Icon-72.png | Icon-Small-50.png | icon-small.png | Icon-Small@2x.png
Artwork: 
![Age-of-Zombies ](https://f.cloud.github.com/assets/3203486/166340/3aba9276-799a-11e2-995f-5474527df6fa.png)

**Comment by Anuskuss** [comment]
Delete this icon since #4727 is a universal app now,
