### ISSUE TITLE
AirVisual Air Quality Forecast

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9710]
**App Name:** AirVisual Air Quality Forecast
**Bundle ID:** com.airvisual.airvisual
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1048912974">1048912974</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/airvisual-air-quality-forecast/id1048912974?mt=8&uo=4">https://itunes.apple.com/us/app/airvisual-air-quality-forecast/id1048912974?mt=8&uo=4</a>
**App Version:** 4.1.1
**Seller:** Air Visual Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/airvisual/id1048912973?uo=4">© AirVisual</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple62/v4/fd/ce/02/fdce02d7-bca0-6742-e0a5-bd61b02ed465/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37878518-ce7f61a8-306a-11e8-9b84-88308eabadea.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37878518-ce7f61a8-306a-11e8-9b84-88308eabadea.png)
https://user-images.githubusercontent.com/2068130/37878518-ce7f61a8-306a-11e8-9b84-88308eabadea.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37878522-df76b290-306a-11e8-8283-2813cbf1680c.png
