### ISSUE TITLE
Stocks Pro App: Stock Tracker

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9711]
**App Name:** Stocks Pro App: Stock Tracker
**Bundle ID:** com.postindustria.stockinvestor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1265086241">1265086241</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/stocks-pro-app-stock-tracker/id1265086241?mt=8&uo=4">https://itunes.apple.com/us/app/stocks-pro-app-stock-tracker/id1265086241?mt=8&uo=4</a>
**App Version:** 1.7.3
**Seller:** Postindustria Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/postindustria/id354978750?uo=4">© Postindustria</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/80/75/ca/8075ca45-cae2-d769-f3b5-8113f59cba6c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37879097-20af45f8-3073-11e8-85aa-e7cd2332437b.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37879097-20af45f8-3073-11e8-85aa-e7cd2332437b.png)
https://user-images.githubusercontent.com/2068130/37879097-20af45f8-3073-11e8-85aa-e7cd2332437b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37879100-2f8009dc-3073-11e8-8ca7-b79e600a6e3a.png
