### ISSUE TITLE
Capital One CreditWise

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9712]
**App Name:** Capital One CreditWise
**Bundle ID:** com.capitalone.credittracker2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1008234539">1008234539</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/capital-one-creditwise/id1008234539?mt=8&uo=4">https://itunes.apple.com/us/app/capital-one-creditwise/id1008234539?mt=8&uo=4</a>
**App Version:** 1.11.0
**Seller:** Capital One Services, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/capital-one/id339644101?uo=4">© Capital One</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/c7/3b/1c/c73b1c85-899d-70fd-7bc4-4cb79219dec4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37878801-c809fc30-306e-11e8-8bfe-f0cc7fe4b84c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/37878801-c809fc30-306e-11e8-8bfe-f0cc7fe4b84c.png)
https://user-images.githubusercontent.com/2068130/37878801-c809fc30-306e-11e8-8bfe-f0cc7fe4b84c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/37878809-d607e392-306e-11e8-86d2-33426fc451fa.png
