### ISSUE TITLE
Nwsty: Skim Top News Headlines

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9713]
**App Name:** Nwsty: Skim Top News Headlines
**Bundle ID:** com.instancea.nwsty
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1239262949">1239262949</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nwsty-skim-top-news-headlines/id1239262949?mt=8&uo=4">https://itunes.apple.com/us/app/nwsty-skim-top-news-headlines/id1239262949?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Instance A
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/instance-a/id1045359492?uo=4">© Instance A</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple118/v4/a5/0c/d4/a50cd4ea-874e-1dca-d7cc-70324fd8d9f6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/37916121-5734c8c0-311b-11e8-97ff-265dd89bba32.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37916121-5734c8c0-311b-11e8-97ff-265dd89bba32.png)
https://user-images.githubusercontent.com/20930745/37916121-5734c8c0-311b-11e8-97ff-265dd89bba32.png

Source:
https://user-images.githubusercontent.com/20930745/37916143-6a30c366-311b-11e8-88df-9775ef539869.png
