### ISSUE TITLE
Headlines: Live Breaking News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9714]
**App Name:** Headlines: Live Breaking News
**Bundle ID:** com.doapps.1d147e7672c3a382a3d8bac253993c23
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=446531039">446531039</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/headlines-live-breaking-news/id446531039?mt=8&uo=4">https://itunes.apple.com/us/app/headlines-live-breaking-news/id446531039?mt=8&uo=4</a>
**App Version:** 4.29.260035701
**Seller:** doapp, inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/doapp-inc/id284819107?uo=4">© doapp, inc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/62/fb/b5/62fbb5ce-75fa-3b2d-0f18-645278b461c0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/37916385-001e15fe-311c-11e8-878f-6d5f7ac5846f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37916385-001e15fe-311c-11e8-878f-6d5f7ac5846f.png)
https://user-images.githubusercontent.com/20930745/37916385-001e15fe-311c-11e8-878f-6d5f7ac5846f.png

Source:
https://user-images.githubusercontent.com/20930745/37916410-0f7e8330-311c-11e8-91ae-faf9316a59a4.png
