### ISSUE TITLE
Bundle News: Breaking & Local

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9715]
**App Name:** Bundle News: Breaking & Local
**Bundle ID:** co.dwarfplanet.bundle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=830521905">830521905</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bundle-news-breaking-local/id830521905?uo=4">https://apps.apple.com/us/app/bundle-news-breaking-local/id830521905?uo=4</a>
**App Version:** 3.0.1
**Seller:** BUNDLE HABER BILISIM TEKNOLOJI ANONIM SIRKETI
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bundle-a-s/id1133527790?uo=4">© Bundle A.S.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/67/52/74/675274aa-9157-8251-7cbd-9f029796d017/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85212352-26ed5680-b352-11ea-9ad5-c0379f13d2e7.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/37916616-98a88af2-311c-11e8-8191-c726ca1e2542.png)
https://user-images.githubusercontent.com/20930745/37916616-98a88af2-311c-11e8-8191-c726ca1e2542.png

Source:
https://user-images.githubusercontent.com/20930745/37916637-a862e60e-311c-11e8-924c-41d00b156e25.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Bundle News: Breaking & Local
**Bundle ID:** co.dwarfplanet.bundle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=830521905">830521905</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/bundle-news-breaking-local/id830521905?uo=4">https://apps.apple.com/us/app/bundle-news-breaking-local/id830521905?uo=4</a>
**App Version:** 3.0.1
**Seller:** BUNDLE HABER BILISIM TEKNOLOJI ANONIM SIRKETI
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/bundle-a-s/id1133527790?uo=4">© Bundle A.S.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/67/52/74/675274aa-9157-8251-7cbd-9f029796d017/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85212352-26ed5680-b352-11ea-9ad5-c0379f13d2e7.png)
https://user-images.githubusercontent.com/2068130/85212352-26ed5680-b352-11ea-9ad5-c0379f13d2e7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85212361-366c9f80-b352-11ea-923f-05c3e08c6d8c.png
