### ISSUE TITLE
Reminder: Widget+

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9716]
**App Name:** Reminder: Widget+
**Bundle ID:** jeeeyul.ReminderPlus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=953906381">953906381</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/reminder-widget/id953906381?mt=8&uo=4">https://itunes.apple.com/us/app/reminder-widget/id953906381?mt=8&uo=4</a>
**App Version:** 1.7.4
**Seller:** Jeeeyul Lee
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jeeeyul-lee/id917932611?uo=4">© Jeeeyul Lee</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/6f/ad/90/6fad90a2-1fe4-f564-0935-ac7aefcb55e6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38038077-77d382fc-32aa-11e8-8d9c-cd40841a412d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38038077-77d382fc-32aa-11e8-8d9c-cd40841a412d.png)
https://user-images.githubusercontent.com/20930745/38038077-77d382fc-32aa-11e8-8d9c-cd40841a412d.png

Source:
https://user-images.githubusercontent.com/20930745/38038103-8a65dd70-32aa-11e8-8d45-344783274093.png
