### ISSUE TITLE
SmileyChat

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9717]
**App Name:** Smileychat
**Bundle ID:** chat.smiley.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1291473386">1291473386</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smileychat/id1291473386?mt=8&uo=4">https://itunes.apple.com/us/app/smileychat/id1291473386?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** Monkey Squad, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/monkey/id1165924248?uo=4">© Monkey</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple128/v4/ed/26/78/ed2678b3-c058-b1a1-dffe-148ad0fc3b5b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38130742-85efbb3e-3404-11e8-8e8e-ac4e2ff80a25.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38130742-85efbb3e-3404-11e8-8e8e-ac4e2ff80a25.png)
https://user-images.githubusercontent.com/2068130/38130742-85efbb3e-3404-11e8-8e8e-ac4e2ff80a25.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38130757-93da6ed8-3404-11e8-83c2-cb3e5c9bc04b.png
