### ISSUE TITLE
Plants vs. Zombies™

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9718]
**App Name:** Plants vs. Zombies™
**Bundle ID:** com.ea.pvzfree.bv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=893677096">893677096</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/plants-vs-zombies/id893677096?mt=8&uo=4">https://itunes.apple.com/us/app/plants-vs-zombies/id893677096?mt=8&uo=4</a>
**App Version:** 2.2.0
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/electronic-arts/id284800461?mt=8&uo=4">© Electronic Arts</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple62/v4/24/d3/7d/24d37da6-4e80-cb9b-f49b-3ea0cd13ff7b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38130331-df8518a8-3402-11e8-9a39-3968d5f8e3df.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38130331-df8518a8-3402-11e8-9a39-3968d5f8e3df.png)
https://user-images.githubusercontent.com/2068130/38130331-df8518a8-3402-11e8-9a39-3968d5f8e3df.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38130341-f24c6af4-3402-11e8-915c-022a174633d2.png
