### ISSUE TITLE
Plants vs. Zombies™ Heroes

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9719]
**App Name:** Plants vs. Zombies™ Heroes
**Bundle ID:** com.ea.ios.pvzheroes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1000876192">1000876192</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/plants-vs-zombies-heroes/id1000876192?mt=8&uo=4">https://itunes.apple.com/us/app/plants-vs-zombies-heroes/id1000876192?mt=8&uo=4</a>
**App Version:** 1.24.6
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/electronic-arts/id284800461?mt=8&uo=4">© Electronic Arts</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/79/a1/5e/79a15e8f-ffdc-8ed1-65c3-8105d2fd979c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38134228-5e840eb6-3412-11e8-9cac-61ee19e060a3.png)

**Comment by dreamnet** [comment]
??
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38134228-5e840eb6-3412-11e8-9cac-61ee19e060a3.png)
https://user-images.githubusercontent.com/2068130/38134228-5e840eb6-3412-11e8-9cac-61ee19e060a3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38134247-70f440a2-3412-11e8-8738-1070ac8867c0.png
