### ISSUE TITLE
YouTube TV

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9720]
**App Name:** YouTube TV
**Bundle ID:** com.google.ios.youtubeunplugged
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1193350206">1193350206</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/youtube-tv/id1193350206?mt=8&uo=4">https://itunes.apple.com/us/app/youtube-tv/id1193350206?mt=8&uo=4</a>
**App Version:** 2.02.8
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/google-inc/id281956209?uo=4">© Google, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple128/v4/58/38/8f/58388fd5-aa95-5a01-0d83-4e1d23bffbd1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38134352-e3a4a11e-3412-11e8-8d3e-22a656b135fe.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38134352-e3a4a11e-3412-11e8-8d3e-22a656b135fe.png)
https://user-images.githubusercontent.com/2068130/38134352-e3a4a11e-3412-11e8-8d3e-22a656b135fe.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38134358-f35e5c08-3412-11e8-9010-0eedc867cb7b.png
