### ISSUE TITLE
Virtual Communications Express Mobile

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9721]
**App Name:** Virtual Communications Express Mobile
**Bundle ID:** com.verizon.vce
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=602731350">602731350</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/virtual-communications-express-mobile/id602731350?mt=8&uo=4">https://itunes.apple.com/us/app/virtual-communications-express-mobile/id602731350?mt=8&uo=4</a>
**App Version:** 21.2.60
**Seller:** Verizon Wireless
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/verizon-wireless/id411772703?uo=4">© Verizon Wireless</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple69/v4/60/03/1c/60031c7c-dcf9-e198-6f92-6f00f42a7efa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38134466-81293f12-3413-11e8-81fd-6157d202f261.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38134466-81293f12-3413-11e8-81fd-6157d202f261.png)
https://user-images.githubusercontent.com/2068130/38134466-81293f12-3413-11e8-81fd-6157d202f261.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38134474-8f0a0ab2-3413-11e8-9201-a7f76fcb87df.png
