### ISSUE TITLE
Minecraft

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9723]
**App Name:** Minecraft
**Bundle ID:** com.mojang.minecraftpe
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=479516143">479516143</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/minecraft/id479516143?mt=8&uo=4">https://itunes.apple.com/us/app/minecraft/id479516143?mt=8&uo=4</a>
**App Version:** 1.2.11
**Seller:** Mojang AB
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mojang/id479516146?uo=4">© Mojang</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple118/v4/eb/42/af/eb42af5f-8098-65ce-41f8-871d012f068a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38162677-eefe7f52-34e5-11e8-9c3c-c5206c710eac.png)

**Comment by Christian9901** [comment]
https://github.com/glasklart/hd/issues/1998

Issue deleted and game needs rename and new icon

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38162677-eefe7f52-34e5-11e8-9c3c-c5206c710eac.png)
https://user-images.githubusercontent.com/2068130/38162677-eefe7f52-34e5-11e8-9c3c-c5206c710eac.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38162682-ff863fc2-34e5-11e8-8f1d-e986aa3bec14.png
