### ISSUE TITLE
Babies"R"Us Registry

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9724]
**App Name:** Babies"R"Us Registry
**Bundle ID:** com.toysrus.BRU
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=423686072">423686072</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/babies-r-us-registry/id423686072?mt=8&uo=4">https://itunes.apple.com/us/app/babies-r-us-registry/id423686072?mt=8&uo=4</a>
**App Version:** 7.3
**Seller:** Toys "R" Us Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/toys-r-us/id399532781?uo=4">© Toys"R"Us</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/4c/3f/20/4c3f20c7-50f2-2090-4846-83bcb6ed5b2d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38161089-8ec0ac7c-34c8-11e8-86a3-4d68dd4eb3e5.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38161089-8ec0ac7c-34c8-11e8-86a3-4d68dd4eb3e5.png)
https://user-images.githubusercontent.com/2068130/38161089-8ec0ac7c-34c8-11e8-86a3-4d68dd4eb3e5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38161092-9dcf9e94-34c8-11e8-86ff-284b5b4415ec.png
