### ISSUE TITLE
Play Chaser

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9725]
**App Name:** Play Chaser
**Bundle ID:** com.toysrus.playchaser
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1289322826">1289322826</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/play-chaser/id1289322826?mt=8&uo=4">https://itunes.apple.com/us/app/play-chaser/id1289322826?mt=8&uo=4</a>
**App Version:** 1.0.17
**Seller:** Toys "R" Us Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/toys-r-us/id399532781?uo=4">© Toys"R"Us</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/47/b1/a4/47b1a414-5ceb-aeb8-83c5-d6d39665a47b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38171397-67181bd4-3599-11e8-8fa9-191d761be21d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38171397-67181bd4-3599-11e8-8fa9-191d761be21d.png)
https://user-images.githubusercontent.com/2068130/38171397-67181bd4-3599-11e8-8fa9-191d761be21d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38171403-78095f84-3599-11e8-982e-e4e359a1af4d.png
