### ISSUE TITLE
Chuck E. Cheese's

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9726]
**App Name:** Chuck E. Cheese's
**Bundle ID:** com.cec.morecheese
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1348047714">1348047714</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chuck-e-cheeses/id1348047714?mt=8&uo=4">https://itunes.apple.com/us/app/chuck-e-cheeses/id1348047714?mt=8&uo=4</a>
**App Version:** 1.1.7
**Seller:** CEC Entertainment, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/chuck-e-cheeses/id615095509?uo=4">© Chuck E. Cheese’s</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple128/v4/03/3f/36/033f3624-b870-a052-aa0c-7b987dd08546/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38165881-2dce9868-351b-11e8-8c36-6818dad88335.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38165881-2dce9868-351b-11e8-8c36-6818dad88335.png)
https://user-images.githubusercontent.com/2068130/38165881-2dce9868-351b-11e8-8c36-6818dad88335.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38165886-3d542424-351b-11e8-98b5-234c207b6fc5.png
