### ISSUE TITLE
Worlds of Fun

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9727]
**App Name:** Worlds of Fun
**Bundle ID:** com.accesso.WorldsOfFun
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=527266478">527266478</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/worlds-of-fun/id527266478?mt=8&uo=4">https://itunes.apple.com/us/app/worlds-of-fun/id527266478?mt=8&uo=4</a>
**App Version:** 4.2.6
**Seller:** Cedar Fair L.P.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/cedar-fair/id971385486?uo=4">© Cedar Fair</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple122/v4/27/cd/bf/27cdbfea-3100-04cb-4b77-75277661b20e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38160758-f8c87af6-34c2-11e8-8798-7273012d9f9c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38160758-f8c87af6-34c2-11e8-8798-7273012d9f9c.png)
https://user-images.githubusercontent.com/2068130/38160758-f8c87af6-34c2-11e8-8798-7273012d9f9c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38160767-08ae28e4-34c3-11e8-9a86-53ca9da76376.png
