### ISSUE TITLE
Silver Dollar City

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9728]
**App Name:** Silver Dollar City
**Bundle ID:** com.silverdollarcity.parkguide
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1195477151">1195477151</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/silver-dollar-city/id1195477151?mt=8&uo=4">https://itunes.apple.com/us/app/silver-dollar-city/id1195477151?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Herschend Family Entertainment Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/herschend-family-entertainment-corporation/id638752384?uo=4">© Herschend Family Entertainment Corporation</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple128/v4/cd/b9/9e/cdb99e66-91a1-41c3-c76f-90213558a8fa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/38176175-cd7fc424-35af-11e8-9393-e4d6995031e1.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/3090247/38176175-cd7fc424-35af-11e8-9393-e4d6995031e1.png)
https://user-images.githubusercontent.com/3090247/38176175-cd7fc424-35af-11e8-9393-e4d6995031e1.png
-- ---
Source
![com silverdollarcity parkguide](https://user-images.githubusercontent.com/3090247/38176183-edcd8356-35af-11e8-9d6a-4669319e47e0.png)
