### ISSUE TITLE
VidCon 2018

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9729]
**App Name:** VidCon 2018
**Bundle ID:** com.vidcon.conference
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=890603641">890603641</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vidcon-2018/id890603641?mt=8&uo=4">https://itunes.apple.com/us/app/vidcon-2018/id890603641?mt=8&uo=4</a>
**App Version:** 8.0
**Seller:** VidCon Admin
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vidcon-admin/id1276635146?uo=4">© VidCon Admin</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple118/v4/0f/fb/bf/0ffbbffa-e90b-ff8d-ef7e-983a14275e63/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38160632-5c27e0ca-34c1-11e8-8568-a349d4c2948d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38160632-5c27e0ca-34c1-11e8-8568-a349d4c2948d.png)
https://user-images.githubusercontent.com/2068130/38160632-5c27e0ca-34c1-11e8-8568-a349d4c2948d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38160629-3f18e2ae-34c1-11e8-83e5-bda5ce77691c.png
