### ISSUE TITLE
Piazza

### ISSUE THREAD

**Issue by zairex** [glasklart/hd#973]
**App Name:** Piazza
**Bundle ID:** com.piazza.Piazza
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=453142230">453142230</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/piazza/id453142230?mt=8&uo=4">https://itunes.apple.com/us/app/piazza/id453142230?mt=8&uo=4</a>
**App Version:** 4.0.14.2
**Seller:** Piazzza, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/piazza-technologies-inc./id453142233?uo=4>© Piazza Technologies, Inc.</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple41/v4/bf/72/e5/bf72e5fe-0408-04a6-52bf-c89f37a74d6e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411565/99d0091c-9304-11e6-8e45-ecc248cfe4c6.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411565/99d0091c-9304-11e6-8e45-ecc248cfe4c6.png)
https://cloud.githubusercontent.com/assets/20930745/19411565/99d0091c-9304-11e6-8e45-ecc248cfe4c6.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411572/aa0212b2-9304-11e6-93c5-16d68a0376d7.png
