### ISSUE TITLE
Garfield - StickerTap

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9730]
**App Name:** Garfield - StickerTap
**Bundle ID:** com.globalresources.garfieldstickertap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1152970623">1152970623</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/garfield-stickertap/id1152970623?mt=8&uo=4">https://itunes.apple.com/us/app/garfield-stickertap/id1152970623?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Global Resources & Associates Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/global-resources/id494854258?uo=4">© Global Resources</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/3d/12/d7/3d12d771-8894-32c3-b416-67c9c7bd5438/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38171168-14be7f22-3594-11e8-8f73-552c27ef2088.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38171168-14be7f22-3594-11e8-8f73-552c27ef2088.png)
https://user-images.githubusercontent.com/2068130/38171168-14be7f22-3594-11e8-8f73-552c27ef2088.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38171170-23752458-3594-11e8-9472-ead45153875f.png
