### ISSUE TITLE
PUBG MOBILE

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9733]
**App Name:** PUBG MOBILE
**Bundle ID:** com.tencent.ig
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1330123889">1330123889</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pubg-mobile/id1330123889?mt=8&uo=4">https://itunes.apple.com/us/app/pubg-mobile/id1330123889?mt=8&uo=4</a>
**App Version:** 0.3.3
**Seller:** Tencent Mobile International Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tencent-mobile-international-limited/id504515421?uo=4">© Tencent Mobile International Limited</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple128/v4/0f/b7/14/0fb7144d-5f7f-2f0b-11b3-9b52c98ed4d3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38734263-30c973c6-3f25-11e8-888c-75b98036e19e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38734263-30c973c6-3f25-11e8-888c-75b98036e19e.png)
https://user-images.githubusercontent.com/20930745/38734263-30c973c6-3f25-11e8-888c-75b98036e19e.png

Source:
https://user-images.githubusercontent.com/20930745/38734278-4124f768-3f25-11e8-8eab-aee7fe6e710f.png
