### ISSUE TITLE
The Themes - Theme maker for your iDevice

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9734]
**App Name:** The Themes - Theme maker for your iDevice
**Bundle ID:** com.CIStatusBarScreen
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=870478952">870478952</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/the-themes-theme-maker-for-your-idevice/id870478952?mt=8&uo=4">https://itunes.apple.com/us/app/the-themes-theme-maker-for-your-idevice/id870478952?mt=8&uo=4</a>
**App Version:** 2.4
**Seller:** Bern Hoani
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bern-hoani/id1201630136?uo=4">© Bern Hoani</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple91/v4/61/e6/d5/61e6d508-da56-a53c-d4f5-503ee59f5f0d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39865010-da2ddc28-544b-11e8-942a-c397fdcee909.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39865010-da2ddc28-544b-11e8-942a-c397fdcee909.png)
https://user-images.githubusercontent.com/2068130/39865010-da2ddc28-544b-11e8-942a-c397fdcee909.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39865035-e92706aa-544b-11e8-8905-6a1d8e05c140.png
