### ISSUE TITLE
Art.com

### ISSUE THREAD

**Issue by Christian9901** [glasklart/hd#9735]
**App Name:** Art.com
**Bundle ID:** com.art.arthome
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1275654918">1275654918</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/art-com/id1275654918?uo=4">https://apps.apple.com/us/app/art-com/id1275654918?uo=4</a>
**App Version:** 2.6.3
**Seller:** Art.com, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/art-com-inc/id348423907?uo=4">© Art.com, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/2e/66/fa/2e66fa15-ce10-dfde-695e-b64dbd98ea62/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979032-a979f380-95e2-11e9-8d75-062a812da3cd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38288202-84527c70-37cf-11e8-90f1-ee39472df402.png)
https://user-images.githubusercontent.com/2068130/38288202-84527c70-37cf-11e8-90f1-ee39472df402.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38288209-92efedbc-37cf-11e8-8ec6-c8b1bb5fa097.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/59979032-a979f380-95e2-11e9-8d75-062a812da3cd.png)
https://user-images.githubusercontent.com/2068130/59979032-a979f380-95e2-11e9-8d75-062a812da3cd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/59979042-b991d300-95e2-11e9-9f0f-54c84d4584ed.png
