### ISSUE TITLE
Remote Drive for Mac - Pro

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9739]
**App Name:** Remote Drive for Mac - Pro
**Bundle ID:** com.cherpake.remote.usb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1095142462">1095142462</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/remote-drive-for-mac-pro/id1095142462?uo=4">https://apps.apple.com/us/app/remote-drive-for-mac-pro/id1095142462?uo=4</a>
**App Version:** 2020.2
**Seller:** Evgeny Cherpak
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/evgeny-cherpak/id619088610?uo=4">© Evgeny Cherpak</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/d1/04/74/d1047488-5240-f6f5-123b-30d349ac36c6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74556119-947d1680-4f5d-11ea-9fdb-eb9bca796547.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38452256-afbf84fc-3a40-11e8-9470-be89cd29e8ba.png)
https://user-images.githubusercontent.com/20930745/38452256-afbf84fc-3a40-11e8-9470-be89cd29e8ba.png

Source:
https://user-images.githubusercontent.com/20930745/38452260-c230d96a-3a40-11e8-9f33-e766de1af101.png

**Comment by l8er4now** [comment]
Needs an update

**App Name:** Remote Drive & File Browser
**Bundle ID:** com.cherpake.remote.usb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1095142462">1095142462</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/remote-drive-file-browser/id1095142462?uo=4">https://apps.apple.com/us/app/remote-drive-file-browser/id1095142462?uo=4</a>
**App Version:** 6.0.4
**Seller:** Evgeny Cherpak
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/evgeny-cherpak/id619088610?uo=4">© Evgeny Cherpak</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/05/02/db/0502db69-8252-b93e-3d0c-bbef9fab7376/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/64032326-802d9480-cb4a-11e9-84d4-00fd38f91a48.png)
https://user-images.githubusercontent.com/2068130/64032326-802d9480-cb4a-11e9-84d4-00fd38f91a48.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/64032352-8facdd80-cb4a-11e9-8c06-3f05b6ddeba5.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Remote Drive for Mac - Pro
**Bundle ID:** com.cherpake.remote.usb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1095142462">1095142462</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/remote-drive-for-mac-pro/id1095142462?uo=4">https://apps.apple.com/us/app/remote-drive-for-mac-pro/id1095142462?uo=4</a>
**App Version:** 2020.2
**Seller:** Evgeny Cherpak
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/evgeny-cherpak/id619088610?uo=4">© Evgeny Cherpak</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/d1/04/74/d1047488-5240-f6f5-123b-30d349ac36c6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/74556119-947d1680-4f5d-11ea-9fdb-eb9bca796547.png)
(https://user-images.githubusercontent.com/20930745/74556119-947d1680-4f5d-11ea-9fdb-eb9bca796547.png

Source:
https://user-images.githubusercontent.com/20930745/74556123-95ae4380-4f5d-11ea-805a-ff1a93bb10b7.png
