### ISSUE TITLE
Collect: Save and share ideas

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9740]
**App Name:** Collect: Save and share ideas
**Bundle ID:** com.wetransfer.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=765359021">765359021</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/collect-save-and-share-ideas/id765359021?uo=4">https://apps.apple.com/us/app/collect-save-and-share-ideas/id765359021?uo=4</a>
**App Version:** 5.1.0
**Seller:** WeTransfer BV
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wetransfer-bv/id485103881?uo=4">© WeTransfer BV</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/5b/e0/f6/5be0f65d-ba91-8ff1-df4a-bb179e5d4df7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85228280-e5f15280-b3e2-11ea-8c99-95746d54b387.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38452183-3b058b44-3a3f-11e8-8c5a-e21078c3c369.png)
https://user-images.githubusercontent.com/20930745/38452183-3b058b44-3a3f-11e8-8c5a-e21078c3c369.png

Source:
https://user-images.githubusercontent.com/20930745/38452186-4c40e21e-3a3f-11e8-9c1d-9208a0a2f54e.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Collect: Save and share ideas
**Bundle ID:** com.wetransfer.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=765359021">765359021</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/collect-save-and-share-ideas/id765359021?uo=4">https://apps.apple.com/us/app/collect-save-and-share-ideas/id765359021?uo=4</a>
**App Version:** 5.1.0
**Seller:** WeTransfer BV
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/wetransfer-bv/id485103881?uo=4">© WeTransfer BV</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/5b/e0/f6/5be0f65d-ba91-8ff1-df4a-bb179e5d4df7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85228280-e5f15280-b3e2-11ea-8c99-95746d54b387.png)
https://user-images.githubusercontent.com/2068130/85228280-e5f15280-b3e2-11ea-8c99-95746d54b387.png
--- ---
https://user-images.githubusercontent.com/2068130/85228292-f99cb900-b3e2-11ea-8580-2262c7d7923e.png
