### ISSUE TITLE
Elgato Eve

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9741]
**App Name:** Elgato Eve
**Bundle ID:** com.elgato.eve
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=917695792">917695792</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/elgato-eve/id917695792?mt=8&uo=4">https://itunes.apple.com/us/app/elgato-eve/id917695792?mt=8&uo=4</a>
**App Version:** 3.1.1
**Seller:** Elgato Systems GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/elgato-systems/id329886714?uo=4">© Elgato Systems</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/76/18/08/761808d4-acb4-a9b1-1fcf-9845c3541f6b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38452158-983f569c-3a3e-11e8-9bf7-0c1661201724.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38452158-983f569c-3a3e-11e8-9bf7-0c1661201724.png)
https://user-images.githubusercontent.com/20930745/38452158-983f569c-3a3e-11e8-9bf7-0c1661201724.png

Source:
https://user-images.githubusercontent.com/20930745/38452163-acb8d2c4-3a3e-11e8-92e9-5a1cb2f5841d.png
