### ISSUE TITLE
Pulse­

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9742]
**App Name:** Pulse­
**Bundle ID:** asklausen.pulseapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1318538015">1318538015</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pulse/id1318538015?mt=8&uo=4">https://itunes.apple.com/us/app/pulse/id1318538015?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Anders Klausen
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/anders-klausen/id514428244?uo=4">© Anders Klausen</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/c7/87/8f/c7878f7a-7a4c-e7fb-52a2-0aa9c9308ba6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43989586-18f15e7c-9d4d-11e8-924e-e1331b48888a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38452122-01f98ff4-3a3e-11e8-9d69-b0a6139a79e1.png)
https://user-images.githubusercontent.com/20930745/38452122-01f98ff4-3a3e-11e8-9d69-b0a6139a79e1.png

Source:
https://user-images.githubusercontent.com/20930745/38452126-116fc5de-3a3e-11e8-9cc2-fb867b4a4799.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Pulse­
**Bundle ID:** asklausen.pulseapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1318538015">1318538015</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pulse/id1318538015?mt=8&uo=4">https://itunes.apple.com/us/app/pulse/id1318538015?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Anders Klausen
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/anders-klausen/id514428244?uo=4">© Anders Klausen</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/c7/87/8f/c7878f7a-7a4c-e7fb-52a2-0aa9c9308ba6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43989586-18f15e7c-9d4d-11e8-924e-e1331b48888a.png)
https://user-images.githubusercontent.com/2068130/43989586-18f15e7c-9d4d-11e8-924e-e1331b48888a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43989588-26dda0ea-9d4d-11e8-9b3b-e1024127044e.png
