### ISSUE TITLE
HeadOut

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9743]
**App Name:** HeadOut
**Bundle ID:** punya.TimeToLeave
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1353684013">1353684013</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/headout/id1353684013?mt=8&uo=4">https://itunes.apple.com/us/app/headout/id1353684013?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Punya Chatterjee
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/punya-chatterjee/id1287859425?uo=4">© Punya Chatterjee</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/73/b8/d6/73b8d69f-681f-ffb1-345c-4fb5eb63b7d0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38452044-c30928a6-3a3b-11e8-9057-ff06cd1968d1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38452012-f40c08d4-3a3a-11e8-832d-f5713f1bc0dc.png)
https://user-images.githubusercontent.com/20930745/38452012-f40c08d4-3a3a-11e8-832d-f5713f1bc0dc.png

Source:
https://user-images.githubusercontent.com/20930745/38452016-089c0934-3a3b-11e8-85fd-d0f79755cbfa.png
