### ISSUE TITLE
Calculator HD Pro Lite

### ISSUE THREAD

**Issue by dreamnet** [glasklart/hd#9744]
**App Name:** Calculator HD Pro Lite
**Bundle ID:** com.cidersoftware.CalculatorFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=571121141">571121141</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/calculator-hd-pro-lite/id571121141?mt=8&uo=4">https://itunes.apple.com/us/app/calculator-hd-pro-lite/id571121141?mt=8&uo=4</a>
**App Version:** 3.7.1
**Seller:** Cider Software LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/cider-software-llc/id465180756?uo=4">© Cider Software LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/3b/fb/c0/3bfbc088-19a2-75ae-4b94-ae45ae54dd06/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38452099-73e57f34-3a3d-11e8-8879-183c5a864175.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/20930745/38452099-73e57f34-3a3d-11e8-8879-183c5a864175.png)
https://user-images.githubusercontent.com/20930745/38452099-73e57f34-3a3d-11e8-8879-183c5a864175.png

Source:
https://user-images.githubusercontent.com/20930745/38452103-877b88cc-3a3d-11e8-8731-2f4298eb57f6.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 
There is no need for the extra `/` in `![](http://preview.dreamnet.at?image=`. 😄

**Comment by 2Qt2beStr8** [comment]
i do only  copy and paste from the wiki :-)

Notice the first part will not change for any preview you create:
![](http://preview.dreamnet.at/?image=

**Comment by dreamnet** [comment]
@2Qt2beStr8 Oooos - I corrected the WIKI.
Normally, you should use
`![](http://preview.dreamnet.at?image=`
--- ---
`![](http://preview.dreamnet.at/?image=`
does also work (because the server can handle it), but it's better without the `/`.
