### ISSUE TITLE
Mein Schiff 5 Bordfinder

### ISSUE THREAD

**Issue by victorlobe** [glasklart/hd#9747]
**App Name:** Mein Schiff 5 Bordfinder
**Bundle ID:** com.victorlobe.meinschiff5
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1329062330">1329062330</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mein-schiff-5-bordfinder/id1329062330?mt=8&uo=4">https://itunes.apple.com/us/app/mein-schiff-5-bordfinder/id1329062330?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Victor Lobe
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/victor-lobe/id1175461065?uo=4">© Victor Lobe</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/ff/b6/a8/ffb6a8b2-edc9-122a-da86-aad511e4199f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38469337-80e69d96-3b53-11e8-8801-9d2b2ef32d3a.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38469337-80e69d96-3b53-11e8-8801-9d2b2ef32d3a.png)
https://user-images.githubusercontent.com/20930745/38469337-80e69d96-3b53-11e8-8801-9d2b2ef32d3a.png

Source:
https://user-images.githubusercontent.com/20930745/38469345-965ba19e-3b53-11e8-871b-b32dfc36f216.png

**Comment by victorlobe** [comment]
Perfect, thanks! ✌️
