### ISSUE TITLE
Screeny 2.0

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9748]
**App Name:** Screeny 2.0
**Bundle ID:** com.nfnlabs.screeny
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=941121450">941121450</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/screeny-2-0/id941121450?mt=8&uo=4">https://itunes.apple.com/us/app/screeny-2-0/id941121450?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** ThreeSea Technologies Private Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/threesea-technologies-private-limited/id522070015?uo=4">© ThreeSea Technologies Private Limited</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/5e/5d/54/5e5d54c1-89d7-61fd-2f80-5d02464dc00a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38469275-673e0af6-3b52-11e8-9758-2967962cd859.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38469275-673e0af6-3b52-11e8-9758-2967962cd859.png)
https://user-images.githubusercontent.com/20930745/38469275-673e0af6-3b52-11e8-9758-2967962cd859.png

Source:
https://user-images.githubusercontent.com/20930745/38469279-796eae60-3b52-11e8-9bd8-9dc2d0a8c5f2.png
