### ISSUE TITLE
Effects Studio

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9749]
**App Name:** Effects Studio
**Bundle ID:** com.bezeaud.effects
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=780467456">780467456</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/effects-studio/id780467456?mt=8&uo=4">https://itunes.apple.com/us/app/effects-studio/id780467456?mt=8&uo=4</a>
**App Version:** 4.4.5
**Seller:** Claude Bezeaud
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/claude-bezeaud/id500254221?uo=4">© Claude Bezeaud</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/87/1f/fe/871ffee2-41e0-0621-74cb-94b5b5592283/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38470993-49350924-3b6b-11e8-8bca-78259c18ded0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38469246-ba772398-3b51-11e8-8949-d34587f00d88.png)
https://user-images.githubusercontent.com/20930745/38469246-ba772398-3b51-11e8-8949-d34587f00d88.png

Source:
https://user-images.githubusercontent.com/20930745/38469250-d084a048-3b51-11e8-8620-93e7bd2706b8.png

**Comment by dreamnet** [comment]
Hmmm... what about inverting this? 🤔

**Comment by 2Qt2beStr8** [comment]
like this?
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38470993-49350924-3b6b-11e8-8bca-78259c18ded0.png)
https://user-images.githubusercontent.com/20930745/38470993-49350924-3b6b-11e8-8bca-78259c18ded0.png

Source:
https://user-images.githubusercontent.com/20930745/38470996-5fc977ec-3b6b-11e8-9d89-5126100a83b3.png

**Comment by dreamnet** [comment]
Yes, I think that's better. 👍
