### ISSUE TITLE
Camera RX

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9750]
**App Name:** Camera RX
**Bundle ID:** com.nutractor.CameraRX
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1200513619">1200513619</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/camera-rx/id1200513619?mt=8&uo=4">https://itunes.apple.com/us/app/camera-rx/id1200513619?mt=8&uo=4</a>
**App Version:** 3.4
**Seller:** NUTRACTOR
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nutractor/id305620719?uo=4">© NUTRACTOR</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/6e/98/f0/6e98f03e-ab61-e668-292e-f3ad1e613565/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38508008-56379f8e-3c1e-11e8-8ffe-586151632a91.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38508008-56379f8e-3c1e-11e8-8ffe-586151632a91.png)
https://user-images.githubusercontent.com/20930745/38508008-56379f8e-3c1e-11e8-8ffe-586151632a91.png

Source:
https://user-images.githubusercontent.com/20930745/38508038-6720fdae-3c1e-11e8-9a03-d05fdc1f1f4d.png
