### ISSUE TITLE
SmartThings (Samsung Connect)

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9758]
**App Name:** SmartThings (Samsung Connect)
**Bundle ID:** com.samsung.oneconnect4ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1222822904">1222822904</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smartthings-samsung-connect/id1222822904?mt=8&uo=4">https://itunes.apple.com/us/app/smartthings-samsung-connect/id1222822904?mt=8&uo=4</a>
**App Version:** 1.6.02
**Seller:** Samsung Electronics
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/samsung-electronics-co-ltd/id359580642?uo=4">© Samsung Electronics CO.LTD.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/12/d7/93/12d79322-5682-f75b-0b85-33412b496393/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38626063-1c6ff370-3dac-11e8-8855-9eae979ba198.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38626063-1c6ff370-3dac-11e8-8855-9eae979ba198.png)
https://user-images.githubusercontent.com/20930745/38626063-1c6ff370-3dac-11e8-8855-9eae979ba198.png

Source:
https://user-images.githubusercontent.com/20930745/38626095-2b3403b0-3dac-11e8-9063-8f8b59ed2227.png
