### ISSUE TITLE
Swatches: Live Color Picker

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9759]
**App Name:** Swatches: Live Color Picker
**Bundle ID:** com.campoli.Swatches
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=964993762">964993762</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/swatches-live-color-picker/id964993762?mt=8&uo=4">https://itunes.apple.com/us/app/swatches-live-color-picker/id964993762?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Andrew Campoli
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/andrew-campoli/id963594345?uo=4">© Andrew Campoli</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/84/ed/99/84ed990f-51a8-e179-8342-5f8cddfa12fa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38627741-faae859a-3daf-11e8-8e04-c56e9dbd63fd.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38627741-faae859a-3daf-11e8-8e04-c56e9dbd63fd.png)
https://user-images.githubusercontent.com/20930745/38627741-faae859a-3daf-11e8-8e04-c56e9dbd63fd.png

Source:
https://user-images.githubusercontent.com/20930745/38627764-08d237ca-3db0-11e8-8b60-31f0e8e8b244.png
