### ISSUE TITLE
12up - Sports News & Scores

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9761]
**App Name:** 12up - Sports News & Scores
**Bundle ID:** com.90min.ussport
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1085058666">1085058666</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/12up-sports-news-scores/id1085058666?mt=8&uo=4">https://itunes.apple.com/us/app/12up-sports-news-scores/id1085058666?mt=8&uo=4</a>
**App Version:** 6.3.2
**Seller:** Sportority Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ftbpro/id600808584?uo=4">© FTBpro</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/b7/20/2d/b7202d2c-e0ab-c82c-11fe-bf5bb67a3535/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38627107-7713dd26-3dae-11e8-9cd4-17dea4de28f1.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38627107-7713dd26-3dae-11e8-9cd4-17dea4de28f1.png)
https://user-images.githubusercontent.com/20930745/38627107-7713dd26-3dae-11e8-9cd4-17dea4de28f1.png

Source:
https://user-images.githubusercontent.com/20930745/38627127-86c52432-3dae-11e8-902a-0f6dc54bec50.png
