### ISSUE TITLE
Chase Mobile

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9762]
**App Name:** Chase Mobile
**Bundle ID:** com.chase.prodipad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=370697773">370697773</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/chase-mobile/id370697773?mt=8&uo=4">https://itunes.apple.com/us/app/chase-mobile/id370697773?mt=8&uo=4</a>
**App Version:** 3.651
**Seller:** JPMorgan Chase Bank, NA
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/jpmorgan-chase-co/id298867250?uo=4">© JPMorgan Chase & Co.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/c1/18/ff/c118ff84-c934-7343-740e-535230bf297d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38765637-191d6dee-3fc6-11e8-8282-86659dc90409.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38765637-191d6dee-3fc6-11e8-8282-86659dc90409.png)
https://user-images.githubusercontent.com/2068130/38765637-191d6dee-3fc6-11e8-8282-86659dc90409.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38765642-27e005c6-3fc6-11e8-8e48-be3e1801e35b.png
