### ISSUE TITLE
Visual Anatomy Lite

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9763]
**App Name:** Visual Anatomy Lite
**Bundle ID:** com.HSSN.VisAnatomyLite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=523422151">523422151</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/visual-anatomy-lite/id523422151?mt=8&uo=4">https://itunes.apple.com/us/app/visual-anatomy-lite/id523422151?mt=8&uo=4</a>
**App Version:** 4.6
**Seller:** YingLiang Ma
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/education-mobile/id519530928?uo=4">© Education Mobile</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/51/4a/23/514a23a4-487b-7303-9a8a-8bd2d033c054/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38767854-c17087ec-3fe9-11e8-9eb5-b708753e8d98.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38767854-c17087ec-3fe9-11e8-9eb5-b708753e8d98.png)
https://user-images.githubusercontent.com/2068130/38767854-c17087ec-3fe9-11e8-9eb5-b708753e8d98.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38767858-d675e088-3fe9-11e8-88e2-7e4c6ecf088a.png
