### ISSUE TITLE
Ext3nder Installer

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9764]
**App Name:** Ext3nder Installer
**Bundle ID:** com.cydia.Ext3nder
**Version:** 16.7
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/38765483-b8671106-3fc2-11e8-910d-4ea84515bca6.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38766147-2fc4f744-3fce-11e8-9620-88c1e7e97b06.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38766147-2fc4f744-3fce-11e8-9620-88c1e7e97b06.png)
https://user-images.githubusercontent.com/2068130/38766147-2fc4f744-3fce-11e8-9620-88c1e7e97b06.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38766149-3dee1d14-3fce-11e8-87d6-2cee021d94c3.png

**Comment by Sly-Fi** [comment]
I found when I added the icon manually to my iPad that I got the bundle name wrong in my request - needed to change the "e" to uppercase to make it work.  Should be

com.cydia.Ext3nder
