### ISSUE TITLE
ERV travel & care

### ISSUE THREAD

**Issue by 2Qt2beStr8** [glasklart/hd#9766]
**App Name:** ERV travel & care
**Bundle ID:** com.erv.travelandcare
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1086577504">1086577504</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/erv-travel-care/id1086577504?uo=4">https://apps.apple.com/us/app/erv-travel-care/id1086577504?uo=4</a>
**App Version:** 5.4.0
**Seller:** Europaeische Reiseversicherung AG
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/europaeische-reiseversicherung-ag/id1086577503?uo=4">© Europaeische Reiseversicherung AG</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/07/f3/03/07f303e4-ea50-3c71-93dd-03ba0acaf5c3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60389851-b35f9300-9ac9-11e9-9772-409d769f56c3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38767827-44772908-3fe9-11e8-8f7a-8c75d1892367.png)
https://user-images.githubusercontent.com/20930745/38767827-44772908-3fe9-11e8-8f7a-8c75d1892367.png

Source:
https://user-images.githubusercontent.com/20930745/38767834-5663932c-3fe9-11e8-9086-71eeba62b24d.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60389851-b35f9300-9ac9-11e9-9772-409d769f56c3.png)
https://user-images.githubusercontent.com/2068130/60389851-b35f9300-9ac9-11e9-9772-409d769f56c3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60389853-c5413600-9ac9-11e9-9628-736d617b0692.png
