### ISSUE TITLE
Tesla

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9768]
**App Name:** Tesla
**Bundle ID:** com.teslamotors.TeslaApp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=582007913">582007913</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tesla/id582007913?mt=8&uo=4">https://itunes.apple.com/us/app/tesla/id582007913?mt=8&uo=4</a>
**App Version:** 3.3.5
**Seller:** Tesla, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/tesla-inc/id582007916?uo=4">© Tesla, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/d0/ea/05/d0ea0529-0a45-a58a-9cf7-0dd2e1ddddf5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38778981-192311de-40c2-11e8-9713-e390739ae8c1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/38778981-192311de-40c2-11e8-9713-e390739ae8c1.png)
https://user-images.githubusercontent.com/20930745/38778981-192311de-40c2-11e8-9713-e390739ae8c1.png)

Source:
https://user-images.githubusercontent.com/20930745/38778984-32a9c92c-40c2-11e8-90d8-dd23e3a77e79.png
