### ISSUE TITLE
Multi Web Browser

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9773]
**App Name:** Multi Web Browser
**Bundle ID:** de.chronocore.multiwebview
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=431398698">431398698</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/multi-web-browser/id431398698?mt=8&uo=4">https://itunes.apple.com/us/app/multi-web-browser/id431398698?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Stefan Kogler
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/stefan-kogler/id327939697?uo=4">© Stefan Kogler</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/aa/ff/8e/aaff8ee4-c098-b25f-37d2-beab3e1c89a9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39097554-19ca71d0-465e-11e8-812e-462e61cd8c62.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39097554-19ca71d0-465e-11e8-812e-462e61cd8c62.png)
https://user-images.githubusercontent.com/20930745/39097554-19ca71d0-465e-11e8-812e-462e61cd8c62.png

Source:
https://user-images.githubusercontent.com/20930745/39097557-29df5860-465e-11e8-9081-d28bb0a87228.png
