### ISSUE TITLE
Weather Hippie: Alerts, Radar

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9774]
**App Name:** Weather Hippie: Alerts, Radar
**Bundle ID:** com.sandhu.Weather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1274367210">1274367210</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/weather-hippie-alerts-radar/id1274367210?mt=8&uo=4">https://itunes.apple.com/us/app/weather-hippie-alerts-radar/id1274367210?mt=8&uo=4</a>
**App Version:** 1.849
**Seller:** Harminder Sandhu
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/harminder-sandhu/id1139488180?uo=4">© Harminder Sandhu</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/47/3d/67/473d6714-1726-25a3-bfc3-9a7a09364f61/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39097721-7c28756e-4660-11e8-8ad8-581215447848.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39097721-7c28756e-4660-11e8-8ad8-581215447848.png)
https://user-images.githubusercontent.com/20930745/39097721-7c28756e-4660-11e8-8ad8-581215447848.png

Source:
https://user-images.githubusercontent.com/20930745/39097724-8d145730-4660-11e8-98a8-8d03a7de4798.png
