### ISSUE TITLE
Type Nine - T9 Keyboard

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9777]
**App Name:** Type Nine - T9 Keyboard
**Bundle ID:** com.porsager.TypeNine
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=926008509">926008509</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/type-nine-t9-keyboard/id926008509?mt=8&uo=4">https://itunes.apple.com/us/app/type-nine-t9-keyboard/id926008509?mt=8&uo=4</a>
**App Version:** 2.2.3
**Seller:** Rasmus Porsager
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/rasmus-porsager/id926008508?uo=4">© Rasmus Porsager</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple111/v4/3a/15/56/3a1556b3-9ad7-50e6-4d90-350fe5efdbfa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39097923-652b5766-4663-11e8-99c1-100affc2bd9c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39097923-652b5766-4663-11e8-99c1-100affc2bd9c.png)
https://user-images.githubusercontent.com/20930745/39097923-652b5766-4663-11e8-99c1-100affc2bd9c.png

Source:
https://user-images.githubusercontent.com/20930745/39097932-874d286a-4663-11e8-8282-a8fc7f19d54b.png
