### ISSUE TITLE
Live Keyboard Plus

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9778]
**App Name:** Live Keyboard Plus
**Bundle ID:** com.keyboardplus.KeyboardPlus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=945409522">945409522</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/live-keyboard-plus/id945409522?mt=8&uo=4">https://itunes.apple.com/us/app/live-keyboard-plus/id945409522?mt=8&uo=4</a>
**App Version:** 1.5.2
**Seller:** Ivan Starchenkov
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ivan-starchenkov/id328195084?uo=4">© Ivan Starchenkov</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/c0/ff/e4/c0ffe454-9f72-ae10-ada5-85ad8aa5dbfd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39141267-98102f2a-4727-11e8-95dc-03f1ea7ed4c9.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39141135-1e0fb272-4727-11e8-9142-718d3f2df198.png)
https://user-images.githubusercontent.com/20930745/39141135-1e0fb272-4727-11e8-9142-718d3f2df198.png

Source:
https://user-images.githubusercontent.com/20930745/39141164-3505a3f6-4727-11e8-9382-deaa7f7d669c.png
