### ISSUE TITLE
Copies 2

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9779]
**App Name:** Copies 2
**Bundle ID:** com.lkmake.ios.copies
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1225014382">1225014382</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/copies-2/id1225014382?mt=8&uo=4">https://itunes.apple.com/us/app/copies-2/id1225014382?mt=8&uo=4</a>
**App Version:** 2.0.3
**Seller:** Kai Luo
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kai-luo/id344176636?uo=4">© Kai Luo</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/a4/5f/dc/a45fdc32-c939-2850-b3e1-fad01ba2c6be/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39141935-7dfc0b20-4729-11e8-8d75-f902a7a72b05.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39141935-7dfc0b20-4729-11e8-8d75-f902a7a72b05.png)
https://user-images.githubusercontent.com/20930745/39141935-7dfc0b20-4729-11e8-8d75-f902a7a72b05.png

Source:
https://user-images.githubusercontent.com/20930745/39141952-8bd3bde2-4729-11e8-9f53-530a730ab545.png
