### ISSUE TITLE
Moxie Classic

### ISSUE THREAD

**Issue by zairex** [glasklart/hd#978]
**App Name:** Moxie Classic
**Bundle ID:** com.yourcompany.MoxieFree
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=309662269">309662269</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/moxie-classic/id309662269?mt=8&uo=4">https://itunes.apple.com/us/app/moxie-classic/id309662269?mt=8&uo=4</a>
**App Version:** 2.2.1
**Seller:** Blue Ox Family Games, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/blue-ox-family-games-inc/id288074001?uo=4">© Blue Ox Family Games, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple91/v4/17/76/07/1776076f-2617-62fe-834b-0c348d05fbf4/source/1024x1024bb.jpg" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32693362-29225c96-c72a-11e7-9b1e-ad85204465d5.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/32693362-29225c96-c72a-11e7-9b1e-ad85204465d5.png)
https://user-images.githubusercontent.com/2068130/32693362-29225c96-c72a-11e7-9b1e-ad85204465d5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/32693364-383b1cae-c72a-11e7-8a41-6e2b058a6822.png
