### ISSUE TITLE
WatchAid TV Show Planner

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9780]
**App Name:** WatchAid TV Show Planner
**Bundle ID:** tv.watchaid.apple
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1098010920">1098010920</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/watchaid-tv-show-planner/id1098010920?mt=8&uo=4">https://itunes.apple.com/us/app/watchaid-tv-show-planner/id1098010920?mt=8&uo=4</a>
**App Version:** 1.6.5
**Seller:** ReVeNG System
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/reveng-system/id1098010919?uo=4">© ReVeNG System</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/42/c8/12/42c81293-2425-27a2-c747-6392ddccafb2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![tv watchaid apple-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39106954-254ed3fa-46bf-11e8-8c33-63308ac6ca11.png)

**Comment by dreamnet** [comment]
![tv watchaid apple-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39106954-254ed3fa-46bf-11e8-8c33-63308ac6ca11.png)
https://user-images.githubusercontent.com/2068130/39106954-254ed3fa-46bf-11e8-8c33-63308ac6ca11.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39106960-3428c192-46bf-11e8-8d46-429a985ccecd.png
