### ISSUE TITLE
Dual Radar Widget -- NOAA SuperRes Weather Radar, Warnings and Forecasts

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9781]
**App Name:** Dual Radar Widget -- NOAA SuperRes Weather Radar, Warnings and Forecasts
**Bundle ID:** com.shuksansoft.radarusdual
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=827141249">827141249</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dual-radar-widget-noaa-superres-weather-radar-warnings/id827141249?mt=8&uo=4">https://itunes.apple.com/us/app/dual-radar-widget-noaa-superres-weather-radar-warnings/id827141249?mt=8&uo=4</a>
**App Version:** 1.2.3
**Seller:** Shuksan Software, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/shuksan-software-llc/id415411642?uo=4">© Shuksan Software, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple30/v4/45/47/d5/4547d57a-19fd-77c4-9097-f82a1194b9bd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39107213-136e4920-46c1-11e8-8866-e910198ea867.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39107213-136e4920-46c1-11e8-8866-e910198ea867.png)
https://user-images.githubusercontent.com/2068130/39107213-136e4920-46c1-11e8-8866-e910198ea867.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39107221-221a9168-46c1-11e8-9bb7-e05ed615e898.png
