### ISSUE TITLE
Taskade - Checklist & Outliner

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9782]
**App Name:** Taskade - Checklist & Outliner
**Bundle ID:** com.taskade.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1264713923">1264713923</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/taskade-checklist-outliner/id1264713923?mt=8&uo=4">https://itunes.apple.com/us/app/taskade-checklist-outliner/id1264713923?mt=8&uo=4</a>
**App Version:** 1.1.0
**Seller:** Taskcade Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/taskcade-inc/id1264713922?uo=4">© Taskcade Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/dd/4e/29/dd4e29c9-6818-ef16-d3db-8680e3d56519/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39107146-8845f532-46c0-11e8-96e0-ab5de86975b9.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39107146-8845f532-46c0-11e8-96e0-ab5de86975b9.png)
https://user-images.githubusercontent.com/2068130/39107146-8845f532-46c0-11e8-96e0-ab5de86975b9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39107154-97d28b50-46c0-11e8-95c6-b9d9646901c9.png
