### ISSUE TITLE
Expedition Atlantis

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#9783]
**App Name:** Expedition Atlantis
**Bundle ID:** com.Robomatter.ExpeditionAtlantis
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=853307500">853307500</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/expedition-atlantis/id853307500?mt=8&uo=4">https://itunes.apple.com/us/app/expedition-atlantis/id853307500?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Robomatter Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/robomatter-inc/id853307503?uo=4">© Robomatter Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple2/v4/ff/bc/b8/ffbcb8d4-45bd-5620-964c-dc1c7b1b12c2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39385139-85396dbc-4a6f-11e8-9649-cfdad69d858a.png)

**Comment by dreamnet** [comment]
❓ 
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39385139-85396dbc-4a6f-11e8-9649-cfdad69d858a.png)
https://user-images.githubusercontent.com/2068130/39385139-85396dbc-4a6f-11e8-9649-cfdad69d858a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39385153-98d88182-4a6f-11e8-81a9-2269a79ef107.png
