### ISSUE TITLE
MINDSTORMS EV3 LEGO® Education

### ISSUE THREAD

**Issue by Mitchdog27** [glasklart/hd#9784]
**App Name:** MINDSTORMS EV3 LEGO® Education
**Bundle ID:** com.lego.education.ev3
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=959374369">959374369</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mindstorms-ev3-lego-education/id959374369?mt=8&uo=4">https://itunes.apple.com/us/app/mindstorms-ev3-lego-education/id959374369?mt=8&uo=4</a>
**App Version:** 1.11.1
**Seller:** LEGO Education
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lego-education/id708170734?uo=4">© LEGO Education</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/aa/9a/86/aa9a86ad-dccf-6641-4194-e255618b128c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39379875-ed32601c-4a5c-11e8-8486-f5d8d3cefcf1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39379672-549fb002-4a5c-11e8-8bf6-d36f8a51a0f9.png)
https://user-images.githubusercontent.com/2068130/39379672-549fb002-4a5c-11e8-8bf6-d36f8a51a0f9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39379693-644c09c4-4a5c-11e8-9785-971457e23d0c.png
