### ISSUE TITLE
GolfLogix GPS + Putt Breaks

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9785]
**App Name:** GolfLogix GPS + Putt Breaks
**Bundle ID:** com.golfgps.golflogix
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=322399059">322399059</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/golflogix-gps-putt-breaks/id322399059?mt=8&uo=4">https://itunes.apple.com/us/app/golflogix-gps-putt-breaks/id322399059?mt=8&uo=4</a>
**App Version:** 5.3.5
**Seller:** GolfLogix, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/golflogix-inc/id322399062?uo=4">© GolfLogix, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/46/fe/f2/46fef253-f7d9-92ad-783a-e9bd1ad0490d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39107058-f42cf508-46bf-11e8-8917-c3a714b824a4.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39107058-f42cf508-46bf-11e8-8917-c3a714b824a4.png)
https://user-images.githubusercontent.com/2068130/39107058-f42cf508-46bf-11e8-8917-c3a714b824a4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39107067-0456f50a-46c0-11e8-9521-cb5ac024ce41.png
