### ISSUE TITLE
Scanner App – Wordscanner pro

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9786]
**App Name:** Scanner App – Wordscanner pro
**Bundle ID:** com.ws.SHScan
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=525343444">525343444</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/scanner-app-wordscanner-pro/id525343444?mt=8&uo=4">https://itunes.apple.com/us/app/scanner-app-wordscanner-pro/id525343444?mt=8&uo=4</a>
**App Version:** 3.4.18
**Seller:** Xiamen Worldscan Information Technology Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/xiamen-worldscan-information-technology-co-ltd/id463430010?uo=4">© Xiamen Worldscan Information Technology Co., Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/0c/91/a2/0c91a265-9fbc-be22-cf4c-1bf33d31aa20/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39198728-10661df2-47e8-11e8-94db-e7bc40bdd6be.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39198728-10661df2-47e8-11e8-94db-e7bc40bdd6be.png)
https://user-images.githubusercontent.com/20930745/39198728-10661df2-47e8-11e8-94db-e7bc40bdd6be.png

Source:
https://user-images.githubusercontent.com/20930745/39198749-2173b1b8-47e8-11e8-8bba-7cd98898777d.png
