### ISSUE TITLE
MLB Perfect Inning 2018

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9787]
**App Name:** MLB Perfect Inning 2018
**Bundle ID:** com.gamevilusa.mlbpilive.ios.apple.global.normal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1203069334">1203069334</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mlb-perfect-inning-2018/id1203069334?mt=8&uo=4">https://itunes.apple.com/us/app/mlb-perfect-inning-2018/id1203069334?mt=8&uo=4</a>
**App Version:** 2.0.2
**Seller:** GAMEVIL USA, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/gamevil-usa-inc/id299302366?uo=4">© GAMEVIL USA, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/de/dc/0c/dedc0cfd-88fb-25b6-de7f-8ab48a974006/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39383848-16b6336a-4a6b-11e8-9b73-ed4d1dcd1144.png)

**Comment by dreamnet** [comment]
❓ 
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39383848-16b6336a-4a6b-11e8-9b73-ed4d1dcd1144.png)
https://user-images.githubusercontent.com/2068130/39383848-16b6336a-4a6b-11e8-9b73-ed4d1dcd1144.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39383876-2b3507ee-4a6b-11e8-85e1-95ccb0ae9589.png
