### ISSUE TITLE
Gin Rummy Plus - Card Game

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9789]
**App Name:** Gin Rummy Plus - Card Game
**Bundle ID:** net.peakgames.ginrummyplus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1068095192">1068095192</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gin-rummy-plus-card-game/id1068095192?mt=8&uo=4">https://itunes.apple.com/us/app/gin-rummy-plus-card-game/id1068095192?mt=8&uo=4</a>
**App Version:** 3.8.8
**Seller:** Zynga Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/zynga-inc/id295913422?mt=8&uo=4">© Zynga Inc.</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/0a/5b/06/0a5b06cc-848a-54ce-d899-30c0190a0721/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39286907-db4f0ac2-4920-11e8-897b-67483128107e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39286907-db4f0ac2-4920-11e8-897b-67483128107e.png)
https://user-images.githubusercontent.com/2068130/39286907-db4f0ac2-4920-11e8-897b-67483128107e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39286923-e9de8d6a-4920-11e8-8853-4a822e92bce1.png
