### ISSUE TITLE
Bubble Island 2: Fruit Shooter

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9790]
**App Name:** Bubble Island 2: Fruit Shooter
**Bundle ID:** net.wooga.bubbleisland2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1147195439">1147195439</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bubble-island-2-fruit-shooter/id1147195439?mt=8&uo=4">https://itunes.apple.com/us/app/bubble-island-2-fruit-shooter/id1147195439?mt=8&uo=4</a>
**App Version:** 1.36.17
**Seller:** wooga gmbh
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wooga/id461402737?uo=4">© wooga</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/b9/6a/e6/b96ae610-1873-3437-bcc2-3ff4c32a5349/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39382902-7e4b5374-4a67-11e8-8d9c-b0b817fb4b36.png)

**Comment by dreamnet** [comment]
❓ 
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39382902-7e4b5374-4a67-11e8-8d9c-b0b817fb4b36.png)
https://user-images.githubusercontent.com/2068130/39382902-7e4b5374-4a67-11e8-8d9c-b0b817fb4b36.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39382915-8d98b902-4a67-11e8-80e2-3d142a61d2bc.png
