### ISSUE TITLE
Google Tasks: Get Things Done

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9792]
**App Name:** Google Tasks: Get Things Done
**Bundle ID:** com.google.tasks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1353634006">1353634006</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/google-tasks-get-things-done/id1353634006?mt=8&uo=4">https://itunes.apple.com/us/app/google-tasks-get-things-done/id1353634006?mt=8&uo=4</a>
**App Version:** 1.0.180426
**Seller:** Google, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/google-inc/id281956209?uo=4">© Google, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/81/3c/5e/813c5e4f-c37b-885b-b5ab-bc27c08a12e6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39397836-fb67306e-4b05-11e8-8768-7e13948d0008.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/39397836-fb67306e-4b05-11e8-8768-7e13948d0008.png)
https://user-images.githubusercontent.com/20930745/39397836-fb67306e-4b05-11e8-8768-7e13948d0008.png

https://user-images.githubusercontent.com/20930745/39397845-0dfc89ae-4b06-11e8-8139-d8c1e9723b68.png
