### ISSUE TITLE
Burst for reddit

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9797]
**App Name:** Burst for reddit
**Bundle ID:** io.burstapp.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1303179128">1303179128</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/burst-for-reddit/id1303179128?mt=8&uo=4">https://itunes.apple.com/us/app/burst-for-reddit/id1303179128?mt=8&uo=4</a>
**App Version:** 1.13
**Seller:** Alex Duckmanton
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/alex-duckmanton/id1016159000?uo=4">© Alex Duckmanton</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/5a/93/30/5a93307c-9257-a2d1-03e5-b00e8b2dbb02/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/40269697-7d3d8f3e-5b82-11e8-92ad-9ad6f3b7bba0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/40269697-7d3d8f3e-5b82-11e8-92ad-9ad6f3b7bba0.png)
https://user-images.githubusercontent.com/20930745/40269697-7d3d8f3e-5b82-11e8-92ad-9ad6f3b7bba0.png

Source:
https://user-images.githubusercontent.com/20930745/40269701-89c7295e-5b82-11e8-99da-00a795ce656a.png
