### ISSUE TITLE
Current - Music Video & Radio

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9799]
**App Name:** Current - Music Video & Radio
**Bundle ID:** com.nativ.current
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1213495204">1213495204</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/current-music-video-radio/id1213495204?mt=8&uo=4">https://itunes.apple.com/us/app/current-music-video-radio/id1213495204?mt=8&uo=4</a>
**App Version:** 2.1.5
**Seller:** Current Media LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/current-media-llc/id1213495203?uo=4">© Current Media LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple125/v4/cc/c3/c7/ccc3c7d1-ecc4-1555-acd5-b071b6992d09/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/40199175-f2b35b42-5a18-11e8-915a-efbbb2824bae.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/40199175-f2b35b42-5a18-11e8-915a-efbbb2824bae.png)
https://user-images.githubusercontent.com/20930745/40199175-f2b35b42-5a18-11e8-915a-efbbb2824bae.png

Source:
https://user-images.githubusercontent.com/20930745/40199196-03c56f06-5a19-11e8-9607-26a24feae523.png
