### ISSUE TITLE
Neighbors by Ring

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9801]
**App Name:** Neighbors by Ring
**Bundle ID:** com.ring.neighborhoods
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1218902777">1218902777</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/neighbors-by-ring/id1218902777?mt=8&uo=4">https://itunes.apple.com/us/app/neighbors-by-ring/id1218902777?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** Bot Home Automation, INC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ring-com/id926252660?uo=4">© Ring.com</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple115/v4/7b/4a/58/7b4a588a-067a-a7a0-b173-18551b80886e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/40197947-41f70338-5a15-11e8-9341-be2a18389f7b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/40197947-41f70338-5a15-11e8-9341-be2a18389f7b.png)
https://user-images.githubusercontent.com/20930745/40197947-41f70338-5a15-11e8-9341-be2a18389f7b.png

Source:
https://user-images.githubusercontent.com/20930745/40197976-574b098c-5a15-11e8-9319-27b8234704ef.png
