### ISSUE TITLE
Padlet

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9802]
**App Name:** Padlet
**Bundle ID:** com.wallwisher.Padlet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=834618886">834618886</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/padlet/id834618886?mt=8&uo=4">https://itunes.apple.com/us/app/padlet/id834618886?mt=8&uo=4</a>
**App Version:** 57.0
**Seller:** Wallwisher, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/wallwisher-inc/id834618889?uo=4">© Wallwisher, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple125/v4/d3/da/54/d3da5471-59aa-63b6-79f3-d07a1225cb87/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/40588276-5fde4e7e-61db-11e8-8497-9cbddee4e7f8.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/40588276-5fde4e7e-61db-11e8-8497-9cbddee4e7f8.png)
https://user-images.githubusercontent.com/2068130/40588276-5fde4e7e-61db-11e8-8497-9cbddee4e7f8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/40588281-6f0280d2-61db-11e8-97e1-3b46ef57f202.png
