### ISSUE TITLE
Shop: delivery & order tracker

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9803]
**App Name:** Shop: delivery & order tracker
**Bundle ID:** com.jadedlabs.arrive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1223471316">1223471316</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/shop-delivery-order-tracker/id1223471316?uo=4">https://apps.apple.com/us/app/shop-delivery-order-tracker/id1223471316?uo=4</a>
**App Version:** 2.0.1
**Seller:** Shopify Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/shopify-inc/id371294475?uo=4">© Shopify Inc.</a>
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/5d/b5/28/5db52861-c438-1648-803c-2894fa5a1044/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/81197917-288cd600-8fc1-11ea-80f1-3f4dd58c7991.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/40588233-9ca0d328-61da-11e8-824c-a174fc7cf718.png)
https://user-images.githubusercontent.com/2068130/40588233-9ca0d328-61da-11e8-824c-a174fc7cf718.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/40588235-aaa311d4-61da-11e8-92db-62805884d1eb.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Shop: delivery & order tracker
**Bundle ID:** com.jadedlabs.arrive
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1223471316">1223471316</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/shop-delivery-order-tracker/id1223471316?uo=4">https://apps.apple.com/us/app/shop-delivery-order-tracker/id1223471316?uo=4</a>
**App Version:** 2.0.0
**Seller:** Shopify Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/shopify-inc/id371294475?uo=4">© Shopify Inc.</a>
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/ab/f7/c6/abf7c6f7-bc55-28cd-9549-02a6aa8bc152/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/81197917-288cd600-8fc1-11ea-80f1-3f4dd58c7991.png)
https://user-images.githubusercontent.com/2068130/81197917-288cd600-8fc1-11ea-80f1-3f4dd58c7991.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/81197977-393d4c00-8fc1-11ea-8e14-a943954a60b8.png

**Comment by popitre** [comment]
icon does not update with bundle id renaming ?

**Comment by l8er4now** [comment]
> icon does not update with bundle id renaming ?

The bundle id didn’t change. I’m not sure if the updated icon is in the current published release. Did you try ssh-ing the icon to your device?
![image](https://user-images.githubusercontent.com/3704186/83982885-1a034880-a8f8-11ea-96e7-31797ad39291.jpeg)

**Comment by popitre** [comment]
> > icon does not update with bundle id renaming ?
> 
> The bundle id didn’t change. I’m not sure if the updated icon is in the current published release. Did you try ssh-ing the icon to your device?
> ![image](https://user-images.githubusercontent.com/3704186/83982885-1a034880-a8f8-11ea-96e7-31797ad39291.jpeg)

yes I saved the new icon on Dropbox, then cut it on device with Filza and renaming com.jadedlabs.arrive@2x. However, after respring, the old Arrive app icon still appears.

**Comment by l8er4now** [comment]
That’s not the naming convention for the icons, it’s **BundleID-large** I’m assume you put it in the right folder? You should be replacing the current, if you didn’t replace it, it’s not going to work. 

com.jadedlabs.arrive-large.png

**Comment by popitre** [comment]
> That’s not the naming convention for the icons, it’s **BundleID-large** I’m assume you put it in the right folder? You should be replacing the current, if you didn’t replace it, it’s not going to work. 
> 
> com.jadedlabs.arrive-large.png

Why does @2x work for every other icon?

**Comment by dreamnet** [comment]
@popitre All Glasklart icons are 180x180px (@3x). We use -large since a long time, it covers all image sizes. 
https://github.com/glasklart/hd/blob/d5d34825b02da47663f76ed4b2b435e9ae0d2fde/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.jadedlabs.arrive-large.png

**Comment by popitre** [comment]
> @popitre All Glasklart icons are 180x180px (@3x). We use -large since a long time, it covers all image sizes. 
> 
> https://github.com/glasklart/hd/blob/d5d34825b02da47663f76ed4b2b435e9ae0d2fde/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.jadedlabs.arrive-large.png

You might want to update how to on the home page, thanks.

**Comment by dreamnet** [comment]
@popitre Ah, yes, thanks!
