### ISSUE TITLE
Action Network Sports Betting

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9804]
**App Name:** Action Network Sports Betting
**Bundle ID:** com.sportsactioninc.action
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1083677479">1083677479</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/action-network-sports-betting/id1083677479?uo=4">https://apps.apple.com/us/app/action-network-sports-betting/id1083677479?uo=4</a>
**App Version:** 3.2.1
**Seller:** The Action Network, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/the-action-network-inc/id1083677478?uo=4">© The Action Network, Inc.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/31/d0/6b/31d06bd5-3d09-a79e-c5f3-e614665bcbf8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73665914-3bca9580-46a2-11ea-8785-734ea5b025c0.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/40588172-c824c686-61d9-11e8-9e28-cb6f30157184.png)
https://user-images.githubusercontent.com/2068130/40588172-c824c686-61d9-11e8-9e28-cb6f30157184.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/40588179-d647a792-61d9-11e8-9da0-a15b394dd3a5.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Action Network Sports Betting
**Bundle ID:** com.sportsactioninc.action
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1083677479">1083677479</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/action-network-sports-betting/id1083677479?uo=4">https://apps.apple.com/us/app/action-network-sports-betting/id1083677479?uo=4</a>
**App Version:** 3.2.1
**Seller:** The Action Network, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/the-action-network-inc/id1083677478?uo=4">© The Action Network, Inc.</a>
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/31/d0/6b/31d06bd5-3d09-a79e-c5f3-e614665bcbf8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/73665914-3bca9580-46a2-11ea-8785-734ea5b025c0.png)
https://user-images.githubusercontent.com/20930745/73665914-3bca9580-46a2-11ea-8785-734ea5b025c0.png

Source:
https://user-images.githubusercontent.com/20930745/73665917-3cfbc280-46a2-11ea-972f-2a933fd52b94.png
