### ISSUE TITLE
Garmin Drive

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9810]
**App Name:** Garmin Drive
**Bundle ID:** com.garmin.gecko
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1276198893">1276198893</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/garmin-drive/id1276198893?uo=4">https://apps.apple.com/us/app/garmin-drive/id1276198893?uo=4</a>
**App Version:** 4.05.31
**Seller:** Garmin International
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/garmin/id411046952?uo=4">© Garmin</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/85/ad/c1/85adc182-eae0-302f-0848-56281b48b57b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59295771-c4fd0a00-8c84-11e9-9776-a5b794a78b08.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41168979-c7c16a56-6b47-11e8-8f6f-07128e37c36b.png)
https://user-images.githubusercontent.com/2068130/41168979-c7c16a56-6b47-11e8-8f6f-07128e37c36b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41168994-d7378308-6b47-11e8-8cdf-20d278603430.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Garmin Drive
**Bundle ID:** com.garmin.gecko
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1276198893">1276198893</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/garmin-drive/id1276198893?uo=4">https://apps.apple.com/us/app/garmin-drive/id1276198893?uo=4</a>
**App Version:** 4.05.31
**Seller:** Garmin International
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/garmin/id411046952?uo=4">© Garmin</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/85/ad/c1/85adc182-eae0-302f-0848-56281b48b57b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/59295771-c4fd0a00-8c84-11e9-9776-a5b794a78b08.png)
https://user-images.githubusercontent.com/20930745/59295771-c4fd0a00-8c84-11e9-9776-a5b794a78b08.png

Source:
https://user-images.githubusercontent.com/20930745/59295774-c62e3700-8c84-11e9-93d3-6f554266d022.png
