### ISSUE TITLE
Virtual Wallet

### ISSUE THREAD

**Issue by zairex** [glasklart/hd#982]
**App Name:** Virtual Wallet
**Bundle ID:** com.PNC.VirtualWallet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=323876167">323876167</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/virtual-wallet/id323876167?mt=8&uo=4">https://itunes.apple.com/us/app/virtual-wallet/id323876167?mt=8&uo=4</a>
**App Version:** 5.1.1
**Seller:** PNC Bank, N.A.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/pnc-bank-n.a./id303113130?uo=4>© PNC Bank, N.A.</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple41/v4/cb/c3/35/cbc33597-1842-763d-acc2-d10737d0683d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411479/cd162e84-9302-11e6-8d5b-bde97e81fa2b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19411479/cd162e84-9302-11e6-8d5b-bde97e81fa2b.png)
https://cloud.githubusercontent.com/assets/20930745/19411479/cd162e84-9302-11e6-8d5b-bde97e81fa2b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19411489/f2049d66-9302-11e6-9f68-faedfed8edd3.png
