### ISSUE TITLE
Microsoft News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9821]
**App Name:** Microsoft News
**Bundle ID:** com.microsoft.axp-ios.BingNews
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=945416273">945416273</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/microsoft-news/id945416273?mt=8&uo=4">https://itunes.apple.com/us/app/microsoft-news/id945416273?mt=8&uo=4</a>
**App Version:** 3.2
**Seller:** Microsoft Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/microsoft-corporation/id298856275?uo=4">© Microsoft Corporation</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple115/v4/78/fe/19/78fe19eb-fac4-767b-d321-afc589c4f05c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41805908-3d1adc36-76b2-11e8-90b3-0cfd2566a0bf.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41805908-3d1adc36-76b2-11e8-90b3-0cfd2566a0bf.png)
https://user-images.githubusercontent.com/2068130/41805908-3d1adc36-76b2-11e8-90b3-0cfd2566a0bf.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41805911-4b847764-76b2-11e8-9306-3ab50b978d80.png
