### ISSUE TITLE
Music Launcher with Widget

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9822]
**App Name:** Music Launcher with Widget
**Bundle ID:** com.cromulentlabs.MusicLauncher
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=943240815">943240815</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/music-launcher-with-widget/id943240815?mt=8&uo=4">https://itunes.apple.com/us/app/music-launcher-with-widget/id943240815?mt=8&uo=4</a>
**App Version:** 1.7.4
**Seller:** Cromulent Labs, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/cromulent-labs/id769433054?uo=4">© Cromulent Labs</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/8d/58/d9/8d58d981-6e3d-95aa-9a40-14ff11cdaf39/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/42137470-268d8b00-7d6d-11e8-9feb-890576a1ec03.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/42137470-268d8b00-7d6d-11e8-9feb-890576a1ec03.png)
https://user-images.githubusercontent.com/2068130/42137470-268d8b00-7d6d-11e8-9feb-890576a1ec03.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/42137472-34e612bc-7d6d-11e8-9457-31687cb1e7b3.png
