### ISSUE TITLE
Views • News Redesigned

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9823]
**App Name:** Views • News Redesigned
**Bundle ID:** com.SApps.Views
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1322754821">1322754821</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/views-news-redesigned/id1322754821?mt=8&uo=4">https://itunes.apple.com/us/app/views-news-redesigned/id1322754821?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Praveen Kambampati
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/praveen-kambampati/id1281197213?uo=4">© Praveen Kambampati</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/95/b0/2d/95b02dc9-2632-44dc-2886-9f61e44c8f15/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41806037-8a512020-76b5-11e8-9c8d-b627ca07cd53.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41806037-8a512020-76b5-11e8-9c8d-b627ca07cd53.png)
https://user-images.githubusercontent.com/2068130/41806037-8a512020-76b5-11e8-9c8d-b627ca07cd53.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41806041-9baf3014-76b5-11e8-9261-168b0e6b0e86.png
