### ISSUE TITLE
Garmin VIRB

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9825]
**App Name:** Garmin VIRB
**Bundle ID:** com.garmin.virb
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=723092894">723092894</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/garmin-virb/id723092894?mt=8&uo=4">https://itunes.apple.com/us/app/garmin-virb/id723092894?mt=8&uo=4</a>
**App Version:** 4.3.1
**Seller:** Garmin International
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/garmin/id411046952?uo=4">© Garmin</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/9d/8c/3a/9d8c3ac1-6102-1a80-15a6-6d0edf7402c9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![com garmin virb-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41806181-5d3ddf2a-76b9-11e8-9ea2-53507e01e6ea.png)

**Comment by dreamnet** [comment]
![com garmin virb-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41806181-5d3ddf2a-76b9-11e8-9ea2-53507e01e6ea.png)
https://user-images.githubusercontent.com/2068130/41806181-5d3ddf2a-76b9-11e8-9ea2-53507e01e6ea.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41806186-6cd4d34e-76b9-11e8-89e8-e6f692b68378.png
