### ISSUE TITLE
Gooba - Notes & Tasks

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9826]
**App Name:** Gooba - Notes & Tasks
**Bundle ID:** com.spectrcompany.gooba
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1258233354">1258233354</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gooba-notes-tasks/id1258233354?mt=8&uo=4">https://itunes.apple.com/us/app/gooba-notes-tasks/id1258233354?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Filippo Zanfini
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/filippo-zanfini/id1258233353?uo=4">© Filippo Zanfini</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/2a/5a/1b/2a5a1b85-9a00-b5e9-b9e5-5767d41395f5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45999670-9a433500-c0a6-11e8-8a2d-0c81447d8885.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/41806375-35efdec4-76bd-11e8-95e0-4c04649bdcfe.png)
https://user-images.githubusercontent.com/2068130/41806375-35efdec4-76bd-11e8-95e0-4c04649bdcfe.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/41806383-45d5e932-76bd-11e8-93c0-8fcd0f7fc3e0.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Gooba - Notes & Tasks
**Bundle ID:** com.spectrcompany.gooba
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1258233354">1258233354</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/gooba-notes-tasks/id1258233354?mt=8&uo=4">https://itunes.apple.com/us/app/gooba-notes-tasks/id1258233354?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** Filippo Zanfini
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/filippo-zanfini/id1258233353?uo=4">© Filippo Zanfini</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/31/94/6a/31946afb-7d6e-315f-88e0-1af4bafdde47/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45999670-9a433500-c0a6-11e8-8a2d-0c81447d8885.png)
https://user-images.githubusercontent.com/2068130/45999670-9a433500-c0a6-11e8-8a2d-0c81447d8885.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45999689-a9c27e00-c0a6-11e8-89e0-73e463ae4a3c.png
