### ISSUE TITLE
atudo - Navigation & Verkehr

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#9827]
**App Name:** atudo - Navigation & Verkehr
**Bundle ID:** com.atudo.pro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=933177680">933177680</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/atudo-navigation-verkehr/id933177680?mt=8&uo=4">https://itunes.apple.com/us/app/atudo-navigation-verkehr/id933177680?mt=8&uo=4</a>
**App Version:** 1.7.1
**Seller:** atudo GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/atudo-gmbh/id933177679?uo=4">© atudo GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple125/v4/51/f5/d7/51f5d733-2acf-7875-da5e-bb2d434dfcdb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43353089-7ee9dcb4-922f-11e8-9a2d-e24bc51504d8.png)

**Comment by XPEric** [comment]
![atudo](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43117751-7f46d85c-8edc-11e8-9f3f-319ec3a2738d.png)
https://user-images.githubusercontent.com/2313873/43117751-7f46d85c-8edc-11e8-9f3f-319ec3a2738d.png
___
Source:
https://user-images.githubusercontent.com/2313873/43117754-81de0ee6-8edc-11e8-815b-1f5760c0f42d.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43353089-7ee9dcb4-922f-11e8-9a2d-e24bc51504d8.png)
https://user-images.githubusercontent.com/2068130/43353089-7ee9dcb4-922f-11e8-9a2d-e24bc51504d8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43353093-8ef031f8-922f-11e8-9d5f-223e5f59dc3b.png
