### ISSUE TITLE
Flatastic - the Roommate App

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#9828]
**App Name:** Flatastic - the Roommate App
**Bundle ID:** com.flatastic.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=840810742">840810742</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flatastic-the-roommate-app/id840810742?mt=8&uo=4">https://itunes.apple.com/us/app/flatastic-the-roommate-app/id840810742?mt=8&uo=4</a>
**App Version:** 2.3.12
**Seller:** mcm.init UG (haftungsbeschraenkt)
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mcm-init-ug-haftungsbeschraenkt/id840810745?uo=4">© mcm.init UG (haftungsbeschraenkt)</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/22/b0/59/22b0599a-aeaa-90ed-b82e-b83264238bd2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43353120-673854e6-9230-11e8-9b60-3ff1a6b14761.png)

**Comment by XPEric** [comment]
![flatastic](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43318130-a012b464-916d-11e8-812f-b94915961c64.png)
https://user-images.githubusercontent.com/2313873/43318130-a012b464-916d-11e8-812f-b94915961c64.png
___
Source:
https://user-images.githubusercontent.com/2313873/43318133-a1c580ac-916d-11e8-828a-94cc385e40b6.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43353120-673854e6-9230-11e8-9b60-3ff1a6b14761.png)
https://user-images.githubusercontent.com/2068130/43353120-673854e6-9230-11e8-9b60-3ff1a6b14761.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43353124-76aee71e-9230-11e8-9232-6695ab98f3dd.png
