### ISSUE TITLE
Qriket

### ISSUE THREAD

**Issue by Expliciate** [glasklart/hd#983]
**App Name:** Qriket
**Bundle ID:** net.rt7.Qriket-Game
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=469250215">469250215</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/qriket/id469250215?mt=8&uo=4">https://itunes.apple.com/us/app/qriket/id469250215?mt=8&uo=4</a>
**App Version:** 5.9
**Seller:** RT7 Incorporated
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/the-c-factor-incorporated/id454595246?uo=4>© The C Factor Incorporated</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is3.mzstatic.com/image/thumb/Purple71/v4/f8/8f/3d/f88f3ddd-75d7-7a90-34e8-058459451694/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19851234/26e29ba8-9f5d-11e6-8757-acc39ee7b33b.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19851234/26e29ba8-9f5d-11e6-8757-acc39ee7b33b.png)
https://cloud.githubusercontent.com/assets/20930745/19851234/26e29ba8-9f5d-11e6-8757-acc39ee7b33b.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19851257/44583116-9f5d-11e6-86f8-2b8f33b40704.png
