### ISSUE TITLE
smartmobil.de Servicewelt

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#9830]
**App Name:** smartmobil.de Servicewelt
**Bundle ID:** de.smartmobil.smartmobil-Servicewelt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=850462583">850462583</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/smartmobil-de-servicewelt/id850462583?mt=8&uo=4">https://itunes.apple.com/us/app/smartmobil-de-servicewelt/id850462583?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Drillisch Aktiengesellschaft
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/drillisch-ag/id774775240?uo=4">© Drillisch AG</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple111/v4/41/4e/f5/414ef590-9a72-6ee4-0000-2423245b1324/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![smartmobil](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43117660-fb07a3aa-8edb-11e8-986a-751ade7a8ecf.png)

**Comment by XPEric** [comment]
![smartmobil](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43117660-fb07a3aa-8edb-11e8-986a-751ade7a8ecf.png)
https://user-images.githubusercontent.com/2313873/43117660-fb07a3aa-8edb-11e8-986a-751ade7a8ecf.png
___
Source:
https://user-images.githubusercontent.com/2313873/43117667-02e9cecc-8edc-11e8-9d3a-dcd57dedb20f.png
