### ISSUE TITLE
DragonSoul RPG

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#9831]
**App Name:** DragonSoul RPG
**Bundle ID:** com.perblue.dragonsoul.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1020327340">1020327340</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dragonsoul-rpg/id1020327340?mt=8&uo=4">https://itunes.apple.com/us/app/dragonsoul-rpg/id1020327340?mt=8&uo=4</a>
**App Version:** 2.20.1
**Seller:** PerBlue Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/perblue-inc/id308407512?uo=4">© PerBlue Inc</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple125/v4/b9/29/df/b929df73-b96b-c1f2-ea3d-327fe1da8df7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43989349-7617ae94-9d48-11e8-8789-692837326bd9.png)

**Comment by dreamnet** [comment]
❓ 
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43735353-af5975b6-99ba-11e8-839e-df75d10d8f5a.png)
https://user-images.githubusercontent.com/2068130/43735353-af5975b6-99ba-11e8-839e-df75d10d8f5a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43735376-be062898-99ba-11e8-9e9f-4eca965504c3.png

**Comment by Gwai** [comment]
Nice, but can you pergaps add a DS on the top right for DragonSoul?

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43989349-7617ae94-9d48-11e8-8789-692837326bd9.png)
https://user-images.githubusercontent.com/2068130/43989349-7617ae94-9d48-11e8-8789-692837326bd9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43989350-84ee4072-9d48-11e8-8e41-f57b76d17050.png

**Comment by Gwai** [comment]
😍
