### ISSUE TITLE
Samsung Gear S

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#9832]
**App Name:** Samsung Gear S
**Bundle ID:** com.samsung.gearwatch
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1117310635">1117310635</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/samsung-gear-s/id1117310635?mt=8&uo=4">https://itunes.apple.com/us/app/samsung-gear-s/id1117310635?mt=8&uo=4</a>
**App Version:** 1.6.18060502
**Seller:** Samsung Electronics
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/samsung-electronics-co-ltd/id359580642?uo=4">© Samsung Electronics CO.LTD.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/22/ed/41/22ed4115-9602-f17f-237f-d55ddcaa531d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43353200-3954deb2-9232-11e8-97ad-bea48a95ec43.png)

**Comment by XPEric** [comment]
![samsunggears](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43117540-4b2be3b0-8edb-11e8-997a-a31b7d2c0697.png)
https://user-images.githubusercontent.com/2313873/43117540-4b2be3b0-8edb-11e8-997a-a31b7d2c0697.png
___
Source:
https://user-images.githubusercontent.com/2313873/43117544-51e48716-8edb-11e8-9d46-55283cb5d12e.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43353200-3954deb2-9232-11e8-97ad-bea48a95ec43.png)
https://user-images.githubusercontent.com/2068130/43353200-3954deb2-9232-11e8-97ad-bea48a95ec43.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43353202-48280342-9232-11e8-970f-0dcdf02c7b73.png
