### ISSUE TITLE
Vipon - Save Money, Vouchers

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#9833]
**App Name:** Vipon - Save Money, Vouchers
**Bundle ID:** com.vipon.www
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1272023223">1272023223</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/vipon-save-money-vouchers/id1272023223?mt=8&uo=4">https://itunes.apple.com/us/app/vipon-save-money-vouchers/id1272023223?mt=8&uo=4</a>
**App Version:** 2.8.6
**Seller:** AMZTRACKER.COM LIMITED
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/amztracker-com-limited/id1276060167?uo=4">© AMZTRACKER.COM LIMITED</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple115/v4/2f/68/b2/2f68b27e-f4ba-8706-0845-583b00e1edd7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43353243-7a16f89e-9233-11e8-9909-ad102c17c9ea.png)

**Comment by XPEric** [comment]
![vipon](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43318497-06c2df30-916f-11e8-993e-7f28673cd770.png)
https://user-images.githubusercontent.com/2313873/43318497-06c2df30-916f-11e8-993e-7f28673cd770.png
___
Source:
https://user-images.githubusercontent.com/2313873/43318500-08583106-916f-11e8-9015-ca217b21e4e0.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43353243-7a16f89e-9233-11e8-9909-ad102c17c9ea.png)
https://user-images.githubusercontent.com/2068130/43353243-7a16f89e-9233-11e8-9909-ad102c17c9ea.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43353246-885e2166-9233-11e8-9401-87d20f7a89e9.png
