### ISSUE TITLE
Mutti

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#9835]
**App Name:** Mutti
**Bundle ID:** de.ivanto.bogestra
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1180076440">1180076440</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mutti/id1180076440?mt=8&uo=4">https://itunes.apple.com/us/app/mutti/id1180076440?mt=8&uo=4</a>
**App Version:** 4.18.5
**Seller:** GeoMobile GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/geomobile-gmbh/id322527309?uo=4">© GeoMobile GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple125/v4/f5/84/d8/f584d8df-e291-5bdd-4057-1967358b0b84/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![mutti](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43318772-1a9d1d12-9170-11e8-8d28-9bad5a9c1b86.png)

**Comment by XPEric** [comment]
![mutti](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43318772-1a9d1d12-9170-11e8-8d28-9bad5a9c1b86.png)
https://user-images.githubusercontent.com/2313873/43318772-1a9d1d12-9170-11e8-8d28-9bad5a9c1b86.png
___
Source:
https://user-images.githubusercontent.com/2313873/43318775-1f9cb976-9170-11e8-98ad-1174ba7e022f.png
