### ISSUE TITLE
PremiumSIM Servicewelt

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#9836]
**App Name:** PremiumSIM Servicewelt
**Bundle ID:** de.premiumsim.PremiumSIM-Servicewelt
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=852923779">852923779</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/premiumsim-servicewelt/id852923779?mt=8&uo=4">https://itunes.apple.com/us/app/premiumsim-servicewelt/id852923779?mt=8&uo=4</a>
**App Version:** 1.2
**Seller:** Drillisch Aktiengesellschaft
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/drillisch-ag/id774775240?uo=4">© Drillisch AG</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple3/v4/a7/8d/97/a78d97a6-ae29-832c-f930-7a2db2462b34/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43990996-104a97f4-9d64-11e8-93fb-96f7440beb9d.png)

**Comment by 2Qt2beStr8** [comment]
???
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43990481-83b7d29a-9d5c-11e8-9e0a-692de8954b2b.png)
https://user-images.githubusercontent.com/20930745/43990481-83b7d29a-9d5c-11e8-9e0a-692de8954b2b.png

Source:
https://user-images.githubusercontent.com/20930745/43990489-98bf7dfa-9d5c-11e8-93f6-9aea7a4f2906.png

**Comment by dreamnet** [comment]
Credits to @2Qt2beStr8 
Very small changes...
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43990996-104a97f4-9d64-11e8-93fb-96f7440beb9d.png)
https://user-images.githubusercontent.com/2068130/43990996-104a97f4-9d64-11e8-93fb-96f7440beb9d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43991004-1eae2d9c-9d64-11e8-8918-d64b79abdc4d.png
