### ISSUE TITLE
Die TK-App – alles im Griff

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#9837]
**App Name:** Die TK-App – alles im Griff
**Bundle ID:** de.tk.tk-app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1163694230">1163694230</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/die-tk-app-alles-im-griff/id1163694230?mt=8&uo=4">https://itunes.apple.com/us/app/die-tk-app-alles-im-griff/id1163694230?mt=8&uo=4</a>
**App Version:** 1.20
**Seller:** Techniker Krankenkasse
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/techniker-krankenkasse-tk/id355493231?uo=4">© Techniker Krankenkasse (TK)</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple115/v4/e7/ca/87/e7ca87d8-3b9b-edc8-b846-c2a8e4bd4997/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43353287-d7c02136-9234-11e8-9598-4e3c2cdd10dd.png)

**Comment by XPEric** [comment]
![dietk](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43317989-1ba7cdcc-916d-11e8-85ff-619e6556909a.png)
https://user-images.githubusercontent.com/2313873/43317989-1ba7cdcc-916d-11e8-85ff-619e6556909a.png
___
Source:
https://user-images.githubusercontent.com/2313873/43317993-1d65fa76-916d-11e8-964e-15566c94af48.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet?image=https://user-images.githubusercontent.com/2068130/43353287-d7c02136-9234-11e8-9598-4e3c2cdd10dd.png)
https://user-images.githubusercontent.com/2068130/43353287-d7c02136-9234-11e8-9598-4e3c2cdd10dd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43353290-e8ff3b12-9234-11e8-8e54-cf9f327eef85.png
