### ISSUE TITLE
Enpass Password Manager

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#9839]
**App Name:** Enpass Password Manager
**Bundle ID:** in.sinew.Walletx
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=455566716">455566716</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/enpass-password-manager/id455566716?uo=4">https://apps.apple.com/us/app/enpass-password-manager/id455566716?uo=4</a>
**App Version:** 6.1.0
**Seller:** Sinew Software Systems Private Limited
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/sinew-software-systems-private-limited/id455566719?uo=4">© Sinew Software Systems Private Limited</a>
**Supported Devices:** Watch4-Watch4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/2c/bc/9c/2cbc9c37-13bc-e2be-6e62-b67595c4bcd4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60389491-2402b180-9ac2-11e9-9f31-b92a2078ce7d.png)

**Comment by dftune** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/41047592/42568207-04cc853e-8515-11e8-85d7-be93d7abc479.png)

Source: https://user-images.githubusercontent.com/41047592/42568194-f555b47c-8514-11e8-909d-24260942440c.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43357735-79516c70-9286-11e8-9c84-83d439d0d5d4.png)
https://user-images.githubusercontent.com/2068130/43357735-79516c70-9286-11e8-9c84-83d439d0d5d4.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43357738-8794e1b8-9286-11e8-9605-26437818c825.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60389491-2402b180-9ac2-11e9-9f31-b92a2078ce7d.png)
https://user-images.githubusercontent.com/2068130/60389491-2402b180-9ac2-11e9-9f31-b92a2078ce7d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60389494-354bbe00-9ac2-11e9-9e8e-2053c535b66d.png
