### ISSUE TITLE
USB Disk Pro

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#9840]
**App Name:** USB Disk Pro
**Bundle ID:** com.imesart.USBDisk-Pro-iPad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=412591849">412591849</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/usb-disk-pro/id412591849?mt=8&uo=4">https://itunes.apple.com/us/app/usb-disk-pro/id412591849?mt=8&uo=4</a>
**App Version:** 2.6.5
**Seller:** Imesart S.a.r.l.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/imesart-s-a-r-l/id290160983?uo=4">© Imesart S.a.r.l.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple115/v4/0b/31/42/0b3142a3-f01d-e4f9-a0aa-516a5707b650/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43359698-0905d9bc-92a7-11e8-9934-01e7bfa63ba7.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43359698-0905d9bc-92a7-11e8-9934-01e7bfa63ba7.png)
https://user-images.githubusercontent.com/2068130/43359698-0905d9bc-92a7-11e8-9934-01e7bfa63ba7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43359703-186ef71c-92a7-11e8-9755-7a73681201fe.png
