### ISSUE TITLE
WerStreamt.es? Filme & Serien

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#9842]
**App Name:** WerStreamt.es? Filme & Serien
**Bundle ID:** es.werstreamt.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=948619315">948619315</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/werstreamt-es-filme-serien/id948619315?mt=8&uo=4">https://itunes.apple.com/us/app/werstreamt-es-filme-serien/id948619315?mt=8&uo=4</a>
**App Version:** 2.1.4
**Seller:** FUNKE Zeitschriften Service GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/funke-zeitschriften-service-gmbh/id1065503949?uo=4">© FUNKE Zeitschriften Service GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple115/v4/e8/93/eb/e893eb1f-92fb-d58d-1f72-d86899c29cb3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43353360-aea5518e-9236-11e8-85b6-fe942cbed9a0.png)

**Comment by XPEric** [comment]
![werstreamt](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43318641-8578b548-916f-11e8-823d-58c0d9a928cc.png)
https://user-images.githubusercontent.com/2313873/43318641-8578b548-916f-11e8-823d-58c0d9a928cc.png
___
Source:
https://user-images.githubusercontent.com/2313873/43318642-86ec4e1c-916f-11e8-9bd7-c412d522534b.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43353360-aea5518e-9236-11e8-85b6-fe942cbed9a0.png)
https://user-images.githubusercontent.com/2068130/43353360-aea5518e-9236-11e8-85b6-fe942cbed9a0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43353368-bd4cd414-9236-11e8-9fea-3142b2becd01.png
