### ISSUE TITLE
Radio Bochum

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#9843]
**App Name:** Radio Bochum
**Bundle ID:** App.Radio-Bochum
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=477103595">477103595</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/radio-bochum/id477103595?mt=8&uo=4">https://itunes.apple.com/us/app/radio-bochum/id477103595?mt=8&uo=4</a>
**App Version:** 2.5.1
**Seller:** MPG Medien Produktion GmbH & Co. KG
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/mpg-medien-produktion-gmbh-co-kg/id472631526?uo=4">© MPG Medien Produktion GmbH & Co. KG</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/e3/67/49/e36749bb-b29e-75c3-a394-198b4f9ed097/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43357692-e7c67674-9285-11e8-972a-99b66242a526.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43357692-e7c67674-9285-11e8-972a-99b66242a526.png)
https://user-images.githubusercontent.com/2068130/43357692-e7c67674-9285-11e8-972a-99b66242a526.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43357697-fb4c5060-9285-11e8-87cd-970c67ec6e05.png
