### ISSUE TITLE
FOCUS Online Nachrichten

### ISSUE THREAD

**Issue by RemiDeluxe** [glasklart/hd#9844]
**App Name:** FOCUS Online Nachrichten
**Bundle ID:** de.focus.iphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=519052678">519052678</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/focus-online-nachrichten/id519052678?mt=8&uo=4">https://itunes.apple.com/us/app/focus-online-nachrichten/id519052678?mt=8&uo=4</a>
**App Version:** 3.2.2
**Seller:** FOCUS Online Group GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/focus-online-group-gmbh/id362104537?uo=4">© FOCUS Online Group GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/13/6c/72/136c72c5-3a79-e27e-a71f-ebfbefd7d53a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/41047592/42599736-e9f4a6e8-8568-11e8-9fca-9f4cd16a14bc.png)

**Comment by dftune** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/41047592/42599665-a0ea82f6-8568-11e8-8a26-2c771bc375a9.png)

Source: https://user-images.githubusercontent.com/41047592/42599676-ad31ed2e-8568-11e8-9336-72ef41f2f5a3.png

**Comment by dftune** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/41047592/42599736-e9f4a6e8-8568-11e8-9fca-9f4cd16a14bc.png)

Source: https://user-images.githubusercontent.com/41047592/42599676-ad31ed2e-8568-11e8-9336-72ef41f2f5a3.png
