### ISSUE TITLE
Evil Apples: Dirty Adult Cards

### ISSUE THREAD

**Issue by dftune** [glasklart/hd#9845]
**App Name:** Evil Apples: Dirty Adult Cards
**Bundle ID:** com.evilapples.evilapples
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=645705454">645705454</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/evil-apples-dirty-adult-cards/id645705454?mt=8&uo=4">https://itunes.apple.com/us/app/evil-apples-dirty-adult-cards/id645705454?mt=8&uo=4</a>
**App Version:** 3.2.2
**Seller:** Evil Studios Limited
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/evil-studios-limited/id645705457?mt=8&uo=4">© Evil Studios Limited</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/3c/e8/4a/3ce84a34-e0da-9b75-4cd1-9ab2e1fd30c1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54837117-e8d43380-4cc5-11e9-9635-818c94a2c17e.png)

**Comment by dftune** [comment]
![evilapples_final](https://user-images.githubusercontent.com/41047592/42496527-0707fc16-842f-11e8-81d8-cfacd36f0c7e.png)

**Comment by dftune** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/41047592/42496571-2af376aa-842f-11e8-9fec-6b4be22773a4.png)

**Comment by dftune** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/41047592/42496674-7ee0e446-842f-11e8-85d0-649cc2e3ebe8.png)

Source: https://user-images.githubusercontent.com/41047592/42496722-a2a93504-842f-11e8-9040-5c7f421c54bd.png

**Comment by alpcinar** [comment]
Needs update.

**Comment by 2Qt2beStr8** [comment]
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/54823367-e5ca4a80-4ca7-11e9-9dce-f5c9435962d0.png)
https://user-images.githubusercontent.com/20930745/54823367-e5ca4a80-4ca7-11e9-9dce-f5c9435962d0.png

Source:
https://user-images.githubusercontent.com/20930745/54823370-e7940e00-4ca7-11e9-9f77-121c5e840577.png
