### ISSUE TITLE
Telekom Sport

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#9848]
**App Name:** Telekom Sport
**Bundle ID:** de.telekom.basketball
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=914912959">914912959</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/de/app/telekom-sport/id914912959?mt=8&uo=4">https://itunes.apple.com/de/app/telekom-sport/id914912959?mt=8&uo=4</a>
**App Version:** 3.0.17
**Seller:** Telekom Deutschland GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/de/developer/telekom-deutschland-gmbh/id930125248?uo=4">© Telekom Deutschland GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple125/v4/d0/a7/49/d0a749a0-767a-9955-61ba-61485429f19d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![telekomsport](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43117401-9aed5312-8eda-11e8-9c55-babddc289506.png)

**Comment by XPEric** [comment]
![telekomsport](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43117401-9aed5312-8eda-11e8-9c55-babddc289506.png)
https://user-images.githubusercontent.com/2313873/43117401-9aed5312-8eda-11e8-9c55-babddc289506.png
___
Source:
https://user-images.githubusercontent.com/2313873/43117407-a28b31d4-8eda-11e8-8254-5dbb564407fa.png
