### ISSUE TITLE
Froggy Jump

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#985]
**App Name:** Froggy Jump
**Bundle ID:** com.invictus.froggyjump
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=364355046">364355046</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/froggy-jump/id364355046?mt=8&uo=4">https://itunes.apple.com/us/app/froggy-jump/id364355046?mt=8&uo=4</a>
**App Version:** 1.29
**Seller:** Invictus Games Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/invictus/id321262193?uo=4">© Invictus</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/cd/68/53/cd6853de-248d-dd37-02eb-2368ced0b504/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39939179-a9294364-5555-11e8-9e6b-68aea1bc86e0.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/39939179-a9294364-5555-11e8-9e6b-68aea1bc86e0.png)
https://user-images.githubusercontent.com/2068130/39939179-a9294364-5555-11e8-9e6b-68aea1bc86e0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/39939197-b827b936-5555-11e8-954e-175a8c88f82c.png
