### ISSUE TITLE
Youfid

### ISSUE THREAD

**Issue by GMoxFr** [glasklart/hd#9853]
**App Name:** Youfid
**Bundle ID:** com.4gsecure.youfid.dev
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=598935698">598935698</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/youfid/id598935698?mt=8&uo=4">https://itunes.apple.com/us/app/youfid/id598935698?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** WOAPPY
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/woappy/id598935701?uo=4">© Woappy</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple49/v4/86/f5/e6/86f5e63b-b580-4959-092d-508e7aaa7ded/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43357557-df98631a-9283-11e8-84d9-f550971da5f2.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43357557-df98631a-9283-11e8-84d9-f550971da5f2.png)
https://user-images.githubusercontent.com/2068130/43357557-df98631a-9283-11e8-84d9-f550971da5f2.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43357562-ee56c00e-9283-11e8-8a5e-5f54fdb11d0a.png
