### ISSUE TITLE
UNiDAYS: Student Deals

### ISSUE THREAD

**Issue by GMoxFr** [glasklart/hd#9854]
**App Name:** UNiDAYS: Student Deals
**Bundle ID:** com.myunidays.UNiDAYS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=599608562">599608562</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/unidays-student-deals/id599608562?mt=8&uo=4">https://itunes.apple.com/us/app/unidays-student-deals/id599608562?mt=8&uo=4</a>
**App Version:** 6.5.5
**Seller:** MyUNiDAYS Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/unidays/id599608565?uo=4">© UNiDAYS</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple115/v4/5d/d0/3c/5dd03c38-ac3f-3f5e-b8e7-6601583663b1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43353414-00543f48-9239-11e8-9603-337c74e303ed.png)

**Comment by XPEric** [comment]
![unidays](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43116798-7fdea70e-8ed7-11e8-895f-e3168a0dfce0.png)
https://user-images.githubusercontent.com/2313873/43116798-7fdea70e-8ed7-11e8-895f-e3168a0dfce0.png
___
Source: 
https://user-images.githubusercontent.com/2313873/43116802-87eaeb2e-8ed7-11e8-9ca9-315f0afc6acf.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43353414-00543f48-9239-11e8-9603-337c74e303ed.png)
https://user-images.githubusercontent.com/2068130/43353414-00543f48-9239-11e8-9603-337c74e303ed.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43353417-0dc02246-9239-11e8-8402-cfe6c7054431.png
