### ISSUE TITLE
Molotov - TV en direct, replay

### ISSUE THREAD

**Issue by GMoxFr** [glasklart/hd#9855]
**App Name:** Molotov - TV en direct, replay
**Bundle ID:** tv.molotov.MolotovAppProd
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1053134780">1053134780</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/fr/app/molotov-tv-en-direct-replay/id1053134780?mt=8&uo=4">https://itunes.apple.com/fr/app/molotov-tv-en-direct-replay/id1053134780?mt=8&uo=4</a>
**App Version:** 3.0.1
**Seller:** Molotov
**Developer:** <a target="_blank" href="https://itunes.apple.com/fr/developer/molotov/id1053134779?uo=4">© Molotov</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple115/v4/80/d1/1c/80d11c14-6655-e537-c8f3-fa1d22c566d4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43354392-320bdd80-924c-11e8-97a8-ded25f72559b.png)

**Comment by XPEric** [comment]
![molotov](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43117171-72306078-8ed9-11e8-9061-568995a62b3e.png)
https://user-images.githubusercontent.com/2313873/43117171-72306078-8ed9-11e8-9061-568995a62b3e.png
___
Source:
https://user-images.githubusercontent.com/2313873/43117178-79a9be1c-8ed9-11e8-856b-48612ece43f0.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43354392-320bdd80-924c-11e8-97a8-ded25f72559b.png)
https://user-images.githubusercontent.com/2068130/43354392-320bdd80-924c-11e8-97a8-ded25f72559b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43354395-3f70ed44-924c-11e8-8eb3-1639fbe4214a.png
