### ISSUE TITLE
Curious Cat: Money for Surveys

### ISSUE THREAD

**Issue by GMoxFr** [glasklart/hd#9856]
**App Name:** Curious Cat: Money for Surveys
**Bundle ID:** com.pawoints.curiouscat
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1234966243">1234966243</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/curious-cat-money-for-surveys/id1234966243?mt=8&uo=4">https://itunes.apple.com/us/app/curious-cat-money-for-surveys/id1234966243?mt=8&uo=4</a>
**App Version:** 0.26.0
**Seller:** On Device Research Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/on-device-research/id642779963?uo=4">© On Device Research</a>
**Supported Devices:** iPhone4S-iPhone4S, iPhone5-iPhone5, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/53/7b/10/537b10b9-90ed-791d-c8bc-e18f5661e047/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43357624-dd1f5b56-9284-11e8-8153-24b4a4621fa0.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43357624-dd1f5b56-9284-11e8-8153-24b4a4621fa0.png)
https://user-images.githubusercontent.com/2068130/43357624-dd1f5b56-9284-11e8-8153-24b4a4621fa0.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43357628-ebae1ae0-9284-11e8-98c8-e7df30d866c5.png
