### ISSUE TITLE
Touch Hockey 2

### ISSUE THREAD

**Issue by DerHimmelsreiter** [glasklart/hd#986]
**App Name:** Touch Hockey 2
**Bundle ID:** com.flipside5.games.th2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=449460801">449460801</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/touch-hockey-2/id449460801?mt=8&uo=4">https://itunes.apple.com/us/app/touch-hockey-2/id449460801?mt=8&uo=4</a>
**App Version:** 2.2.6
**Seller:** FlipSide5, Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/flipside5-inc./id283490538?uo=4>© FlipSide5, Inc.</a>
**Supported Devices:** iPadMini, iPodTouchThirdGen, iPhone5s, iPhone5c, iPad3G, iPodTouchourthGen, iPhone4, iPhone-3GS, iPadFourthGen, iPhone5, iPodTouchFifthGen, iPadThirdGen, iPad2Wifi, iPadThirdGen4G, iPadWifi, iPad23G, iPhone4S, iPadFourthGen4G, iPadMini4G
**Original Artwork:**
<img src="http://a1060.phobos.apple.com/us/r30/Purple/v4/13/4e/f1/134ef11f-f7fb-3d36-c146-321e2d43b529/mzl.jgafmdvc.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16967458/4aa90ce8-4e09-11e6-954f-5e3d49c11b5b.png)

**Comment by Anuskuss** [comment]
@dreamnet Could you remove the lines here as well.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/16967458/4aa90ce8-4e09-11e6-954f-5e3d49c11b5b.png)
https://cloud.githubusercontent.com/assets/2068130/16967458/4aa90ce8-4e09-11e6-954f-5e3d49c11b5b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/16967467/58d95b88-4e09-11e6-94f9-d1ca7865684f.png

**Comment by Anuskuss** [comment]
:+1:
