### ISSUE TITLE
Frontier Airlines

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9861]
**App Name:** Frontier Airlines
**Bundle ID:** com.flyfrontier.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1041410548">1041410548</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/frontier-airlines/id1041410548?mt=8&uo=4">https://itunes.apple.com/us/app/frontier-airlines/id1041410548?mt=8&uo=4</a>
**App Version:** 1.5.8
**Seller:** Frontier Airlines, Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/frontier-airlines/id593988621?uo=4">© Frontier Airlines</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple125/v4/52/39/e3/5239e3be-ce48-bc3e-1719-d8b19532da73/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/41047592/42597240-d6f8188e-8560-11e8-9dbb-1d22187a3106.png)

**Comment by dftune** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/41047592/42597240-d6f8188e-8560-11e8-9dbb-1d22187a3106.png)

Source: https://user-images.githubusercontent.com/41047592/42597248-dc588034-8560-11e8-9f30-7b4c5df54f41.png
