### ISSUE TITLE
WedPics - Wedding Photo App

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9862]
**App Name:** WedPics - Wedding Photo App
**Bundle ID:** com.dejami.wedpicsapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=549402355">549402355</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wedpics-wedding-photo-app/id549402355?mt=8&uo=4">https://itunes.apple.com/us/app/wedpics-wedding-photo-app/id549402355?mt=8&uo=4</a>
**App Version:** 3.3.0
**Seller:** deja Mi
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/deja-mi/id447681383?uo=4">© deja Mi</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple125/v4/19/31/84/193184c7-26c9-a60b-e6e7-c214247f54e8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/41047592/42600024-ab6023f2-8569-11e8-8354-b45e794eb9f8.png)

**Comment by dftune** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/41047592/42600024-ab6023f2-8569-11e8-8354-b45e794eb9f8.png)

Source: https://user-images.githubusercontent.com/41047592/42600056-c1a33690-8569-11e8-9939-20ae2fcaff77.png
