### ISSUE TITLE
CoinCap

### ISSUE THREAD

**Issue by dftune** [glasklart/hd#9867]
**App Name:** CoinCap
**Bundle ID:** io.coinCap.coinCap
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1074052280">1074052280</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/coincap/id1074052280?uo=4">https://apps.apple.com/us/app/coincap/id1074052280?uo=4</a>
**App Version:** 2.0.0
**Seller:** ShapeShift AG
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/shapeshift-ag/id996568144?uo=4">© ShapeShift AG</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, Watch4-Watch4, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/4b/52/d3/4b52d3a5-a201-1b86-07e5-bc86209d3389/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60370197-43cca380-99f6-11e9-9e15-3ed27b299c17.png)

**Comment by dftune** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/41047592/42596093-250f4280-855d-11e8-93a8-d194d911d0e0.png)

Source: https://user-images.githubusercontent.com/41047592/42596105-35448bc4-855d-11e8-929c-c6f3a0a5329e.png

**Comment by dftune** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/41047592/42596197-7e983cb2-855d-11e8-8287-4be26cd2b1d5.png)

Source: https://user-images.githubusercontent.com/41047592/42596217-8a700c2c-855d-11e8-9e7c-2dedac9e5bf7.png

**Comment by dreamnet** [comment]
Needs an update.

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60370197-43cca380-99f6-11e9-9e15-3ed27b299c17.png)
https://user-images.githubusercontent.com/2068130/60370197-43cca380-99f6-11e9-9e15-3ed27b299c17.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60370217-53e48300-99f6-11e9-8308-bd97feaaff07.png
