### ISSUE TITLE
BOND: Smarten Your Ceiling Fan

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9870]
**App Name:** BOND: Smarten Your Ceiling Fan
**Bundle ID:** io.olibra.BondHome
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1287223849">1287223849</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bond-smarten-your-ceiling-fan/id1287223849?mt=8&uo=4">https://itunes.apple.com/us/app/bond-smarten-your-ceiling-fan/id1287223849?mt=8&uo=4</a>
**App Version:** v1.120
**Seller:** Olibra LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/olibra-llc/id1237267096?uo=4">© Olibra, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple115/v4/a2/6e/36/a26e36c3-f19f-f1f7-5a60-0b47bf07abf0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048655-87d94cd0-8deb-11e8-85af-31a79ceb922d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048655-87d94cd0-8deb-11e8-85af-31a79ceb922d.png)
https://user-images.githubusercontent.com/2068130/43048655-87d94cd0-8deb-11e8-85af-31a79ceb922d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43048660-972112ae-8deb-11e8-87ea-82ab9d586562.png
