### ISSUE TITLE
Sensi

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9871]
**App Name:** Sensi
**Bundle ID:** com.emerson.Sensi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=792612452">792612452</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sensi/id792612452?mt=8&uo=4">https://itunes.apple.com/us/app/sensi/id792612452?mt=8&uo=4</a>
**App Version:** 4.1.3
**Seller:** Emerson Climate Technologies, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/emerson-climate-technologies-inc/id464252882?uo=4">© Emerson Climate Technologies, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/2f/5a/8d/2f5a8dfb-68a1-f5b0-5294-4ed12dee4666/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048613-c0374600-8dea-11e8-96ad-3cd94e4f76e5.png)

**Comment by XPEric** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/42741976-e791dc1c-8884-11e8-8d69-86e121c6b544.png)

Source: https://user-images.githubusercontent.com/2313873/42742024-5468a97e-8885-11e8-8670-c315040e912f.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048613-c0374600-8dea-11e8-96ad-3cd94e4f76e5.png)
https://user-images.githubusercontent.com/2068130/43048613-c0374600-8dea-11e8-96ad-3cd94e4f76e5.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43048616-ce64b424-8dea-11e8-8c5a-433d8f1e9fd2.png
