### ISSUE TITLE
DoorDash - Order Food Delivery

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9872]
**App Name:** DoorDash - Order Food Delivery
**Bundle ID:** doordash.DoorDashConsumer
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=719972451">719972451</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/doordash-order-food-delivery/id719972451?mt=8&uo=4">https://itunes.apple.com/us/app/doordash-order-food-delivery/id719972451?mt=8&uo=4</a>
**App Version:** 3.0.80
**Seller:** DoorDash, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/doordash-inc/id719972454?uo=4">© DoorDash, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple115/v4/61/b7/1c/61b71c63-3b21-3bc1-c96e-8862c6e62ace/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048552-b75a87c8-8de9-11e8-99ad-35f308365646.png)

**Comment by XPEric** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/42742294-b1aee0ce-8887-11e8-883e-ba53b41dfe84.png)

Source: https://user-images.githubusercontent.com/2313873/42742284-9ff999a0-8887-11e8-9daa-60217c8091c8.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048552-b75a87c8-8de9-11e8-99ad-35f308365646.png)
https://user-images.githubusercontent.com/2068130/43048552-b75a87c8-8de9-11e8-99ad-35f308365646.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43048557-c93a7962-8de9-11e8-8194-c7bb435f575f.png
