### ISSUE TITLE
Instacart

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9873]
**App Name:** Instacart
**Bundle ID:** com.instacart
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=545599256">545599256</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/instacart/id545599256?mt=8&uo=4">https://itunes.apple.com/us/app/instacart/id545599256?mt=8&uo=4</a>
**App Version:** 6.10.1
**Seller:** Apoorva Mehta
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/instacart-inc/id545599259?uo=4">© Instacart Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple115/v4/04/4e/26/044e26c3-9e5c-5d67-6191-91a85d9e64a9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048518-3c32d924-8de9-11e8-961d-a1f71beabce1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048518-3c32d924-8de9-11e8-961d-a1f71beabce1.png)
https://user-images.githubusercontent.com/2068130/43048518-3c32d924-8de9-11e8-961d-a1f71beabce1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43048523-4b4a5e00-8de9-11e8-9934-341fd7621dc3.png
