### ISSUE TITLE
Postmates - Food Delivery

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9875]
**App Name:** Postmates - Food Delivery
**Bundle ID:** com.postmates.getitnow
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=512393983">512393983</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/postmates-food-delivery/id512393983?mt=8&uo=4">https://itunes.apple.com/us/app/postmates-food-delivery/id512393983?mt=8&uo=4</a>
**App Version:** 4.2.5
**Seller:** Postmates Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/postmates-inc/id486092873?uo=4">© Postmates Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple125/v4/bd/73/7f/bd737fa6-c9ce-2f30-4f6d-7a342b931273/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048486-ab20ba46-8de8-11e8-836c-eea420bc6dc8.png)

**Comment by XPEric** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/42742495-fd6cd7f4-8888-11e8-8f69-ae8369109806.png)

Source: https://user-images.githubusercontent.com/2313873/42742541-5de80e5a-8889-11e8-9834-c0e8a069d884.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048486-ab20ba46-8de8-11e8-836c-eea420bc6dc8.png)
https://user-images.githubusercontent.com/2068130/43048486-ab20ba46-8de8-11e8-836c-eea420bc6dc8.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43048488-bab55570-8de8-11e8-9d9c-a06c7ea9c8c9.png)
