### ISSUE TITLE
TETRIS® [free.bv]

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9876]
**App Name:** TETRIS®
**Bundle ID:** com.ea.tetris2011free.bv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=480805652">480805652</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tetris/id480805652?mt=8&uo=4">https://itunes.apple.com/us/app/tetris/id480805652?mt=8&uo=4</a>
**App Version:** 3.0.15
**Seller:** EA Swiss Sarl
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/electronic-arts/id284800461?mt=8&uo=4">© Electronic Arts</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple125/v4/d7/a2/fa/d7a2fa52-7779-7cfe-2384-6ab5ddfa5f38/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20276864/884d5dfa-aa9e-11e6-930c-5ff70ad26a72.png)

**Comment by XPEric** [comment]
There is an existing issue for ‘TETRIS®’, although it appears to have a different iTunes and bundle ID.

**Comment by dreamnet** [comment]
Icon by @2Qt2beStr8 .
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20276864/884d5dfa-aa9e-11e6-930c-5ff70ad26a72.png)
https://cloud.githubusercontent.com/assets/20930745/20276864/884d5dfa-aa9e-11e6-930c-5ff70ad26a72.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/20930745/20276881/93d4389c-aa9e-11e6-8814-47898a0a1a22.png
