### ISSUE TITLE
Informed Delivery®

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9877]
**App Name:** Informed Delivery®
**Bundle ID:** com.usps.myusps
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1068536939">1068536939</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/informed-delivery/id1068536939?mt=8&uo=4">https://itunes.apple.com/us/app/informed-delivery/id1068536939?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** United States Postal Service
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/united-states-postal-service/id339597581?uo=4">© United States Postal Service</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/d9/98/85/d9988576-e2e8-d65a-5957-6b2c0979961f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048455-0133aafc-8de8-11e8-97fd-e39cf5b13b75.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048455-0133aafc-8de8-11e8-97fd-e39cf5b13b75.png)
https://user-images.githubusercontent.com/2068130/43048455-0133aafc-8de8-11e8-97fd-e39cf5b13b75.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43048461-0efa99d4-8de8-11e8-94a8-846d9a540ac0.png
