### ISSUE TITLE
Drizly: Alcohol Delivery

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9878]
**App Name:** Drizly: Alcohol Delivery
**Bundle ID:** com.drizly.Drizly
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=574731947">574731947</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/drizly-alcohol-delivery/id574731947?mt=8&uo=4">https://itunes.apple.com/us/app/drizly-alcohol-delivery/id574731947?mt=8&uo=4</a>
**App Version:** 3.13.0
**Seller:** Drizly, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/drizly-inc/id574732150?uo=4">© Drizly Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple125/v4/c7/13/03/c7130372-192f-db69-a060-19ae11708c4f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048412-7c14543e-8de7-11e8-8459-6c0f80243e40.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048412-7c14543e-8de7-11e8-8459-6c0f80243e40.png)
https://user-images.githubusercontent.com/2068130/43048412-7c14543e-8de7-11e8-8459-6c0f80243e40.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43048421-8de78118-8de7-11e8-864f-c3b10f60018e.png
