### ISSUE TITLE
DRAGON BALL Z DOKKAN BATTLE

### ISSUE THREAD

**Issue by Eltalite27** [glasklart/hd#9879]
**App Name:** DRAGON BALL Z DOKKAN BATTLE
**Bundle ID:** jp.co.bandainamcogames.BNGI0221
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=951627425">951627425</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dragon-ball-z-dokkan-battle/id951627425?mt=8&uo=4">https://itunes.apple.com/us/app/dragon-ball-z-dokkan-battle/id951627425?mt=8&uo=4</a>
**App Version:** 3.11.0
**Seller:** BANDAI NAMCO Entertainment Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bandai-namco-entertainment-inc/id352305770?uo=4">© BANDAI NAMCO Entertainment Inc.</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/15/73/7a/15737a07-b6f2-54b5-1cf8-d97025d0572e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43359383-e0214b62-92a1-11e8-9071-a49fb2511758.png)

**Comment by dreamnet** [comment]
❓ 
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43359383-e0214b62-92a1-11e8-9071-a49fb2511758.png)
https://user-images.githubusercontent.com/2068130/43359383-e0214b62-92a1-11e8-9071-a49fb2511758.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43359387-f17d214c-92a1-11e8-836c-7c4494291553.png
