### ISSUE TITLE
Cloudy - Weather Forecast

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9881]
**App Name:** Cloudy - Weather Forecast
**Bundle ID:** com.applicodo.cloudy
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1274112191">1274112191</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/cloudy-weather-forecast/id1274112191?mt=8&uo=4">https://itunes.apple.com/us/app/cloudy-weather-forecast/id1274112191?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Ciprian Redinciuc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ciprian-redinciuc/id1051055696?uo=4">© Ciprian Redinciuc</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/08/6c/36/086c36f8-b05d-3b20-31f1-2e50af02e18e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43359601-08e769ca-92a5-11e8-9256-d8178647646e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43359601-08e769ca-92a5-11e8-9256-d8178647646e.png)
https://user-images.githubusercontent.com/2068130/43359601-08e769ca-92a5-11e8-9256-d8178647646e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43359604-198aa9ea-92a5-11e8-9995-5971f53e5e4b.png
