### ISSUE TITLE
Movitaur - Movie Database

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9882]
**App Name:** Movitaur - Movie Database
**Bundle ID:** com.vinit.MovIn
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1178893582">1178893582</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/movitaur-movie-database/id1178893582?mt=8&uo=4">https://itunes.apple.com/us/app/movitaur-movie-database/id1178893582?mt=8&uo=4</a>
**App Version:** 1.0.1
**Seller:** Vinit Jasoliya
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/vinit-jasoliya/id1037635423?uo=4">© Vinit Jasoliya</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/21/a2/85/21a2853d-c551-3087-9351-24fb3743844e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43047925-9d412dec-8ddf-11e8-915d-90e46c90c900.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43047925-9d412dec-8ddf-11e8-915d-90e46c90c900.png)
https://user-images.githubusercontent.com/2068130/43047925-9d412dec-8ddf-11e8-915d-90e46c90c900.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43047931-ab99124c-8ddf-11e8-9c8a-bf8ec9befb05.png
