### ISSUE TITLE
Agenda – A new take on notes

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9884]
**App Name:** Agenda – A new take on notes
**Bundle ID:** com.momenta.agenda.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1370289240">1370289240</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/agenda-a-new-take-on-notes/id1370289240?mt=8&uo=4">https://itunes.apple.com/us/app/agenda-a-new-take-on-notes/id1370289240?mt=8&uo=4</a>
**App Version:** 2.1.3
**Seller:** Momenta BV
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/momenta-b-v/id1287445659?uo=4">© Momenta B.V.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/4b/1f/a1/4b1fa15b-63b4-ee2c-942e-d741407fcd6a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43356797-e43b89ee-9277-11e8-85ae-5f1f961a17bd.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43356797-e43b89ee-9277-11e8-85ae-5f1f961a17bd.png)
https://user-images.githubusercontent.com/2068130/43356797-e43b89ee-9277-11e8-85ae-5f1f961a17bd.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43356803-f332c282-9277-11e8-9267-87dc12477e0b.png
