### ISSUE TITLE
Touch Bar on any Mac#TouchArch

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9885]
**App Name:** Touch Bar on any Mac#TouchArch
**Bundle ID:** io.iooio.toucharch.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1138518113">1138518113</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/touch-bar-on-any-mac-toucharch/id1138518113?mt=8&uo=4">https://itunes.apple.com/us/app/touch-bar-on-any-mac-toucharch/id1138518113?mt=8&uo=4</a>
**App Version:** 1.4.0
**Seller:** Chao Tian
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/chao-tian/id1010524845?uo=4">© Chao Tian</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple115/v4/87/b1/b8/87b1b802-76a0-dc36-c4bc-7dc7a804e8cb/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43356741-c82c6418-9276-11e8-898a-f62b4a1db1b3.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43356741-c82c6418-9276-11e8-898a-f62b4a1db1b3.png)
https://user-images.githubusercontent.com/2068130/43356741-c82c6418-9276-11e8-898a-f62b4a1db1b3.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43356743-d6584d18-9276-11e8-855f-46a348cb5eed.png
