### ISSUE TITLE
Shake Shack

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9886]
**App Name:** Shake Shack
**Bundle ID:** com.halickman.ShackHQ
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=317279545">317279545</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/shake-shack/id317279545?mt=8&uo=4">https://itunes.apple.com/us/app/shake-shack/id317279545?mt=8&uo=4</a>
**App Version:** 3.2.12
**Seller:** Shake Shack Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/shake-shack/id1081036203?uo=4">© Shake Shack</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple115/v4/a5/e8/30/a5e830ca-ffde-c438-0c5e-b3dd47284d7a/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048691-2db103a0-8dec-11e8-82a5-03f5c858d1fb.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048691-2db103a0-8dec-11e8-82a5-03f5c858d1fb.png)
https://user-images.githubusercontent.com/2068130/43048691-2db103a0-8dec-11e8-82a5-03f5c858d1fb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43048696-3d4ca29c-8dec-11e8-91c5-9d19889a95a9.png
