### ISSUE TITLE
Skiplagged — Flights & Hotels

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9887]
**App Name:** Skiplagged — Flights & Hotels
**Bundle ID:** com.skiplagged
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=823443083">823443083</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/skiplagged-flights-hotels/id823443083?mt=8&uo=4">https://itunes.apple.com/us/app/skiplagged-flights-hotels/id823443083?mt=8&uo=4</a>
**App Version:** 2.1.9
**Seller:** Skiplagged LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/skiplagged-llc/id823443086?uo=4">© Skiplagged LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/99/3d/26/993d269e-1b4d-8521-03e3-6dfd6d833f87/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048733-ce88f2d8-8dec-11e8-9f59-e6762e141ef1.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43048733-ce88f2d8-8dec-11e8-9f59-e6762e141ef1.png)
https://user-images.githubusercontent.com/2068130/43048733-ce88f2d8-8dec-11e8-9f59-e6762e141ef1.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43048743-dc82f514-8dec-11e8-9e63-4b7cb7bb8a07.png
