### ISSUE TITLE
TYT - Home of Progressives

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9894]
**App Name:** TYT - Home of Progressives
**Bundle ID:** com.tyt.battlecruiser
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1319576607">1319576607</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tyt-home-of-progressives/id1319576607?mt=8&uo=4">https://itunes.apple.com/us/app/tyt-home-of-progressives/id1319576607?mt=8&uo=4</a>
**App Version:** 1.8.0
**Seller:** The Young Turks, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-young-turks-inc/id412793198?mt=8&uo=4">© The Young Turks, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/a0/12/c3/a012c315-3dae-8e81-b915-76e19186e4b8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58763877-21fc1000-8561-11e9-87ae-52230e125a6a.png)

**Comment by XPEric** [comment]
![tytplus](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43118689-f0168e0c-8ee0-11e8-890b-a3943901fd25.png)
https://user-images.githubusercontent.com/2313873/43118689-f0168e0c-8ee0-11e8-890b-a3943901fd25.png
___
Source:
https://user-images.githubusercontent.com/2313873/43118695-f5cf0d7e-8ee0-11e8-9ae8-858b35c0345c.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43355877-68ddddc2-9265-11e8-980c-2917bfbdca53.png)
https://user-images.githubusercontent.com/2068130/43355877-68ddddc2-9265-11e8-980c-2917bfbdca53.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43355883-7a69ae2c-9265-11e8-98a0-fa42dad9063c.png

**Comment by XPEric** [comment]
Needs update to name and icon.

[DUPLICATE of #9894]
**App Name:** TYT - Home of Progressives
**Bundle ID:** com.tyt.battlecruiser
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1319576607">1319576607</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tyt-home-of-progressives/id1319576607?mt=8&uo=4">https://itunes.apple.com/us/app/tyt-home-of-progressives/id1319576607?mt=8&uo=4</a>
**App Version:** 1.8.0
**Seller:** The Young Turks, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-young-turks-inc/id412793198?mt=8&uo=4">© The Young Turks, Inc.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/a0/12/c3/a012c315-3dae-8e81-b915-76e19186e4b8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by XPEric** [comment]
![tyt](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/58762594-518a2880-851f-11e9-8576-4d99fb63a512.png)
https://user-images.githubusercontent.com/2313873/58762594-518a2880-851f-11e9-8576-4d99fb63a512.png

___
Source:
![tyt-source](https://user-images.githubusercontent.com/2313873/58762597-5c44bd80-851f-11e9-8b36-c7480c38221d.png)

**Comment by dreamnet** [comment]
Strange source... anyway good work!
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/58763877-21fc1000-8561-11e9-87ae-52230e125a6a.png)
https://user-images.githubusercontent.com/2068130/58763877-21fc1000-8561-11e9-87ae-52230e125a6a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/58763893-36400d00-8561-11e9-9c6d-9959989e17c3.png
