### ISSUE TITLE
Rossmann

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#9895]
**App Name:** Rossmann
**Bundle ID:** de.rossmann.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1034309353">1034309353</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/rossmann/id1034309353?mt=8&uo=4">https://itunes.apple.com/us/app/rossmann/id1034309353?mt=8&uo=4</a>
**App Version:** 2.5.1
**Seller:** Dirk Rossmann GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dirk-rossmann-gmbh-drogerie/id941118800?uo=4">© Dirk Rossmann GmbH - Drogerie</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple125/v4/3c/96/af/3c96af06-b16b-72fa-03a0-c2d52a10551b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![rossmann](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43117852-021c18a0-8edd-11e8-8c12-29e386616334.png)

**Comment by XPEric** [comment]
![rossmann](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43117852-021c18a0-8edd-11e8-8c12-29e386616334.png)
https://user-images.githubusercontent.com/2313873/43117852-021c18a0-8edd-11e8-8c12-29e386616334.png
___
Source:
https://user-images.githubusercontent.com/2313873/43117859-07a2ec9a-8edd-11e8-9378-04b34c4acd3c.png

**Comment by tarkan78** [comment]
Thank You
