### ISSUE TITLE
Is there a way to fix YouTube icon in sharesheet when sharing video from Photos app?

### ISSUE THREAD

**Issue by pradtk** [glasklart/hd#9896]
![65dc0095-54ab-48ae-a259-0a03badf1029](https://user-images.githubusercontent.com/41028466/43090003-62a593fc-8ed0-11e8-8bf5-c59774ae8cd9.jpeg)

**Comment by dreamnet** [comment]
I think this is an [Anemone](https://github.com/AnemoneTeam/Anemone) problem. Don't know a way to theme this. 😢

**Comment by pradtk** [comment]
Also “Create PDF” icon cannot be themed?

![1f81447e-4f1a-416f-9164-c74e09b2ab32](https://user-images.githubusercontent.com/41028466/43510469-ed0e2aba-959f-11e8-9a2b-96103a2588a6.jpeg)

**Comment by dreamnet** [comment]
@pradtk Sorry, I don't think so.
