### ISSUE TITLE
Volotea

### ISSUE THREAD

**Issue by grkka** [glasklart/hd#9897]
**App Name:** Volotea
**Bundle ID:** com.volotea.ios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=635331043">635331043</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/volotea/id635331043?mt=8&uo=4">https://itunes.apple.com/us/app/volotea/id635331043?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Volotea S.A.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/volotea-s-a/id635331046?uo=4">© Volotea S.A.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple125/v4/15/33/d6/1533d6d2-65f6-7a73-394a-b15d77657668/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![volotea](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43170847-3a0d1a0a-8f75-11e8-96f5-c98e2f1fc57e.png)

**Comment by XPEric** [comment]
![volotea](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43170847-3a0d1a0a-8f75-11e8-96f5-c98e2f1fc57e.png)
https://user-images.githubusercontent.com/2313873/43170847-3a0d1a0a-8f75-11e8-96f5-c98e2f1fc57e.png
___
Source:
https://user-images.githubusercontent.com/2313873/43170852-3bb2f1ea-8f75-11e8-971e-5ddc62780717.png
