### ISSUE TITLE
Nero Streaming Player

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#9898]
**App Name:** Nero Streaming Player
**Bundle ID:** com.nero.nmh.neromobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1020666442">1020666442</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/nero-streaming-player/id1020666442?mt=8&uo=4">https://itunes.apple.com/us/app/nero-streaming-player/id1020666442?mt=8&uo=4</a>
**App Version:** 1.2.11
**Seller:** Nero AG
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nero-ag/id598875299?uo=4">© Nero AG</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple125/v4/71/d1/08/71d108e0-3760-a400-d0b8-d4cbc80f8cd5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![nero](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43170574-d5570ea0-8f73-11e8-8e65-98c0f57fc58a.png)

**Comment by XPEric** [comment]
![nero](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43170574-d5570ea0-8f73-11e8-8e65-98c0f57fc58a.png)
https://user-images.githubusercontent.com/2313873/43170574-d5570ea0-8f73-11e8-8e65-98c0f57fc58a.png
___
Source:
https://user-images.githubusercontent.com/2313873/43170580-d7b0f7ec-8f73-11e8-9480-d8b7b207d3fc.png

**Comment by tarkan78** [comment]
Thank You
