### ISSUE TITLE
clever-tanken.de

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#9899]
**App Name:** clever-tanken.de
**Bundle ID:** de.inforoad.cleverTanken
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=300763441">300763441</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/clever-tanken-de/id300763441?mt=8&uo=4">https://itunes.apple.com/us/app/clever-tanken-de/id300763441?mt=8&uo=4</a>
**App Version:** 6.0.5
**Seller:** infoRoad GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/inforoad-gmbh/id300763444?uo=4">© infoRoad GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple115/v4/aa/f8/d7/aaf8d70a-7c1a-05f8-9b05-18167d649d71/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![clevertanken](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/2313873/43296316-accc1614-9118-11e8-9925-372e7fe11305.png)

**Comment by XPEric** [comment]
![clevertanken](http://preview.dreamnet.at/?image=https://user-images.githubusercontent.com/2313873/43296316-accc1614-9118-11e8-9925-372e7fe11305.png)
https://user-images.githubusercontent.com/2313873/43296316-accc1614-9118-11e8-9925-372e7fe11305.png
___
Source: 
https://user-images.githubusercontent.com/2313873/43296330-bb17bcc8-9118-11e8-9801-06f162487fc7.png

**Comment by tarkan78** [comment]
Thank You
