### ISSUE TITLE
Hay Day

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#990]
**App Name:** Hay Day
**Bundle ID:** com.supercell.soil
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=506627515">506627515</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/hay-day/id506627515?mt=8&uo=4">https://itunes.apple.com/us/app/hay-day/id506627515?mt=8&uo=4</a>
**App Version:** 1.29.96
**Seller:** Supercell Oy
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/supercell/id488106216?uo=4>© Supercell</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple18/v4/8d/78/c3/8d78c350-7541-1213-3c9c-d8e33ace538d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18953218/9f84fa66-864d-11e6-9570-5390f547eb73.png)

**Comment by haen7** [comment]
this needs to be updated

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18953218/9f84fa66-864d-11e6-9570-5390f547eb73.png)
https://cloud.githubusercontent.com/assets/20930745/18953218/9f84fa66-864d-11e6-9570-5390f547eb73.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18953246/be8e46e2-864d-11e6-919d-777a1d3221e1.png
