### ISSUE TITLE
satellite – Handy in der App

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#9900]
**App Name:** satellite – Handy in der App
**Bundle ID:** de.sipgate.app.satellite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1322354195">1322354195</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/satellite-handy-in-der-app/id1322354195?mt=8&uo=4">https://itunes.apple.com/us/app/satellite-handy-in-der-app/id1322354195?mt=8&uo=4</a>
**App Version:** 1.1.2
**Seller:** sipgate GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/sipgate-gmbh/id515224773?uo=4">© sipgate GmbH</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple115/v4/34/07/62/34076227-2606-e0e6-9a72-a194f8e66f4d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![satellite](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43296343-ceaa2712-9118-11e8-983e-148c55b15505.png)

**Comment by XPEric** [comment]
![satellite](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43296343-ceaa2712-9118-11e8-983e-148c55b15505.png)
https://user-images.githubusercontent.com/2313873/43296343-ceaa2712-9118-11e8-983e-148c55b15505.png
___
Source: 
https://user-images.githubusercontent.com/2313873/43296348-d69cdc76-9118-11e8-88bb-f7d13d6b601a.png

**Comment by tarkan78** [comment]
Thank You
