### ISSUE TITLE
Telemundo Deportes VR

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9901]
**App Name:** Telemundo Deportes VR
**Bundle ID:** com.telemundo.vr.mobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1395426257">1395426257</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/telemundo-deportes-vr/id1395426257?mt=8&uo=4">https://itunes.apple.com/us/app/telemundo-deportes-vr/id1395426257?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** NBCUniversal Media, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nbcuniversal-media-llc/id303544359?uo=4">© NBCUniversal Media, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple115/v4/a8/7b/c3/a87bc32f-af08-f50f-0a10-b5a7516b3aba/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![telemundodeportesvr](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43296278-77233f60-9118-11e8-8fa9-22bd2d6ef9ee.png)

**Comment by XPEric** [comment]
![telemundodeportesvr](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43296278-77233f60-9118-11e8-8fa9-22bd2d6ef9ee.png)
https://user-images.githubusercontent.com/2313873/43296278-77233f60-9118-11e8-8fa9-22bd2d6ef9ee.png
___
Source:
https://user-images.githubusercontent.com/2313873/43296282-7e6140ec-9118-11e8-846a-cc19e54f6940.png
