### ISSUE TITLE
Telemundo Deportes - En Vivo

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9902]
**App Name:** Telemundo Deportes - En Vivo
**Bundle ID:** com.nbcuni.telemundo.deportestelemundoenvivo
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=686218010">686218010</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/telemundo-deportes-en-vivo/id686218010?mt=8&uo=4">https://itunes.apple.com/us/app/telemundo-deportes-en-vivo/id686218010?mt=8&uo=4</a>
**App Version:** 5.10.5
**Seller:** NBCUniversal Media, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nbcuniversal-media-llc/id303544359?uo=4">© NBCUniversal Media, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/7f/50/2d/7f502de8-fb03-97d7-3bf0-eb97f3960de8/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43991286-e879724e-9d69-11e8-8b1c-77567cb9ae69.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43991286-e879724e-9d69-11e8-8b1c-77567cb9ae69.png)
https://user-images.githubusercontent.com/2068130/43991286-e879724e-9d69-11e8-8b1c-77567cb9ae69.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43991290-f6a62678-9d69-11e8-957c-996e57965b3f.png
