### ISSUE TITLE
Planet Pootwaddle

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9903]
**App Name:** Planet Pootwaddle
**Bundle ID:** com.planetpootwaddle.planetpootwaddle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1357949110">1357949110</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/planet-pootwaddle/id1357949110?mt=8&uo=4">https://itunes.apple.com/us/app/planet-pootwaddle/id1357949110?mt=8&uo=4</a>
**App Version:** 1.0
**Seller:** Emphatek LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/emphatek-llc/id303252738?uo=4">© Emphatek LLC</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/a2/52/18/a2521868-7a83-3cd5-dfd5-c6d065ff3828/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18813768/18eb2c18-8306-11e6-9173-d5509fa344ec.png)

**Comment by dreamnet** [comment]
Icon by @2Qt2beStr8.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18813768/18eb2c18-8306-11e6-9173-d5509fa344ec.png)
https://cloud.githubusercontent.com/assets/20930745/18813768/18eb2c18-8306-11e6-9173-d5509fa344ec.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/20930745/18813774/3003cdf6-8306-11e6-9572-31f6cc76bf20.png
