### ISSUE TITLE
Logi Circle Security Camera

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#9904]
**App Name:** Logi Circle Security Camera
**Bundle ID:** com.logitech.Circle
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1018340690">1018340690</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/logi-circle-security-camera/id1018340690?mt=8&uo=4">https://itunes.apple.com/us/app/logi-circle-security-camera/id1018340690?mt=8&uo=4</a>
**App Version:** 3.2.5
**Seller:** Logitech Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/logitech-inc/id332300071?mt=8&uo=4">© Logitech Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/50/11/82/501182de-50bd-8c74-045d-5cc9f1bfd435/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![logicircle](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43298905-259f103e-9126-11e8-80b0-992aef88a785.png)

**Comment by XPEric** [comment]
![logicircle](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/43298905-259f103e-9126-11e8-80b0-992aef88a785.png)
https://user-images.githubusercontent.com/2313873/43298905-259f103e-9126-11e8-80b0-992aef88a785.png
___
Source: 
https://user-images.githubusercontent.com/2313873/43298915-2bb32f28-9126-11e8-81ef-4f95a472ab47.png

**Comment by StevenZwicker** [comment]
Thanks a bunch! About to request a few more.
