### ISSUE TITLE
Sling TV

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9909]
**App Name:** Sling TV
**Bundle ID:** com.dishdigital.sling
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=945077360">945077360</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/sling-tv/id945077360?mt=8&uo=4">https://itunes.apple.com/us/app/sling-tv/id945077360?mt=8&uo=4</a>
**App Version:** 5.5.0
**Seller:** Sling TV LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/artist/sling-tv-llc/959665097?uo=4">© Sling TV, LLC</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple125/v4/d2/89/f5/d289f5a8-008e-9971-c2fd-9eb59321f855/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43355992-5ac2743e-9268-11e8-9109-f3729ee1299e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43355992-5ac2743e-9268-11e8-9109-f3729ee1299e.png)
https://user-images.githubusercontent.com/2068130/43355992-5ac2743e-9268-11e8-9109-f3729ee1299e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43355996-694a9e14-9268-11e8-9731-4859656cc7cb.png
