### ISSUE TITLE
Password Manager - Touch ID & Passcode

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#9910]
**App Name:** Password Manager - Touch ID & Passcode
**Bundle ID:** PTS.Password-Manager
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=936773316">936773316</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/password-manager-touch-id-passcode/id936773316?mt=8&uo=4">https://itunes.apple.com/us/app/password-manager-touch-id-passcode/id936773316?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Kalai Chelvan
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kalai-chelvan/id541795739?uo=4">© Kalai Chelvan</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple62/v4/7c/bf/ec/7cbfec5c-7af2-e7ec-df40-c23bc2f8ae57/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43356617-4c14809c-9274-11e8-9695-6b4eeb3e042f.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43356617-4c14809c-9274-11e8-9695-6b4eeb3e042f.png)
https://user-images.githubusercontent.com/2068130/43356617-4c14809c-9274-11e8-9695-6b4eeb3e042f.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43356619-5a981f34-9274-11e8-98de-919fcf1e7eb1.png
