### ISSUE TITLE
BundleIDsXI

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9918]
**App Name:** BundleIDsXI
**Bundle ID:** com.wavelink.bundleidsxi
**Version:** 1.0.2-3
**iTunes ID:** none (Cydia app)
**Original Artwork:**
<img src="https://user-images.githubusercontent.com/2068130/44197703-b1a21080-a13f-11e8-974d-895b9b83242e.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44199014-40fcf300-a143-11e8-801d-58d4a9b8413b.png)

**Comment by Sly-Fi** [comment]
Same icon as issue #5568:

![com sassoty bundleids-large](https://user-images.githubusercontent.com/11544849/43651721-62774546-9700-11e8-9526-2d50a5c6fbd1.png)

**Comment by dreamnet** [comment]
![com sassoty bundleids-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43729070-62503a9c-99a7-11e8-8e6e-b2fbe8af61b7.png)
https://user-images.githubusercontent.com/2068130/43729070-62503a9c-99a7-11e8-8e6e-b2fbe8af61b7.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43729088-735f5fca-99a7-11e8-94fc-306329ca251b.png

**Comment by Sly-Fi** [comment]
Bundle ID has changed in recent update to 

com.wavelink.bundleidsxi

**Comment by dreamnet** [comment]
App has also a new icon:
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44199014-40fcf300-a143-11e8-801d-58d4a9b8413b.png)
https://user-images.githubusercontent.com/2068130/44199014-40fcf300-a143-11e8-801d-58d4a9b8413b.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44199050-5a9e3a80-a143-11e8-948c-2eea640e02f4.png
