### ISSUE TITLE
QuickThoughts - Earn Rewards

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9919]
**App Name:** QuickThoughts - Earn Rewards
**Bundle ID:** com.ssi.PanelistApplication
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=589328270">589328270</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/quickthoughts-earn-rewards/id589328270?mt=8&uo=4">https://itunes.apple.com/us/app/quickthoughts-earn-rewards/id589328270?mt=8&uo=4</a>
**App Version:** 2.15.6
**Seller:** Survey Sampling International, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/survey-sampling-international-llc/id589328273?uo=4">© Survey Sampling International, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/ba/c2/ea/bac2ea04-8f1f-2319-f63e-93fc7baf4d0f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43728115-589a65de-99a4-11e8-8646-890554f541da.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43728115-589a65de-99a4-11e8-8646-890554f541da.png)
https://user-images.githubusercontent.com/2068130/43728115-589a65de-99a4-11e8-8646-890554f541da.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43728140-6868bed4-99a4-11e8-9de4-9fddb23f1eac.png
