### ISSUE TITLE
ANA

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9920]
**App Name:** ANA
**Bundle ID:** jp.co.ana.iphoneapp.Tabidachi
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=382028327">382028327</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ana/id382028327?mt=8&uo=4">https://itunes.apple.com/us/app/ana/id382028327?mt=8&uo=4</a>
**App Version:** 4.0.30
**Seller:** All Nippon Airways
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/ana-all-nippon-airways/id382028330?uo=4">© ANA (All Nippon Airways)</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/2e/89/c7/2e89c718-e739-bb6f-556c-043aa32f9f7e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43960753-4bd30600-9cb3-11e8-8a48-d3b53fd21aa0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43960753-4bd30600-9cb3-11e8-8a48-d3b53fd21aa0.png)
https://user-images.githubusercontent.com/20930745/43960753-4bd30600-9cb3-11e8-8a48-d3b53fd21aa0.png

Source:
https://user-images.githubusercontent.com/20930745/43960781-63aa8a00-9cb3-11e8-986f-aec545b0f174.png
