### ISSUE TITLE
AllTrails: Hike, Run & Cycle

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#9921]
**App Name:** AllTrails: Hike, Run & Cycle
**Bundle ID:** com.alltrails.AllTrails
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=405075943">405075943</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/alltrails-hike-run-cycle/id405075943?mt=8&uo=4">https://itunes.apple.com/us/app/alltrails-hike-run-cycle/id405075943?mt=8&uo=4</a>
**App Version:** 8.8.7
**Seller:** AllTrails, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/alltrails-inc/id405075946?uo=4">© AllTrails, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/05/e1/16/05e1163f-2c01-3040-45a7-fd2a010cbf21/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43910781-088f3a54-9bfe-11e8-9ae3-9fcd87fd91ba.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43910781-088f3a54-9bfe-11e8-9ae3-9fcd87fd91ba.png)
https://user-images.githubusercontent.com/20930745/43910781-088f3a54-9bfe-11e8-9ae3-9fcd87fd91ba.png

Source:
https://user-images.githubusercontent.com/20930745/43910810-201da9f8-9bfe-11e8-8a7e-73fdb9251e3d.png
