### ISSUE TITLE
ezPDF Reader

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9922]
**App Name:** ezPDF Reader
**Bundle ID:** kr.co.unidocs.ezPDFReader4iPad
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=407445075">407445075</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/ezpdf-reader/id407445075?mt=8&uo=4">https://itunes.apple.com/us/app/ezpdf-reader/id407445075?mt=8&uo=4</a>
**App Version:** 3.0.3
**Seller:** Unidocs Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/unidocs-inc/id396101795?uo=4">© Unidocs Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/81/f6/28/81f628de-2ac9-fe21-efe2-140775fb3ccd/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43911246-4f032e90-9bff-11e8-9583-528bdf6b6de8.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43911246-4f032e90-9bff-11e8-9583-528bdf6b6de8.png)
https://user-images.githubusercontent.com/20930745/43911246-4f032e90-9bff-11e8-9583-528bdf6b6de8.png

Source:
https://user-images.githubusercontent.com/20930745/43911267-6074c7b0-9bff-11e8-82ef-06e3801fc83b.png
