### ISSUE TITLE
Yoink - Improved Drag and Drop

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9923]
**App Name:** Yoink - Improved Drag and Drop
**Bundle ID:** at.EternalStorms.YoinkiOS
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1260915283">1260915283</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yoink-improved-drag-and-drop/id1260915283?mt=8&uo=4">https://itunes.apple.com/us/app/yoink-improved-drag-and-drop/id1260915283?mt=8&uo=4</a>
**App Version:** 1.1.5
**Seller:** Matthias Gansrigler
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/matthias-gansrigler/id403111076?uo=4">© Matthias Gansrigler</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/29/85/56/29855693-d9b9-04fb-5ca3-91bb3a97e102/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43909322-5a38f3c6-9bfa-11e8-8a0a-56d87d4e055f.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43909322-5a38f3c6-9bfa-11e8-8a0a-56d87d4e055f.png)
https://user-images.githubusercontent.com/20930745/43909322-5a38f3c6-9bfa-11e8-8a0a-56d87d4e055f.png

Source:
https://user-images.githubusercontent.com/20930745/43909372-7a9c47f8-9bfa-11e8-9852-2a33ba0d8631.png
