### ISSUE TITLE
WSH LST

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9924]
**App Name:** WSH LST
**Bundle ID:** com.hvt.wishlist
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1323785754">1323785754</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/wsh-lst/id1323785754?mt=8&uo=4">https://itunes.apple.com/us/app/wsh-lst/id1323785754?mt=8&uo=4</a>
**App Version:** 1.7
**Seller:** Horizon Video Technologies Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/horizon-video-technologies/id940622092?uo=4">© Horizon Video Technologies</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/aa/01/53/aa0153db-5813-10da-83a7-ab4e313c4e70/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43910440-211bc50c-9bfd-11e8-88b0-fd8f2714d683.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43910440-211bc50c-9bfd-11e8-88b0-fd8f2714d683.png)
https://user-images.githubusercontent.com/20930745/43910440-211bc50c-9bfd-11e8-88b0-fd8f2714d683.png

Source:
https://user-images.githubusercontent.com/20930745/43910474-34ec3f3a-9bfd-11e8-87d9-a70d373f5960.png
