### ISSUE TITLE
infltr - Infinite Filters

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#9925]
**App Name:** infltr - Infinite Filters
**Bundle ID:** com.Yooshr.Infltr
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=935623257">935623257</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/infltr-infinite-filters/id935623257?mt=8&uo=4">https://itunes.apple.com/us/app/infltr-infinite-filters/id935623257?mt=8&uo=4</a>
**App Version:** 2.15.3
**Seller:** YOOSHR LTD
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/yooshr-ltd/id630611380?uo=4">© Yooshr Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/dc/88/96/dc8896b7-4579-0291-4047-285c5f7bf14f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43910122-418c54ec-9bfc-11e8-9d47-691d8052fff4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43910122-418c54ec-9bfc-11e8-9d47-691d8052fff4.png)
https://user-images.githubusercontent.com/20930745/43910122-418c54ec-9bfc-11e8-9d47-691d8052fff4.png

Source:
https://user-images.githubusercontent.com/20930745/43910158-578e0fec-9bfc-11e8-9d4e-0b9321e43760.png

**Comment by tarkan78** [comment]
Thank You
