### ISSUE TITLE
iTopnews

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#9926]
**App Name:** iTopnews
**Bundle ID:** de.itopnews.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=419081559">419081559</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/itopnews/id419081559?mt=8&uo=4">https://itunes.apple.com/us/app/itopnews/id419081559?mt=8&uo=4</a>
**App Version:** 4.9.4
**Seller:** Michael Gronau
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/michael-gronau/id419081562?uo=4">© Michael Gronau</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple125/v4/1b/d1/5a/1bd15a5b-e75f-3c7a-faa9-4b1d6092fa2c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43909876-a50b5604-9bfb-11e8-807b-d3c01617888e.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43909876-a50b5604-9bfb-11e8-807b-d3c01617888e.png)
https://user-images.githubusercontent.com/20930745/43909876-a50b5604-9bfb-11e8-807b-d3c01617888e.png

Source:
https://user-images.githubusercontent.com/20930745/43909916-bb73f608-9bfb-11e8-8756-79bdec3009a9.png

**Comment by tarkan78** [comment]
Thank You
