### ISSUE TITLE
Py - Learn to Code

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#9927]
**App Name:** Py - Learn to Code
**Bundle ID:** Thundr.Pythonic
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1111105894">1111105894</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/py-learn-to-code/id1111105894?mt=8&uo=4">https://itunes.apple.com/us/app/py-learn-to-code/id1111105894?mt=8&uo=4</a>
**App Version:** 6.2.9
**Seller:** Py Learning, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/py/id1237810946?uo=4">© Py</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/c2/dd/c1/c2ddc1a4-81ec-8a7f-95b4-bbe38e40ad76/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43989733-bff887ca-9d4f-11e8-8973-4cfbc2fb9b11.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43989733-bff887ca-9d4f-11e8-8973-4cfbc2fb9b11.png)
https://user-images.githubusercontent.com/2068130/43989733-bff887ca-9d4f-11e8-8973-4cfbc2fb9b11.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43989740-cee82362-9d4f-11e8-9d68-aa9af15ed170.png
