### ISSUE TITLE
Tiny Wings

### ISSUE THREAD

**Issue by StevenZwicker** [glasklart/hd#9929]
**App Name:** Tiny Wings
**Bundle ID:** com.andreasilliger.tinywings
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=417817520">417817520</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/tiny-wings/id417817520?mt=8&uo=4">https://itunes.apple.com/us/app/tiny-wings/id417817520?mt=8&uo=4</a>
**App Version:** 2.3
**Seller:** Andreas Illiger
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/andreas-illiger/id417817523?uo=4">© Andreas Illiger</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/50/25/7d/50257d84-e15b-f03f-0c7d-8786d424c51e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43990615-ef107c94-9d5d-11e8-9c0b-df1266cbeff2.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43990325-05464afa-9d5b-11e8-8fb1-7697b2bb341a.png)
https://user-images.githubusercontent.com/2068130/43990325-05464afa-9d5b-11e8-8fb1-7697b2bb341a.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43990329-12cc1574-9d5b-11e8-87a8-5ebdf1cc85c0.png

**Comment by 2Qt2beStr8** [comment]
@dreamnet das "Flügelchen" fehlt :-)

**Comment by 2Qt2beStr8** [comment]
credits to dreamnet

![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/43990615-ef107c94-9d5d-11e8-9c0b-df1266cbeff2.png)
https://user-images.githubusercontent.com/20930745/43990615-ef107c94-9d5d-11e8-9c0b-df1266cbeff2.png

Source:
https://user-images.githubusercontent.com/20930745/43990618-04029e0c-9d5e-11e8-940e-6dc949f5bf59.png

**Comment by dreamnet** [comment]
@2Qt2beStr8 Hast recht, uuuups! 😉
