### ISSUE TITLE
ZeroPC Cloud for iPhone

### ISSUE THREAD

**Issue by RikimaruHazuma77** [glasklart/hd#993]
**App Name:** ZeroPC Cloud for iPhone
**Bundle ID:** com.zeropc.zcniphone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=536804716">536804716</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/zeropc-cloud-for-iphone/id536804716?mt=8&uo=4">https://itunes.apple.com/us/app/zeropc-cloud-for-iphone/id536804716?mt=8&uo=4</a>
**App Version:** 2.6.1
**Seller:** ZeroDesktop Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/zerodesktop/id474091536?uo=4">© ZeroDesktop</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple1/v4/b4/b2/5e/b4b25e63-596f-802e-9eb2-965fa2ed6955/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20040201/5c2bc5fa-a453-11e6-8b25-862ae9fbb0f5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20040201/5c2bc5fa-a453-11e6-8b25-862ae9fbb0f5.png)
https://cloud.githubusercontent.com/assets/20930745/20040201/5c2bc5fa-a453-11e6-8b25-862ae9fbb0f5.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20040205/79d8d00c-a453-11e6-9727-dd126fefebe9.png
