### ISSUE TITLE
AT&T TV

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9930]
**App Name:** AT&T TV
**Bundle ID:** com.att.tv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1136238277">1136238277</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/at-t-tv/id1136238277?uo=4">https://apps.apple.com/us/app/at-t-tv/id1136238277?uo=4</a>
**App Version:** 3.0.2
**Seller:** AT&T Services, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/at-t-services-inc/id290854684?uo=4">© AT&T Services, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/7a/21/a1/7a21a13d-4b57-2b16-af59-e69a96838dd3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66270167-76393880-e850-11e9-86d1-1b307f77a08c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/43989698-35823c62-9d4f-11e8-817b-b8a2223e474d.png)
https://user-images.githubusercontent.com/2068130/43989698-35823c62-9d4f-11e8-817b-b8a2223e474d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/43989704-4410f728-9d4f-11e8-921d-d2a4891703f9.png

**Comment by l8er4now** [comment]
Needs an update
**App Name:** AT&T TV
**Bundle ID:** com.att.tv
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1136238277">1136238277</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/at-t-tv/id1136238277?uo=4">https://apps.apple.com/us/app/at-t-tv/id1136238277?uo=4</a>
**App Version:** 3.0.2
**Seller:** AT&T Services, Inc.
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/at-t-services-inc/id290854684?uo=4">© AT&T Services, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen, iPhone11-iPhone11, iPhone11Pro-iPhone11Pro, iPadSeventhGen-iPadSeventhGen, iPadSeventhGenCellular-iPadSeventhGenCellular, iPhone11ProMax-iPhone11ProMax
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/7a/21/a1/7a21a13d-4b57-2b16-af59-e69a96838dd3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/66270167-76393880-e850-11e9-86d1-1b307f77a08c.png)
https://user-images.githubusercontent.com/2068130/66270167-76393880-e850-11e9-86d1-1b307f77a08c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/66270177-86511800-e850-11e9-8845-40aa8fb8e48d.png
