### ISSUE TITLE
Network Radar

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9931]
**App Name:** Network Radar
**Bundle ID:** com.mac-attender.Net-Radar
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=824490166">824490166</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/network-radar/id824490166?mt=8&uo=4">https://itunes.apple.com/us/app/network-radar/id824490166?mt=8&uo=4</a>
**App Version:** 2.0
**Seller:** Witt Software UG (haftungsbeschrankt)
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/witt-software-ug-haftungsbeschrankt/id504700305?uo=4">© Witt Software UG (haftungsbeschrankt)</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple125/v4/b5/95/72/b5957203-210a-484c-cb69-31840c94f526/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/44160653-562e3f00-a0bb-11e8-81ab-b907ab1a09c1.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/44160653-562e3f00-a0bb-11e8-81ab-b907ab1a09c1.png)
https://user-images.githubusercontent.com/20930745/44160653-562e3f00-a0bb-11e8-81ab-b907ab1a09c1.png

Source:
https://user-images.githubusercontent.com/20930745/44160676-69410f00-a0bb-11e8-919c-5382483d5a10.png
