### ISSUE TITLE
Fine - Photo Editor

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9932]
**App Name:** Fine - Photo Editor
**Bundle ID:** com.youthpe.fine
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1391571907">1391571907</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fine-photo-editor/id1391571907?mt=8&uo=4">https://itunes.apple.com/us/app/fine-photo-editor/id1391571907?mt=8&uo=4</a>
**App Version:** 1.4
**Seller:** Zhan QiaoXia
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/zhan-qiaoxia/id1367594057?uo=4">© Zhan QiaoXia</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/e5/ef/8c/e5ef8cb4-0bcf-1904-8058-b265f7e831a1/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44165065-0609a980-a0c8-11e8-8f61-ce096c218680.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44165065-0609a980-a0c8-11e8-8f61-ce096c218680.png)
https://user-images.githubusercontent.com/2068130/44165065-0609a980-a0c8-11e8-8f61-ce096c218680.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44165088-1457c580-a0c8-11e8-89a5-f8e9b0bd59fc.png
