### ISSUE TITLE
1Weather: Forecast and Radar

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9933]
**App Name:** 1Weather: Forecast and Radar
**Bundle ID:** com.onelouder.oneweather
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1044809694">1044809694</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/1weather-forecast-and-radar/id1044809694?mt=8&uo=4">https://itunes.apple.com/us/app/1weather-forecast-and-radar/id1044809694?mt=8&uo=4</a>
**App Version:** 4.2.4
**Seller:** OneLouder
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/onelouder/id455388591?uo=4">© OneLouder</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/a2/34/cc/a234ccf1-dbe1-f593-d3ec-94d522cd2009/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/44161908-f3d73d80-a0be-11e8-98c3-7405adc8956c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/44161908-f3d73d80-a0be-11e8-98c3-7405adc8956c.png)
https://user-images.githubusercontent.com/20930745/44161908-f3d73d80-a0be-11e8-98c3-7405adc8956c.png

Source:
https://user-images.githubusercontent.com/20930745/44161938-05204a00-a0bf-11e8-9b8f-1a17479dda1b.png
