### ISSUE TITLE
Xmart Calculator Pro

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9934]
**App Name:** Xmart Calculator Pro
**Bundle ID:** com.xmartsoft.XmartCalc
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=827740598">827740598</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/xmart-calculator-pro/id827740598?mt=8&uo=4">https://itunes.apple.com/us/app/xmart-calculator-pro/id827740598?mt=8&uo=4</a>
**App Version:** 3.5.3
**Seller:** XH Liu
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/xhliu/id460419472?uo=4">© XHLIU</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/fb/0c/3e/fb0c3e7b-bd91-80da-ec41-78e0abd333fe/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/44161636-39473b00-a0be-11e8-81bf-2b2178876f5d.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/44161636-39473b00-a0be-11e8-81bf-2b2178876f5d.png)
https://user-images.githubusercontent.com/20930745/44161636-39473b00-a0be-11e8-81bf-2b2178876f5d.png

Source:
https://user-images.githubusercontent.com/20930745/44161664-4a904780-a0be-11e8-8214-72a3be1b8fdb.png
