### ISSUE TITLE
WatchChat for WhatsApp

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#9937]
**App Name:** WatchChat for WhatsApp
**Bundle ID:** de.bassapps.WatchChat
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1299535391">1299535391</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/watchchat-for-whatsapp/id1299535391?mt=8&uo=4">https://itunes.apple.com/us/app/watchchat-for-whatsapp/id1299535391?mt=8&uo=4</a>
**App Version:** 1.53
**Seller:** Alexander Nowak
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/alexander-nowak/id942090166?uo=4">© Alexander Nowak</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/4c/ed/85/4ced85b4-f5bd-05dd-9db1-fb9ff8904e1e/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44250963-e7ee9700-a1f6-11e8-887b-d4635a80bd3d.png)

**Comment by tarkan78** [comment]
Thank You

**Comment by BassApps** [comment]
Yo, just came across this. I'm the creator of the app and I feel flattered to seem to be important enough to have an icon added here hahaha

Just a general question; I don't know much about jailbreaking - what iOS version are you running this on? Is WatchChat actually compatible to iOS9? I have never tried so I'm kinda surprised haha

**Comment by dreamnet** [comment]
@BassApps Thanks for the flowers... 😉 
[Here](https://fce365.info/jailbreak-central/) ist a List of jailbreaks currently available. Nothing for iOS12 at this time. 😢
