### ISSUE TITLE
YouCam Perfect-Fotobearbeitung

### ISSUE THREAD

**Issue by tarkan78** [glasklart/hd#9938]
**App Name:** YouCam Perfect - Photo Editor
**Bundle ID:** com.cyberlink.youperfect
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=768469908">768469908</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/youcam-perfect-photo-editor/id768469908?mt=8&uo=4">https://itunes.apple.com/us/app/youcam-perfect-photo-editor/id768469908?mt=8&uo=4</a>
**App Version:** 5.31.0
**Seller:** PERFECT CORP.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/perfect-corp/id1018779369?uo=4">© Perfect Corp.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/09/a6/4a/09a64a53-08ee-c25e-d2c5-aee1e2abd93f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44253834-28531280-a201-11e8-97b0-8b4b27525d19.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44253834-28531280-a201-11e8-97b0-8b4b27525d19.png)
https://user-images.githubusercontent.com/2068130/44253834-28531280-a201-11e8-97b0-8b4b27525d19.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/44253852-36a12e80-a201-11e8-86fc-031f9d5bcd95.png

**Comment by tarkan78** [comment]
Thank You
