### ISSUE TITLE
MyBell Mobile

### ISSUE THREAD

**Issue by nitsujb** [glasklart/hd#9939]
**App Name:** MyBell Mobile
**Bundle ID:** ca.bell.selfserve.mybellmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=850549838">850549838</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/mybell-mobile/id850549838?mt=8&uo=4">https://itunes.apple.com/us/app/mybell-mobile/id850549838?mt=8&uo=4</a>
**App Version:** 4.2.4
**Seller:** Bell Canada
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/bell-canada/id373367642?uo=4">© Bell Canada</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/56/22/1a/56221a5c-b7c6-4ffa-a71a-cda14bcabfcf/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/44297469-49376880-a2d2-11e8-9176-ec4943c924a2.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/44297469-49376880-a2d2-11e8-9176-ec4943c924a2.png)
https://user-images.githubusercontent.com/20930745/44297469-49376880-a2d2-11e8-9176-ec4943c924a2.png

Source:
https://user-images.githubusercontent.com/20930745/44297474-5ce2cf00-a2d2-11e8-9899-d2e37ca43dc3.png
