### ISSUE TITLE
Three

### ISSUE THREAD

**Issue by bluewomble** [glasklart/hd#994]
**App Name:** Three
**Bundle ID:** com.hutchison3g.three
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=393530266">393530266</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/gb/app/three/id393530266?mt=8&uo=4">https://itunes.apple.com/gb/app/three/id393530266?mt=8&uo=4</a>
**App Version:** 2.6.1
**Seller:** Hutchison 3G UK Ltd
**Developer:** <a target="_blank" href=https://itunes.apple.com/gb/developer/three-uk/id393530269?uo=4>© Three UK</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple5/v4/e6/a6/61/e6a661d2-2bab-1e8e-737b-e6256281bf1b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19233856/738ea224-8ee8-11e6-936f-0c08aaaa1010.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/19233856/738ea224-8ee8-11e6-936f-0c08aaaa1010.png)
https://cloud.githubusercontent.com/assets/20930745/19233856/738ea224-8ee8-11e6-936f-0c08aaaa1010.png

Source:
https://cloud.githubusercontent.com/assets/20930745/19233866/7fa4bf76-8ee8-11e6-8c16-a199f98c26ce.png
