### ISSUE TITLE
Forest - Stay focused

### ISSUE THREAD

**Issue by nitsujb** [glasklart/hd#9940]
**App Name:** Forest - Stay focused
**Bundle ID:** com.forestapp.Forest
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=866450515">866450515</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/forest-stay-focused/id866450515?mt=8&uo=4">https://itunes.apple.com/us/app/forest-stay-focused/id866450515?mt=8&uo=4</a>
**App Version:** 4.2.2
**Seller:** SEEKRTECH CO., LTD.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/seekrtech-co-ltd/id469475888?uo=4">© SEEKRTECH CO., LTD.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/af/8c/00/af8c009c-2f24-f23b-2006-9bfef7a52b75/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/44297540-8fd99280-a2d3-11e8-998f-82207da0dece.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/44297540-8fd99280-a2d3-11e8-998f-82207da0dece.png)
https://user-images.githubusercontent.com/20930745/44297540-8fd99280-a2d3-11e8-998f-82207da0dece.png

Source:
https://user-images.githubusercontent.com/20930745/44297545-a1bb3580-a2d3-11e8-9de9-b55b62495446.png
