### ISSUE TITLE
Castanet

### ISSUE THREAD

**Issue by nitsujb** [glasklart/hd#9941]
**App Name:** Castanet
**Bundle ID:** com.castanet.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=383228296">383228296</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/castanet/id383228296?mt=8&uo=4">https://itunes.apple.com/us/app/castanet/id383228296?mt=8&uo=4</a>
**App Version:** 3.0.19
**Seller:** Castanet Media Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/castanet-media-ltd/id383228299?uo=4">© Castanet Media Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/be/b1/59/beb15983-2460-17bf-70b1-51a1db90903c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/44297656-720d2d00-a2d5-11e8-99d1-1c5b1523bada.png)

**Comment by 2Qt2beStr8** [comment]
?
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/44297656-720d2d00-a2d5-11e8-99d1-1c5b1523bada.png)
https://user-images.githubusercontent.com/20930745/44297656-720d2d00-a2d5-11e8-99d1-1c5b1523bada.png

Source:
https://user-images.githubusercontent.com/20930745/44297662-87825700-a2d5-11e8-88c8-714e0bc880a1.png
