### ISSUE TITLE
Juno - A Better Way to Ride

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9942]
**App Name:** Juno - A Better Way to Ride
**Bundle ID:** com.gojuno.rider
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1095607448">1095607448</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/juno-a-better-way-to-ride/id1095607448?mt=8&uo=4">https://itunes.apple.com/us/app/juno-a-better-way-to-ride/id1095607448?mt=8&uo=4</a>
**App Version:** 1.58.0
**Seller:** Juno USA LP
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/juno-usa/id1276181934?uo=4">© Juno USA</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/ec/19/ce/ec19ce8b-90c1-975f-10c1-f8dcc10b02b5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/44538002-6f10a300-a700-11e8-902d-8815d6a76881.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/44538002-6f10a300-a700-11e8-902d-8815d6a76881.png)
https://user-images.githubusercontent.com/20930745/44538002-6f10a300-a700-11e8-902d-8815d6a76881.png

Source:
https://user-images.githubusercontent.com/20930745/44538041-88b1ea80-a700-11e8-9a51-4a16248ba900.png
