### ISSUE TITLE
British Airways for iPad

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9944]
**App Name:** British Airways for iPad
**Bundle ID:** com.britishairways.BAFlightsPlus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1001908191">1001908191</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/british-airways-for-ipad/id1001908191?mt=8&uo=4">https://itunes.apple.com/us/app/british-airways-for-ipad/id1001908191?mt=8&uo=4</a>
**App Version:** 1.6
**Seller:** British Airways Plc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/british-airways-plc/id284793092?uo=4">© British Airways Plc</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/2b/59/c6/2b59c6f3-3adc-1371-ee50-6e9220d5df9d/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/44626431-7c09de00-a91c-11e8-8024-6cbecc75de01.png)

**Comment by Sly-Fi** [comment]
Same icon as iPhone app in issue #7196

**Comment by dreamnet** [comment]
Icon by @Trubbel
