### ISSUE TITLE
King Soopers

### ISSUE THREAD

**Issue by Sly-Fi** [glasklart/hd#9945]
**App Name:** King Soopers
**Bundle ID:** com.kroger.kingsoopers
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=584397734">584397734</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/king-soopers/id584397734?mt=8&uo=4">https://itunes.apple.com/us/app/king-soopers/id584397734?mt=8&uo=4</a>
**App Version:** 14.3.1
**Seller:** The Kroger Co.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-kroger-co/id403901189?uo=4">© The Kroger Co.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/5f/6b/35/5f6b35cc-1b99-8f73-5baa-5971f34df7b3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45232168-bdac6880-b2ce-11e8-969d-6977d241fd9e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45232168-bdac6880-b2ce-11e8-969d-6977d241fd9e.png)
https://user-images.githubusercontent.com/2068130/45232168-bdac6880-b2ce-11e8-969d-6977d241fd9e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45232182-cd2bb180-b2ce-11e8-8ca5-f62ca525a6f6.png
