### ISSUE TITLE
my Alpha wallet

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9946]
**App Name:** my Alpha wallet
**Bundle ID:** gr.alpha.myalphawallet
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1050902503">1050902503</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-alpha-wallet/id1050902503?mt=8&uo=4">https://itunes.apple.com/us/app/my-alpha-wallet/id1050902503?mt=8&uo=4</a>
**App Version:** 2.6.0
**Seller:** Alpha Bank
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/alpha-bank-a-e/id378674534?uo=4">© Alpha Bank A.E.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/00/ae/21/00ae21f1-683c-837f-27de-afae1a77a8aa/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45238058-c86ff900-b2e0-11e8-8ff1-feb4b1333315.png)

**Comment by XPEric** [comment]
![alphawallet](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/45233248-17496e80-b2a0-11e8-9df7-2db55a72ed39.png)
https://user-images.githubusercontent.com/2313873/45233248-17496e80-b2a0-11e8-9df7-2db55a72ed39.png
___
Source:
https://user-images.githubusercontent.com/2313873/45233249-17496e80-b2a0-11e8-9be2-806783c94ea4.png

**Comment by dreamnet** [comment]
❓ 
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45238058-c86ff900-b2e0-11e8-8ff1-feb4b1333315.png)
https://user-images.githubusercontent.com/2068130/45238058-c86ff900-b2e0-11e8-8ff1-feb4b1333315.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45238076-da519c00-b2e0-11e8-8b6a-696d680577d8.png
