### ISSUE TITLE
AdGuard Pro — adblock

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9947]
**App Name:** AdGuard Pro — adblock
**Bundle ID:** com.adguard.AdguardPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1126386264">1126386264</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/adguard-pro-adblock/id1126386264?mt=8&uo=4">https://itunes.apple.com/us/app/adguard-pro-adblock/id1126386264?mt=8&uo=4</a>
**App Version:** 2.1.1
**Seller:** Performiks OOO
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/performix/id1047223161?uo=4">© Performix</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple115/v4/cf/2a/1e/cf2a1e61-daba-1f9e-c67d-ec02e20c5151/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45232298-37dced00-b2cf-11e8-88bf-2d584f27abc9.png)

**Comment by dreamnet** [comment]
Same as #7493.
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45232298-37dced00-b2cf-11e8-88bf-2d584f27abc9.png)
https://user-images.githubusercontent.com/2068130/45232298-37dced00-b2cf-11e8-88bf-2d584f27abc9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45232329-52af6180-b2cf-11e8-817c-d48c100ab6b8.png
