### ISSUE TITLE
Fusion 360

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9948]
**App Name:** Fusion 360
**Bundle ID:** com.autodesk.ios.fusion360
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=991074843">991074843</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/fusion-360/id991074843?mt=8&uo=4">https://itunes.apple.com/us/app/fusion-360/id991074843?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Autodesk
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/autodesk-inc/id295089690?uo=4">© Autodesk Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/d1/8e/7b/d18e7b31-6d11-bb20-5bb1-677f65238781/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45250367-16611d00-b332-11e8-867e-815e9df64552.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45250367-16611d00-b332-11e8-867e-815e9df64552.png)
https://user-images.githubusercontent.com/2068130/45250367-16611d00-b332-11e8-867e-815e9df64552.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45250378-2678fc80-b332-11e8-9708-aa97dcd7045c.png
