### ISSUE TITLE
Focalmark

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9949]
**App Name:** Focalmark
**Bundle ID:** com.focalmark.app
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1161230451">1161230451</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/focalmark/id1161230451?mt=8&uo=4">https://itunes.apple.com/us/app/focalmark/id1161230451?mt=8&uo=4</a>
**App Version:** 2.6
**Seller:** Focalmark Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/focalmark-ltd/id1210452416?uo=4">© Focalmark Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/db/ca/10/dbca10ab-febd-16e4-0fd2-d511c676b6f9/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45234256-74134c00-b2d5-11e8-82dc-248f21aa4c92.png)

**Comment by XPEric** [comment]
![focalmark](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/45233378-9179f300-b2a0-11e8-9db2-8780692cf485.png)
https://user-images.githubusercontent.com/2313873/45233378-9179f300-b2a0-11e8-9db2-8780692cf485.png
___
Source:
https://user-images.githubusercontent.com/2313873/45233379-9179f300-b2a0-11e8-970a-e61f7628aa55.png

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45234256-74134c00-b2d5-11e8-82dc-248f21aa4c92.png)
https://user-images.githubusercontent.com/2068130/45234256-74134c00-b2d5-11e8-82dc-248f21aa4c92.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45234281-855c5880-b2d5-11e8-8c78-1a748a963e69.png
