### ISSUE TITLE
Official Kodi Remote

### ISSUE THREAD

**Issue by RikimaruHazuma77** [glasklart/hd#995]
**App Name:** Official Kodi Remote
**Bundle ID:** it.joethefox.XBMC-Remote
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=520480364">520480364</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/official-kodi-remote/id520480364?mt=8&uo=4">https://itunes.apple.com/us/app/official-kodi-remote/id520480364?mt=8&uo=4</a>
**App Version:** 1.5.5
**Seller:** Giovanni Messina
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/joethefox/id520480367?uo=4>© joethefox</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/thumb/Purple49/v4/c9/20/81/c9208131-ca1a-b093-6277-bff8fa9cb63c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18477667/b7ad108c-79ce-11e6-8810-0176fbf3989c.png)

**Comment by 2Qt2beStr8** [comment]
needs update

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/18477667/b7ad108c-79ce-11e6-8810-0176fbf3989c.png)
https://cloud.githubusercontent.com/assets/20930745/18477667/b7ad108c-79ce-11e6-8810-0176fbf3989c.png

Source:
https://cloud.githubusercontent.com/assets/20930745/18477696/d357d59c-79ce-11e6-8417-3a436e308f4c.png
