### ISSUE TITLE
Dancing Ballz: Magic Beat

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9950]
**App Name:** Dancing Ballz: Magic Beat
**Bundle ID:** com.amanotes.ttmios
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1265019448">1265019448</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/dancing-ballz-magic-beat/id1265019448?uo=4">https://apps.apple.com/us/app/dancing-ballz-magic-beat/id1265019448?uo=4</a>
**App Version:** 1.8.0
**Seller:** Amanotes Pte Ltd
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/amanotes-pte-ltd/id1441389613?uo=4">© Amanotes Pte. Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR, iPad812-iPad812, iPad834-iPad834, iPad856-iPad856, iPad878-iPad878, iPadMini5-iPadMini5, iPadMini5Cellular-iPadMini5Cellular, iPadAir3-iPadAir3, iPadAir3Cellular-iPadAir3Cellular, iPodTouchSeventhGen-iPodTouchSeventhGen
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/db/8f/9b/db8f9b87-9360-0f6f-dbbc-bab3a2e0b2c4/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60381822-f6cee880-9a5a-11e9-94b7-111ffdc82952.png)

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/60381822-f6cee880-9a5a-11e9-94b7-111ffdc82952.png)
https://user-images.githubusercontent.com/2068130/60381822-f6cee880-9a5a-11e9-94b7-111ffdc82952.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/60381832-064e3180-9a5b-11e9-98a2-ca284fd3a1e7.png
