### ISSUE TITLE
Helix Jump

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9951]
**App Name:** Helix Jump
**Bundle ID:** com.h8games.falldown
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1345968745">1345968745</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/helix-jump/id1345968745?mt=8&uo=4">https://itunes.apple.com/us/app/helix-jump/id1345968745?mt=8&uo=4</a>
**App Version:** 1.1.3
**Seller:** Voodoo
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/voodoo/id714804730?uo=4">© Voodoo</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/e7/7f/33/e77f337e-5962-86b8-2ccd-a9a8e9b4f93f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58636401-84020e80-82f0-11e9-95b5-aff625664819.png)

**Comment by 2Qt2beStr8** [comment]
I can't do it better .. the origina artwork ist very bad … so the Icon is also bad ;-(
![](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/58636401-84020e80-82f0-11e9-95b5-aff625664819.png)
https://user-images.githubusercontent.com/20930745/58636401-84020e80-82f0-11e9-95b5-aff625664819.png

Source:
https://user-images.githubusercontent.com/20930745/58636406-86646880-82f0-11e9-81de-9431ef6de995.png
