### ISSUE TITLE
Εορτές

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9952]
**App Name:** Εορτές
**Bundle ID:** com.yourcompany.Eortes
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=331965174">331965174</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/%CE%B5%CE%BF%CF%81%CF%84%CE%AD%CF%82/id331965174?mt=8&uo=4">https://itunes.apple.com/us/app/%CE%B5%CE%BF%CF%81%CF%84%CE%AD%CF%82/id331965174?mt=8&uo=4</a>
**App Version:** 2.5.4
**Seller:** Nikos Bitoulas
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/nickbit/id331965177?uo=4">© nickbit</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/e8/ad/76/e8ad76a7-1daa-747c-2df6-45ab4f71b024/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45231975-32cb6e00-b2ce-11e8-8e31-a071fd223f70.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45231975-32cb6e00-b2ce-11e8-8e31-a071fd223f70.png)
https://user-images.githubusercontent.com/2068130/45231975-32cb6e00-b2ce-11e8-8e31-a071fd223f70.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45232005-437be400-b2ce-11e8-8624-f0a57afd4ba5.png
