### ISSUE TITLE
ViewBug - Photography

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9955]
**App Name:** ViewBug - Photography
**Bundle ID:** com.viewbug.mobileapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1100927060">1100927060</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/viewbug-photography/id1100927060?mt=8&uo=4">https://itunes.apple.com/us/app/viewbug-photography/id1100927060?mt=8&uo=4</a>
**App Version:** 1.16
**Seller:** Golozo, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/viewbug/id1100927059?uo=4">© ViewBug</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/48/05/42/480542f0-8e76-4615-84d4-21ff965425db/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45233413-f3535080-b2d2-11e8-88a8-f03e52b55f19.png)

**Comment by XPEric** [comment]
![viewbug](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2313873/45233012-6ba01e80-b29f-11e8-9f39-d2c30b3e87c6.png)
https://user-images.githubusercontent.com/2313873/45233012-6ba01e80-b29f-11e8-9f39-d2c30b3e87c6.png
___
Source:
https://user-images.githubusercontent.com/2313873/45233013-6ba01e80-b29f-11e8-8a87-5e6c4d098f31.png

**Comment by dreamnet** [comment]
@XPEric Good, but a bit too big.
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45233413-f3535080-b2d2-11e8-88a8-f03e52b55f19.png)
https://user-images.githubusercontent.com/2068130/45233413-f3535080-b2d2-11e8-88a8-f03e52b55f19.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45233432-049c5d00-b2d3-11e8-826e-0a1cfa97e4d6.png
