### ISSUE TITLE
Pricepulse - Always buy low!

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9957]
**App Name:** Pricepulse - Always buy low!
**Bundle ID:** com.applyai.realdeal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1379795991">1379795991</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/pricepulse-always-buy-low/id1379795991?uo=4">https://apps.apple.com/us/app/pricepulse-always-buy-low/id1379795991?uo=4</a>
**App Version:** 2.22
**Seller:** Apply ai Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/apply-ai-inc/id1262088221?uo=4">© Apply ai Inc</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/38/1c/aa/381caaa0-f7ec-50a5-b314-5e1dcf10bb94/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85228711-484b5280-b3e5-11ea-92e3-c0c8220248ed.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45233066-de29f200-b2d1-11e8-95e0-4098bf3ef4fb.png)
https://user-images.githubusercontent.com/2068130/45233066-de29f200-b2d1-11e8-95e0-4098bf3ef4fb.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45233091-f1d55880-b2d1-11e8-8a13-bdbda0ce7030.png

**Comment by l8er4now** [comment]
Needs an update.

**App Name:** Pricepulse - Always buy low!
**Bundle ID:** com.applyai.realdeal
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1379795991">1379795991</a>
**iTunes URL:** <a target="_blank" href="https://apps.apple.com/us/app/pricepulse-always-buy-low/id1379795991?uo=4">https://apps.apple.com/us/app/pricepulse-always-buy-low/id1379795991?uo=4</a>
**App Version:** 2.22
**Seller:** Apply ai Inc
**Developer:** <a target="_blank" href="https://apps.apple.com/us/developer/apply-ai-inc/id1262088221?uo=4">© Apply ai Inc</a>
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/38/1c/aa/381caaa0-f7ec-50a5-b314-5e1dcf10bb94/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
![-large](https://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/85228711-484b5280-b3e5-11ea-92e3-c0c8220248ed.png)
https://user-images.githubusercontent.com/2068130/85228711-484b5280-b3e5-11ea-92e3-c0c8220248ed.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/85228722-60bb6d00-b3e5-11ea-8d39-0e9c98541f7c.png
