### ISSUE TITLE
File Manager PRO - Documents

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9959]
**App Name:** File Manager PRO - Documents
**Bundle ID:** com.appaspect.PDFCreatorDocumentEditorPro
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=760489885">760489885</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/file-manager-pro-documents/id760489885?mt=8&uo=4">https://itunes.apple.com/us/app/file-manager-pro-documents/id760489885?mt=8&uo=4</a>
**App Version:** 7.2
**Seller:** APPASPECT TECHNOLOGIES PRIVATE LIMITED
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/appaspect-technologies-pvt-ltd/id962656494?uo=4">© AppAspect Technologies Pvt. Ltd.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple115/v4/e7/4c/1d/e74c1d69-f038-f9b4-1aa5-09b4244440e2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45232727-b4240000-b2d0-11e8-8e79-1327f67da33c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45232727-b4240000-b2d0-11e8-8e79-1327f67da33c.png)
https://user-images.githubusercontent.com/2068130/45232727-b4240000-b2d0-11e8-8e79-1327f67da33c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45232743-c2721c00-b2d0-11e8-8570-d4f29e3b1288.png
