### ISSUE TITLE
Flink - Calendar Note

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9961]
**App Name:** Flink - Calendar Note
**Bundle ID:** com.saltycrackers.Flink
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1234490078">1234490078</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/flink-calendar-note/id1234490078?mt=8&uo=4">https://itunes.apple.com/us/app/flink-calendar-note/id1234490078?mt=8&uo=4</a>
**App Version:** 1.9
**Seller:** SaltyCrackers Co., Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/saltycrackers-co-ltd/id956440527?uo=4">© SaltyCrackers Co., Ltd.</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple125/v4/28/c4/5f/28c45fea-0624-ed8d-0ec7-fb5822ed1c47/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45233788-221df680-b2d4-11e8-9622-6c8c12f9663c.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45233788-221df680-b2d4-11e8-9622-6c8c12f9663c.png)
https://user-images.githubusercontent.com/2068130/45233788-221df680-b2d4-11e8-9622-6c8c12f9663c.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45233797-306c1280-b2d4-11e8-9a29-26c74a2a3117.png
