### ISSUE TITLE
Schwab Mobile

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9963]
**App Name:** Schwab Mobile
**Bundle ID:** com.schwab.schwabmobile
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=407358186">407358186</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/schwab-mobile/id407358186?mt=8&uo=4">https://itunes.apple.com/us/app/schwab-mobile/id407358186?mt=8&uo=4</a>
**App Version:** 8.5.1
**Seller:** The Charles Schwab Corporation
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/the-charles-schwab-corporation/id404050704?uo=4">© The Charles Schwab Corporation</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/4e/69/a7/4e69a756-ee6f-6021-ed39-9bab1397a859/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45230851-7f14af00-b2ca-11e8-94a3-3e6419bb53e9.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45230851-7f14af00-b2ca-11e8-94a3-3e6419bb53e9.png)
https://user-images.githubusercontent.com/2068130/45230851-7f14af00-b2ca-11e8-94a3-3e6419bb53e9.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45230867-918ee880-b2ca-11e8-8367-14fd660c4a7f.png
