### ISSUE TITLE
Enlight Pixaloop

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9965]
**App Name:** Enlight Pixaloop
**Bundle ID:** com.lightricks.Enlight-Phoenix
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1381206010">1381206010</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/enlight-pixaloop/id1381206010?mt=8&uo=4">https://itunes.apple.com/us/app/enlight-pixaloop/id1381206010?mt=8&uo=4</a>
**App Version:** 1.0.7
**Seller:** Lightricks Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lightricks-ltd/id606310584?uo=4">© Lightricks Ltd.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/9f/32/d4/9f32d462-81ef-466b-6ac8-b3a83c7864b5/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45930425-6f4ec900-bf60-11e8-858a-e273201af272.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45930425-6f4ec900-bf60-11e8-858a-e273201af272.png)
https://user-images.githubusercontent.com/2068130/45930425-6f4ec900-bf60-11e8-858a-e273201af272.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45930429-7e357b80-bf60-11e8-9697-0a99b91dce58.png

**Comment by LelandBowen** [comment]
To get the best photos for yourself you can use [url=https://techbigs.com/enlight-pixaloop.html]enlight pixaloop apk[/url] at techbigs to edit your photos to be the most magical.
