### ISSUE TITLE
Huji Cam

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9966]
**App Name:** Huji Cam
**Bundle ID:** com.jbinary.hujicam
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=781383622">781383622</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/huji-cam/id781383622?mt=8&uo=4">https://itunes.apple.com/us/app/huji-cam/id781383622?mt=8&uo=4</a>
**App Version:** 2.2
**Seller:** Manhole, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/manhole-inc/id1345885776?uo=4">© Manhole, Inc.</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/87/19/b3/8719b38f-b0c6-9d70-4236-b9a4113853ee/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/45568525-2fe7f480-b85d-11e8-90c9-eac96ccdb57c.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/45568525-2fe7f480-b85d-11e8-90c9-eac96ccdb57c.png)
https://user-images.githubusercontent.com/20930745/45568525-2fe7f480-b85d-11e8-90c9-eac96ccdb57c.png

Source:
https://user-images.githubusercontent.com/20930745/45568566-4a21d280-b85d-11e8-9aeb-3e7b8afe49e0.png
