### ISSUE TITLE
PLOTAVERSE•Create Your Reality

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9967]
**App Name:** PLOTAVERSE•Create Your Reality
**Bundle ID:** com.plotagraphs.Plotagraph
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1244669793">1244669793</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/plotaverse-create-your-reality/id1244669793?mt=8&uo=4">https://itunes.apple.com/us/app/plotaverse-create-your-reality/id1244669793?mt=8&uo=4</a>
**App Version:** 2.9
**Seller:** PLOTAGRAPH, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/plotagraph-inc/id1244669792?uo=4">© PLOTAGRAPH, Inc.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/5f/28/0a/5f280aa9-19d1-fb9c-4f2a-3c68593ba7c6/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/45570198-1bf2c180-b862-11e8-9cf0-3f92856ceef3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/45570198-1bf2c180-b862-11e8-9cf0-3f92856ceef3.png)
https://user-images.githubusercontent.com/20930745/45570198-1bf2c180-b862-11e8-9cf0-3f92856ceef3.png

Source:
https://user-images.githubusercontent.com/20930745/45570221-2dd46480-b862-11e8-911b-b87505a39e8c.png
