### ISSUE TITLE
Lens Distortions®

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9968]
**App Name:** Lens Distortions®
**Bundle ID:** com.lensdistortions.Lens-Distortions
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=938026822">938026822</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/lens-distortions/id938026822?mt=8&uo=4">https://itunes.apple.com/us/app/lens-distortions/id938026822?mt=8&uo=4</a>
**App Version:** 3.1.0
**Seller:** Lens Distortions, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lens-distortions-llc/id938026821?uo=4">© Lens Distortions, LLC</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is3-ssl.mzstatic.com/image/thumb/Purple118/v4/6f/fe/2f/6ffe2f8a-a34d-ece1-cf23-5838e3f57c37/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/45569893-3b3d1f00-b861-11e8-9459-a76779841861.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/45569893-3b3d1f00-b861-11e8-9459-a76779841861.png)
https://user-images.githubusercontent.com/20930745/45569893-3b3d1f00-b861-11e8-9459-a76779841861.png

Source:
https://user-images.githubusercontent.com/20930745/45569921-514adf80-b861-11e8-860e-8e6f6cb57efe.png
