### ISSUE TITLE
Enlight Quickshot

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9969]
**App Name:** Enlight Quickshot
**Bundle ID:** com.lightricks.Enlight-Photos
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1254875992">1254875992</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/enlight-quickshot/id1254875992?mt=8&uo=4">https://itunes.apple.com/us/app/enlight-quickshot/id1254875992?mt=8&uo=4</a>
**App Version:** 1.2.8
**Seller:** Lightricks Ltd.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/lightricks-ltd/id606310584?uo=4">© Lightricks Ltd.</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/ae/45/6f/ae456f2a-858b-b7e4-1abb-de48c72919ac/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45931117-4f6fd300-bf69-11e8-8e8f-25ca891c2a6e.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45931117-4f6fd300-bf69-11e8-8e8f-25ca891c2a6e.png)
https://user-images.githubusercontent.com/2068130/45931117-4f6fd300-bf69-11e8-8e8f-25ca891c2a6e.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45931121-5f87b280-bf69-11e8-8960-43953f94f8ff.png
