### ISSUE TITLE
Photo Investigator: Edit, Remove GPS EXIF Metadata

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9971]
**App Name:** Photo Investigator: Edit, Remove GPS EXIF Metadata
**Bundle ID:** com.augmen.Investigator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=571574618">571574618</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/photo-investigator-edit-remove-gps-exif-metadata/id571574618?mt=8&uo=4">https://itunes.apple.com/us/app/photo-investigator-edit-remove-gps-exif-metadata/id571574618?mt=8&uo=4</a>
**App Version:** 5.2.1
**Seller:** Daniel Anderson
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/daniel-anderson/id434333497?uo=4">© Daniel Anderson</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple122/v4/50/7b/4b/507b4b65-5464-0a2e-3d81-93dc8eb68f12/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45929768-8ee0f400-bf56-11e8-82ae-d9134f323c48.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45929768-8ee0f400-bf56-11e8-82ae-d9134f323c48.png)
https://user-images.githubusercontent.com/2068130/45929768-8ee0f400-bf56-11e8-82ae-d9134f323c48.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45929777-9d2f1000-bf56-11e8-8a8b-260c9d1601f3.png
