### ISSUE TITLE
My Bakery Club

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9972]
**App Name:** My Bakery Club
**Bundle ID:** com.crm.app.rewards
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1075394689">1075394689</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/my-bakery-club/id1075394689?mt=8&uo=4">https://itunes.apple.com/us/app/my-bakery-club/id1075394689?mt=8&uo=4</a>
**App Version:** 2.0.18
**Seller:** CRM.COM Software Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/crm-com-ltd/id1075394688?uo=4">© CRM.COM Ltd</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/ae/ba/f8/aebaf8a3-965e-b28e-fd43-1787347716be/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45929439-03656400-bf52-11e8-8c5e-d3af93a2566d.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45929439-03656400-bf52-11e8-8c5e-d3af93a2566d.png)
https://user-images.githubusercontent.com/2068130/45929439-03656400-bf52-11e8-8c5e-d3af93a2566d.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45929443-111ae980-bf52-11e8-8f0b-b0518c1d982a.png
