### ISSUE TITLE
Pharmacies In Cyprus

### ISSUE THREAD

**Issue by STiXzoOR** [glasklart/hd#9973]
**App Name:** Pharmacies In Cyprus
**Bundle ID:** com.geoathien.PharmaciesInCyprus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1039632848">1039632848</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/pharmacies-in-cyprus/id1039632848?mt=8&uo=4">https://itunes.apple.com/us/app/pharmacies-in-cyprus/id1039632848?mt=8&uo=4</a>
**App Version:** 1.0.2
**Seller:** George Athienitis
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/george-athienitis/id1039632847?uo=4">© George Athienitis</a>
**Supported Devices:** iPhone3GS-iPhone-3GS, iPhone4-iPhone4, iPodTouchFourthGen-iPodTouchFourthGen, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple19/v4/ef/a4/09/efa4098c-e057-274f-9c00-f3587f91f505/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/45569459-e3ea7f00-b85f-11e8-85cd-04aa82ad7304.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/45569459-e3ea7f00-b85f-11e8-85cd-04aa82ad7304.png)
https://user-images.githubusercontent.com/20930745/45569459-e3ea7f00-b85f-11e8-85cd-04aa82ad7304.png

Source:
https://user-images.githubusercontent.com/20930745/45569495-f95fa900-b85f-11e8-9384-98fad604b676.png
