### ISSUE TITLE
Desmos Graphing Calculator

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9975]
**App Name:** Desmos Graphing Calculator
**Bundle ID:** com.desmos.Desmos
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=653517540">653517540</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/desmos-graphing-calculator/id653517540?mt=8&uo=4">https://itunes.apple.com/us/app/desmos-graphing-calculator/id653517540?mt=8&uo=4</a>
**App Version:** 3.2.2
**Seller:** Desmos, Inc.
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/desmos/id653517543?uo=4">© Desmos</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple115/v4/e3/41/3f/e3413f59-3214-4e94-d816-dec118b7e24b/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/45915409-a5068b80-be54-11e8-845d-dac877ca7e50.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/45915409-a5068b80-be54-11e8-845d-dac877ca7e50.png)
https://user-images.githubusercontent.com/20930745/45915409-a5068b80-be54-11e8-845d-dac877ca7e50.png

Source:
https://user-images.githubusercontent.com/20930745/45915422-b6e82e80-be54-11e8-9fa1-fad3a502662e.png
