### ISSUE TITLE
AWS Console

### ISSUE THREAD

**Issue by XPEric** [glasklart/hd#9976]
**App Name:** AWS Console
**Bundle ID:** com.amazonaws.mobileConsole
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=580990573">580990573</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/aws-console/id580990573?mt=8&uo=4">https://itunes.apple.com/us/app/aws-console/id580990573?mt=8&uo=4</a>
**App Version:** 1.19.6
**Seller:** AMZN Mobile LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/amzn-mobile-llc/id297606954?uo=4">© AMZN Mobile LLC</a>
**Supported Devices:** iPhone4-iPhone4, iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/5e/33/91/5e3391fd-3a72-df82-dbe3-cf70710a2b5c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/45915349-c61aac80-be53-11e8-9c18-21b84df1eabe.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/45915349-c61aac80-be53-11e8-9c18-21b84df1eabe.png)
https://user-images.githubusercontent.com/20930745/45915349-c61aac80-be53-11e8-9c18-21b84df1eabe.png

Source:
https://user-images.githubusercontent.com/20930745/45915356-db8fd680-be53-11e8-9d79-15c7bd53a55a.png
