### ISSUE TITLE
DKB-Banking

### ISSUE THREAD

**Issue by chrismarino84** [glasklart/hd#9977]
**App Name:** DKB-Banking
**Bundle ID:** de.dkb.portalapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=953939164">953939164</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dkb-banking/id953939164?mt=8&uo=4">https://itunes.apple.com/us/app/dkb-banking/id953939164?mt=8&uo=4</a>
**App Version:** 2.6.0
**Seller:** Deutsche Kreditbank AG
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/deutsche-kreditbank-ag/id580150855?uo=4">© Deutsche Kreditbank AG</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/d2/90/dc/d290dc3e-5f8b-2156-675a-9a1c67f79c27/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![de dkb portalapp-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45929398-54c12380-bf51-11e8-83fb-06335caf5f76.png)

**Comment by dreamnet** [comment]
![de dkb portalapp-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45929398-54c12380-bf51-11e8-83fb-06335caf5f76.png)
https://user-images.githubusercontent.com/2068130/45929398-54c12380-bf51-11e8-83fb-06335caf5f76.png
--- ---
Source:
![de dkb portalapp_source](https://user-images.githubusercontent.com/2068130/45929403-6276a900-bf51-11e8-937d-82d9e9701a31.png)
