### ISSUE TITLE
[DUPLICATE of #7197]

### ISSUE THREAD

**Issue by chrismarino84** [glasklart/hd#9978]
[DUPLICATE of #7197]
**App Name:** N26 – The Mobile Bank
**Bundle ID:** de.no26.Number26
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=956857223">956857223</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/n26-the-mobile-bank/id956857223?mt=8&uo=4">https://itunes.apple.com/us/app/n26-the-mobile-bank/id956857223?mt=8&uo=4</a>
**App Version:** 3.15
**Seller:** N26 GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/n26-gmbh/id897464435?uo=4">© N26 GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/7b/4d/be/7b4dbe26-b45e-b3fe-db22-db4b6c6067e2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
\#\#\# THIS IS FOR GLASKLART MAINTAINERS DO NOT MODIFY THIS LINE OR WRITE BELOW IT. CONTRIBUTIONS AND COMMENTS SHOULD BE IN A SEPARATE COMMENT. \#\#\#

**Comment by dreamnet** [comment]
@chrismarino84 Yes, I have reopened and updated #7197.
