### ISSUE TITLE
Eurowings

### ISSUE THREAD

**Issue by chrismarino84** [glasklart/hd#9980]
**App Name:** Eurowings
**Bundle ID:** com.wings.iPhone
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1063273316">1063273316</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/eurowings/id1063273316?mt=8&uo=4">https://itunes.apple.com/us/app/eurowings/id1063273316?mt=8&uo=4</a>
**App Version:** 4.5.0
**Seller:** Eurowings GmbH
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/eurowings-gmbh/id1063273315?uo=4">© Eurowings GmbH</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/94/3c/e5/943ce571-61fa-f722-a062-4c3628f07102/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45929612-753ead00-bf54-11e8-990e-747cd6222689.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/45929612-753ead00-bf54-11e8-990e-747cd6222689.png)
https://user-images.githubusercontent.com/2068130/45929612-753ead00-bf54-11e8-990e-747cd6222689.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/45929614-84255f80-bf54-11e8-9105-ff2405df8c69.png
