### ISSUE TITLE
Super Habit Tracker & Streaks

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9982]
**App Name:** Super Habit Tracker & Streaks
**Bundle ID:** com.kevinquisquater.Habits
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1403517519">1403517519</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/super-habit-tracker-streaks/id1403517519?mt=8&uo=4">https://itunes.apple.com/us/app/super-habit-tracker-streaks/id1403517519?mt=8&uo=4</a>
**App Version:** 1.3.1
**Seller:** Kevin Quisquater
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/kevin-quisquater/id997825935?uo=4">© Kevin Quisquater</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/69/ed/c4/69edc4b1-fab2-41ea-53ec-d384536be09c/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/46883393-3ebcc980-ce52-11e8-9d6d-9c838506a338.png)

**Comment by 2Qt2beStr8** [comment]
?
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/46883393-3ebcc980-ce52-11e8-9d6d-9c838506a338.png)
https://user-images.githubusercontent.com/20930745/46883393-3ebcc980-ce52-11e8-9d6d-9c838506a338.png

Source:
https://user-images.githubusercontent.com/20930745/46883439-572ce400-ce52-11e8-9392-daa441afa885.png
