### ISSUE TITLE
HealthFace

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9983]
**App Name:** HealthFace
**Bundle ID:** com.healthfaceapp.healthface
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1176374647">1176374647</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/healthface/id1176374647?mt=8&uo=4">https://itunes.apple.com/us/app/healthface/id1176374647?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Crunchy Bagel Pty Ltd
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/crunchy-bagel/id1084571682?uo=4">© Crunchy Bagel</a>
**Supported Devices:** iPhone5-iPhone5, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is2-ssl.mzstatic.com/image/thumb/Purple128/v4/37/23/1a/37231aa8-504d-7b90-f7ab-41503abb6bc3/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/46154994-98c86700-c276-11e8-9809-e04e0e514ca5.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/46154994-98c86700-c276-11e8-9809-e04e0e514ca5.png)
https://user-images.githubusercontent.com/20930745/46154994-98c86700-c276-11e8-9809-e04e0e514ca5.png

Source:
https://user-images.githubusercontent.com/20930745/46155025-ada4fa80-c276-11e8-9e1a-2cf473b739f4.png
