### ISSUE TITLE
Upright Fantasy News

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9984]
**App Name:** Upright Fantasy News
**Bundle ID:** com.DanielKoza.RotoReWrite
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1333375442">1333375442</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/upright-fantasy-news/id1333375442?mt=8&uo=4">https://itunes.apple.com/us/app/upright-fantasy-news/id1333375442?mt=8&uo=4</a>
**App Version:** 1.0.3
**Seller:** Dan Koza
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/dan-koza/id1060882131?uo=4">© Dan Koza</a>
**Supported Devices:** iPhone5-iPhone5, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/e8/a2/f8/e8a2f815-2b2b-6cba-8282-97e65dfa30c0/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/46155496-ba761e00-c277-11e8-8150-9221619ee7d0.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/46155496-ba761e00-c277-11e8-8150-9221619ee7d0.png)
https://user-images.githubusercontent.com/20930745/46155496-ba761e00-c277-11e8-8150-9221619ee7d0.png

Source:
https://user-images.githubusercontent.com/20930745/46155522-cbbf2a80-c277-11e8-8284-e33ebe884dea.png
