### ISSUE TITLE
Workouts++

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9985]
**App Name:** Workouts++
**Bundle ID:** com.crossforward.WorkoutPlusPlus
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1182551958">1182551958</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/workouts/id1182551958?mt=8&uo=4">https://itunes.apple.com/us/app/workouts/id1182551958?mt=8&uo=4</a>
**App Version:** 2.1
**Seller:** Cross Forward Consulting, LLC
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/cross-forward-consulting-llc/id295660206?uo=4">© Cross Forward Consulting, LLC</a>
**Supported Devices:** iPhone5s-iPhone5s, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="https://is1-ssl.mzstatic.com/image/thumb/Purple118/v4/3c/e8/d0/3ce8d075-78c8-1f05-4deb-5f4ea2769c61/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/46155746-50aa4400-c278-11e8-846a-066f21e49ec3.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/46155746-50aa4400-c278-11e8-846a-066f21e49ec3.png)
https://user-images.githubusercontent.com/20930745/46155746-50aa4400-c278-11e8-846a-066f21e49ec3.png

Source:
https://user-images.githubusercontent.com/20930745/46155778-63bd1400-c278-11e8-85ac-48a2d8823d33.png
