### ISSUE TITLE
Paper Toss Boss

### ISSUE THREAD

**Issue by ghost** [glasklart/hd#999]
**App Name:** Paper Toss Boss
**Bundle ID:** com.backflipstudios.papertoss2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=477846014">477846014</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/paper-toss-boss/id477846014?mt=8&uo=4">https://itunes.apple.com/us/app/paper-toss-boss/id477846014?mt=8&uo=4</a>
**App Version:** 2.0.5
**Seller:** Backflip Studios
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/backflip-studios/id315282170?uo=4">© Backflip Studios</a>
**Supported Devices:** iPad2Wifi-iPad2Wifi, iPad23G-iPad23G, iPhone4S-iPhone4S, iPadThirdGen-iPadThirdGen, iPadThirdGen4G-iPadThirdGen4G, iPhone5-iPhone5, iPodTouchFifthGen-iPodTouchFifthGen, iPadFourthGen-iPadFourthGen, iPadFourthGen4G-iPadFourthGen4G, iPadMini-iPadMini, iPadMini4G-iPadMini4G, iPhone5c-iPhone5c, iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX
**Original Artwork:**
<img src="http://is5.mzstatic.com/image/thumb/Purple118/v4/e9/14/ea/e914eaf1-c483-3b27-1462-eebb0ce19b00/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38288084-b564feec-37ce-11e8-8e20-1c7f177d5642.png)

**Comment by dreamnet** [comment]
![-large](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/2068130/38288084-b564feec-37ce-11e8-8e20-1c7f177d5642.png)
https://user-images.githubusercontent.com/2068130/38288084-b564feec-37ce-11e8-8e20-1c7f177d5642.png
--- ---
Source:
https://user-images.githubusercontent.com/2068130/38288091-c3f7408c-37ce-11e8-924b-405496aa8ae0.png
