### ISSUE TITLE
Movie Time - Find your movie

### ISSUE THREAD

**Issue by l8er4now** [glasklart/hd#9993]
**App Name:** Movie Time - Find your movie
**Bundle ID:** velekeyp.Movie-Time
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=1434052999">1434052999</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/movie-time-find-your-movie/id1434052999?mt=8&uo=4">https://itunes.apple.com/us/app/movie-time-find-your-movie/id1434052999?mt=8&uo=4</a>
**App Version:** 1.1
**Seller:** Patrik Velekey
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/patrik-velekey/id598962355?uo=4">© Patrik Velekey</a>
**Supported Devices:** iPhone5s-iPhone5s, iPadAir-iPadAir, iPadAirCellular-iPadAirCellular, iPadMiniRetina-iPadMiniRetina, iPadMiniRetinaCellular-iPadMiniRetinaCellular, iPhone6-iPhone6, iPhone6Plus-iPhone6Plus, iPadAir2-iPadAir2, iPadAir2Cellular-iPadAir2Cellular, iPadMini3-iPadMini3, iPadMini3Cellular-iPadMini3Cellular, iPodTouchSixthGen-iPodTouchSixthGen, iPhone6s-iPhone6s, iPhone6sPlus-iPhone6sPlus, iPadMini4-iPadMini4, iPadMini4Cellular-iPadMini4Cellular, iPadPro-iPadPro, iPadProCellular-iPadProCellular, iPadPro97-iPadPro97, iPadPro97Cellular-iPadPro97Cellular, iPhoneSE-iPhoneSE, iPhone7-iPhone7, iPhone7Plus-iPhone7Plus, iPad611-iPad611, iPad612-iPad612, iPad71-iPad71, iPad72-iPad72, iPad73-iPad73, iPad74-iPad74, iPhone8-iPhone8, iPhone8Plus-iPhone8Plus, iPhoneX-iPhoneX, iPad75-iPad75, iPad76-iPad76, iPhoneXS-iPhoneXS, iPhoneXSMax-iPhoneXSMax, iPhoneXR-iPhoneXR
**Original Artwork:**
<img src="https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/ff/4d/20/ff4d20d0-17b4-d497-0b12-c71c32b1940f/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/46882593-8726b800-ce4f-11e8-8f18-605cfc4948b4.png)

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at?image=https://user-images.githubusercontent.com/20930745/46882593-8726b800-ce4f-11e8-8f18-605cfc4948b4.png)
https://user-images.githubusercontent.com/20930745/46882593-8726b800-ce4f-11e8-8f18-605cfc4948b4.png

Source:
https://user-images.githubusercontent.com/20930745/46882617-99085b00-ce4f-11e8-9267-f6c5dd13ec37.png
